### PR TITLE
OPCM: ensure contract upgrade methods are called in opcm.upgrade

### LINKED ISSUE #14569: OPCM: ensure contract `upgrade` methods are called in `opcm.upgrade`
We need to ensure that, if any L1 source contracts that have an `upgrade` method, that upgrade method is called in the `OPContractsManager.upgrade` method. Ideally, if OPCM was missing this, tests would fail. But that will not always be the case, so we should have a go script to traverse the AST to verify this. The spec is roughly:

- Collect all `upgrade` functions from the L1 artifacts
- Look at the AST for `OPCM.upgrade(..)`
- Make sure that the AST contains a function call to `X.upgrade` for each X in step 1

cc @maurelian @smartcontracts

### PR DESCRIPTION
**Pull request by AmadiMichael**
fixes https://github.com/ethereum-optimism/optimism/issues/14569

This scripts ensures that any contract within `packages/contracts-bedrock/src/L1/` with an upgrade function is called via it's contract/interface type by searching the OPCMUpgrader's upgrade function AST for this. It supports calls to any L1 
top level external upgrade call e.g
```
IContract.upgrade(...)
```
and internal ones following this rule:
```
upgradeToAndCall(param: IProxyAdmin, address(param: IContract), param: address, abi.encodeCall(IContract.upgrade, (...)))
```
defined:
- At the top level of the OPCMUpgrader's function,
- Within a block i.e `{ }`
- Within an if/else-if/else statement
- Within a for, while or do loop
- As a `Try` external call or within its `Try` or `Catch` block
- Support when it's called within a ternary i.e `cond ? call : call` statement

- Adds just commands for them

Also, good feature is that it is very easy to add more tests for this, just create a contract that has the combination of statements you intend to check for and add it in the opcm_upgrade_checks_mocks.sol file, it automatically gets added to the tests.

### CODE REVIEW

**Comment by opgitgovernance** [comment]
This pr has been automatically marked as stale and will be closed in 5 days if no updates

File: packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go [hunk 1]
```diff
@@ -0,0 +1,243 @@
...
+	// Get OPCM's AST.
+	opcmAst, err = common.ReadForgeArtifact(opcmArtifactPath)
+	if err != nil {
+		fmt.Println(err)
+		os.Exit(1)
+	}
+
+	// Process.
+	if _, err := common.ProcessFilesGlob(
+		includedFiles,
```
Comment (smartcontracts) [inline packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go]: You should be able to do this without the need for `filterFilesAndDeriveArtifactPath`:

```
common.ProcessFilesGlob(
  []string{"forge-artifacts/**/*.json"},
  []string{"forge-artifacts/OPContractsManager.sol/*.json"}
); err != nil {
```

File: packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go [hunk 2]
```diff
@@ -0,0 +1,243 @@
...
+	fileNames, err := os.ReadDir(l1Dir)
+	if err != nil {
+		fmt.Println(err)
+		os.Exit(1)
+	}
+
+	// Create a new array of string paths and only add the file to
+	// the array if it's not in the global excludedFiles array.
+	var excludedFiles = []string{
+		"OPPrestateUpdater.sol",
```
Comment (smartcontracts) [inline packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go]: OPPrestateUpdater no longer exists

File: packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/opcm_upgrade_checks_mocks.sol
Comment (smartcontracts) [inline packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/opcm_upgrade_checks_mocks.sol:1]: Can we rename to `OPCMUpgradeCheckMocks.sol`?

File: packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go (hunk 1 above)
Comment (smartcontracts) [reply packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go]: Then to filter for only L1 contracts, use `artifact.Ast.AbsolutePath`

Comment (AmadiMichael) [reply packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go]: but this will include contracts that are not within the L1 folder

File: packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/opcm_upgrade_checks_mocks.sol
Comment (AmadiMichael) [reply packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/opcm_upgrade_checks_mocks.sol:1]: yup

Comment (AmadiMichael) [reply packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/opcm_upgrade_checks_mocks.sol:1]: done

File: packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go (hunk 2 above)
Comment (AmadiMichael) [reply packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go]: removed

File: packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go (hunk 1 above)
Comment (smartcontracts) [reply packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go]: Yes that's fine, inside of `processFile` you can simply filter out any files where `artifact.Ast.AbsolutePath` does not start with `src/L1`

Comment (AmadiMichael) [reply packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go]: fixed

File: packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go [hunk 3]
```diff
@@ -0,0 +1,219 @@
...
+		return nil, []error{err}
+	}
+
+	// If the absolute path is not src/L1, return early.
+	if !strings.HasPrefix(artifact.Ast.AbsolutePath, "src/L1") {
+		return nil, nil
+	}
+
+	// Find if it contains any upgrade function and if there are no upgradeFunctions, return early.
+	if getNumberOfUpgradeFunctions(artifact) == 0 {
```
Comment (smartcontracts) [inline packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go]: Actually maybe better to check that this is exactly 1?

Comment (AmadiMichael) [reply packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go]: yeah, just fixed that now

File: packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go [hunk 4]
```diff
@@ -0,0 +1,219 @@
...
+	}
+
+	// If the absolute path is not src/L1, return early.
+	if !strings.HasPrefix(artifact.Ast.AbsolutePath, "src/L1") {
+		return nil, nil
+	}
+
+	// Find if it contains any upgrade function and if there are no upgradeFunctions, return early.
+	if getNumberOfUpgradeFunctions(artifact) != 1 {
+		return nil, nil
```
Comment (smartcontracts) [inline packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go:97]: This should error

Comment (smartcontracts) [reply packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go:97]: Oh I see the problem. If it's 0 then return nil, if it's more than 1 then error.

Comment (AmadiMichael) [reply packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go:97]: ah yeah fixed it now

File: packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go [hunk 5]
```diff
@@ -0,0 +1,227 @@
...
+	// If there are no upgrade functions, return early.
+	if numOfUpgradeFunctions == 0 {
+		return nil, nil
+	}
+
+	// If there are more than 1 upgrade functions, return an error.
+	if numOfUpgradeFunctions > 1 {
+		return nil, []error{fmt.Errorf("expected 0 or 1 upgrade function, found %v", numOfUpgradeFunctions)}
+	}
+
```
Comment (smartcontracts) [inline packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/main.go:104]: Nit, if you want to simplify a bit you can just load opcmAst here, not a huge benefit to doing it globally

**Review by smartcontracts — APPROVED** [review]

File: packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/OPCMUpgradeChecksMocks.sol [hunk 6]
```diff
@@ -0,0 +1,396 @@
...
+    function aaa() external {
+        upgradeToAndCall(UPGRADE_CONTRACT, address(UPGRADE_CONTRACT), address(0), bytes(""));
+    }
+}
+
+contract WithinTopLevelFunctionInternal is InternalUpgradeFunction {
+    uint8 constant EXPECTED_OUTPUT = UPGRADE_TO_AND_CALL_INTERNAL_CALL;
+
+    function upgrade() external {
+        upgradeToAndCall(UPGRADE_CONTRACT, address(UPGRADE_CONTRACT), address(0), bytes(""));
```
Comment (smartcontracts) [inline packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/OPCMUpgradeChecksMocks.sol]: I'd expect this to fail because the last parameter is not specifically MyContract.upgrade(..)

File: packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/OPCMUpgradeChecksMocks.sol [hunk 7]
```diff
@@ -0,0 +1,396 @@
...
+    }
+}
+
+contract WithinBlockStatementInternal is InternalUpgradeFunction {
+    uint8 constant EXPECTED_OUTPUT = UPGRADE_TO_AND_CALL_INTERNAL_CALL;
+
+    function upgrade() external {
+        {
+            upgradeToAndCall(UPGRADE_CONTRACT, address(UPGRADE_CONTRACT), address(0), bytes(""));
```
Comment (smartcontracts) [inline packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/OPCMUpgradeChecksMocks.sol]: Same as above

File: packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/OPCMUpgradeChecksMocks.sol (hunk 6 above)
Comment (AmadiMichael) [reply packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/OPCMUpgradeChecksMocks.sol]: you mean the bytes parameter?

Comment (AmadiMichael) [reply packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/OPCMUpgradeChecksMocks.sol]: the only check is that the type of the variable that is cast into an address in the second parameter to the `upgradeToAndCall` function is of type "MyContract". there was not a need to also check the type of interface used with abi.encodeCall to derive the bytes type also

Comment (smartcontracts) [reply packages/contracts-bedrock/scripts/checks/opcm-upgrade-checks/OPCMUpgradeChecksMocks.sol]: I might just be a bit confused by the implementation, apologies. Will try to clearly lay out the use-case.

We know that this is ok:

```solidity
upgradeTo(proxyAdmin, myContractProxy, myNewImplementation);
myContractProxy.upgrade(...);
```

Because it calls the upgrade function directly, no problem.

Now we also want to support this case:

```solidity
proxyAdmin.upgradeToAndCall(proxyAdmin, myContractProxy, myNewImplementation, abi.encodeCall(MyContract.upgrade, (...)));
```

It's important that we check the last parameter because otherwise it would be possible to make a mistake:

```solidity
proxyAdmin.upgradeToAndCall(proxyAdmin, myContractProxy, myNewImplementation, abi.encodeCall(MyContract.notTheUpgradeFunction, (...))); // this is bad
```

Let me know if that makes sense

**Review by smartcontracts — APPROVED** [review]

**Review by smartcontracts — APPROVED** [review]
