### PR TITLE
op-node: fix driver step hot loop, improve events and add utils

### LINKED ISSUE #10983: Interop: event handling utils and syntax sugar
### Event helper functions

See review-discussion in: https://github.com/ethereum-optimism/optimism/pull/10947#pullrequestreview-2134407555

Instead of defining inline functions that help run an action-test until a certain event, we can use generics.

Example:
```go
// in rollup package

// IsEventType is syntax-sugar to do a type check as a boolean function
func IsEventType[T Event](ev Event) bool {
	_, ok := ev.(T)
	return ok
}

// IsEventAny combines different event conditions into a single function
func IsEventAny(fns ...func(ev Event) bool) func(ev Event) bool {
	return func(ev Event) bool {
		for _, fn := range fns {
			if fn(ev) {
				return true
			}
		}
		return false
	}
}

// in action test package, example:

sequencer.ActL2EventsUntil(rollup.IsEventEny(rollup.IsEventType[derive.DeriverIdleEvent], rollup.IsEventType[engine.PendingSafeUpdateEvent]))

```

Generally the op-e2e tests, especially the action-test framework, can benefit from the new event system, and introducing some helper functions would improve future test writing.

### Event metrics

We can add 2 counter metrics:
- total emitted events
- total processed events

And with the stringified event type (`.String()`, no need for reflection) as `event` label.

From these two we can then monitor a lot of the processing:
- rate of events
- backlogs (diff of emitted and processed)

All per event type, and the totals.

### Event package

We can probably make this even more elegant, by putting all the event utils and types into its own `event` package:
- helpers: `event.Is`, `event.Any`
- main interface type: `event.Event`
- relevant interfaces: `event.Emitter`, `event.Deriver`
- core utils: `event.Loop` (the `rollup.SynchronousEvents` loop util)
- future utils: `event.System` (the parallel processing system)
- etc.

This way the type util/interface usage reads better.

### PR DESCRIPTION
**Pull request by protolambda**
**Description**

- move events common types / utils into `event` package
- rename `SynchronousEvents` to `event.Queue`
- rename `SynchronousDerivers` to `event.DeriverMux`
- rename `EventEmitter` to `event.Emitter`
- add `event.Limiter` to rate limit events with
  - apply the rate-limiter to the driver. And log a warning when the rate-limit is being hit
  - apply the rate-limiter to action tests. And fail the test if the generous test rate limit is hit.
- add `event.Drainer` interface for event-draining
- add `Is`, `Any` event matching utils
- add events_emitted metric (with event_type label for filtering per kind, so we can monitor e.g. derivation steps, error events, sequencing performance, etc. And alert on uncommon events)
- add events_processed metric (the diff with events_emitted is the size of the queued up events. We can add alerts when the diff is getting too large, ).

**Tests**

Added tests for all new utils. Updated some of the existing tests to use the new syntax-sugar helpers.

**Metadata**

Fix https://github.com/ethereum-optimism/optimism/issues/10983

### CODE REVIEW

File: op-node/rollup/event/util.go [hunk 1]
```diff
@@ -0,0 +1,19 @@
+package event
+
+// Is as helper function is syntax-sugar to do an Event type check as a boolean function
+func Is[T Event](ev Event) bool {
+	_, ok := ev.(T)
+	return ok
+}
```
Comment (tynes) [inline op-node/rollup/event/util.go:7]: How do you feel about making concrete types that bind the generics for the events that we care about? I think it would improve readability in places where the type binding happens inline

Comment (protolambda) [reply op-node/rollup/event/util.go:7]: Wouldn't it then just become `rollup.IsResetEvent` instead of `event.Is[rollup.ResetEvent]`? It's shorter, but also need to use it a lot for the extra lines of type definitions to really be worth it.

File: op-e2e/actions/l2_verifier.go [hunk 2]
```diff
@@ -88,8 +91,13 @@ func NewL2Verifier(t Testing, log log.Logger, l1 derive.L1Fetcher, blobsSrc deri
...
 	t.Cleanup(cancel)
 
-	rootDeriver := &rollup.SynchronousDerivers{}
-	synchronousEvents := rollup.NewSynchronousEvents(log, ctx, rootDeriver)
+	rootDeriver := &event.DeriverMux{}
+	var synchronousEvents event.EmitterDrainer
+	synchronousEvents = event.NewQueue(log, ctx, rootDeriver, event.NoopMetrics{})
+	synchronousEvents = event.NewLimiterDrainer(ctx, synchronousEvents, rate.Limit(1000), 20, func() {
+		log.Warn("Hitting events rate-limit. An events code-path may be hot-looping.")
+		t.Fatal("Tests must not hot-loop events")
```
Comment (ajsutton) [inline op-e2e/actions/l2_verifier.go:99]: Very clever. I like it.

File: op-node/rollup/driver/driver.go [hunk 3]
```diff
@@ -167,8 +179,12 @@ func NewDriver(
...
 ) *Driver {
 	driverCtx, driverCancel := context.WithCancel(context.Background())
-	rootDeriver := &rollup.SynchronousDerivers{}
-	synchronousEvents := rollup.NewSynchronousEvents(log, driverCtx, rootDeriver)
+	rootDeriver := &event.DeriverMux{}
+	var synchronousEvents event.EmitterDrainer
+	synchronousEvents = event.NewQueue(log, driverCtx, rootDeriver, metrics)
+	synchronousEvents = event.NewLimiterDrainer(context.Background(), synchronousEvents, eventsLimit, eventsBurst, func() {
+		log.Warn("Driver is hitting events rate limit.")
+	})
```
Comment (ajsutton) [inline op-node/rollup/driver/driver.go]: I'd suggest we add a metric for this - just a counter of the number of times the limit was hit is probably enough. We probably should setup alerting for it since it's not something we generally expect to happen. Theoretically we could do that by looking at the rate of increase of the event count metric but would be good to have an at-a-glance number too.

Although, if we're doing something like syncing from genesis would we hit this limit or is the delay for geth to import the block long enough to keep us below it?

File: op-node/rollup/driver/state.go [hunk 4]
```diff
@@ -508,7 +509,8 @@ func (s *SyncDeriver) onStepEvent() {
 		s.Log.Error("Derivation process error", "err", err)
 		s.Emitter.Emit(StepReqEvent{})
 	} else {
-		s.Emitter.Emit(StepReqEvent{ResetBackoff: true}) // continue with the next step if we can
+		// Revisit SyncStep in 1/2 of a L2 block.
+		s.Emitter.Emit(StepDelayedReqEvent{Delay: (time.Duration(s.Config.BlockTime) * time.Second) / 2})
```
Comment (ajsutton) [inline op-node/rollup/driver/state.go:513]: So we don't have an error, haven't reached an idle state so there's more to do, but we want to delay.  Is that because there's async stuff happening like importing the next block?  I'm just nervous that a delay here could have major impacts to sync times if the node is behind.

**Review by ajsutton — APPROVED** [review]
Approving because it fixes an existing issue where it runs too hot. I am slightly nervous about the delay causing slow downs when syncing though, but not sure if that really is a problem or not.

**Comment by tynes** [comment]
All of the semgrep issues in https://github.com/ethereum-optimism/optimism/pull/11040#issuecomment-2195685962 have been addressed by deleting the code in https://github.com/ethereum-optimism/optimism/pull/11021

File: op-node/rollup/driver/state.go (hunk 4 above)
Comment (protolambda) [reply op-node/rollup/driver/state.go:513]: The main issue is that it needs to poll/retry L1 traversal during regular operation. For this we need to trigger a re-attempt, either by monitoring L1 proactively, or by making the derivation-pipeline do that. Hence the delay here.


If the derivation-pipeline is busy, then it will emit an event that things can continue straight away (i.e. there's more data): https://github.com/ethereum-optimism/optimism/blob/793f98d851489be8257eb811f2466bd2370f4175/op-node/rollup/derive/deriver.go#L124
And a non-delayed step will then be requested.

Ideally we clean up the Driver and SyncDeriver more; it can just be a simple event handler that ties together some actions (like more-data => step) but not do anything that's not triggered by an event or outside input.

File: op-node/rollup/driver/driver.go (hunk 3 above)
Comment (protolambda) [reply op-node/rollup/driver/driver.go]: Added metrics. And bumped the rate-limit to 10k events per second. If we have 2ms blocks (already unreal, avg block is more like 20-100ms), then we see 500 blocks / second. But we do process multiple events per block, so bumping it to 10k makes sense.

File: op-node/rollup/event/limiter.go [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+	}
+}
+
+// Emit is thread-safe, multiple parallel derivers can safely emit events to it.
+func (l *Limiter[E]) Emit(ev Event) {
+	if l.onLimited != nil && l.rl.Tokens() < 1.0 {
+		l.onLimited()
+	}
+	if err := l.rl.Wait(l.ctx); err != nil {
+		return // ctx error, safe to ignore.
```
Comment (zhiqiangxu) [inline op-node/rollup/event/limiter.go:36]: I'm a bit concerned: is it possible that some critical event was dropped silently here?

Comment (protolambda) [reply op-node/rollup/event/limiter.go:36]: No, the Wait function error is limited to just the ctx. And all important events are processed before context cancellation. Besides, we do aim for events to be possible to drop without critical effects.
