### PR TITLE
fix(op-batcher): exempt generic da from max input size

### LINKED ISSUE #17872: Investigate upstreaming Celestia batcher DA size fix
Investigate fixing this issue: https://github.com/ethereum-optimism/optimism/issues/17796. Celestia has already developed a fix here which we could potentially upstream: https://github.com/celestiaorg/optimism/commit/1911fd9424ae9542f666ae7ee9b227ad46384994.

DoD:

- Either upstream the fix, or determine how we would resolve this issue ourselves.

### PR DESCRIPTION
**Pull request by mslipper**
Cherry-pick Celestia's fixes to alt-DA the remove max frame size limits for generic DA types. Credit to @tuxcanfly from the Celestia team.

Closes https://github.com/ethereum-optimism/optimism/issues/17872.

### CODE REVIEW

**Review by sebastianst — APPROVED** [review]

File: op-batcher/batcher/service.go [hunk 1]
```diff
@@ -284,7 +286,7 @@ func (bs *BatcherService) initChannelConfig(cfg *CLIConfig) error {
 		return fmt.Errorf("cannot use data availability type blobs or auto with Alt-DA")
 	}
 
-	if bs.UseAltDA && cc.MaxFrameSize > altda.MaxInputSize {
+	if bs.UseAltDA && !bs.GenericDA &&  cc.MaxFrameSize > altda.MaxInputSize {
```
Comment (sebastianst) [inline op-batcher/batcher/service.go]:
```suggestion
	if bs.UseAltDA && !bs.GenericDA && cc.MaxFrameSize > altda.MaxInputSize {
```
