### PR TITLE
interop: op-supervisor <> op-node reconnection

### LINKED ISSUE #15427: Supervisor should reconnect to node after node restart
op-supervisor connects with op-node via ws connection when it starts, or using `admin_addL2RPC`. When op-node restarts and even if it listens with persistent ws endpoint again, op-supervisor fails to reconnect.

Need a reconnection/connection cleanup logic at op-supervisor. 

We may need this for for fluent [interop sync tests](https://github.com/ethereum-optimism/optimism/issues/15325).

### PR DESCRIPTION
**Pull request by pcw109550**
**Description**

This PR adds reconnection logic between op-supervisor and op-node

When op-node shuts down, supervisor detects closed `nodeEvent` channel, and stops the ManagedNode busy loop consuming events:
https://github.com/ethereum-optimism/optimism/blob/273fd6abd4a92824e05f3daa9322b0c8add9e843/op-supervisor/supervisor/backend/syncnode/node.go#L197-L216

Even if the `nodeEvent` channel is reinitialized at:
https://github.com/ethereum-optimism/optimism/blob/273fd6abd4a92824e05f3daa9322b0c8add9e843/op-supervisor/supervisor/backend/syncnode/node.go#L149-L161

the event consuming loop already exited.

Diff of this PR:
- Supervisor ManagedNode loop does not exit when `nodeEvent` channel is closed. Instead it sleeps for some time quantum and loops again to check the `nodeEvent` channel is open again.
- When websocket closure is detected, it attempts to reconnect with the op-node with its known auth info and endpoint.

Supervisor will now reconnect and make the op-node happy and re-sync(advancing unsafe head).

**Tests**

Added `TestL2CLResync` sysgo test which restarts L2 CL and checks it resyncs.

Example testlogs(discard the XXX)
```
    sync_test.go:65:            INFO [04-17|19:11:24.638] wait until passing genesis               XXX=XXX
    sync_test.go:60:            INFO [04-17|19:11:27.644] chain A                                  XXX=XXX blockNum=0 tip=1371d7..d59b9c:0
    sync_test.go:61:            INFO [04-17|19:11:27.645] chain B                                  XXX=XXX blockNum=0 tip=f6a2bf..0df97f:0
    sync_test.go:60:            INFO [04-17|19:11:30.639] chain A                                  XXX=XXX blockNum=3 tip=aa0ca2..04e08d:3
    sync_test.go:61:            INFO [04-17|19:11:30.639] chain B                                  XXX=XXX blockNum=3 tip=eb1e1e..d9d1e0:3
    sync_test.go:74:            INFO [04-17|19:11:33.639] check unsafe chains are advancing        XXX=XXX
    sync_test.go:60:            INFO [04-17|19:11:36.640] chain A                                  XXX=XXX blockNum=6 tip=c3597e..7c1597:6
    sync_test.go:61:            INFO [04-17|19:11:36.640] chain B                                  XXX=XXX blockNum=6 tip=d534ca..58c45e:6
    sync_test.go:60:            INFO [04-17|19:11:39.641] chain A                                  XXX=XXX blockNum=7 tip=5ab9c8..86da2b:7
    sync_test.go:61:            INFO [04-17|19:11:39.641] chain B                                  XXX=XXX blockNum=7 tip=6b039d..f2b802:7
    sync_test.go:60:            INFO [04-17|19:11:42.641] chain A                                  XXX=XXX blockNum=9 tip=558841..246877:9
    sync_test.go:61:            INFO [04-17|19:11:42.641] chain B                                  XXX=XXX blockNum=9 tip=53312a..a46a65:9
    sync_test.go:82:            INFO [04-17|19:11:43.640] stop L2CL nodes                          XXX=XXX
    sync_test.go:86:            INFO [04-17|19:11:43.642] make sure L2ELs does not advance         XXX=XXX
    sync_test.go:60:            INFO [04-17|19:11:46.644] chain A                                  XXX=XXX blockNum=9 tip=558841..246877:9
    sync_test.go:61:            INFO [04-17|19:11:46.645] chain B                                  XXX=XXX blockNum=9 tip=53312a..a46a65:9
    sync_test.go:94:            INFO [04-17|19:11:46.645] restart L2CL nodes                       XXX=XXX
    sync_test.go:100:           INFO [04-17|19:11:46.708] boot up L2CL nodes                       XXX=XXX
    sync_test.go:60:            INFO [04-17|19:11:49.710] chain A                                  XXX=XXX blockNum=12 tip=089910..ce0ad9:12
    sync_test.go:61:            INFO [04-17|19:11:49.710] chain B                                  XXX=XXX blockNum=12 tip=6f171c..6c27ec:12
    sync_test.go:109:           INFO [04-17|19:11:49.710] check unsafe chains are advancing again  XXX=XXX
    sync_test.go:60:            INFO [04-17|19:11:52.712] chain A                                  XXX=XXX blockNum=14 tip=c3c8fe..7339ab:14
    sync_test.go:61:            INFO [04-17|19:11:52.712] chain B                                  XXX=XXX blockNum=14 tip=96cf2e..b768d4:14
    sync_test.go:60:            INFO [04-17|19:11:55.711] chain A                                  XXX=XXX blockNum=15 tip=082967..b26aa6:15
    sync_test.go:61:            INFO [04-17|19:11:55.711] chain B                                  XXX=XXX blockNum=15 tip=6211ad..7689bd:15
    sync_test.go:60:            INFO [04-17|19:11:58.712] chain A                                  XXX=XXX blockNum=17 tip=b2d5aa..467707:17
    sync_test.go:61:            INFO [04-17|19:11:58.712] chain B                                  XXX=XXX blockNum=17 tip=be8109..be84ea:17
    sync_test.go:60:            INFO [04-17|19:12:01.712] chain A                                  XXX=XXX blockNum=18 tip=5e5699..0519d9:18
    sync_test.go:61:            INFO [04-17|19:12:01.712] chain B                                  XXX=XXX blockNum=18 tip=eac32d..df0b3d:18
```

**Metadata**

- Fixes https://github.com/ethereum-optimism/optimism/issues/15427

### CODE REVIEW

File: devnet-sdk/devstack/sysgo/sync_test.go [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+
+		logger.Info("check unsafe chains are advancing again")
+		prevBlockA, prevBlockB = pausedBlockA, pausedBlockB
+		for range 5 {
+			blockA, blockB := query()
+			require.Greater(t, blockA.Number, prevBlockA.Number)
+			require.Greater(t, blockB.Number, prevBlockB.Number)
+			prevBlockA, prevBlockB = blockA, blockB
+			time.Sleep(time.Millisecond * 2500)
+		}
```
Comment (axelKingsley) [inline devnet-sdk/devstack/sysgo/sync_test.go]: Can these two sections me merged, seeing as they both use `query`, and the only difference is the second check checks the output?

File: devnet-sdk/devstack/sysgo/sync_test.go [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+		control.L2CLNodeState(ids.L2BCL, stack.Stop)
+
+		logger.Info("make sure ELs does not advance")
+		pausedBlockA, pausedBlockB := query()
+		for range 5 {
+			blockA, blockB := query()
+			require.Equal(t, pausedBlockA.Hash, blockA.Hash)
+			require.Equal(t, pausedBlockB.Hash, blockB.Hash)
+			time.Sleep(time.Millisecond * 2500)
+		}
```
Comment (axelKingsley) [inline devnet-sdk/devstack/sysgo/sync_test.go]: wouldn't it be the case that if any of these `require.Equal` iterations fail, the whole test would fail? If so, why make the same expectation five times over 1.25s?

Why not use `require.Eventually` to await the condition you want? Or `require.Never` if you want to make sure all of the checks satisfy the same thing.

File: op-supervisor/supervisor/backend/syncnode/node.go [hunk 3]
```diff
@@ -156,6 +157,15 @@ func (m *ManagedNode) SubscribeToNodeEvents() {
 			if prevErr != nil {
 				// This is the RPC runtime error, not the setup error we have logging for below.
 				m.log.Error("RPC subscription failed, restarting now", "err", prevErr)
+				var closeErr *websocket.CloseError
+				if errors.As(prevErr, &closeErr) {
```
Comment (axelKingsley) [inline op-supervisor/supervisor/backend/syncnode/node.go:161]: I think you mean `errors.Is` here? You could then skip making `closeErr`

**Review by axelKingsley — COMMENTED** [review]
One thing I almost missed is that the `ReconnectRPC` call is embedded in the subscription function, so any time the subscription stops it automatically triggers this reconnect. That's a nice solution, thank you.

I left a few comments about the test, and one change on the error comparison in the reconection.

File: op-supervisor/supervisor/backend/syncnode/node.go (hunk 3 above)
Comment (pcw109550) [reply op-supervisor/supervisor/backend/syncnode/node.go:161]: You mean `if errors.Is(prevErr, &websocket.CloseError{})`? This won't work because `errors.Is` only compares the values, not types. I wanted to compare with types to detect every `CloseError`.

File: devnet-sdk/devstack/sysgo/sync_test.go (hunk 2 above)
Comment (pcw109550) [reply devnet-sdk/devstack/sysgo/sync_test.go]: Thank you for the suggestion. I updated the test using your suggestion; require.Never and require.Eventually

File: devnet-sdk/devstack/sysgo/sync_test.go (hunk 1 above)
Comment (pcw109550) [reply devnet-sdk/devstack/sysgo/sync_test.go]: op-node somehow advances few blocks(two or three) after restart, without supervisor connection. After that, it stalls until supervisor reconnects. I added in the test comment to mention this behavior. Thats why I initially added two separate loops.

**Review by axelKingsley — APPROVED** [review]
