### PR TITLE
op-supervisor: fix deep local-safe invalidation case

### LINKED ISSUE #14990: Supervisor: Rewind can rewind
When accessing the Local Derivation Database, it is possible for an L2 block height to appear multiple times:

- Block A1 is derived from L1 X
- Block A2 is derived from L1 Y
- Block A1 is discovered invalid from L1 Z

When this happens, all three entries remain in the database. This means that calls to `derivedNumToFirstSource` will find the *first* source for the L2 block, which is the block that has been invalidated. using `derivedNumToLastSource` will fetch a different L1 height (which could happen naturally), but notably the *hash* of the L2 will be different.

This `derivedNumToFirstSource` call gets used as part of our `Rewind` routine to reset the Local database. But this rewinds the database farther than it should, rewinding back to the *first* time this block height was seen.

The Rewind code should check if the block we are rewinding to gets replaced ever, and if it does, should rewind only to the replacement location.

### PR DESCRIPTION
**Pull request by protolambda**
**Description**

Work in progress.

Fixes:
- `lookup` should use the L1 key as primary key, and L2 as secondary key, not the other way around, to account for local-safe invalidation where a new L1 scope rolls back the L2 chain many blocks
- `lookupOrAfter` should be used by the local-safe invalidation code, to determine what to rewind to
- `addLink` should handle that when invalidating something, that something can be an older block, attached to a new scope
- remove duplicate `if cmpFn(link) != 0` case
- fix logs-DB truncation off-by-one (it was self-recovering, but now it doesn't log anymore about dropping the inconsistent entries after truncation)
- fix `derivedNumToFirstSource`: always use the exact revision number. (any later revision would be from a later source)
- fix `derivedNumToLastSource`: check if the revision query is open-ended, if so, we can accept the trailing invalidated data if it matches. If not, then do an exact search.

### About `revision` in the fromda DB

This is a number that tracks per L1-L2-link when the last block-replacement (local-safe invalidation) happened.

This makes it so that there is a L2-key that is strictly incremental. And for all entries with the same revision, the L2 derived block number is strictly incremental (since there is no block replacement that can set things back within the same revision).

Using the revision number, the local-safe DB can now safely be searched by L2 derived block number again. Previously this was subtly broken, where it would work, unless there was an invalidated local-safe chain that is deeper than a single L1 batch (older tests all did minimal increments, not capturing the deeper invalidation).

The cross-safe DB is still the same canonical chain view, with no conflicting L2 blocks, but now tracks a copy of the revision number with every link. Anyone querying the local-safe DB with an L2 block can first get a revision-number from the cross-safe DB, and then use that for the local-safe lookup. If the cross-safe DB does not include the block yet, then the last known revision is used.
The local-safe DB may be invalidating something (there may be an invalidated placeholder entry, that hasn't been replaced yet), while that new revision isn't yet in the cross-safe DB. This is accepted in the "open ended" case, and checked explicitly, before searching the DB, since it can only affect the last entry in the DB.

image

excalidraw link: https://excalidraw.com/#json=d_hSkpGGBfTlunRlZwMLL,re0b2Ik8PwOpK7JaWReq9A

**Tests**

See new `fromda` unit tests.

**Additional context**

**Metadata**

Fix https://github.com/ethereum-optimism/optimism/issues/14990

### CODE REVIEW

File: op-supervisor/supervisor/backend/db/fromda/update.go [hunk 1]
```diff
@@ -196,11 +238,35 @@ func (db *DB) addLink(source eth.BlockRef, derived eth.BlockRef, invalidated com
...
+			if last.revision != revision {
+				if derived.Number != revision.Number() {
+					return fmt.Errorf("cannot insert entry %s with revision %s, after %s with revision %s: %w",
+						derived, revision, last.derived, last.revision, types.ErrDataCorruption)
+				}
+				db.log.Warn("New revision", "revision", revision, "source", source, "derived", derived)
+			}
+		} else if derived.Hash == invalidated {
+			if last.revision == revision {
+				return fmt.Errorf("invalidated link %s should change revision: %w", link, types.ErrConflict)
```
Comment (axelKingsley) [inline op-supervisor/supervisor/backend/db/fromda/update.go:261]: I'm a little unsure of ErrConflict here semantically, but functionally its likely the best match we have.

**Review by axelKingsley — APPROVED** [review]
Much of this we reviewed in person yesterday, and then discussed in detail the changes to come. This morning I looked over the new commits to see *what* had changed, and then reviewed the PR itself, focusing on those changes.

The code makes sense to me, and the checks are all passing, so I'm satisfied. We talked about cutting a ticket to track additional testing, and I've done so here: https://github.com/ethereum-optimism/optimism/issues/15024 .

Given the passing checks, sound reasoning for changes, and offline review, I think this is good to go.
