### PR TITLE
fix: damgr_test.go

### LINKED ISSUE #14054: Enable AltDA package unit tests in ci
Seems like currently altda unit tests are not being ran in the ci: https://github.com/ethereum-optimism/optimism/blob/develop/.circleci/config.yml#L1421-L1439

One of them was actually failing: #14050 

Is there a specific reason for not enabling these?

### PR DESCRIPTION
**Pull request by vdrg**
**Description**

Fixes the `damgr_test.go` `TestFinalization` test and enables `op-alt-da` tests in ci.

Fixes https://github.com/ethereum-optimism/optimism/issues/14054

### CODE REVIEW

File: op-alt-da/damgr_test.go [hunk 1]
```diff
@@ -58,7 +58,7 @@ func TestFinalization(t *testing.T) {
 	state.Prune(bID(7))
 	require.Equal(t, eth.L1BlockRef{}, state.lastPrunedCommitment)
 	state.Prune(bID(8))
-	require.Equal(t, eth.L1BlockRef{}, state.lastPrunedCommitment)
+	require.Equal(t, l1Ref(bn1), state.lastPrunedCommitment)
```
Comment (samlaf) [inline op-alt-da/damgr_test.go:61]: Out of curiosity do you know why did this test start failing?
Is op's circleci not running these tests? Prob should also change that as part of this PR?

Comment (samlaf) [reply op-alt-da/damgr_test.go:61]: Also, isn't it this line that should be changed instead? https://github.com/ethereum-optimism/optimism/blob/f4506a8a77314cca8e27998dd28cf9a4f8b2cc90/op-alt-da/dastate.go#L101
to
```
challengeWindowEnd: inclusionBlock.Number + s.cfg.ChallengeWindow + 1,
```

The description for ChallengeWindow is https://github.com/ethereum-optimism/optimism/blob/f4506a8a77314cca8e27998dd28cf9a4f8b2cc90/op-alt-da/damgr.go#L56

So in this case given that the commitment was at block 2, and challengeWindow in the test is set to 6, then block 8 should still be challenageable, so it shouldn't have been prune (aka the initial require was correct, not your fix)

Comment (vdrg) [reply op-alt-da/damgr_test.go:61]: Unfortunately tests were not being ran in the ci, I enable them here: https://github.com/ethereum-optimism/optimism/pull/14056, but I can combine both PRs if you prefer.

When I was going through the code it actually made sense to me that `resolveWindowEnd` was defined as it is, but I think you are right, will update. Thanks!

Comment (samlaf) [reply op-alt-da/damgr_test.go:61]: Not my repo so its @tynes's call. But how do you plan on getting the other PR in if it doesn't pass CI?

Comment (vdrg) [reply op-alt-da/damgr_test.go:61]: I was thinking that this could be merged first, but yeah will prob just merge that branch into this one

Comment (vdrg) [reply op-alt-da/damgr_test.go:61]: merged, now this also enables tests in ci. Will now look into adapting the test. Thanks again.

Comment (vdrg) [reply op-alt-da/damgr_test.go:61]: actually, @axelKingsley could you confirm if the comment is incorrect or if I should actually fix the implementation? Because this would also apply to the way `resolveWindowEnd` is set. Thanks

Comment (tynes) [reply op-alt-da/damgr_test.go:61]: Just ran CI, lets see if the tests pass. I dont have good insight into the safety of this change right now. Would it be a hardfork? Given that lack of certainty, I don't love the idea of merging that change. Going to need to rely on you and the other chains that run alt da in prod to ensure changes to altda are safe. I dont have the bandwidth to context switch into alt da and provide a lot of meaningful input on its technical details right now

**Review by tynes — APPROVED** [review]
