### PR TITLE
genesis: fix permit2 panic

### LINKED ISSUE #10309: L2 Genesis construction state dump parsing failure
**Bug Description**
Working from https://github.com/ethereum-optimism/optimism/commit/b23d3f67bd5a5f9adb24d76353b8e10e3c04080d, I've encountered a panic which attempts to derive the chainId from the Permit2 preinstall. https://github.com/ethereum-optimism/optimism/blob/b23d3f67bd5a5f9adb24d76353b8e10e3c04080d/op-chain-ops/genesis/layer_two.go#L43 is the offending line and at least doesn't handle non-existence of the Permit2Addr from the state dump gracefully. 

```json
[
  "0x019d6f4ff5e7f7479f9ad311db2adab745fff514",
  "0x1d0e526e190d5cf464d5efb626b64beb5c0a9ffe",
  "0x206ce7376c5f869c7230d95c269aab41cf3bd137",
  "0x20b55a4b9c69c20052d502e0551510efc5b3fd22",
  "0x2333114deb7ab1e78c6c7717d570c3ddd7a19432",
  "0x253c7a62b053244a32b68977c4da8b51839c818b",
  "0x2ae66ad450d98dc7046bbc76be45a18a90315be3",
  "0x3374efe7ee2652bda7856789f1d167db8be5f62e",
  "0x3bd5e6f9ae68dd1035b3a8398fc87194dea068db",
  "0x3d5b60f668d8eb22ed7e86401fda80d1e74f80ed",
  "0x409a393e18ebc9f02d07eac914992b526e4ccc52",
  "0x4e59b44847b379578588920ca78fbf26c0b4956c",
  "0x6951524d1f9a4192ccc3de6bd3db7a0c1fd05826",
  "0x7b10d6a1d4df267ad6982843378a0fdb5c952ff4",
  "0x7cba20a9c2662dd79d0bf9db4e4e7a6fe6990cba",
  "0x8812efba71a611e7cb1f85bd9e58950f4fd2d6da",
  "0x8cc78ea82c8287fc4602398aa5fc5ffa7397103f",
  "0x8fb13d52658e7a96cf143b279de0d0fc8e6c78b8",
  "0x9568d36e291c2c4c34fa5593fce73715abef6f9c",
  "0x9605b422a26e7a45c690fb9e6952f56de3e9f5fd",
  "0x9755d8db31b1f1847ab179f35d45c86e93f23d04",
  "0x97d7b97ece30ca38db45e300b17da343540640d3",
  "0x9baa3244565d51d9c7897c0eb6679ed4890e536e",
  "0x9bfd6282b82b397f653e24f55627871cb14d465c",
  "0xa3ae8f23250098bf49f22bc626c2b464a35a4131",
  "0xa6b71e26c5e0845f74c812102ca7114b6a896ab2",
  "0xa9c49fbab2791188fe7f46b7edfaa26e65b114a8",
  "0xb2eb05e77dd09c60d853b07aaac391b57693f1c6",
  "0xb361e3e9994fe2096a96659a9e1691b58f471f95",
  "0xb459fd82b64f4c9120cdf618f2ecbf67b86d2cee",
  "0xd8f91b839c2e79ffcaa296392503d9963bdbc7f1",
  "0xd9db270c1b5e3bd161e8c8503c55ceabee709552",
  "0xdd23cd146283a4f44b04a520caf370288ea5060e",
  "0xde6e43af56a87352beef5f0d3a735f2cc54cb90f",
  "0xe425bfa661f07b1f0d54665e2e0aaad3fc9535f0",
  "0xed5974433baccd637ab49ebe35fda09726840cdc",
  "0xf764a1e709d360f2d5209bed087241515759262c"
]
```

Above are the keys taken from the state-dump and by would indicate that the Permit2Addr `0x000000000022D473030F116dDEE9F6B43aC78BA3` is not present 

**Steps to Reproduce**

The below is the configuration for the deployment on holesky. I deviated from the docs advice and ran the deployment by calling `runWithStateDump()` to output the json file for the genesis --l2-allocs arg.

```json
{
  "l1StartingBlockTag": "0x14beb91ca9994ccbc266734ce17e77f8a0bd55accf037bf1420d2ed3874e2a61",

  "l1ChainID": 17000,
  "l2ChainID": 7169398,
  "l2BlockTime": 2,
  "l1BlockTime": 12,

  "maxSequencerDrift": 600,
  "sequencerWindowSize": 3600,
  "channelTimeout": 300,

  "p2pSequencerAddress": "0x1cE5497aC297291623b9dd4b17d0368E27F3B59f",
  "batchInboxAddress": "0xff00000000000000000000000000000000042069",
  "batchSenderAddress": "0xAc60f35070E6afa67f5E56a96ad35503FA429618",

  "l2OutputOracleSubmissionInterval": 120,
  "l2OutputOracleStartingBlockNumber": 0,
  "l2OutputOracleStartingTimestamp": 1714051776,

  "l2OutputOracleProposer": "0xaf5506962452194d631DA5258d81d71dfB34A4F2",
  "l2OutputOracleChallenger": "0xF6Ddd92616b3c837012311AdAEA7644879aB4c4A",

  "finalizationPeriodSeconds": 12,

  "proxyAdminOwner": "0xF6Ddd92616b3c837012311AdAEA7644879aB4c4A",
  "baseFeeVaultRecipient": "0xF6Ddd92616b3c837012311AdAEA7644879aB4c4A",
  "l1FeeVaultRecipient": "0xF6Ddd92616b3c837012311AdAEA7644879aB4c4A",
  "sequencerFeeVaultRecipient": "0xF6Ddd92616b3c837012311AdAEA7644879aB4c4A",
  "finalSystemOwner": "0xF6Ddd92616b3c837012311AdAEA7644879aB4c4A",
  "superchainConfigGuardian": "0xF6Ddd92616b3c837012311AdAEA7644879aB4c4A",

  "baseFeeVaultMinimumWithdrawalAmount": "0x8ac7230489e80000",
  "l1FeeVaultMinimumWithdrawalAmount": "0x8ac7230489e80000",
  "sequencerFeeVaultMinimumWithdrawalAmount": "0x8ac7230489e80000",
  "baseFeeVaultWithdrawalNetwork": 0,
  "l1FeeVaultWithdrawalNetwork": 0,
  "sequencerFeeVaultWithdrawalNetwork": 0,

  "gasPriceOracleOverhead": 2100,
  "gasPriceOracleScalar": 1000000,

  "enableGovernance": true,
  "governanceTokenSymbol": "MEV_OP_GOV",
  "governanceTokenName": "MEV Optimism Governance Token",
  "governanceTokenOwner": "0xF6Ddd92616b3c837012311AdAEA7644879aB4c4A",

  "l2GenesisBlockGasLimit": "0x1c9c380",
  "l2GenesisBlockBaseFeePerGas": "0x3b9aca00",
  "l2GenesisRegolithTimeOffset": "0x0",

  "eip1559Denominator": 50,
  "eip1559DenominatorCanyon": 250,
  "eip1559Elasticity": 6,

  "l2GenesisDeltaTimeOffset": null,
  "l2GenesisCanyonTimeOffset": "0x0",

  "systemConfigStartBlock": 0,

  "requiredProtocolVersion": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "recommendedProtocolVersion": "0x0000000000000000000000000000000000000000000000000000000000000000",

  "faultGameAbsolutePrestate": "0x03c7ae758795765c6664a5d39bf63841c71ff191e9189522bad8ebff5d4eca98",
  "faultGameMaxDepth": 44,
  "faultGameClockExtension": 0,
  "faultGameMaxClockDuration": 600,
  "faultGameGenesisBlock": 0,
  "faultGameGenesisOutputRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "faultGameSplitDepth": 14,

  "faultGameWithdrawalDelay": 604800,

  "preimageOracleMinProposalSize": 1800000,
  "preimageOracleChallengePeriod": 86400
}
```

**Expected behavior**

The genesis.json and rollup.json files to be constructed correctly

**Environment Information:**
 - Operating System: NixOS/Linux
 - Package Version https://github.com/ethereum-optimism/optimism/commit/b23d3f67bd5a5f9adb24d76353b8e10e3c04080d

**Configurations:**

```bash
go run cmd/main.go genesis l2 --l2-allocs ../packages/contracts-bedrock/state-dump-17000.json  --deploy-config ../packages/contracts-bedrock/deploy-config/holesky.json --l1-deployments ../packages/contracts-bedrock/240425171831_holesky_addresses.json --outfile.l2 genesis.json --outfile.rollup rollup.json --l1-rpc $L1_RPC_URL
```

### PR DESCRIPTION
**Pull request by tynes**
**Description**

Its possible that permit2 isn't in the genesis allocs even
though it should be, it removes the flexibility to define the
genesis spec arbitrarily if we implicitly enforce it being present.
We need a better way to check that the chain id during genesis
allocation matches the chain id in the genesis spec.
An attempt at this is done in https://github.com/ethereum-optimism/optimism/pull/10326.

Fixes https://github.com/ethereum-optimism/optimism/issues/10309

### CODE REVIEW

File: op-chain-ops/genesis/layer_two.go [hunk 1]
```diff
@@ -40,10 +40,15 @@ func BuildL2Genesis(config *DeployConfig, dump *ForgeAllocs, l1StartBlock *types
 		return nil, fmt.Errorf("deploy config mismatch with allocs. Deploy config fundDevAccounts: %v, actual allocs: %v", config.FundDevAccounts, hasDevAccounts)
 	}
 	// sanity check the permit2 immutable, to verify we using the allocs for the right chain.
-	chainID := [32]byte(genspec.Alloc[predeploys.Permit2Addr].Code[6945 : 6945+32])
-	expected := uint256.MustFromBig(genspec.Config.ChainID).Bytes32()
-	if chainID != expected {
-		return nil, fmt.Errorf("allocs were generated for chain ID %x, but expected chain %x (%d)", chainID, expected, genspec.Config.ChainID)
+	if permit2 := genspec.Alloc[predeploys.Permit2Addr].Code; len(permit2) != 0 {
```
Comment (protolambda) [inline op-chain-ops/genesis/layer_two.go:52]: We should add a check to enforce the `permit2` presence, not silently ignore it if it's missing.

See original issue, it appears like a L1 state dump was passed as a L2 allocs.

**Review by protolambda — CHANGES_REQUESTED** [review]

File: op-chain-ops/genesis/layer_two.go (hunk 1 above)
Comment (tynes) [reply op-chain-ops/genesis/layer_two.go:52]: This is fair, I don't love that we couple so tightly what the allocs should be in this way but its definitely an approach, there are some allocs that MUST exist for the system to work and permit2 is technically not one of them

Comment (protolambda) [reply op-chain-ops/genesis/layer_two.go:52]: I'm fine with allowing a missing permit2 preinstall, if we at least keep some sanity checks that the allocs were properly configured. It's too easy to just accidentally point at a L1 chain genesis, or an allocs file of another chain / test, if it's completely silent.

**Comment by tynes** [comment]
@protolambda I added a sanity check that ensures there is code at the predeploys

**Comment by tynes** [comment]
@protolambda this is good for review again

**Review by protolambda — APPROVED** [review]
nice
