### PR TITLE
fix(kona/derive): make syscfg update failure non-fatal in L1Traversal

### LINKED ISSUE #19353: kona: syscfg update failure is fatal (Critical) instead of non-fatal (warn+continue) like op-node
## Summary

In kona's L1 traversal stage, when `update_with_receipts` fails to update the system config, the error is returned as a **critical pipeline error** (`PipelineError::SystemConfigUpdate(err).crit()`), permanently halting the pipeline. In op-node, the equivalent call (`UpdateSystemConfigWithL1Receipts`) is explicitly non-fatal — on failure it logs a warning and continues processing.

This divergence means kona can be halted by a malformed receipt that op-node would ignore, causing a liveness failure.

## Details

**op-node reference behaviour** (non-fatal, warn + continue):
[`op-node/rollup/derive/l1_traversal.go#L78`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/op-node/rollup/derive/l1_traversal.go#L78)

```go
if err := UpdateSystemConfigWithL1Receipts(&l1t.sysCfg, receipts, l1t.cfg, nextL1Origin.Time); err != nil {
    // if UpdateSystemConfigWithL1Receipts returns an error, it is because one or more of the receipts are malformed or invalid
    // failure to apply is just informational, so we just log the error and continue
    l1t.log.Warn("failed to fully update L1 sysCfg with receipts from block", "block", nextL1Origin, "error", err)
}
```

**kona subject behaviour** (fatal, returns Critical error):

`PollingTraversal::advance_origin` at [`rust/kona/crates/protocol/derive/src/stages/traversal/polling.rs#L110`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/rust/kona/crates/protocol/derive/src/stages/traversal/polling.rs#L110):

```rust
Err(err) => {
    error!(target: "l1_traversal", ?err, "Failed to update system config at block {}", next_l1_origin.number);
    // ...metrics...
    return Err(PipelineError::SystemConfigUpdate(err).crit());
}
```

`IndexedTraversal::provide_next_block` at [`rust/kona/crates/protocol/derive/src/stages/traversal/indexed.rs#L102`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/rust/kona/crates/protocol/derive/src/stages/traversal/indexed.rs#L102):

```rust
Err(err) => {
    error!(target: "traversal", ?err, "Failed to update system config at block {}", block_info.number);
    // ...metrics...
    return Err(PipelineError::SystemConfigUpdate(err).crit());
}
```

## Validation

- **Confidence:** confirmed
- **Validated:** ✓ valid — test `test_spec_l1_traversal_syscfg_update_error_is_nonfatal` is present in `polling.rs` and confirms kona returns a Critical error where op-node continues
- **Batcher:** n/a (triggered by a malformed L1 receipt in the chain, not by the batcher)
- **Human review:** ✓ valid

## Fix

In both `PollingTraversal::advance_origin` and `IndexedTraversal::provide_next_block`, change the `Err(err)` arm of the `update_with_receipts` match to log a warning and continue (`Ok(())`), matching op-node's non-fatal behaviour.

## References

- **Finding:** `LT-03` in [rollup-spectre/issues.md](https://github.com/ajsutton/rollup-spectre/blob/main/issues.md)
- **Review:** `kona-node-vs-op-node`
- **Component doc:** `reviews/kona-node-vs-op-node/components/l1-traversal.md`

### PR DESCRIPTION
**Pull request by ajsutton**
## Summary

Fixes https://github.com/ethereum-optimism/optimism/issues/19353

When `update_with_receipts` fails to apply system config changes from L1 receipts (e.g. due to malformed logs), both `PollingTraversal::advance_origin` and `IndexedTraversal::provide_next_block` were returning `PipelineError::SystemConfigUpdate(err).crit()`, permanently halting the pipeline.

op-node's reference implementation ([`l1_traversal.go:78-82`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/op-node/rollup/derive/l1_traversal.go#L78)) treats this as explicitly non-fatal:

> "if UpdateSystemConfigWithL1Receipts returns an error, it is because one or more of the receipts are malformed or invalid — failure to apply is just informational, so we just log the error and continue"

## Changes

- **`rust/kona/crates/protocol/derive/src/stages/traversal/polling.rs`** — `PollingTraversal::advance_origin`: change `Err` arm from `return Err(...crit())` to `warn!` + continue
- **`rust/kona/crates/protocol/derive/src/stages/traversal/indexed.rs`** — `IndexedTraversal::provide_next_block`: same change
- Update existing tests to expect non-fatal behaviour (the existing tests were asserting the old broken critical-error path)

## Testing

Existing test `test_l1_traversal_system_config_update_fails` (polling) and `test_managed_traversal_system_config_update_fails` (indexed) have been updated to assert `is_ok()` rather than an unwrap of the critical error.

### CODE REVIEW

File: rust/kona/crates/protocol/derive/src/stages/traversal/polling.rs [hunk 1]
```diff
@@ -108,13 +108,15 @@ impl<F: ChainProvider + Send> OriginAdvancer for PollingTraversal<F> {
             }
             Ok(false) => { /* Ignore, no update applied */ }
             Err(err) => {
-                error!(target: "l1_traversal", ?err, "Failed to update system config at block {}", next_l1_origin.number);
+                // Failure to update the system config is non-fatal: one or more receipts may be
+                // malformed or invalid. Log a warning and continue, matching op-node behaviour
+                // (l1_traversal.go:78-82: "failure to apply is just informational").
```
Comment (ajsutton) [inline rust/kona/crates/protocol/derive/src/stages/traversal/polling.rs]:
```suggestion
                // malformed or invalid. Log a warning and continue.
```

File: rust/kona/crates/protocol/derive/src/stages/traversal/polling.rs [hunk 2]
```diff
@@ -293,10 +295,12 @@ pub(crate) mod tests {
         let receipts = TraversalTestHelper::new_receipts();
         let mut traversal = TraversalTestHelper::new_from_blocks(blocks, receipts);
         assert!(traversal.advance_origin().await.is_ok());
-        // Only the second block should fail since the second receipt
-        // contains invalid logs that will error for a system config update.
-        let err = traversal.advance_origin().await.unwrap_err();
-        matches!(err, PipelineErrorKind::Critical(PipelineError::SystemConfigUpdate(_)));
+        // A system config update error is now non-fatal (matches op-node behaviour):
```
Comment (ajsutton) [inline rust/kona/crates/protocol/derive/src/stages/traversal/polling.rs]:
```suggestion
        // A system config update error is now non-fatal:
```

File: rust/kona/crates/protocol/derive/src/stages/traversal/indexed.rs [hunk 3]
```diff
@@ -100,13 +100,15 @@ impl<F: ChainProvider> IndexedTraversal<F> {
             }
             Ok(false) => { /* Ignore, no update applied */ }
             Err(err) => {
-                error!(target: "traversal", ?err, "Failed to update system config at block {}", block_info.number);
+                // Failure to update the system config is non-fatal: one or more receipts may be
+                // malformed or invalid. Log a warning and continue, matching op-node behaviour
+                // (l1_traversal.go:78-82: "failure to apply is just informational").
```
Comment (ajsutton) [inline rust/kona/crates/protocol/derive/src/stages/traversal/indexed.rs]:
```suggestion
                // malformed or invalid. Log a warning and continue.
```

**Review by ajsutton — COMMENTED** [review]
Remove all the references to matching op-node behaviour.

**Review by ajsutton — COMMENTED** [review]
LGTM. Clean fix aligning kona with op-node's non-fatal syscfg update behavior.

Minor note: the PR description mentions a conformance test `test_spec_l1_traversal_syscfg_update_error_is_nonfatal` but this test doesn't appear in the diff. Looks like a stale reference from an earlier iteration — might want to update the description for accuracy.

**Review by theochap — APPROVED** [review]
