### PR TITLE
op-batcher: fix MaxChannelDuration tracking for large block backlogs

### LINKED ISSUE #18092: op-batcher: Fix max channel duration tracking for large block backlogs
The batcher supports setting a max channel duration that controls for how long (in terms of L1 blocks) to keep open a channel. This effectively enables chain operators to specify a max duration between safe head increases.

However, the way this is currently implemented it also applies when the batcher is working its way through a large backlog of blocks. During a recent safe head lagging incident on OPM on Oct 10/11, during which the batcher was throttling for a prolonged period of ~2h,  this caused the batcher to create only half-full 1-blob channels that span the configured duration of ~15 min.

We need to fix this so that the max duration is not applied when working through a block backlog.

### PR DESCRIPTION
**Pull request by nonsense**
Fixes: https://github.com/ethereum-optimism/optimism/issues/18092

---

This PR is:
1. Adding `time travel` support for the L2 chains in `op-devstack`.
2. Adding `TestBatcherFullChannelsAfterDowntime` integration test, which creates a backlog of ~1h worth of blocks, in order to test the `op-batcher` handling of a backlog after some downtime.
3. Locks the current behavior of the `op-batcher` with respect to processing backlogs and the number of channels it submits in such a scenario.
4. Modifying the `publishSignal` channel in the `op-batcher` to include information about the backlog of blocks (namely `pubInfo`), which should be taken into account when deciding if a channel has timed out, currently done in `registerL1Block`.
5. Derives back L2 data from L1 in `TestBatcherFullChannelsAfterDowntime` and confirm the number of `channels` and `frames` submitted as well as their `data length`, to determine if the batcher is working as expected.

### CODE REVIEW

File: op-acceptance-tests/tests/batcher/batcher_test.go [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+			{min: 100, max: 1000, note: "channel 1 - only a few blocks due to racy behavior, nowhere near the channel capacity"},
+			{min: 100, max: 1000, note: "channel 2 - only a few blocks due to racy behavior, nowhere near the channel capacity"},
+			{min: 100, max: 1000, note: "channel 3 - only a few blocks due to racy behavior, nowhere near the channel capacity"},
+			{min: 100, max: 1000, note: "channel 4 - only a few blocks due to racy behavior, nowhere near the channel capacity"},
+			{min: 100, max: 1000, note: "channel 5 - only a few blocks due to racy behavior, nowhere near the channel capacity"},
+			{min: 100, max: 1000, note: "channel 6 - only a few blocks due to racy behavior, nowhere near the channel capacity"},
+			{min: 100, max: 1000, note: "channel 7 - only a few blocks due to racy behavior, nowhere near the channel capacity"},
+			{min: 20_000, max: 40_000, note: "channel 8 - filled to the max capacity, due to blocking behavior because of MaxPendingTransactions limit reached"},
+			{min: 20_000, max: 40_000, note: "channel 9 - filled to the max capacity, due to blocking behavior because of MaxPendingTransactions limit reached"},
+		}
```
Comment (nonsense) [inline op-acceptance-tests/tests/batcher/batcher_test.go:84]: Confirmed that that's the case on a devnet too.

Image
Image

File: op-batcher/batcher/channel_builder.go [hunk 2]
```diff
@@ -252,17 +255,12 @@ func (c *ChannelBuilder) updateTimeout(timeoutBlockNum uint64, reason error) {
...
 		c.setFullErr(c.timeoutReason)
 	}
 }
 
-// TimedOut returns whether the passed block number is after the timeout block
-// number. If no block timeout is set yet, it returns false.
-func (c *ChannelBuilder) TimedOut(blockNum uint64) bool {
-	return c.timeout != 0 && blockNum >= c.timeout
-}
-
```
Comment (geoknee) [inline op-batcher/batcher/channel_builder.go:265]: Curious why you removed this? I think having some encapsulation / abstraction here is good in general.

File: op-batcher/batcher/channel_manager.go [hunk 3]
```diff
@@ -461,6 +461,8 @@ func (s *channelManager) outputFrames() error {
 	s.log.Info("Channel closed",
 		"id", s.currentChannel.ID(),
 		"blocks_pending", s.pendingBlocks(),
+		"block_cursor", s.blockCursor,
```
Comment (geoknee) [inline op-batcher/batcher/channel_manager.go:476]: I don't feel strongly, but `block_cursor` is quite implementation specific, so not sure it belongs in an info log.

File: op-batcher/batcher/channel_manager.go [hunk 4]
```diff
@@ -267,6 +266,11 @@ func (s *channelManager) TxData(l1Head eth.BlockID, isPectra, isThrottling, forc
 	return s.nextTxData(channel)
 }
 
+type pubInfo struct {
+	forcePublish bool
+	moreComing   bool
+}
```
Comment (geoknee) [inline op-batcher/batcher/channel_manager.go:277]: 1. Wondering if we should put `isPectra`, `isThrottling` in here as well? Generally the mix of basic types plus a struct doesn't seem to be that obvious to me. 

2. Out of scope for this PR, but `isPectra` could also be removed. As that fork is a while ago now, we can just assume the L1 has Pectra enabled and simplify a lot of code in the batcher. 

3. `moreComing` could have a better name, and at least some explanatory godoc. Perhaps we could use `publishingBackLog` or something a bit more descriptive?

File: op-batcher/batcher/channel_manager_test.go [hunk 5]
```diff
@@ -103,9 +103,9 @@ func ChannelManagerReturnsErrReorgWhenDrained(t *testing.T, batchType uint) {
 
 	require.NoError(t, m.AddL2Block(a))
 
-	_, err := m.TxData(eth.BlockID{}, false, false, false)
+	_, err := m.TxData(eth.BlockID{}, false, false, pubInfo{forcePublish: false, moreComing: false})
```
Comment (geoknee) [inline op-batcher/batcher/channel_manager_test.go]: Nit: you can just use `pubInfo{}` if all fields are `false` (default value).

File: op-batcher/batcher/driver.go [hunk 6]
```diff
@@ -117,7 +117,7 @@ type BatchSubmitter struct {
 
 	throttleController *throttler.ThrottleController
 
-	publishSignal chan bool // true if we should force a tx to be published now, false if we should check the usual conditions (timeouts)
+	publishSignal chan pubInfo // true if we should force a tx to be published now, false if we should check the usual conditions (timeouts)
```
Comment (geoknee) [inline op-batcher/batcher/driver.go]: Comment needs updating.

File: op-batcher/batcher/channel_manager.go [hunk 7]
```diff
@@ -225,7 +224,7 @@ func (s *channelManager) nextTxData(channel *channel) (txData, error) {
 // It will decide whether to switch DA type automatically.
 // When switching DA type, the channelManager state will be rebuilt
 // with a new ChannelConfig.
-func (s *channelManager) TxData(l1Head eth.BlockID, isPectra, isThrottling, forcePublish bool) (txData, error) {
+func (s *channelManager) TxData(l1Head eth.BlockID, isPectra bool, isThrottling bool, forcePublish pubInfo) (txData, error) {
```
Comment (geoknee) [inline op-batcher/batcher/channel_manager.go]: Nit: probably want to use `pi` for the `pubInfo` variable?

File: op-batcher/batcher/channel_manager.go [hunk 8]
```diff
@@ -275,9 +279,8 @@ func (s *channelManager) TxData(l1Head eth.BlockID, isPectra, isThrottling, forc
 // there is no channel with txData
 // If forcePublish is true, it will force close channels and
 // generate frames for them.
-func (s *channelManager) getReadyChannel(l1Head eth.BlockID, forcePublish bool) (*channel, error) {
-
-	if forcePublish && s.currentChannel.TotalFrames() == 0 {
+func (s *channelManager) getReadyChannel(l1Head eth.BlockID, pi pubInfo) (*channel, error) {
+	if pi.forcePublish && s.currentChannel.TotalFrames() == 0 {
```
Comment (geoknee) [inline op-batcher/batcher/channel_manager.go:288]: Why thread the whole `pubInfo` down to this function? IIUC, it only needs the `pi.forcePublish` information, so you could keep the same API here and extract the relevant bool in the parent..

File: op-acceptance-tests/tests/batcher/init_test.go [hunk 9]
```diff
@@ -0,0 +1,33 @@
...
+		stack.MakeCommon(sysgo.WithBatcherOption(func(id stack.L2BatcherID, cfg *bss.CLIConfig) {
+			cfg.Stopped = true
+
+			// set the blob max size to 40_000 bytes for test purposes
+			cfg.MaxL1TxSize = 40_000
+			cfg.TestUseMaxTxSizeForBlobs = true
+
+			cfg.PollInterval = 1000 * time.Millisecond
+
+			cfg.MaxChannelDuration = 50 // not sure if this is reasonable, or should be larger?
```
Comment (geoknee) [inline op-acceptance-tests/tests/batcher/init_test.go]: Can we resolve this question before merging?

File: op-acceptance-tests/tests/batcher/batcher_test.go [hunk 10]
```diff
@@ -0,0 +1,132 @@
...
+		// - MaxPendingTransactions
+		// - number of blocks and transactions sent in the test - 1000 L2 blocks with 1 transaction from cathrine to alice
+		// - MaxL1TxSize (this is set to 40_000 bytes for test purposes)
+		sizeRanges := []struct {
+			min  int
+			max  int
+			note string
+		}{
+			{min: 7_000, max: 10_000, note: "channel 0 - the first 100 blocks"},
+			{min: 100, max: 1000, note: "channel 1 - only a few blocks due to racy behavior, nowhere near the channel capacity"},
```
Comment (geoknee) [inline op-acceptance-tests/tests/batcher/batcher_test.go]: Since you declare quite wide ranges here (of number of blocks per channel) to assert on, I presume this means the test is not deterministic / we get some scatter in the actual value. Can you comment on how much scatter there is? Do we expect the test to be flaky?

File: op-acceptance-tests/tests/batcher/batcher_test.go [hunk 11]
```diff
@@ -0,0 +1,132 @@
...
+		for i, entry := range sizeRanges {
+			require.LessOrEqual(t, len(channelFrames[channels[i]][0].Data), entry.max, entry.note)
+			require.GreaterOrEqual(t, len(channelFrames[channels[i]][0].Data), entry.min, entry.note)
+		}
+
+		require.Equal(t, len(l2Txs[cathrine.Address()]), 1000) // we expect 1000 transactions total sent from cathrine to alice
+	}
+
+	//sys.L2Chain.PrintChain()
+	//sys.L1Network.PrintChain()
```
Comment (geoknee) [inline op-acceptance-tests/tests/batcher/batcher_test.go]: ✂️

File: op-acceptance-tests/tests/batcher/batcher_test.go [hunk 12]
```diff
@@ -0,0 +1,132 @@
...
+		require.NoError(t, err, "Expected to be able to evaluate a planned transaction on op-test-sequencer, but got error")
+		txdata, err := signed_tx.MarshalBinary()
+		require.NoError(t, err, "Expected to be able to marshal a signed transaction on op-test-sequencer, but got error")
+
+		err = ts.IncludeTx(t.Ctx(), txdata)
+		require.NoError(t, err, "Expected to be able to include a signed transaction on op-test-sequencer, but got error")
+	}
+
+	require.NoError(t, ts.Next(t.Ctx()))
+}
```
Comment (geoknee) [inline op-acceptance-tests/tests/batcher/batcher_test.go]: Could / should these utilities be pushed down into the DSL?

File: op-batcher/batcher/channel_builder_test.go [hunk 13]
```diff
@@ -166,23 +168,6 @@ func addTooManyBlocks(cb *ChannelBuilder, blockCount int) (int, error) {
...
-		channelConfig := defaultTestChannelConfig()
-		channelConfig.MaxChannelDuration = 0
-		cb, err := newChannelBuilder(channelConfig, defaultTestRollupConfig, latestL1BlockOrigin)
-		require.NoError(t, err)
-		cb.timeout = 0
-		cb.updateDurationTimeout(l1BlockNum)
-		require.False(t, cb.TimedOut(l1BlockNum))
-	})
-}
-
```
Comment (geoknee) [inline op-batcher/batcher/channel_builder_test.go:185]: What's the justification for removing this?

File: op-devstack/dsl/l2_network.go [hunk 14]
```diff
@@ -261,3 +265,262 @@ func (n *L2Network) DisputeGameFactoryProxyAddr() common.Address {
 func (n *L2Network) DepositContractAddr() common.Address {
 	return n.inner.RollupConfig().DepositContractAddress
 }
+
+func (n *L2Network) DeriveData(blocks int) (channels []derive.ChannelID, channelFrames map[derive.ChannelID][]derive.Frame, l2Txs map[common.Address][]*ethtypes.Transaction) {
```
Comment (geoknee) [inline op-devstack/dsl/l2_network.go:269]: This is a very big function which is replicating the derivation code in op-node. 

1. Is there any way we can rely on shared code more here to prevent duplication and all the associated problems (maintenance burden etc)?

2. Could we perform a more lightweight check in the test which tells us what we need? Like the size of the batcher transactions / blobs?

Comment (geoknee) [reply op-devstack/dsl/l2_network.go:269]: I also think a unit test of the batcher's `ChannelManager` would be good, and it would be much easier to introspect the number of channels and their contents in such a test.

**Review by geoknee — COMMENTED** [review]
Looking good so far, left some nits.

My overall feedback is that I think we are using a sledgehammer to crack a nut here in terms of testing. To cover regressions / bugs in the batcher, we are relying on acceptance testing and need to add time travel (code which can run in production) to op-node, and quite a bit of testing boilerplate which duplicates derivation code just to see what the batcher ended up doing.

I'm not opposed to adding the AT and related code, but I would like to also see a more fine-grained / focussed test in the batcher channel manager if possible.

File: op-acceptance-tests/tests/batcher/init_test.go (hunk 9 above)
Comment (nonsense) [reply op-acceptance-tests/tests/batcher/init_test.go]: I will update the comment, I now know this is a reasonable value, as this is what we also use in production.

File: op-batcher/batcher/channel_builder_test.go (hunk 13 above)
Comment (nonsense) [reply op-batcher/batcher/channel_builder_test.go:185]: Fuzz testing the result of setting `MaxChannelDuration` to 0 doesn't make much sense. Fuzz testing is generally used for handling untrusted input, in this specific case, we are literally hitting an if-condition for `MaxChannelDuration` being 0.

File: op-batcher/batcher/channel_builder.go (hunk 2 above)
Comment (nonsense) [reply op-batcher/batcher/channel_builder.go:265]: The keyword `timeout` is overloaded, and we don't really need this method. We have `CheckTimeout`, `TimedOut`, `c.timeout`, `timeoutBlockNum`, etc. - when speaking about the code, it can get very confusing very fast.

Furthermore `TimedOut` is used at only 1 place, and I think it is unnecessary indirection.

File: op-batcher/batcher/channel_manager.go (hunk 3 above)
Comment (nonsense) [reply op-batcher/batcher/channel_manager.go:476]: I think the purpose of logs is for them to provide benefit not just to the users of the software, but to developers as well. I agree this is an implementation detail, but it is an important one.

File: op-devstack/dsl/l2_network.go (hunk 14 above)
Comment (nonsense) [reply op-devstack/dsl/l2_network.go:269]: The bug that is fixed in this set of PRs is an interdependence between the:
- channel manager
- tx manager and the fact that we configure a number of concurrent transactions
- backlog with many blocks that is not processed

I am not sure how we can have all this in a unit test.

Do you have a specific unit test in mind that could visualize this bugfix?

File: op-acceptance-tests/tests/batcher/batcher_test.go (hunk 10 above)
Comment (nonsense) [reply op-acceptance-tests/tests/batcher/batcher_test.go]: I define ranges because the block production is not 100% deterministic, furthermore we run this in CI, which is yet another environment.

All the timing assumptions, for example batcher pooling interval, as well as block production is not 100% deterministic, and I don't want to introduce a flaky test, even if these values are very similar/the same across many runs.

**Comment by nonsense** [comment]
> My overall feedback is that I think we are using a sledgehammer to crack a nut here in terms of testing.

This bug is due to interdependency between the channel manager, as well as the concurrent sending of transactions by the transaction manager, and the fact that one of our actors blocks only when the pending transactions are exhausted.

So I agree the test is elaborate, but I think it is necessary to have it, so that we have good coverage on one of the `happy` scenarios for the batcher - namely, *make sure that batcher processes backlogs and fills blobs fully on startup*.

> To cover regressions / bugs in the batcher, we are relying on acceptance testing and need to add time travel (code which can run in production) to op-node.

`time travel` functionality is useful for other code too. Just the other day someone asked for it, as we currently have it only on L1, and it is handy to have it for L2.

>, and quite a bit of testing boilerplate which duplicates derivation code just to see what the batcher ended up doing.

Having the derivation code in the op-acceptance-tests is useful, so that we can confirm in an integration/acceptance test if the batcher has done it's work correctly.

> I'm not opposed to adding the AT and related code, but I would like to also see a more fine-grained / focussed test in the batcher channel manager if possible.

I don't mind adding a fine-grained test (although not sure what it should be for this specific bug), but I think the integration test added here is providing good coverage, that we don't have in other tests.

File: op-acceptance-tests/tests/batcher/batcher_test.go (hunk 10 above)
Comment (geoknee) [reply op-acceptance-tests/tests/batcher/batcher_test.go]: OK that's what I suspected. I suppose what I am asking is, how do we know these ranges are sufficiently wide to prevent flakes, but also not so huge to hide anomalously high variation in block count? What values do you tend to see locally and in CI?

File: op-batcher/batcher/channel_builder_test.go (hunk 13 above)
Comment (geoknee) [reply op-batcher/batcher/channel_builder_test.go:185]: I agree that fuzzing here isn't necessary. Why not change the test to just be a simple unit test with a well chosen l1 block number?

File: op-acceptance-tests/tests/batcher/batcher_test.go (hunk 10 above)
Comment (nonsense) [reply op-acceptance-tests/tests/batcher/batcher_test.go]: I think the ranges are fine.

`> 100` ~ we have `some` data, so a good minimum
`< 1000` ~ pretty empty tx data, given that our limit is `40000` bytes
`[7000..10000]` ~ thats the size of ~100 blocks, with 1 tx in them.

The concrete values from the test are:

```
batcher_test.go:68:         INFO [0m[12-01|11:41:04.251] Channel details                          channelID\u001b[0m=16a5715e84c3a6f333940045d1b34bb0 frameCount\u001b[0m=1 dataLength_frame0\u001b[0m=7500\n"}
batcher_test.go:68:         INFO [0m[12-01|11:41:04.251] Channel details                          channelID\u001b[0m=6efd52aecce9026e3edf1de356bc8507 frameCount\u001b[0m=1 dataLength_frame0\u001b[0m=392\n"}
batcher_test.go:68:         INFO [0m[12-01|11:41:04.251] Channel details                          channelID\u001b[0m=f5b42fdf00e0136c27342751d461ac6a frameCount\u001b[0m=1 dataLength_frame0\u001b[0m=355\n"}
batcher_test.go:68:         INFO [0m[12-01|11:41:04.251] Channel details                          channelID\u001b[0m=28f9850cec15ad64fdcf3742744d4040 frameCount\u001b[0m=1 dataLength_frame0\u001b[0m=358\n"}
batcher_test.go:68:         INFO [0m[12-01|11:41:04.251] Channel details                          channelID\u001b[0m=e4a19115af815db210d6e4e174f4d8c1 frameCount\u001b[0m=1 dataLength_frame0\u001b[0m=360\n"}
batcher_test.go:68:         INFO [0m[12-01|11:41:04.251] Channel details                          channelID\u001b[0m=ac198f7b049f365ca185ec0079fbcf0e frameCount\u001b[0m=1 dataLength_frame0\u001b[0m=364\n"}
batcher_test.go:68:         INFO [0m[12-01|11:41:04.251] Channel details                          channelID\u001b[0m=e80943ab0fd2164b6e88ec344db1049f frameCount\u001b[0m=1 dataLength_frame0\u001b[0m=414\n"}
batcher_test.go:68:         INFO [0m[12-01|11:41:04.251] Channel details                          channelID\u001b[0m=74950076f77fadcf188b72546693d83f frameCount\u001b[0m=1 dataLength_frame0\u001b[0m=420\n"}
batcher_test.go:68:         INFO [0m[12-01|11:41:04.251] Channel details                          channelID\u001b[0m=858088a357630ee14366e7ada31de514 frameCount\u001b[0m=1 dataLength_frame0\u001b[0m=39935\n"}
batcher_test.go:68:         INFO [0m[12-01|11:41:04.251] Channel details                          channelID\u001b[0m=6a80dd65cbe1f344a668fa2cf82d6007 frameCount\u001b[0m=1 dataLength_frame0\u001b[0m=25611\n"}
```

File: op-devstack/dsl/l2_network.go (hunk 14 above)
Comment (geoknee) [reply op-devstack/dsl/l2_network.go:269]: As discussed on slack , I am suggesting a really simple test that just calls m.TxData with moreComing: true/false with a well chosen l1Head. It then asserts on whether any actual tx data was returned.

File: op-acceptance-tests/tests/batcher/batcher_test.go (hunk 12 above)
Comment (nonsense) [reply op-acceptance-tests/tests/batcher/batcher_test.go]: I extracted `sequenceBlock` as we use it at 2 places.

`sequenceBlockWithL1Origin` is fairly specific and since it is only used here, I'd rather we keep it here for now. No other test needs such a specific block for the test sequencer (specific L1Origin reference, and some transactions, so that block size is larger).

File: op-batcher/batcher/channel_builder_test.go (hunk 13 above)
Comment (nonsense) [reply op-batcher/batcher/channel_builder_test.go:185]: Added `TestChannelBuilder_MaxChannelDurationZero`

File: op-batcher/batcher/channel_manager_test.go [hunk 15]
```diff
@@ -318,6 +318,47 @@ func newFakeDynamicEthChannelConfig(lgr log.Logger,
...
+	// Seed channel manager with blocks
+	rng := rand.New(rand.NewSource(99))
+	for range 2 {
+		block := derivetest.RandomL2BlockWithChainId(rng, 2, defaultTestRollupConfig.L2ChainID)
+		m.blocks.Enqueue(SizedBlock{Block: block})
+	}
+
+	// Call TxData a first time - if `publishingBacklog` is `false`, channel would be timed out.
+	_, err := m.TxData(eth.BlockID{Number: 21}, false, false, pubInfo{forcePublish: false, publishingBacklog: true})
+	require.ErrorIs(t, err, io.EOF)
```
Comment (geoknee) [inline op-batcher/batcher/channel_manager_test.go]: If the channel is timed out, why does it return `io.EOF`? If the comment is correct, wouldn't we want to do the same assertions as in L354-359?

Comment (nonsense) [reply op-batcher/batcher/channel_manager_test.go]: When `publishingBacklog` is set to `true`, we essentially ignore the registering of L1 block, so channels don't time out. So `io.EOF` is expected here.

On the second call to `TxData` we have `publishingBacklog` set to `false`, and then registering of L1 block kicks in, and channel is timed out.

Comment (geoknee) [reply op-batcher/batcher/channel_manager_test.go]: I see, this is like a counterfactual comment. Ideally we should add "since it is set to true, the channel does not time out".

Comment (nonsense) [reply op-batcher/batcher/channel_manager_test.go]: I updated the comment so that it is clearer.

File: op-batcher/batcher/channel_manager.go (hunk 4 above)
Comment (geoknee) [reply op-batcher/batcher/channel_manager.go:277]: Filed this https://github.com/ethereum-optimism/optimism/issues/18479

File: op-acceptance-tests/tests/batcher/batcher_test.go [hunk 16]
```diff
@@ -0,0 +1,116 @@
...
+
+		for i := 0; i < 5; i++ {
+			l.Debug("Sequencing L2 block", "iteration", i, "parent", parent)
+			sequenceBlockWithL1Origin(t, ts_L2, parent, l1Origin, alice, cathrine, nonce)
+			nonce++
+
+			parent = sys.L2CL.HeadBlockRef(types.LocalUnsafe).Hash
+
+			sys.AdvanceTime(time.Second * 2)
+			time.Sleep(20 * time.Millisecond) // failed to force-include tx: type: 2 sender; err: nonce too high
```
Comment (geoknee) [inline op-acceptance-tests/tests/batcher/batcher_test.go:51]: 1. Why do we need this? Slightly concerned it could be another source of flakiness when run in CI. 
2. What does the comment refer to? Is it the error we get if we don't wait?

Comment (nonsense) [reply op-acceptance-tests/tests/batcher/batcher_test.go:51]: When sequencing of blocks is so fast, the tx manager could get outdated nonce - i.e. you correctly submit a tx with nonce 20, but the tx pool thinks that the next nonce should be 19, because it is not fully updated (hence why I left the comment).

This is probably not an issue for regular blocks (2 seconds), or flash blocks (100-200ms), but here generation of blocks was even faster, so this issue becomes visible.

20 milliseconds seems to be enough, even without the time.Sleep, the test was passing most of the time, so I don't think it will be flaky.

Comment (geoknee) [reply op-acceptance-tests/tests/batcher/batcher_test.go:51]: OK, if we hit flakes we can circle back here and try to wait on the nonce being correct instead of waiting.

**Review by geoknee — APPROVED** [review]
