### PR TITLE
op-proposer: retry failed output proposals

### LINKED ISSUE #11266: op-proposer: Retry getting output root on error
The op-proposer doesn't currently retry getting the output root. Instead, it just waits for a full interval to retry. This affects, both the old L200 and new DGF code paths.

Easy fix could be to just add a parameter like `OutputRetryInterval` to the config and retry in both L2OO and GDF loops getting the output root with this retry interval.

### PR DESCRIPTION
**Pull request by bitwiseguy**
## Description

The op-proposer doesn't currently retry getting the output root. Instead, it just waits for a full interval to retry. This pr allows op-proposer to be configured with a new `OutputRetryInterval` parameter, which determines the time until a retry is attempted if a previous attempt fails.

## Tests

Added unit tests for op-proposer driver. Updated e2e tests to include the new param in all instances where a new `Proposer` is instantiated.

## Metadata

- Fixes https://github.com/ethereum-optimism/optimism/issues/11266

### CODE REVIEW

File: op-proposer/proposer/driver.go
Comment (bitwiseguy) [inline op-proposer/proposer/driver.go:1]: Should [this](https://github.com/ethereum-optimism/optimism/pull/11291/files#diff-afaa28b7b15c05e8f0ad1e91973363f5972a448620fcb20224a8923bbf18eb75R405-R406) also return an error so that it triggers an output proposal retry? Or is a reverted tx not a case where we want a retry?

File: op-proposer/proposer/driver.go [hunk 1]
```diff
@@ -471,27 +490,48 @@ func (l *L2OutputSubmitter) loopL2OO(ctx context.Context) {
...
-			}
-
-			output, shouldPropose, err := l.FetchOutput(ctx, blockNumber)
-			if err != nil || !shouldPropose {
-				break
+			retryOutputProposal = proposeOutput()
+		case <-retryTicker.C:
+			if retryOutputProposal {
+				l.Log.Info("retrying output proposal")
+				retryOutputProposal = proposeOutput()
```
Comment (bitwiseguy) [inline op-proposer/proposer/driver.go]: I need to find the best spot to test this code. There aren't currently many tests in op-proposer, so leaning towards adding a op-e2e test. Open to suggestions though!

Comment (tynes) [reply op-proposer/proposer/driver.go]: This approach seems kind of complex since it depends on behavior of `select`. Wouldn't it be better to wrap our retry helpers around functions like this one? https://github.com/ethereum-optimism/optimism/blob/59fbf91ec45f0c636d37b4c7bbab3bb7a1c79440/op-proposer/proposer/driver.go#L281

That would prevent the error from bubbling up in the first place

File: op-proposer/flags/flags.go [hunk 2]
```diff
@@ -60,6 +60,12 @@ var (
 		Usage:   "Interval between submitting L2 output proposals when the dispute game factory address is set",
 		EnvVars: prefixEnvVars("PROPOSAL_INTERVAL"),
 	}
+	ProposalRetryIntervalFlag = &cli.DurationFlag{
+		Name:    "proposal-retry-interval",
+		Usage:   "Interval between retrying output proposals if one fails",
+		Value:   120 * time.Second,
```
Comment (sebastianst) [inline op-proposer/flags/flags.go]:
```suggestion
		Value:   time.Minute,
```
I think 1 minute is also OK.

File: op-proposer/proposer/driver.go (hunk 1 above)
Comment (sebastianst) [reply op-proposer/proposer/driver.go]: I agree, I think a simpler solution is really to just wrap the `l.FetchOutput(ctx, blockNumber)` call in `retry.Do2` call with a `retry.Fixed` strategy, and otherwise restore the old code. Applies to both, L2OO and DGF.

The `l.proposeOutput(ctx, output)` call shouldn't be part of the retry, as retrying failing txs is already handled within the txmgr.

File: op-proposer/proposer/driver.go
Comment (sebastianst) [reply op-proposer/proposer/driver.go:1]: The retrying should just be scoped to getting the output, not the tx sending itself. The txmgr already handles tx sending instability.

File: op-e2e/actions/l2_proposer.go [hunk 3]
```diff
@@ -31,6 +31,7 @@ type ProposerCfg struct {
 	OutputOracleAddr       *common.Address
 	DisputeGameFactoryAddr *common.Address
 	ProposalInterval       time.Duration
+	ProposalRetryInterval  time.Duration
```
Comment (sebastianst) [inline op-e2e/actions/l2_proposer.go:35]: Maybe we rename this `OutputRetryInterval` because it really describes retrying getting the output, not submitting the proposal. Same for the flag etc.

File: op-proposer/proposer/driver.go (hunk 1 above)
Comment (sebastianst) [reply op-proposer/proposer/driver.go]: As for the test, you could write two unit tests for the two loops `loopL2OO` and `loopDGF` using a mock `RollupProvider` that returns a mock `RollupClient` and then set the mock up to return a couple of errors before returning the right value (and also set the mock up to return a sync status). There are other tests that set these mocks up already, and the generated mocks already exist.

You would also need to set up the `Txmgr` mock and assert that it receives a correct `Send` call and a bunch of other getter calls.

These are two non-trivial tests to add, but a nice bonus is that we'd finally have unit tests of the proposer loops, which are currently missing.

**Review by sebastianst — CHANGES_REQUESTED** [review]
Retrying should only be scoped to getting the output.

Added a suggestion on how to set up unit tests of the loops.

File: op-proposer/proposer/driver.go (hunk 1 above)
Comment (bitwiseguy) [reply op-proposer/proposer/driver.go]: Any reason we wouldn't also want to wrap the retry helper around this request inside the `loopDGF`?
```
			blockNumber, err := l.FetchCurrentBlockNumber(ctx)
			if err != nil {
				break
			}
```

Comment (bitwiseguy) [reply op-proposer/proposer/driver.go]: @sebastianst any suggestions for how to mock out [this contract call](https://github.com/ethereum-optimism/optimism/blob/develop/op-proposer/proposer/driver.go#L223)? Do we have any examples of mocking one of those huge contract bindings interfaces anywhere else? I only need to mock that one method so trying not to create a huge mock with a bunch of unused code if possible.

Maybe I should just create a mock of the L1Client [here](https://github.com/ethereum-optimism/optimism/blob/develop/op-proposer/proposer/driver.go#L31-L40)? That is what gets used to create the contract binding instance [here](https://github.com/ethereum-optimism/optimism/blob/develop/op-proposer/proposer/driver.go#L100). Then I can mock the lower level `L1Client.CallContract` method

Comment (sebastianst) [reply op-proposer/proposer/driver.go]: sorry for the confusion @bitwiseguy we totally should also include `l.FetchCurrentBlockNumber(ctx)` in the retrying.

Comment (sebastianst) [reply op-proposer/proposer/driver.go]: Oh I see the issue with mocking the contract calls. Maybe what we do is just use an interface for the `l2ooContract` field, we only access the two methods `NextBlockNumber` and `Version`. You can then set that field in the test to a mock. Sorry for the mocking mess.

Comment (sebastianst) [reply op-proposer/proposer/driver.go]: I think the test can just create the proposer struct directly and only test the loops, so we don't need use any of the `new*Submitter` functions.

Comment (bitwiseguy) [reply op-proposer/proposer/driver.go]: Yea good idea to use interface for `l2ooContract`. I will try that.

For the test is it acceptable to trigger the `loopL2OO` and then just set a sleep/timer long enough that we know some retries are triggered, then check that mocked functions were called as expected? Generally I try to avoid sleep/timer in tests but not sure if there is a better way in this case since `loopL2OO` runs a forever loop

Comment (sebastianst) [reply op-proposer/proposer/driver.go]: We can set the proposer and retry intervals super short in the test, maybe even to 0. Then the mock could be set up so that the n'th time `SendTransaction` is called, it closes the `l.done` channel and the loop should return.

Comment (ajsutton) [reply op-proposer/proposer/driver.go]: Not sure if it helps in this case, but we do have [a clock abstraction](https://github.com/ethereum-optimism/optimism/blob/770d37f86fccec38596a134bf9bbe075f08ebd10/op-service/clock/clock.go#L12) in `op-service/clock` which has a test stub so you can deterministically control time, including stepping forward a certain amount of time and having any created timers trigger deterministically.

File: op-proposer/proposer/driver.go [hunk 4]
```diff
@@ -226,88 +228,91 @@ func (l *L2OutputSubmitter) FetchNextOutputInfo(ctx context.Context) (*eth.Outpu
...
+	// Always propose if it's part of the Finalized L2 chain. Or if allowed, if it's part of the safe L2 chain.
+	if output.BlockRef.Number > output.Status.FinalizedL2.Number && (!l.Cfg.AllowNonFinalized || output.BlockRef.Number > output.Status.SafeL2.Number) {
+		l.Log.Debug("Not proposing yet, L2 block is not ready for proposal",
+			"l2_proposal", output.BlockRef,
+			"l2_safe", output.Status.SafeL2,
+			"l2_finalized", output.Status.FinalizedL2,
+			"allow_non_finalized", l.Cfg.AllowNonFinalized)
+		return output, false, nil
+	}
+	return output, true, nil
```
Comment (bitwiseguy) [inline op-proposer/proposer/driver.go:262]: Suggestion: reverse the logic of the `if` statement so that its checking for the conditions that allow a proposal, and the `else` statement causes the `l.Log.Debug`. That would make the `if` logic and the comment above it match a bit better

File: op-proposer/proposer/driver.go [hunk 5]
```diff
@@ -478,26 +497,37 @@ func (l *L2OutputSubmitter) loopL2OO(ctx context.Context) {
...
+			var (
+				output *eth.OutputResponse
+				err    error
+			)
+			// A note on retrying: because the proposal interval is usually much
+			// larger than the interval at which to retry proposing on a failed attempt,
+			// we want to keep retrying getting the output proposal until we succeed.
+			for output == nil || err != nil {
+				output, err = l.FetchDGFOutput(ctx)
+				if err != nil {
```
Comment (bitwiseguy) [inline op-proposer/proposer/driver.go:526]: Should this be `if output == nil || err != nil` to match the `for` loop condition above? Or do we only care about the `err` value inside this loop?

Comment (sebastianst) [reply op-proposer/proposer/driver.go:526]: The `output == nil` condition is for the first iteration, when `err == nil`. When we check the error, we already set `output, err`, so we only need to check for the error.

File: op-proposer/proposer/driver.go (hunk 4 above)
Comment (sebastianst) [reply op-proposer/proposer/driver.go:262]: I didn't modify this bit of code, it just shows up because it got moved around. I can see how it could be easier to read, but then there's also the argument to first test for all conditions that prevent proposing, and then only at the end return `true`. So since I didn't modify it, and there are arguments for both, I prefer to just keep it as is for now.

**Review by sebastianst — APPROVED** [review]

**Comment by sebastianst** [comment]
I realized that the two loops work quite differently, which explains why we suddenly have this problem with long intervals and missing retries for the DGF. In the L2OO case, we regularly poll the contract for when to propose next. This solves both, correct intervals across restarts, and continuous retrying. In the DGF case, the proposer has to watch itself for the correct proposal intervals. And this explains why the outer loop was a ticker with a proposal interval duration, which meant retries would only happen every hour.

The unit test also nicely caught a race condition between the ticker and the `done` channel.

File: op-proposer/proposer/driver.go [hunk 6]
```diff
@@ -468,20 +497,37 @@ func (l *L2OutputSubmitter) loopL2OO(ctx context.Context) {
...
+					l.Log.Warn("Error getting DGF output, retrying...", "err", err)
+					time.Sleep(l.Cfg.OutputRetryInterval)
```
Comment (ajsutton) [inline op-proposer/proposer/driver.go:528]: Shutdown will get stuck while this is happening. Should we be checking the quit signal in this inner loop?

**Review by ajsutton — APPROVED** [review]
LGTM, just the one question about avoiding delaying shutdown too much.

File: op-proposer/proposer/driver.go (hunk 6 above)
Comment (sebastianst) [reply op-proposer/proposer/driver.go:528]: good catch

Comment (sebastianst) [reply op-proposer/proposer/driver.go:528]: moved the check into the inner loop, at the start
