### PR TITLE
interop: address strong-consistency review follow-ups (#19561)

### LINKED ISSUE #19561: interop: follow-up items from strong-consistency review
## Context

Follow-up items from Adrian's review of #19505 (interop: add strong consistency guarantees). These are the items that require more than a trivial fix.

### 1. Tests should pass a no-op `l1Checker` instead of nil check
[Review comment](https://github.com/ethereum-optimism/optimism/pull/19505#discussion_r2937364078)

`l1Checker` is only ever nil in tests. Tests should pass a no-op l1Checker and the `if i.l1Checker != nil` guard in `observeRound` should be removed — not having an l1Checker in production would be a significant issue.

### 2. `Decision` enum WAL serialization resilience
[Review comment](https://github.com/ethereum-optimism/optimism/pull/19505#discussion_r2937399214)

`Decision` is serialized to JSON as a bare integer via `iota`. If the enum order is ever changed or a new variant inserted, any pending WAL entry written by a previous binary would be silently misinterpreted on restart. Consider assigning explicit numeric values or using string-based serialization (`MarshalJSON`/`UnmarshalJSON` returning `"advance"`, `"invalidate"`, etc.).

### 3. Idempotent replay should compare deserialized structs, not raw bytes
[Review comment](https://github.com/ethereum-optimism/optimism/pull/19505#discussion_r2937399277)

The idempotent replay check in `VerifiedDB.Commit()` uses `bytes.Equal` on JSON-serialized `VerifiedResult`. Go's `encoding/json` does not guarantee byte-stable output across Go versions. If a node crashes after `Commit()` succeeds but before `ClearPendingTransition()`, and restarts on a newer Go version, the re-serialized value could differ, turning an idempotent replay into a hard `ErrAlreadyCommitted` failure. Compare the deserialized structs instead.

### 4. Add rewind replay test after partial failure
[Review comment](https://github.com/ethereum-optimism/optimism/pull/19505#discussion_r2937413264)

`TestPendingTransition_RecoverRewindPreservedOnFailure` verifies the WAL is preserved when rewind fails, but doesn't test the second attempt — the actual replay. Add a test that: (1) fails chain B on first attempt, (2) fixes chain B, (3) replays via `progressAndRecord`, (4) verifies both chains end up correct and the WAL is cleared.

### 5. Integration tests should exercise `progressAndRecord` directly
[Review comment](https://github.com/ethereum-optimism/optimism/pull/19505#discussion_r2937429822)

The compat shims used by `TestInterop_FullCycle` and most `TestProgressInterop*` tests bypass the WAL entirely. The core correctness property (WAL write → apply → clear) is not exercised. Two suggestions:
- Add an integration test using `progressAndRecord` directly for multiple advance cycles
- Add an end-to-end test for L1-inconsistency → rewind through `progressAndRecord`

### 6. Pass `frontierView` through call chain instead of storing as struct field
[Review comment](https://github.com/ethereum-optimism/optimism/pull/19505#discussion_r2937449091)

Non-blocking nit: `frontierView` is only non-nil during `verify()` but as a struct field it looks like persistent state. Passing it through the call chain would make the lifetime explicit in the type signatures. Requires updating `verifyFn`/`cycleVerifyFn` function types and ~10-12 test stubs.

### 7. Narrow `ChainContainer` interface so reorg-triggering operations are only accessible to interop
[Review comments](https://github.com/ethereum-optimism/optimism/pull/19505#discussion_r2937526917) / [also](https://github.com/ethereum-optimism/optimism/pull/19505#discussion_r2937529321)

The TODO about removing the footgun (reorg-triggering operations exposed on ChainContainer) appears four times across `chain_container.go` and `invalidation.go`. This tracking issue captures that follow-up: move reorg-triggering operations behind a smaller interop-owned interface so that `RewindEngine` and `InvalidateBlock` are only callable from interop transition application.

### 8. Remove legacy DenyRecord backward compatibility after devnet reset
[Review comment](https://github.com/ethereum-optimism/optimism/pull/19505#discussion_r2937413341)

Once the internal devnet is reset, remove the legacy `decodeDenyRecords` backward-compatibility path (concatenated 32-byte hashes). Knowing that all `DenyRecord` instances have a `DecisionTimestamp` would simplify reasoning about the code.

## Related PR
- #19505

### PR DESCRIPTION
**Pull request by wwared**
## Summary

Closes #19561 — the follow-up issue that captured the non-trivial review feedback on #19505 (interop: add strong consistency guarantees). Each item is its own commit so they can be reviewed and reverted independently.

| # | Commit | What changes |
|---|--------|--------------|
| 1 | `interop: replace nil-check with no-op l1Checker in tests` | `byNumberConsistencyChecker` becomes the `l1ConsistencyChecker` interface; concrete prod impl stays as `l1ByNumberChecker`. Test harness injects a `noopL1Checker{}`. The `if i.l1Checker != nil` guard in `observeRound` is removed — production now requires a real checker. |
| 2 | `interop: serialize Decision as a string in the WAL` | `Decision` round-trips as `"wait" / "advance" / "invalidate" / "rewind"` via `MarshalJSON` / `UnmarshalJSON`. Marshal rejects unknown ints; Unmarshal rejects unknown strings and non-strings. WAL is now resilient to enum re-ordering or new variants. |
| 3 | `interop: compare deserialized VerifiedResult on idempotent replay` | `VerifiedDB.Commit` decodes the existing stored value and compares with `reflect.DeepEqual` instead of `bytes.Equal` on JSON output. Removes a Go-version-dependent failure mode where a re-marshal on a newer Go could turn an idempotent replay into `ErrAlreadyCommitted`. New test writes indented JSON straight into the bucket to exercise the byte-divergent / struct-equal path. |
| 4 | `interop: add rewind-replay-after-failure test` | Existing `TestPendingTransition_RecoverRewindPreservedOnFailure` only covered the first attempt. New `TestPendingTransition_RewindReplaysAfterFailure` drives the failure → fix → replay loop end-to-end via `progressAndRecord` and asserts the WAL is cleared and `RewindEngine` was called on both attempts. |
| 5 | `interop: add progressAndRecord integration tests` | `TestInterop_FullCycle` and most `TestProgressInterop*` tests bypass the WAL through `progressInteropCompat` / `applyResultCompat` shims. Added two new tests that drive the real `progressAndRecord` path: a multi-cycle advance (asserts WAL cleared after every cycle, logsDB sealed through the latest ts) and an L1-inconsistency → rewind (drives a flipped `inconsistentL1Checker{}` and asserts the full WAL → apply → clear cycle, with `RewindEngine` called exactly once). Existing compat-shim tests untouched. |
| 6 | `interop: pass frontierView through call chain` | `frontierView` was a struct field on `Interop` only non-nil during `verify()`. Moves it into the call signature: `verifyFn` and `cycleVerifyFn` now take `view *frontierVerificationView`, and `verifyInteropMessages`, `verifyExecutingMessage`, `verifyCycleMessages` accept it explicitly. Lifetime is now visible in the type signatures. |
| 7 | `interop: hide reorg ops behind InteropChain interface` | Drops `RewindEngine` / `InvalidateBlock` from `ChainContainer`. New `InteropChain` interface (in chain_container.go, fronted by a banner-style WARNING) embeds `ChainContainer` and adds the two reorg-triggering methods. `Supernode.chains` is `map[ChainID]cc.InteropChain`; supernode builds a narrower `ChainContainer` map for heartbeat / supernode / superroot activities so they cannot call the reorg methods at compile time. Removes the four `TODO(#19561)` "footgun" comments and the dead `RewindEngine` / `InvalidateBlock` stubs from the superroot / supernode test mocks. |

### WAL compatibility note (item 2)

The string-based `Decision` encoding is **not backward-compatible with on-disk WAL entries written by the previous integer encoding** — a node restarting with this PR over a pre-existing pending transition will fail to unmarshal it. The intended upgrade path is to ensure no pending transition exists before upgrading (let the node drain its WAL first) or to reset the devnet entirely. This mostly matters for the internal devnet; there is no production deployment yet.

### Item 8 (legacy `decodeDenyRecords`)

Already resolved by #19839 (commit 6cdfde0837): the concatenated-32-byte-hash decode path was removed and `DenyRecord` always carries a `DecisionTimestamp`. No commit was needed in this PR. After this PR lands the issue can be closed.

## Test plan

- [x] `mise exec -- go test ./op-supernode/...` (all packages green)
- [x] `mise exec -- ./linter/bin/op-golangci-lint run ./op-supernode/...` (0 issues)
- [x] `mise exec -- go build ./...` (whole-repo build clean)
- [x] CI green on this branch

### CODE REVIEW

File: op-supernode/supernode/activity/interop/algo_test.go [hunk 1]
```diff
@@ -48,7 +48,7 @@ type verifyInteropTestCase struct {
 func runVerifyInteropTest(t *testing.T, tc verifyInteropTestCase) {
 	t.Parallel()
 	interop, timestamp, blocks := tc.setup()
-	result, err := interop.verifyInteropMessages(timestamp, blocks)
+	result, err := interop.verifyInteropMessages(timestamp, blocks, nil)
```
Comment (ajsutton) [inline op-supernode/supernode/activity/interop/algo_test.go:51]: How does this not crash with a nil pointer?

**Review by ajsutton — APPROVED** [review]
LGTM, just the one query about the test passing nil as the view but it seems to work so not a blocker.

File: op-supernode/supernode/activity/interop/algo_test.go (hunk 1 above)
Comment (wwared) [reply op-supernode/supernode/activity/interop/algo_test.go:51]: It's a bit tricky, but this is actually a typed nil pointer (of type `*frontierVerificationView`), so it calls into this function which exits early because it never dereferences `v`:
https://github.com/ethereum-optimism/optimism/blob/f6746efc891e6b9161c31497a9f8a9aa1c59c3f2/op-supernode/supernode/activity/interop/verification_view.go#L93-L95
The same happens here:
https://github.com/ethereum-optimism/optimism/blob/f6746efc891e6b9161c31497a9f8a9aa1c59c3f2/op-supernode/supernode/activity/interop/verification_view.go#L101-L105
