### PR TITLE
fix(sdk): bug in supportsTokenPair

### LINKED ISSUE #8154: ECOBridgeAdapter breaks the SDK
**Describe the bug**
Was trying to use the SDK to do a deposit, when approving the token there's a call to `supportsTokenPair` for the `ECOBridgeAdapter`. However since there's no try/catch in this adapter, it tries to call the `l2Eco` function which reverts if the token doesn't have an `l2Eco` function, which causes the function to fail. See [here](https://github.com/ethereum-optimism/optimism/blob/111f3f3a3a2881899662e53e0f1b2f845b188a38/packages/sdk/src/adapters/eco-bridge.ts#L14).

Fix is easy, wrap the call in try/catch to handle the case where `l2Eco` or `l1Eco` doesn't exist as a function on the token.

### PR DESCRIPTION
**Pull request by smartcontracts**
Fixes a bug in the supportsTokenPair where unsupported token interfaces would cause the SDK to error out. Happens because the adapters check for things that are only present in certain types of tokens. Adds a new error handling check that wraps all sub-calls to supportsTokenPair in each of the adapters so that the adapters don't need to worry about this.

Fixes #8154

### CODE REVIEW

File: packages/sdk/src/cross-chain-messenger.ts [hunk 1]
```diff
@@ -490,8 +490,17 @@ export class CrossChainMessenger {
...
-        bridges.push(bridge)
+      try {
+        if (await bridge.supportsTokenPair(l1Token, l2Token)) {
+          bridges.push(bridge)
+        }
+      } catch (err) {
+        if (
+          !err?.message?.toString().includes('CALL_EXCEPTION') &&
+          !err?.stack?.toString().includes('execution reverted')
+        ) {
```
Comment (roninjin10) [inline packages/sdk/src/cross-chain-messenger.ts:501]: Unrelated to pr but this is disgusting and I wish the json rpc spec better specified errors

**Review by roninjin10 — APPROVED** [review]

**Review by roninjin10 — CHANGES_REQUESTED** [review]
Needs a changeset actually

**Review by roninjin10 — APPROVED** [review]
