### PR TITLE
fix(kona/derive): add over-fill check in BlobSource::load_blobs

### LINKED ISSUE #19363: kona: BlobSource::load_blobs silently ignores over-fill instead of returning Reset error
## Summary

`BlobSource::load_blobs` in kona's derivation pipeline is missing a post-loop over-fill check. After the fill loop completes, if the blob provider returned more blobs than were requested (i.e. `blob_index < blobs.len()`), kona silently discards the extra blobs with no error. The Go op-node reference implementation treats this condition as a Reset-level error.

## Go Reference Behaviour

In `op-node`, `fillBlobPointers` at [`blob_data_source.go:162-164`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/op-node/rollup/derive/blob_data_source.go#L162) performs this check after the fill loop:

```go
if blobIndex != len(blobs) {
    return fmt.Errorf("got too many blobs")
}
```

This error is then wrapped as `NewResetError` at the call site (`blob_data_source.go:110`), causing the pipeline to reset and retry rather than silently accepting a malformed provider response.

## Kona Subject Location

[`blobs.rs:164-173`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/rust/kona/crates/protocol/derive/src/sources/blobs.rs#L164) — the fill loop ends at line 173 with no subsequent check:

```rust
// Fill the blob pointers.
let mut blob_index = 0;
for blob in &mut data {
    let should_increment = blob
        .fill(&blobs, blob_index)
        .map_err(|e| -> PipelineErrorKind { e.into() })?;
    if should_increment {
        blob_index += 1;
    }
}
// ← no check that blob_index == blobs.len() here
```

## When This Can Occur

While uncommon, this situation can arise in practice:

- **Buggy L1 providers**: A beacon/blob provider that returns more blobs than requested (not spec-compliant but not unheard-of with third-party providers).
- **L1 reorgs**: In rare reorg scenarios the set of blob transactions referenced by an L1 block can shift between the time the hashes are collected and the time the blobs are fetched, resulting in a count mismatch.

## Proposed Fix

After the fill loop in `load_blobs`, add a post-loop check:

```rust
if blob_index < blobs.len() {
    return Err(ResetError::BlobsOverFill(blob_index, blobs.len()).reset());
}
```

A new `ResetError::BlobsOverFill(usize, usize)` variant should be added (symmetric to the existing `BlobsUnderFill` variant), mapping to `PipelineErrorKind::Reset`. This mirrors `op-node`'s `NewResetError` wrapping and ensures the pipeline resets and retries rather than silently accepting an inconsistent provider response.

## References

- Subject: https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/rust/kona/crates/protocol/derive/src/sources/blobs.rs#L164
- Reference: https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/op-node/rollup/derive/blob_data_source.go#L162

### PR DESCRIPTION
**Pull request by ajsutton**
## Summary

`BlobSource::load_blobs` was missing a post-loop over-fill check. After the blob-pointer fill loop completes, if `blob_index < blobs.len()` the blob provider returned more blobs than were requested. Previously kona silently discarded the extra blobs. This PR adds a guard that returns `ResetError::BlobsOverFill` (→ `PipelineErrorKind::Reset`) in that case, mirroring the op-node reference.

## Background

The Go op-node performs this check in `fillBlobPointers` in [`blob_data_source.go`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/op-node/rollup/derive/blob_data_source.go#L162):

```go
if blobIndex != len(blobs) {
    return fmt.Errorf("got too many blobs")
}
```

This error is wrapped as `NewResetError` at the call site, causing the pipeline to reset and retry from a clean state. Kona was missing the over-fill check; under-fill is handled separately via `BlobDecodingError::InvalidLength` in `BlobData::fill()`.

## When Over-fill Can Occur

- **Buggy L1 providers**: A beacon/blob provider that returns more blobs than requested (not spec-compliant but observed in practice with third-party providers).
- **Rare L1 reorg scenarios**: The set of blob transactions referenced by an L1 block can shift between the time the hashes are collected and the time the blobs are fetched, resulting in a count mismatch.

## Changes

- Add `ResetError::BlobsOverFill(usize, usize)` variant to `pipeline.rs` (addresses the over-fill case; under-fill is handled separately via `BlobDecodingError::InvalidLength` in `BlobData::fill()`).
- Import `ResetError` in `blobs.rs` and add the post-loop check after the fill loop.
- Add `should_return_extra_blob` flag to `TestBlobProvider` for testing.
- Add `test_load_blobs_overfill_triggers_reset` regression test.

## Testing

```
cargo test --package kona-derive sources::blobs
```

All 12 tests pass, including the new `test_load_blobs_overfill_triggers_reset`.

Fixes https://github.com/ethereum-optimism/optimism/issues/19363

### CODE REVIEW

**Review by ajsutton — COMMENTED** [review]
Remove references to matching op-node.

Reduce the number and verbosity of comments. No need to explain the same thing multiple times.

**Review by ajsutton — COMMENTED** [review]
LGTM. Correct fix matching Go's `fillBlobPointers` over-fill check.

Two minor notes:

1. **PR body inaccuracy**: The description says this is "symmetric with the existing `BlobsUnderFill` variant," but no `BlobsUnderFill` variant exists. Under-fill is handled inside `BlobData::fill()` via `BlobDecodingError::InvalidLength`. The `BlobsOverFill` name is fine on its own, but the symmetry claim is misleading.

2. **Comment line-number references**: The comments reference specific Go line numbers (e.g., `blob_data_source.go:162`). These go stale quickly — consider referencing just the function name (`fillBlobPointers`) instead.

File: rust/kona/crates/protocol/derive/src/errors/pipeline.rs [hunk 1]
```diff
@@ -353,6 +353,15 @@ pub enum ResetError {
...
     BlockNotFound(BlockId),
+    /// The blob provider returned more blobs than were requested (over-fill). The first argument
+    /// is the number of blob placeholders filled; the second is the total number of blobs
+    /// returned. This matches the check in `fillBlobPointers` in `blob_data_source.go`
+    /// which returns `fmt.Errorf("got too many blobs")` wrapped as `NewResetError`. Can occur
+    /// with buggy blob providers or in rare L1 reorg scenarios.
+    #[error(
+        "Blob provider over-fill: filled {0} blob placeholders but provider returned {1} blobs"
+    )]
+    BlobsOverFill(usize, usize),
```
Comment (theochap) [inline rust/kona/crates/protocol/derive/src/errors/pipeline.rs]: Let's use named fields here instead of anonymous tuple types

File: rust/kona/crates/protocol/derive/src/sources/blobs.rs [hunk 2]
```diff
@@ -173,6 +173,15 @@ where
             }
         }
 
+        // Post-loop over-fill check: if the provider returned more blobs than were
+        // requested, the pipeline state is inconsistent. Reset so the pipeline retries
+        // from a clean state. Matches the check in `fillBlobPointers` in
+        // blob_data_source.go which returns `fmt.Errorf("got too many blobs")`
+        // wrapped as `NewResetError`.
+        if blob_index < blobs.len() {
```
Comment (theochap) [inline rust/kona/crates/protocol/derive/src/sources/blobs.rs]: Independent of this PR, but `blob_index` is a confusing name in my opinion. This should be more like `expected_blobs`

**Review by theochap — APPROVED** [review]
Looks good, two nits

File: rust/kona/crates/protocol/derive/src/sources/blobs.rs (hunk 2 above)
Comment (ajsutton) [reply rust/kona/crates/protocol/derive/src/sources/blobs.rs]: Renamed to `filled_blobs`.
