### PR TITLE
cannon: Fix parentheses in syscall noop handling

### LINKED ISSUE #13427: Incorrect parentheses in handleSyscall in mips.go
Per a Spearbit audit:

The line in mips.go:214,
```go
if arch.IsMips32 && syscallNum == arch.SysFstat64 || syscallNum == arch.SysStat64 || syscallNum == arch.SysLlseek {
```
should read
```go
if arch.IsMips32 && (syscallNum == arch.SysFstat64 || syscallNum == arch.SysStat64 || syscallNum == arch.SysLlseek) {
```
instead.

On mips32, there is a differentiation between 32-bit versions of these syscalls and 64-bit versions. But on mips64, the "regular" syscalls are already 64 bit, so the constants `arch.SysFstat64`, `arch.SysSta64` and `arch.SysLlseek` are all defined as `^Word(0)`. This means that this bug does not manifest on mips64.

### PR DESCRIPTION
**Pull request by Inphi**
Fix grouping of conditions in syscall noop handling in mt-cannon. This does not alter the behavior of the VMs as explained below.

## Testing

Not necessary. The behavior doesn't change on cannon32.
And on cannon64, the 64-bit syscalls that are found in the 32-bit syscall table uses an undefined syscall number (`^uint64(0)`). Thus the noop codepath isn't reachable on cannon64.

## Meta

Fixes https://github.com/ethereum-optimism/optimism/issues/13427

### CODE REVIEW

File: cannon/mipsevm/multithreaded/mips.go [hunk 1]
```diff
@@ -212,7 +212,7 @@ func (m *InstrumentedState) handleSyscall() error {
 	case arch.SysLseek:
 	default:
 		// These syscalls have the same values on 64-bit. So we use if-stmts here to avoid "duplicate case" compiler error for the cannon64 build
-		if arch.IsMips32 && syscallNum == arch.SysFstat64 || syscallNum == arch.SysStat64 || syscallNum == arch.SysLlseek {
+		if arch.IsMips32 && (syscallNum == arch.SysFstat64 || syscallNum == arch.SysStat64 || syscallNum == arch.SysLlseek) {
```
Comment (mbaxter) [inline cannon/mipsevm/multithreaded/mips.go:215]: I think it's worth adding a test for this.  We would just need to append `arch.UndefinedSysNr` to the `unsupportedSyscalls` [here](https://github.com/ethereum-optimism/optimism/blob/89f623e3d9b9c9591d21750707de89d97288140b/cannon/mipsevm/tests/evm_multithreaded64_test.go#L474).

Comment (Inphi) [reply cannon/mipsevm/multithreaded/mips.go:215]: The undefined syscall number is a fully set 64-bit value. This was chosen to avoid the possibility of conflicting syscall numbers as syscalls are 32-bit values.

As such, adding undefined syscalls to the unsupported syscall table requires retyping the syscall numbers in tests. I think this creates confusion in how such syscalls are tested for little benefit. And this is only sorta useful to test the unreachable codepath on cannon64. Because on cannon32, the parenthesis fix doesn't change the actual logic for no-op handling - thus you can't write a cannon32 test for this issue.

Comment (Inphi) [reply cannon/mipsevm/multithreaded/mips.go:215]: I guess to minimize confusion in the test, I'll create a special test for the undefined case. Let me see if that's doable.

Comment (Inphi) [reply cannon/mipsevm/multithreaded/mips.go:215]: Added a cannon64 test case for the undefined code path.

**Review by mbaxter — APPROVED** [review]
