### PR TITLE
fix[smock]: add support for hardhat 2.4.0

### LINKED ISSUE #1110: Smock doesn't work with Hardhat 2.4.0
**Describe the bug**

When a project using Smock upgrades to Hardhat 2.4.0, it stops working because `hardhat/internal/hardhat-network/stack-traces/revert-reasons` doesn't exist anymore.

We now have a class in `hardhat/internal/hardhat-network/provider/return-data` that deals with revert reasons, panic codes and custom errors.

BTW, we are planning to start using `package.json`'s `exports` field some time in the future, and as a side-effect, things from `internal/` won't be exposed anymore. We will keep you posted about this, and help you make Smock work without internal APIs.

**To Reproduce**

This was reported by Synthetix. Cloning their repo and upgrading Hardhat should work. It's probably easier to reproduce it in a new project though.

### PR DESCRIPTION
**Pull request by smartcontracts**
**Description**
Fixes a conflict between smock and hardhat 2.4.0. An import that existed in previous versions of hardhat no longer exists as of 2.4.0 (`decodeRevertReason`). I recreated `decodeRevertReason` using the tools available in hardhat@2.4.0 so we can minimize the diff.

**Metadata**
- Fixes #1110

### CODE REVIEW

File: packages/smock/src/smockit/binding.ts [hunk 1]
```diff
@@ -1,9 +1,22 @@
...
 import { VmError } from '@nomiclabs/ethereumjs-vm/dist/exceptions'
 import BN from 'bn.js'
 
+// Handle hardhat ^2.4.0
+let decodeRevertReason: (value: Buffer) => string
+try {
+  decodeRevertReason = require('hardhat/internal/hardhat-network/stack-traces/revert-reasons')
+    .decodeRevertReason
+} catch (err) {
+  const {
```
Comment (alcuadrado) [inline packages/smock/src/smockit/binding.ts:12]: Makes a lot of sense. I was wondering how you'd support both versions.

Comment (smartcontracts) [reply packages/smock/src/smockit/binding.ts:12]: Yeah meh this is good enough for now.

**Review by ben-chain — APPROVED** [review]
LGTM!
