### PR TITLE
op-supervisor: resetTracker fixes

### LINKED ISSUE #15769: Interop: test and handle sequencing-window expiry
The op-node needs to be able to go through a sequencing window expiry, without the supervisor being forced to halt or go out of sync.

This should include:
- [ ] devstack test (see sub-issue)
- [ ] Any remaining op-node / op-supervisor changes to better accommodate the sequencing window expiry. Some work has been done here already: https://github.com/ethereum-optimism/optimism/pull/15677
- [ ] In the test, enable sequencing recovery mode via RPC, and confirm that a new tx can be confirmed and finalized after the sequencing window expiry has been healed.

### PR DESCRIPTION
**Pull request by protolambda**
**Description**

This fixes the resetTracker, but leaves some TODOs for upgrade activation (covered in https://github.com/ethereum-optimism/optimism/pull/16008 ) and some remaining cleanup (tracked in https://github.com/ethereum-optimism/optimism/issues/16026 )

These changes also unlock the sequencing window expiry test.

This PR is extracted from the prior draft in https://github.com/ethereum-optimism/optimism/pull/16013

**Tests**

- existing tests pass (action tests covered)
- sequencing window expiry test no longer needs the skip
- unit-test follow ups tracked in https://github.com/ethereum-optimism/optimism/issues/16026

**Additional context**

**Metadata**

Fix https://github.com/ethereum-optimism/optimism/issues/15769

### CODE REVIEW

File: op-supervisor/supervisor/backend/syncnode/reset.go [hunk 1]
```diff
@@ -79,11 +79,20 @@ func (t *resetTracker) bisectToTarget() {
...
 	if t.a == (eth.BlockID{}) {
 		t.managed.log.Debug("Start of range is empty, fetching the anchor block as starting point")
+		// TODO(#16026): change name: GetActivationBlock, Anchor point = get first block of DB
 		anchor, err := t.managed.backend.AnchorPoint(internalCtx, t.managed.chainID)
 		if err != nil {
+			if errors.Is(err, types.ErrFuture) {
+				// TODO(#16026): need to trigger pre-interop reset
+				t.managed.log.Info("Missing activation block", "err", err)
+				return
+			}
```
Comment (sebastianst) [inline op-supervisor/supervisor/backend/syncnode/reset.go:95]:
```suggestion
		if errors.Is(err, types.ErrFuture) {
			// TODO(#16026): need to trigger pre-interop reset
			t.managed.log.Info("Missing activation block", "err", err)
			return
		} else if err != nil {
```
avoids one indentation

File: op-supervisor/supervisor/backend/syncnode/reset.go [hunk 2]
```diff
@@ -200,11 +210,32 @@ func (t *resetTracker) resetHeadsFromTarget(target eth.BlockID) {
...
+	if err := t.managed.backend.IsLocalUnsafe(internalCtx, t.managed.chainID, target); err != nil {
+		if errors.Is(err, types.ErrConflict) {
+			lUnsafe = target
+		} else {
+			t.managed.log.Error("Failed to check local-unsafe", "target", target, "err", err)
+			t.endReset()
+			return
+		}
+	} else {
+		// TODO(#16026): cleanup how we fall back to the tip of unsafe chain
```
Comment (sebastianst) [inline op-supervisor/supervisor/backend/syncnode/reset.go]: what's meant by this comment?

**Review by sebastianst — APPROVED** [review]

File: op-supervisor/supervisor/backend/syncnode/reset.go (hunk 2 above)
Comment (protolambda) [reply op-supervisor/supervisor/backend/syncnode/reset.go]: I'll clarify in the github issue that we want rewind-locking around this function that determines the reset continuation point.

File: op-supervisor/supervisor/backend/syncnode/reset.go (hunk 1 above)
Comment (protolambda) [reply op-supervisor/supervisor/backend/syncnode/reset.go:95]: I'm not a fan of checking the error-type as an alternative case of the err!=nil case.

File: op-supervisor/supervisor/backend/syncnode/reset.go [hunk 3]
```diff
@@ -214,28 +214,11 @@ func (t *resetTracker) resetHeadsFromTarget(target eth.BlockID) {
...
-			t.managed.log.Error("Failed to get latest local-unsafe", "err", err)
-			t.endReset()
-			return
-		}
-		lUnsafe = tip
-	}
+	// We set the local unsafe block to our target (the local-safe block we determined to reset to).
+	// The node checks it for consistency, but if it builds on this target,
+	// it does not revert back the existing unsafe chain.
+	// We do not have to pick the latest possible unsafe target here.
```
Comment (sebastianst) [inline op-supervisor/supervisor/backend/syncnode/reset.go:220]: Oh interesting, so that was guaranteed all along?

File: op-acceptance-tests/tests/interop/seqwindow/expiry_test.go [hunk 4]
```diff
@@ -83,13 +83,34 @@ func TestSequencingWindowExpiry(gt *testing.T) {
 		"tx", receipt2.TxHash, "l2Block", old)
 	// The logs will show a "Chain reorg detected" from op-geth.
 
+	// Once this happens we don't want to continue to try and include the tx in a block again,
+	// since that will then be reorged out again.
+	// We need to enter recovery-mode to not continue to build an incompatible chain that will not get submitted.
+	// It may reorg once more, but then stays compatible.
+	// For a while we'll have to build blocks that are not going to be reorged out due to subtle L1 origin divergence.
+	t.Logger().Info("Turning on recovery-mode")
+	t.Require().NoError(sys.L2CLA.Escape().RollupAPI().SetRecoverMode(t.Ctx(), true))
```
Comment (sebastianst) [inline op-acceptance-tests/tests/interop/seqwindow/expiry_test.go:92]: just for my understanding, what's `Escape()` doing?

File: op-acceptance-tests/tests/interop/seqwindow/expiry_test.go [hunk 5]
```diff
@@ -110,6 +131,38 @@ func TestSequencingWindowExpiry(gt *testing.T) {
 	other := sys.L2ELA.BlockRefByNumber(safe.Derived.Number)
 	require.Equal(safe.Derived.Hash, other.Hash, "supervisor must match chain with EL")
 
+	t.Logger().Info("Re-enabling batch-submitter")
 	// re-enable the batcher now that we are done with the test.
 	t.Require().NoError(sys.L2BatcherA.ActivityAPI().StartBatcher(t.Ctx()))
+	// TODO: batcher submits future span batch, misses a L2 block
```
Comment (sebastianst) [inline op-acceptance-tests/tests/interop/seqwindow/expiry_test.go]: when should this TODO be addressed?

**Review by sebastianst — APPROVED** [review]

File: op-supervisor/supervisor/backend/syncnode/reset.go (hunk 3 above)
Comment (protolambda) [reply op-supervisor/supervisor/backend/syncnode/reset.go:220]: Yes, the old fix is what broke `TestUnsafeChainKnownToL2CL` iirc

File: op-acceptance-tests/tests/interop/seqwindow/expiry_test.go (hunk 4 above)
Comment (protolambda) [reply op-acceptance-tests/tests/interop/seqwindow/expiry_test.go:92]: It's an intentional thing, to make it clear when we go from the DSL world to the full-capabilities world. We can introduce DSL for the API later, once we see a need for it.

File: op-acceptance-tests/tests/interop/seqwindow/expiry_test.go (hunk 5 above)
Comment (protolambda) [reply op-acceptance-tests/tests/interop/seqwindow/expiry_test.go]: I'll create a ticket for it so we can track

File: op-acceptance-tests/tests/interop/seqwindow/expiry_test.go (hunk 4 above)
Comment (sebastianst) [reply op-acceptance-tests/tests/interop/seqwindow/expiry_test.go:92]: got it, thanks

File: op-acceptance-tests/tests/interop/seqwindow/expiry_test.go (hunk 5 above)
Comment (protolambda) [reply op-acceptance-tests/tests/interop/seqwindow/expiry_test.go]: tracked here: https://github.com/ethereum-optimism/optimism/issues/16036
