### PR TITLE
cannon: Fix GC emulation of Go programs

### LINKED ISSUE #11658: Debug alloc test
Ensure the alloc test does not exceed a maximum amount of memory for allocations.

### PR DESCRIPTION
**Pull request by Inphi**
## Meta

Necro of https://github.com/ethereum-optimism/optimism/pull/11292.
Fixes https://github.com/ethereum-optimism/optimism/issues/11658 and https://github.com/ethereum-optimism/optimism/issues/11648

## Description

This patch improves Linux/MIPS32 emulation for Go programs that utilize the garbage collector and goroutine scheduling.

This adds support for the following syscalls:

- `getpid` - used by the go scheduler
- `clock_gettime` - used by the go scheduler and for GC assists and to properly emulate time related operations such as `time.Sleep`.

### Note on GC assists

The Go GC relies on `clock_gettime` for GC "assists", whereby a mutator can perform a little bit of GC without waiting for the scheduler to do so.
A monotonic clock (runtime.nanotime) is used to compute the current goroutine's compute budget. By modeling a MIPS32 CPU that runs at some clock speed (ex: 10 MHz), we can provide a consistent emulation of monotonic time needed by the Go runtime. All other clock_gettime flags are handled as unimplemented syscalls.

### Memory Proofs

Emulating `clock_gettime` a special as it's the only syscall that requires multi-word memory writes. There are two obvious ways to deal with this:
- Break up the syscall into two "microsteps" (similar to futex handling), where one step writes the 32-bit seconds field in the timespec struct, while the other writes the nanoseconds time field. This requires a single proof per microstep.
- Issue two memory writes for the single step.

This patch uses the latter approach in order to not complicate the VM state machine that handles futex and thread traversal. However, this means proofs need to be carefully verified between memory accesses. Thus, `MIPS2.sol` requires a second memory proof when stepping on a `clock_gettime` syscall.
This second memory proof is used to verify that the leaf node associated with the second write corresponds to a valid memory root (i.e. a merkle tree containing the first memory write).

## Testing

- `TestInstrumentedState_Alloc` re-enabled and now asserts against a couple more allocation patterns.

### CODE REVIEW

File: op-chain-ops/srcmap/solutil.go [hunk 1]
```diff
@@ -235,8 +235,15 @@ func (s *SourceMapTracer) info(codeAddr common.Address, pc uint64) string {
...
-		val := scope.StackData()[:start]
+		var val []byte
+		sc, ok := scope.(*vm.ScopeContext)
+		if ok {
+			start := pc + 1
+			end := uint64(op) - uint64(vm.PUSH1) + 1
+			val = sc.Contract.Code[start : start+end]
+		} else {
+			val = []byte("N/A")
+		}
```
Comment (Inphi) [inline op-chain-ops/srcmap/solutil.go:250]: Fixes a bug where the tracer prints the pre-state stack values rather than the PUSHx operand

File: cannon/mipsevm/exec/mips_syscalls.go [hunk 2]
```diff
@@ -132,7 +133,18 @@ const (
...
 const (
+	// SchedQuantum is the number of steps dedicated for a thread before it's preempted. Effectively used to emulate thread "time slices"
 	SchedQuantum = 100_000
+
+	// HZ is the assumed clock rate of an emulated MIPS32 CPU.
+	// The value of HZ is a rough estimate of the Cannon instruction count / second on a typical machine.
+	// HZ is used to emulate the clock_gettime syscall used by guest programs that have a Go runtime.
+	// The Go runtime consumes the system time to determine when to initiate gc assists and for goroutine scheduling.
+	// A HZ value that is too low (i.e. lower than the emulation speed) results in the main goroutine attempting to assist with GC more often.
+	// Adjust this value accordingly as the emulation speed changes. The HZ value should be within the same order of magnitude as the emulation speed.
```
Comment (mbaxter) [inline cannon/mipsevm/exec/mips_syscalls.go:144]: This is going to be easy to miss.  Is there some kind of test we could add to alert if the GC behavior drifts substantially from expectation?  For example, looks like there's [a `NumGC` value](https://pkg.go.dev/runtime#MemStats) we could check.

File: cannon/mipsevm/exec/mips_syscalls.go [hunk 3]
```diff
@@ -132,7 +133,18 @@ const (
...
+	HZ = 10_000_000
+
+	ClockGettimeMonotonicFlag = 1
```
Comment (mbaxter) [inline cannon/mipsevm/exec/mips_syscalls.go:150]: Probably worth linking to where this is defined?:
```suggestion
    // The id for Linux's monotonic clock: https://github.com/torvalds/linux/blob/ad618736883b8970f66af799e34007475fe33a68/include/uapi/linux/time.h#L50
	ClockGettimeMonotonicFlag = 1
```

File: cannon/mipsevm/multithreaded/mips.go [hunk 4]
```diff
@@ -143,6 +143,22 @@ func (m *InstrumentedState) handleSyscall() error {
 	case exec.SysOpen:
 		v0 = exec.SysErrorSignal
 		v1 = exec.MipsEBADF
+	case exec.SysClockGetTime:
+		v0 = 0
+		v1 = 0
```
Comment (mbaxter) [inline cannon/mipsevm/multithreaded/mips.go]: Should we return an error for unsupported clock ids (a0)?

File: packages/contracts-bedrock/src/cannon/MIPS2.sol [hunk 5]
```diff
@@ -381,69 +381,127 @@ contract MIPS2 is ISemver {
...
                 // ignored
-            } else if (syscall_no == sys.SYS_GETAFFINITY) {
-                // ignored
-            } else if (syscall_no == sys.SYS_MADVISE) {
+            }
+            else if (syscall_no == sys.SYS_GETAFFINITY) {
                 // ignored
-            } else if (syscall_no == sys.SYS_RTSIGPROCMASK) {
+            }
+            else if (syscall_no == sys.SYS_MADVISE) {
```
Comment (mbaxter) [inline packages/contracts-bedrock/src/cannon/MIPS2.sol]: Looks like a bunch of whitespace changes here - is that intentional?

File: packages/contracts-bedrock/src/cannon/MIPS2.sol [hunk 6]
```diff
@@ -381,69 +381,127 @@ contract MIPS2 is ISemver {
...
+            } else if (syscall_no == sys.SYS_CLOCKGETTIME) {
+                if (a0 == sys.CLOCK_GETTIME_MONOTONIC_FLAG) {
+                    v0 = 0;
+                    v1 = 0;
+                    uint32 secs = uint32(state.step / sys.HZ);
+                    uint32 nsecs = uint32((state.step % sys.HZ) * (1_000_000_000 / sys.HZ));
+                    uint32 effAddr = a1 & 0xFFffFFfc;
+                    // First verify the effAddr path
+                    require(
+                        MIPSMemory.isValidProof(
```
Comment (mbaxter) [inline packages/contracts-bedrock/src/cannon/MIPS2.sol]: Why don't we always do this validation in `MIPSMemory.writeMem`?

File: packages/contracts-bedrock/src/cannon/libraries/MIPSMemory.sol [hunk 7]
```diff
@@ -97,6 +97,47 @@ library MIPSMemory {
         }
     }
 
+    /// @notice Verifies a memory proof.
+    /// @param _memRoot The expected memory root
+    /// @param _addr The _addr proven.
+    /// @param _proofOffset The offset of the memory proof in calldata.
+    /// @return valid_ True iff it is a valid proof.
+    function isValidProof(bytes32 _memRoot, uint32 _addr, uint256 _proofOffset) internal pure returns (bool valid_) {
```
Comment (mbaxter) [inline packages/contracts-bedrock/src/cannon/libraries/MIPSMemory.sol:127]: We have a bunch of similar merkle proof logic in this file - is there a way to dedupe?

File: packages/contracts-bedrock/test/cannon/MIPS2.t.sol [hunk 8]
```diff
@@ -565,6 +565,121 @@ contract MIPS2_Test is CommonTest {
...
+        bytes memory threadWitness = abi.encodePacked(encodeThread(thread), EMPTY_THREAD_ROOT);
+        updateThreadStacks(state, thread);
+        (, bytes memory memProof2) = ffi.getCannonMemoryProof2(pc, insn, timespecAddr, 10, timespecAddr + 4);
+
+        bytes memory invalidInsnAndMemProof = new bytes(insnAndMemProof.length);
+        for (uint256 i = 0; i < invalidInsnAndMemProof.length; i++) {
+            if (i < 897) {
+                invalidInsnAndMemProof[i] = insnAndMemProof[i];
+            } else {
+                invalidInsnAndMemProof[i] = 0x0;
```
Comment (mbaxter) [inline packages/contracts-bedrock/test/cannon/MIPS2.t.sol]: (optional) We could fuzz zeroing out just one 32-byte segment in the memory proof.

File: packages/contracts-bedrock/test/cannon/MIPS2.t.sol [hunk 9]
```diff
@@ -565,6 +565,121 @@ contract MIPS2_Test is CommonTest {
         assertEq(postState, outputState(expect), "unexpected post state");
     }
 
+    function test_syscallGetPid_succeeds() public {
```
Comment (mbaxter) [inline packages/contracts-bedrock/test/cannon/MIPS2.t.sol:600]: I think it would be a good idea to add similar tests to `evm_multithreaded_test.go` to validate behavior across on- and off-chain impls.

File: packages/contracts-bedrock/test/cannon/MIPS2.t.sol [hunk 10]
```diff
@@ -565,6 +565,121 @@ contract MIPS2_Test is CommonTest {
...
+
+        bytes32 postState = mips.step(encodeState(state), bytes.concat(threadWitness, memProof), 0);
+        assertEq(postState, outputState(expect), "unexpected post state");
+    }
+
+    /// @dev static unit test asserting that clock_gettime syscall for monotonic time succeeds
+    function test_syscallClockGettimeMonotonic_succeeds() public {
+        uint32 pc = 0;
+        uint32 insn = 0x0000000c; // syscall
+        uint32 timespecAddr = 0xb000;
```
Comment (mbaxter) [inline packages/contracts-bedrock/test/cannon/MIPS2.t.sol:636]: Would also be a good idea to validate behavior for unaligned addresses.

File: packages/contracts-bedrock/scripts/go-ffi/differential-testing.go [hunk 11]
```diff
@@ -371,14 +371,22 @@ func DiffTestUtils() {
...
 			mem.SetMemory(uint32(memAddr), uint32(memValue))
 			memProof = mem.MerkleProof(uint32(memAddr))
 		}
+		if len(args) == 7 {
+			memAddr, err := strconv.ParseUint(args[5], 10, 32)
+			checkErr(err, "Error decoding memAddr")
+			memValue, err := strconv.ParseUint(args[6], 10, 32)
+			checkErr(err, "Error decoding memValue")
+			mem.SetMemory(uint32(memAddr), uint32(memValue))
+			memProof = mem.MerkleProof(uint32(memAddr))
```
Comment (mbaxter) [inline packages/contracts-bedrock/scripts/go-ffi/differential-testing.go:389]: Should this append to the memProof instead of overwriting?

File: packages/contracts-bedrock/test/setup/FFIInterface.sol [hunk 12]
```diff
@@ -245,6 +245,56 @@ contract FFIInterface {
...
+        cmds[5] = vm.toString(memAddr);
+        cmds[6] = vm.toString(memVal);
+        cmds[7] = vm.toString(memAddr2);
+        cmds[8] = vm.toString(memVal2);
+        bytes memory result = Process.run(cmds);
+        (bytes32 memRoot, bytes memory proof) = abi.decode(result, (bytes32, bytes));
+        return (memRoot, proof);
+    }
+
+    function getCannonMemoryProof2(
```
Comment (mbaxter) [inline packages/contracts-bedrock/test/setup/FFIInterface.sol:274]: The distinction between these 2 methods is a little opaque - maybe worth some comments here. 

I also wonder if we even need this second style ("cannonMemoryProof2").  Seems like we could instead have the original method return the full proof (insn + mem1 + mem2 proofs), and then add another method that breaks up that full proof into those 3 constituent proofs?

Comment (Inphi) [reply packages/contracts-bedrock/test/setup/FFIInterface.sol:274]: I originally went with a single function to do this. But the api is awkward as it needs to support building a tree containing either two or three non-zero nodes, while generating a proof for another, possible disjoint zero node.
With the existing `cannonMemoryProof`, you'd have to support these two use cases:
```
addressA valueA addressB valueB proveAddressC
```
and
```
addressA valueA proveAddressB
```
It's not straight forward to disambiguat the two without introducing a flag, which is one option.

I figured it'll be clearer to have a separate method for this usecsse.

File: cannon/mipsevm/multithreaded/mips.go (hunk 4 above)
Comment (Inphi) [reply cannon/mipsevm/multithreaded/mips.go]: We should. I've limited it emulation to realtime (used for logging) and monotonic clocks. The VM returns an error for any other clock.

File: packages/contracts-bedrock/src/cannon/MIPS2.sol (hunk 5 above)
Comment (Inphi) [reply packages/contracts-bedrock/src/cannon/MIPS2.sol]: forge formatting was broken. I've merged the latest foundry version in develop that fixes this.

File: packages/contracts-bedrock/src/cannon/MIPS2.sol (hunk 6 above)
Comment (Inphi) [reply packages/contracts-bedrock/src/cannon/MIPS2.sol]: it's redundant. For all other operations, the VM reads the memory value before writing to it. And we already validate the memory during that read.
But in this case, no reads occurs before we write to memory so we have to pre-validate it.

File: packages/contracts-bedrock/src/cannon/libraries/MIPSMemory.sol (hunk 7 above)
Comment (Inphi) [reply packages/contracts-bedrock/src/cannon/libraries/MIPSMemory.sol:127]: yup. Done.

File: cannon/mipsevm/multithreaded/mips.go (hunk 4 above)
Comment (Inphi) [reply cannon/mipsevm/multithreaded/mips.go]: And fwiw, I ran this on the op-program and confirmed that it uses only realtime and monotonic clocks. So we shouldn't observe any other clocks used by the program. But just in case that changes, I'm opting use errno to indicate that they're unsupported rather than panic.

File: packages/contracts-bedrock/scripts/go-ffi/differential-testing.go (hunk 11 above)
Comment (Inphi) [reply packages/contracts-bedrock/scripts/go-ffi/differential-testing.go:389]: I've added a comment to this file that clarifies usage. Here we're writing two items to the merkle trie and single generating a proof of those two updates for a memory location.

File: packages/contracts-bedrock/test/cannon/MIPS2.t.sol (hunk 9 above)
Comment (Inphi) [reply packages/contracts-bedrock/test/cannon/MIPS2.t.sol:600]: Good idea. It's done.

File: packages/contracts-bedrock/test/cannon/MIPS2.t.sol (hunk 10 above)
Comment (Inphi) [reply packages/contracts-bedrock/test/cannon/MIPS2.t.sol:636]: added

File: cannon/mipsevm/exec/mips_syscalls.go (hunk 2 above)
Comment (Inphi) [reply cannon/mipsevm/exec/mips_syscalls.go:144]: When the main goroutine assists in GC, it may not actually perform a GC. Or I should say that the main goroutine _attempts_ to assist. There are other factors including memory pressure, and last time since the last GC, that affect when a GC actually occurs. As such, we can't rely on `runtime` metrics like `NumGC` to figure out if this is occurring to frequently.

A GC assist attempt that doesn't actual run the gc isn't expensive (about 1-5% of an actual GC run from what I've seen). So I'm not too worried if the op-program attempts to assist more often that necessary. As long as it doesn't do so for a large fraction of memory allocations. And I assume it'll be pretty evident once we're seeing alot of assist attempts because the runtime would be noticeably slower.

File: cannon/mipsevm/memory/memory.go [hunk 13]
```diff
@@ -328,6 +328,20 @@ func (m *Memory) Deserialize(in io.Reader) error {
 	return nil
 }
 
+func (m *Memory) Copy() *Memory {
```
Comment (mbaxter) [inline cannon/mipsevm/memory/memory.go:331]: nice - I've thought about adding a copy method but never really looked into it.  Also appreciate the new memory expectation helpers! 🎉

File: cannon/mipsevm/multithreaded/mips.go [hunk 14]
```diff
@@ -144,17 +144,22 @@ func (m *InstrumentedState) handleSyscall() error {
...
 			secs := uint32(m.state.Step / exec.HZ)
 			nsecs := uint32((m.state.Step % exec.HZ) * (1_000_000_000 / exec.HZ))
 			effAddr := a1 & 0xFFffFFfc
 			m.memoryTracker.TrackMemAccess(effAddr)
 			m.state.Memory.SetMemory(effAddr, secs)
 			m.memoryTracker.TrackMemAccess2(effAddr + 4)
 			m.state.Memory.SetMemory(effAddr+4, nsecs)
+		default:
+			v0 = exec.SysErrorSignal
+			v1 = exec.MipsEBADF
```
Comment (mbaxter) [inline cannon/mipsevm/multithreaded/mips.go]: Is this the right error (bad file descriptor)?

File: cannon/mipsevm/multithreaded/mips.go [hunk 15]
```diff
@@ -144,17 +144,22 @@ func (m *InstrumentedState) handleSyscall() error {
 		v0 = exec.SysErrorSignal
 		v1 = exec.MipsEBADF
 	case exec.SysClockGetTime:
-		v0 = 0
-		v1 = 0
+		switch a0 {
+		case exec.ClockGettimeRealtimeFlag:
```
Comment (mbaxter) [inline cannon/mipsevm/multithreaded/mips.go]: So this one will basically just report whatever random time value happens to be in memory?  And that's fine because its only used for logging?

**Review by mbaxter — APPROVED** [review]
Looks good!  Just one question on the ClockGetTime error type.

File: cannon/mipsevm/multithreaded/mips.go (hunk 14 above)
Comment (Inphi) [reply cannon/mipsevm/multithreaded/mips.go]: That's not right. I'll set it to `EINVAL`.

File: cannon/mipsevm/multithreaded/mips.go (hunk 15 above)
Comment (Inphi) [reply cannon/mipsevm/multithreaded/mips.go]: Yeah, which will typically be unix epoch if the program clears that memory address. I'll change this to always set the real time to epoch. I don't think we need to adjust the epoch time by the monotonic clock as it's only used for logging.

File: packages/contracts-bedrock/test/cannon/MIPS2.t.sol (hunk 8 above)
Comment (Inphi) [reply packages/contracts-bedrock/test/cannon/MIPS2.t.sol]: yup. done.

**Comment by Inphi** [comment]
@smartcontracts The heavy fuzz tests are timing out in CI due to slow MIPS test fuzzing. The MIPS tests utilize ffi which is terribly slow to execute for fuzzing. I've [tweaked](https://github.com/ethereum-optimism/optimism/pull/11704/commits/82f3e3571e9d27eccc0fd336ae671abf6cbd1d5f) the heavy fuzzer to ignore the MIPS tests in order to unblock this PR. I'll follow up on this by completely moving all forge fuzz testing for the MIPS VM to Go (as done [here](https://github.com/ethereum-optimism/optimism/blob/a81de910dc2fd9b2f67ee946466f2de70d62611a/cannon/mipsevm/tests/fuzz_evm_test.go)) so that we can remove the tweaks.

We probably need to adjust the number of runs the heavy fuzzer uses as this issue may crop up again for other contracts.
