### PR TITLE
op-supervisor: remove redundant RLock/RUnlock and fix deadlock

### LINKED ISSUE #16335: op-supervisor: Event overflow on large unsafe head gap
The supervisor can enter a non-recoverable crash-loop when the unsafe head gap between its log DB and a managed node grows too large. This seems to be caused by the supervisor's `ChainProcessor` entering a loop triggered by a `ChainProcessEvent` event that then internally emits `ChainIndexingContinueEvent`. These stack up, eventually leading to an even overflow panic (taken from `dev-infra-rehearsal-0-bn-op-supervisor-snapsync-0`):
```
t=2025-06-09T14:38:12+0000 lvl=debug msg="Building new HazardSet" chain=420120009 worker=cross-unsafe chainID=420120009 block="BlockSeal(hash:0xa1a0991221ad53f62f9cbd608dff4eff0b47ea2a27591e304b4a94c27a4d8b1e, number:125630, time:1749236224)"
t=2025-06-09T14:38:12+0000 lvl=debug msg="Processing block for hazards" chain=420120009 worker=cross-unsafe chainID=420120009 block="BlockSeal(hash:0xa1a0991221ad53f62f9cbd608dff4eff0b47ea2a27591e304b4a94c27a4d8b1e, number:125630, time:1749236224)"
t=2025-06-09T14:38:12+0000 lvl=debug msg="Successfully built HazardSet" chain=420120009 worker=cross-unsafe chainID=420120009 block="BlockSeal(hash:0xa1a0991221ad53f62f9cbd608dff4eff0b47ea2a27591e304b4a94c27a4d8b1e, number:125630, time:1749236224)"
t=2025-06-09T14:38:12+0000 lvl=info msg="Updated cross-unsafe" chain=420120009 crossUnsafe="BlockSeal(hash:0xa1a0991221ad53f62f9cbd608dff4eff0b47ea2a27591e304b4a94c27a4d8b1e, number:125630, time:1749236224)"
t=2025-06-09T14:38:12+0000 lvl=debug msg="Building new HazardSet" chain=420120010 worker=cross-unsafe chainID=420120010 block="BlockSeal(hash:0x9cfcc8f132f5467055073e18d0230eac29c7771e107b1d196442319cae65a0bb, number:241533, time:1749226497)"
t=2025-06-09T14:38:12+0000 lvl=debug msg="Processing block for hazards" chain=420120010 worker=cross-unsafe chainID=420120010 block="BlockSeal(hash:0x9cfcc8f132f5467055073e18d0230eac29c7771e107b1d196442319cae65a0bb, number:241533, time:1749226497)"
t=2025-06-09T14:38:12+0000 lvl=debug msg="Successfully built HazardSet" chain=420120010 worker=cross-unsafe chainID=420120010 block="BlockSeal(hash:0x9cfcc8f132f5467055073e18d0230eac29c7771e107b1d196442319cae65a0bb, number:241533, time:1749226497)"
t=2025-06-09T14:38:12+0000 lvl=info msg="Updated cross-unsafe" chain=420120010 crossUnsafe="BlockSeal(hash:0x9cfcc8f132f5467055073e18d0230eac29c7771e107b1d196442319cae65a0bb, number:241533, time:1749226497)"
t=2025-06-09T14:38:12+0000 lvl=error msg="Failed to enqueue event" emitter=chainsDBs event=cross-unsafe-update context=0
panic: something is very wrong, queued up too many events! Dropping event "cross-unsafe-update"
goroutine 44 [running]:
github.com/ethereum-optimism/optimism/op-node/rollup/event.(*Sys).emit(0xc00004e600, {0x11badad, 0x9}, 0x0, {0x15578c0, 0xc000d31270}, 0x0)
	/app/op-node/rollup/event/system.go:293 +0x245
github.com/ethereum-optimism/optimism/op-node/rollup/event.(*systemActor).Emit(0xc00047e6c0, {0x15578c0, 0xc000d31270})
	/app/op-node/rollup/event/system.go:81 +0x65
github.com/ethereum-optimism/optimism/op-node/rollup/event.(*Limiter[...]).Emit(0x1553660, {0x15578c0, 0xc000d31270})
	/app/op-node/rollup/event/limiter.go:38 +0xa2
github.com/ethereum-optimism/optimism/op-supervisor/supervisor/backend/db.(*ChainsDB).UpdateCrossUnsafe(0xc0001aab00, {0x190a85ca, 0x0, 0x0, 0x0}, {{0x9c, 0xfc, 0xc8, 0xf1, 0x32, ...}, ...})
	/app/op-supervisor/supervisor/backend/db/update.go:180 +0x2e3
github.com/ethereum-optimism/optimism/op-supervisor/supervisor/backend/cross.CrossUnsafeUpdate({0x156f998, 0xc00048e5a0}, {0x190a85ca, 0x0, 0x0, 0x0}, {0x1568bc8, 0xc0001aab00}, {0x15587c0, 0xc000449f70})
	/app/op-supervisor/supervisor/backend/cross/unsafe_update.go:77 +0x982
github.com/ethereum-optimism/optimism/op-supervisor/supervisor/backend/cross.(*CrossUnsafeWorker).OnEvent(0xc0004c2140, {0x1558920?, 0xc000f90ac0?})
	/app/op-supervisor/supervisor/backend/cross/unsafe_update.go:93 +0x99
github.com/ethereum-optimism/optimism/op-node/rollup/event.(*systemActor).RunEvent(0xc00047eba0, {{0x1558920?, 0xc000f90ac0?}, 0x41c8?, 0x0?})
	/app/op-node/rollup/event/system.go:101 +0x144
github.com/ethereum-optimism/optimism/op-node/rollup/event.(*globalHandle).onEvent(...)
	/app/op-node/rollup/event/executor_global.go:252
github.com/ethereum-optimism/optimism/op-node/rollup/event.(*GlobalSyncExec).processEvent(0xc00060cb60?, {{0x1558920?, 0xc000f90ac0?}, 0x2be2?, 0x0?})
	/app/op-node/rollup/event/executor_global.go:155 +0xeb
github.com/ethereum-optimism/optimism/op-node/rollup/event.(*GlobalSyncExec).Drain(0xc00060cb60)
	/app/op-node/rollup/event/executor_global.go:189 +0x29
github.com/ethereum-optimism/optimism/op-supervisor/supervisor.(*SupervisorService).initBackend.func1()
	/app/op-supervisor/supervisor/service.go:87 +0x25
github.com/ethereum-optimism/optimism/op-service/tasks.(*Poller).Start.func1()
	/app/op-service/tasks/poll.go:57 +0xa4
created by github.com/ethereum-optimism/optimism/op-service/tasks.(*Poller).Start in goroutine 1
	/app/op-service/tasks/poll.go:49 +0x156
```

We need to revisit the event flows here to make sure the supervisor can make incremental progress without events stacking too high. In this particular case I suggest we remove the `ChainIndexingContinueEvent` event completely, as it's just used for the chain processor to communicate with itself, and refactor it instead to run a classic outer loop.

### LINKED ISSUE #16603: Investigate spikes of `local-derived` events in `op-supervisor`
On occasion we are receiving a ton of events on the op-supervisor, a lot of `local-derived`, but others too, such as `local-unsafe-received`.

We should investigate what is triggering this, and why are we getting such congestion of inflight events.

Image

At 10000 inflight events being processed, the supervisor panics.

Image

Related: https://github.com/ethereum-optimism/optimism/issues/16335

### PR DESCRIPTION
**Pull request by nonsense**
**Description**

Fixes: https://github.com/ethereum-optimism/optimism/issues/16603
Fixes: https://github.com/ethereum-optimism/optimism/issues/16335

```
func (rw *RWMutex) RLock() {
...
// When a writer is pending, it blocks subsequent readers to ensure
// write access is not starved.
```

In our case, I believe the following is happening:

1. Goroutine A acquires RLock() in SyncStatus(). (`goroutine 927671` from logs)
2. Goroutine B tries to acquire Lock() in OnEvent() and waits. (`goroutine 206` from logs)
3. Goroutine A continues to HasInitializedStatuses() and tries to acquire another RLock() and deadlocks goroutines A and B. (`goroutine 927671` from logs)

```
goroutine 206 gp=0xc000609180 m=nil [sync.RWMutex.Lock, 58 minutes]
goroutine 927671 gp=0xc0008b9500 m=nil [sync.RWMutex.RLock, 58 minutes]
```

Logs at: https://optimistic.grafana.net/a/grafana-lokiexplore-app/explore/cluster/oplabs-dev-infra-primary/logs?patterns=%5B%5D&from=2025-07-08T15:57:28.000Z&to=2025-07-08T15:57:30.000Z&var-lineFormat=&var-ds=grafanacloud-logs&var-filters=cluster%7C%3D%7Coplabs-dev-infra-primary&var-filters=instance%7C%3D%7Cdev-infra-rehearsal-1-bn-op-supervisor-sequencer-2&var-fields=&var-levels=&var-metadata=&var-jsonFields=&var-patterns=&var-lineFilterV2=&var-lineFilters=caseInsensitive,0%7C__gfp__%3D%7Cstatus.go&displayedFields=%5B%5D&urlColumns=%5B%22Time%22,%22Line%22%5D&visualizationType=%22logs%22&var-fieldBy=$__all&var-labelBy=&timezone=browser&var-all-fields=&prettifyLogMessage=false&sortOrder=%22Descending%22&wrapLogMessage=false

I can't think of another reason why a goroutine holding a RLock would block on the same nested RLock, other than a writer (Lock) waiting, which also explains the deadlocks we are seeing, considering that `StatusTracker` doesn't do any time-consuming work.

### CODE REVIEW

**Comment by nonsense** [comment]
@protolambda while no `Deriver` should block the event system forever, we should probably consider if we can refactor the event system to make it impossible a single `Deriver` to block the whole event system, and just timeout with an error if processing takes too long?

In this case it was the `StatusTracker.OnEvent`, but I imagine we could introduce a bug elsewhere and have a similar problem again in the future?

File: op-supervisor/supervisor/backend/status/status.go [hunk 1]
```diff
@@ -82,10 +82,8 @@ func (su *StatusTracker) OnEvent(ctx context.Context, ev event.Event) bool {
 	return true
 }
 
-func (su *StatusTracker) HasInitializedStatuses() bool {
-	su.mu.RLock()
```
Comment (nonsense) [inline op-supervisor/supervisor/backend/status/status.go:86]: Note that `su.mu.RLock()` is already nested, as `HasInitializedStatuses` has a single caller already behind `su.mu.RLock()`, so this is redundant.

**Review by protolambda — APPROVED** [review]
Good catch! Confirmed in the go-docs that it indeed shouldn't be recursive-read-locking on the same go routine. Fix LGTM, thank you.

**Comment by protolambda** [comment]
> we should probably consider if we can refactor the event system to make it impossible a single Deriver to block the whole event system, and just timeout with an error if processing takes too long?

Yes, we should implement event-completion / contexts better in the next iteration of the event system.
That said, this recursive read lock wouldn't be fixed by a timeout alone, so this fix is worth merging, and we should all be cautious of similar recursive-read-lock issues in the future.
