### PR TITLE
kona/protocol/derive: handle "blob not found" correctly

### LINKED ISSUE #18716: kona: blob fetching failure leads to safe head stall
Looks like one of our kona nodes has a [safe head stall](https://optimistic.grafana.net/d/nUSlc3d4k/bedrock-networks?orgId=1&from=now-3h&to=now&timezone=browser&var-network=mainnet-dev&var-node=op-mainnet-kona-geth-a-rpc-1&var-layer=$__all&var-safety=$__all&var-cluster=$__all&var-konaNodes=$__all&refresh=30s). The logs say 

```
WARN blob_source: Failed to fetch blobs: error decoding response body
```

Dugtrigo is showing 404s. See logs from mainnet-l1-b [here](https://optimistic.grafana.net/a/grafana-lokiexplore-app/explore/namespace/mainnet-l1-b/logs?patterns=%5B%5D&from=2025-12-25T01:25:00.000Z&to=2025-12-25T01:59:59.000Z&var-lineFormat=&var-ds=grafanacloud-logs&var-filters=namespace%7C%3D%7Cmainnet-l1-b&var-filters=service_name%7C%3D%7Clighthouse&var-fields=&var-levels=detected_level%7C%3D%7Cunknown&var-metadata=&var-jsonFields=&var-patterns=&var-lineFilterV2=&var-lineFilters=&timezone=browser&var-all-fields=&displayedFields=%5B%5D&urlColumns=%5B%5D&visualizationType=%22logs%22&prettifyLogMessage=false&sortOrder=%22Descending%22&wrapLogMessage=false):

```
WARN Error processing HTTP API request elapsed_ms: 0.737062, status: 404 Not Found, path: /eth/v1/beacon/blobs/13316896, method: GET
```

The log appears even after the node has synced past slot 13316896, which was a [skipped slot](https://beaconscan.com/slot/13316896). Can kona handle skipped slots? (@geoknee also pointed out that this could be due to incomplete reorg handling, it the block in this slot was reorged out)

### PR DESCRIPTION
**Pull request by geoknee**
Generated by Claude.

We are seeing safe head stalls from some kona nodes and traced it to a missing beacon slot and kona stuck trying to pull blobs. The aim of this PR is to make kona-node behave more like op-node in such a scenario. 

Closes https://github.com/ethereum-optimism/optimism/issues/18716

### CODE REVIEW

File: rust/kona/crates/protocol/derive/src/errors/pipeline.rs [hunk 1]
```diff
@@ -344,6 +344,10 @@ pub enum ResetError {
     /// The next l1 block provided to the managed traversal stage is not the expected one.
     #[error("Next L1 block hash mismatch: expected {0}, got {1}")]
     NextL1BlockHashMismatch(B256, B256),
+    /// Blobs referenced by an L1 block are permanently unavailable (e.g. missed beacon slot).
+    /// The pipeline must reset to move past the offending L1 block.
+    #[error("Blobs unavailable: beacon node returned 404 for slot")]
+    BlobsUnavailable,
```
Comment (theochap) [inline rust/kona/crates/protocol/derive/src/errors/pipeline.rs]: We should add a block number or hash in the error message

File: rust/kona/crates/protocol/derive/src/errors/sources.rs [hunk 2]
```diff
@@ -33,6 +33,11 @@ pub enum BlobProviderError {
     /// Blob decoding error.
     #[error("Blob decoding error: {0}")]
     BlobDecoding(#[from] BlobDecodingError),
+    /// The beacon node returned a 404 for the requested slot, indicating the slot was missed or
+    /// orphaned. Blobs for missed/orphaned slots will never become available, so the pipeline
+    /// must reset to move past the L1 block that referenced them.
+    #[error("Blob not found at slot {0}: {1}")]
+    BlobNotFound(u64, String),
```
Comment (theochap) [inline rust/kona/crates/protocol/derive/src/errors/sources.rs]: Can we add named fields there to make it easier to understand where the error comes from?

File: rust/kona/crates/providers/providers-alloy/src/beacon_client.rs [hunk 3]
```diff
@@ -162,8 +174,16 @@ impl OnlineBeaconClient {
...
-            .await?
-            .error_for_status()?;
+            .await?;
+
+        // A 404 means the beacon slot was missed or orphaned. Blobs for such slots will never
+        // become available, so surface this as a distinct error rather than a generic HTTP error
+        // so that callers can trigger a pipeline reset instead of retrying indefinitely.
+        if response.status() == reqwest::StatusCode::NOT_FOUND {
+            return Err(BeaconClientError::SlotNotFound(slot));
+        }
```
Comment (theochap) [inline rust/kona/crates/providers/providers-alloy/src/beacon_client.rs:184]: I am wondering if here we shouldn't always try to reset the pipeline (not just on 404). How is the op-node handling it ?

**Review by theochap — COMMENTED** [review]
Looks good, few small comments

File: rust/kona/crates/providers/providers-alloy/src/beacon_client.rs (hunk 3 above)
Comment (geoknee) [reply rust/kona/crates/providers/providers-alloy/src/beacon_client.rs:184]: We don't want to reset on things like a 500 error. In op-node, 404 is special cased:

https://github.com/ethereum-optimism/optimism/blob/a10fd5259a3af9a465955b035e16f516327d51d5/op-service/sources/l1_beacon_client.go#L76-L84

converted to `ethereum.NotFound`, which is then used as a sentinel for a derivation reset

https://github.com/ethereum-optimism/optimism/blob/a10fd5259a3af9a465955b035e16f516327d51d5/op-node/rollup/derive/blob_data_source.go#L96-L105

So I think what we have here matches op-node now.

File: rust/kona/crates/protocol/derive/src/errors/pipeline.rs (hunk 1 above)
Comment (geoknee) [reply rust/kona/crates/protocol/derive/src/errors/pipeline.rs]: [aadc471](https://github.com/ethereum-optimism/optimism/pull/19328/commits/aadc4714347754483ecada0f4d147890adbd40c9)

File: rust/kona/crates/protocol/derive/src/errors/sources.rs (hunk 2 above)
Comment (geoknee) [reply rust/kona/crates/protocol/derive/src/errors/sources.rs]: [81c56bb](https://github.com/ethereum-optimism/optimism/pull/19328/commits/81c56bb67d620ce5e3ecfef8b5138c55693ff82f)

File: rust/kona/crates/protocol/derive/src/sources/blobs.rs [hunk 4]
```diff
@@ -134,8 +133,33 @@ where
...
+                            warn!(
+                                target: "blob_source",
+                                block_hash = %block_ref.hash,
+                                block_number = block_ref.number,
+                                timestamp = block_ref.timestamp,
+                                "Failed to fetch blobs: {kind}"
+                            );
+                        }
+                    }
+                    kind
```
Comment (theochap) [inline rust/kona/crates/protocol/derive/src/sources/blobs.rs]: nit: I think that here you could use `inspect_error` to print the warning and then just use the question mark (?) instead of `map_err` to automatically convert and propagate the error. This is a bit easier to parse

File: rust/kona/crates/protocol/derive/src/sources/blobs.rs [hunk 5]
```diff
@@ -149,7 +173,8 @@ where
                     }
                 }
                 Err(e) => {
-                    return Err(e.into());
+                    let err: BlobProviderError = e.into();
+                    return Err(err.into());
```
Comment (theochap) [inline rust/kona/crates/protocol/derive/src/sources/blobs.rs]: nit: This looks a bit suspicious. I am wondering if there is not an easier way to convert the error without doing two `.into` calls. That way we could also remove the match statement and just return an error with the question mark pattern (?)

File: rust/kona/crates/providers/providers-alloy/src/blobs.rs [hunk 6]
```diff
@@ -87,11 +88,27 @@ impl<B: BeaconClient> OnlineBlobProvider<B> {
...
+                            slot = missing_slot,
+                            "Beacon slot not found (404); slot may be missed or orphaned. \
+                             Triggering pipeline reset."
+                        );
+                        BlobProviderError::BlobNotFound {
+                            slot: missing_slot,
+                            reason: e.to_string(),
+                        }
+                    },
+                )
```
Comment (theochap) [inline rust/kona/crates/providers/providers-alloy/src/blobs.rs]: nit: That pattern is a bit suspicious and hard to parse. A better way would be to return a `Option<BlobProviderError>` directly in `slot_not_found`. That way we can just use `ok_or_else`. Or maybe it would be even simpler to inline the code from `slot_not_found` there directly.

**Review by theochap — APPROVED** [review]
Looks good a few more nits

File: rust/kona/crates/protocol/derive/src/sources/blobs.rs (hunk 4 above)
Comment (geoknee) [reply rust/kona/crates/protocol/derive/src/sources/blobs.rs]: [d9bd6b8](https://github.com/ethereum-optimism/optimism/pull/19328/commits/d9bd6b88ef925b0fb138976d518e2297f0226283)

File: rust/kona/crates/protocol/derive/src/sources/blobs.rs (hunk 5 above)
Comment (geoknee) [reply rust/kona/crates/protocol/derive/src/sources/blobs.rs]: Simplified here [47c32a8](https://github.com/ethereum-optimism/optimism/pull/19328/commits/47c32a861fede1fa4c71623545aa0a2d06d47d1e)

File: rust/kona/crates/providers/providers-alloy/src/blobs.rs (hunk 6 above)
Comment (geoknee) [reply rust/kona/crates/providers/providers-alloy/src/blobs.rs]: [47c32a8](https://github.com/ethereum-optimism/optimism/pull/19328/commits/47c32a861fede1fa4c71623545aa0a2d06d47d1e)
