### PR TITLE
fix(devnet-sdk): keep devnet descriptor updated

### LINKED ISSUE #15270: Add control plane support to devnet-sdk
For some tests we need control operations for some components of the devnet.
Right now, start/stop operations for op-node and supervisor, but this will be extended later on.

### PR DESCRIPTION
**Pull request by sigma**
**Description**

Make sure that after service lifecycle operations the devnet
descriptor stored in Kurtosis enclave still reflects the reality of
the deployment.

This enables tests to be somewhat destructive, yet leave the devnet in
a usable state for the next test.

**Tests**

manual validation that stopping/restarting services indeed  refreshes the descriptor stored in the enclave

**Additional context**

**Metadata**

- Fixes #15270

### CODE REVIEW

File: devnet-sdk/controller/kt/mutate_env.go [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+}
+
+func findSvcInEnv(env *descriptors.DevnetEnvironment, serviceName string) redundantService {
+	if svc := findSvcInChain(env.L1, serviceName); svc != nil {
+		return redundantService{svc}
+	}
+
+	var services redundantService = nil
+	for _, l2 := range env.L2 {
+		if svc := findSvcInChain(l2.Chain, serviceName); svc != nil {
```
Comment (janjakubnanista) [inline devnet-sdk/controller/kt/mutate_env.go:52]: Ah I thought service names had to be unique within an enclave

File: kurtosis-devnet/pkg/kurtosis/api/wrappers/wrappers.go [hunk 2]
```diff
@@ -26,6 +26,23 @@ type ServiceContextWrapper struct {
 	*services.ServiceContext
 }
 
+// mostly a no-op, to force the values to be typed as interfaces
+func convertPortSpecMap(ports map[string]*services.PortSpec) map[string]interfaces.PortSpec {
+	wrappedPorts := make(map[string]interfaces.PortSpec)
+	for name, port := range ports {
+		wrappedPorts[name] = port
+	}
```
Comment (janjakubnanista) [inline kurtosis-devnet/pkg/kurtosis/api/wrappers/wrappers.go:34]: Still bugs me how the simplest operations take four lines in go

**Review by janjakubnanista — APPROVED** [review]

File: kurtosis-devnet/pkg/kurtosis/api/wrappers/wrappers.go (hunk 2 above)
Comment (sigma) [reply kurtosis-devnet/pkg/kurtosis/api/wrappers/wrappers.go:34]: yeah, that one in particular is super annoying, as the type system could really easily make that whole block unnecessary

File: devnet-sdk/controller/kt/mutate_env.go (hunk 1 above)
Comment (sigma) [reply devnet-sdk/controller/kt/mutate_env.go:52]: at the kurtosis level yes, but we currently have redundant entries in the descriptor (that map to the same kurtosis service)
