### PR TITLE
fix(op-supernode): consolidate block-to-timestamp helpers and respect genesis offset

### LINKED ISSUE #19539: op-supernode: consolidate duplicated BlockNumberToTimestamp helpers
## Summary
`simpleChainContainer` currently has two near-identical block-number-to-timestamp helpers with different failure semantics:
- exported `BlockNumberToTimestamp(ctx, blocknum) (uint64, error)`
- private `blockNumberToTimestamp(blockNum) uint64`

The private helper silently returns `0` when rollup config is unavailable, while the exported helper returns an error.

## Why this matters
This is a maintenance hazard and makes it easy for one path to drift from the other. It also hides configuration problems on the private path instead of surfacing them.

## Relevant code
- `op-supernode/supernode/chain_container/chain_container.go`
- current private call site: `op-supernode/supernode/chain_container/invalidation.go`

## Suggested fix
Consolidate these into a single validated conversion path and remove the silent-zero variant.

## Audit note
This came up during audit follow-up while reviewing supernode rewind logic.

### LINKED ISSUE #19540: op-supernode: BlockNumberToTimestamp should respect Genesis.L2.Number
## Summary
`simpleChainContainer.BlockNumberToTimestamp` computes timestamps as `Genesis.L2Time + blockNum * BlockTime`, which ignores `Genesis.L2.Number`. The canonical rollup helper already models the correct formula as `Genesis.L2Time + ((blockNumber - Genesis.L2.Number) * BlockTime)`.

## Why this matters
If a chain uses a nonzero L2 genesis block number, the current helper returns the wrong timestamp. In the supernode today, this primarily affects invalidation-triggered rewinds, because the rewind path converts block -> timestamp and then timestamp -> block again using the canonical rollup helper.

That means the current code can compute the wrong rewind target on nonzero-genesis configurations.

## Relevant code
- buggy helper: `op-supernode/supernode/chain_container/chain_container.go`
- canonical helper: `op-node/rollup/types.go` `TimestampForBlock()`
- affected path: `op-supernode/supernode/chain_container/invalidation.go` -> `RewindEngine()`

## Suggested fix
Use the canonical rollup helper for block-number-to-timestamp conversion and preserve validation at the chain-container layer.

## Notes
This issue is configuration-dependent: if `Genesis.L2.Number == 0`, the current formula happens to work. The bug appears when the genesis L2 block number is nonzero.

### PR DESCRIPTION
**Pull request by karlfloersch**
Closes #19539
Closes #19540

## Summary
- consolidate the duplicated block-number-to-timestamp conversion logic in `simpleChainContainer`
- remove the silent-zero private helper behavior and surface conversion failures as errors
- switch conversion to the canonical rollup timestamp mapping so nonzero `Genesis.L2.Number` is handled correctly
- make invalidation fail closed if rewind timestamp conversion cannot be computed
- add regressions for missing rollup config and nonzero genesis block number handling

## Testing
- `./linter/bin/op-golangci-lint run ./op-supernode/...`
- `go test ./op-supernode/...`

### CODE REVIEW

**Review by ajsutton — APPROVED** [review]

File: op-supernode/supernode/chain_container/invalidation_test.go [hunk 1]
```diff
@@ -420,6 +435,34 @@ func TestInvalidateBlock(t *testing.T) {
...
+		}
+
+		c := &simpleChainContainer{
+			denyList: dl,
+			log:      testLogger(),
+			engine:   mockEng,
+			vn:       &mockVNForInvalidation{},
+		}
+
+		rewound, err := c.InvalidateBlock(context.Background(), 5, common.HexToHash("0xdead"))
```
Comment (wwared) [inline op-supernode/supernode/chain_container/invalidation_test.go]:
```suggestion
		rewound, err := c.InvalidateBlock(context.Background(), 5, common.HexToHash("0xdead"), 0)
```

Something like this should fix the test failure

**Review by wwared — APPROVED** [review]
