### PR TITLE
interop: add strong consistency guarantees 

### LINKED ISSUE #19420: supernode: add L1 consistency verification to cross-safety validation
## Problem

The supernode's cross-safety validation operates over a global view of multiple L2 chains, but each chain is individually asynchronous and unsynchronized. Currently, the interop verification pipeline (`progressInterop()`) processes timestamps sequentially:

1. `checkChainsReady(ts)` — wait for all chains to have blocks at the timestamp
2. `loadLogs(ts)` — download and persist cross-chain execution logs
3. `verifyInteropMessages()` — validate executing messages exist on source chains
4. Cycle detection — check for circular same-timestamp dependencies
5. Commit `VerifiedResult` with `L1Inclusion` (max L1 block number across chains) and `L2Heads`

The `VerifiedResult` stores the L1 block hash alongside the L2 heads, but **there is no verification that:**

- The previously recorded `L1Inclusion` is still on the canonical L1 chain (L1 reorg detection)
- All L2 chains' source L1 blocks are on the **same** L1 chain (cross-chain L1 consistency)
- The new frontier's L1 blocks are on the same chain as the previously stored L1 (pre-post consistency link)

Without these checks, the verifiedDB could contain results that reference reorged L1 blocks, or results where different chains were derived from different L1 forks.

## Relevant Code

- **Verification pipeline**: `op-supernode/supernode/activity/interop/interop.go` — `progressInterop()` (line ~253)
- **L1 inclusion calculation**: `op-supernode/supernode/activity/interop/algo.go` — `l1Inclusion()` (line ~34)
- **Verified DB**: `op-supernode/supernode/activity/interop/verified_db.go` — sequential-only BBolt store with `VerifiedResult{Timestamp, L1Inclusion, L2Heads}`
- **Reorg/rewind**: `op-supernode/supernode/activity/interop/interop.go` — `resetVerifiedDB()`, `resetLogsDB()`
- **Verifier interface**: `op-supernode/supernode/activity/activity.go` — `VerificationActivity`
- **Super authority**: `op-supernode/supernode/chain_container/super_authority.go` — `FullyVerifiedL2Head()`, `FinalizedL2Head()`

### Approach A: Synchronous L1 Consistency Check (recommended)

Add L1 consistency verification directly into the `progressInterop()` loop, before committing any new verified results. This ensures the verifiedDB is consistent **by construction**.

#### Algorithm

**Step 1 — Reorg detection (backward check):**
At the start of each verification round, verify the previously stored `VerifiedResult.L1Inclusion` is still on the canonical L1 chain. If L1 has reorged, travel backward through timestamps, rewinding the verifiedDB until we find a timestamp whose `L1Inclusion` is still canonical.

**Step 2 — Frontier consistency (forward check):**
When building the new frontier (all L2 heads at the next timestamp), query each chain's source L1 block. Verify that:
1. All chains' L1 source blocks are on the **same L1 chain** (they may be different block numbers, but must share ancestry)
2. The frontier's L1 blocks are on the **same chain as the previously recorded `L1Inclusion`** — this is the pre-post link

This pre-post link provides a recursive guarantee: if timestamp N is consistent, and timestamp N+1's L1 is on the same chain as N's L1, then N+1 is also consistent. The consistency proof is inductive.

**Step 3 — Proceed with verification:**
Only after both checks pass, proceed with the existing `loadLogs()` → `verifyInteropMessages()` → cycle detection → commit pipeline.

**If the frontier check fails:**
Stop and wait. On the next attempt, the L1 reorg detection (Step 1) will catch the canonical chain change and rewind appropriately.

#### Edge cases

- **L1 reorgs between check and L2 pull:** The frontier consistency check catches this — L2s will show L1 sources from the old fork, which won't match the new canonical chain.
- **L2 hasn't caught up to L1 reorg:** `checkChainsReady()` returns stale data derived from the old L1 fork. The frontier consistency check detects the mismatch.
- **All L2s stale but internally consistent:** The L1 reorg detection at the start of the next round catches this, since the previously stored `L1Inclusion` will no longer be canonical.

#### Why this approach

- **Consistency by construction.** The verifiedDB never contains inconsistent data. No window of vulnerability.
- **Fits existing architecture.** Sequential timestamp processing in `progressInterop()` — this is just an additional gate before the existing pipeline. No new goroutines or coordination primitives.
- **The pre-post link is provably correct.** Recursive consistency guarantee via induction on timestamps.
- **Performance is acceptable.** Checking L1 chain consistency requires verifying parent hashes on a small number of headers. The L1 ETH client caches headers. An in-memory cache could be added but likely isn't needed initially.

### Approach B: Async Self-Healing

A background process periodically walks the verifiedDB, re-checks that stored `L1Inclusion` values are still canonical and L2 heads still match, and rewinds if inconsistency is found.

#### Tradeoffs vs Approach A

- **Pro:** Defense-in-depth — catches bugs in the synchronous verification logic itself
- **Con:** Window of inconsistency between commit and detection
- **Con:** Requires coordination with `progressInterop()` to avoid concurrent writes/rewinds — adds locking complexity
- **Con:** Harder to reason about correctness — the system is eventually consistent rather than always consistent

Could be useful as a **read-only audit/monitoring layer** on top of Approach A, but not recommended as the primary consistency mechanism.

## Implementation Notes

The L1 chain consistency check needs a function like:

```go
// AreOnSameL1Chain checks whether two L1 block IDs are on the same chain
// by verifying parent hash ancestry from the higher block to the lower block.
func AreOnSameL1Chain(ctx context.Context, l1Client ethclient.Client, a, b eth.BlockID) (bool, error)
```

This function should be usable in a "dumb" way (called for each pair) with the L1 client's header cache absorbing repeated lookups. Can add an explicit in-memory cache later if needed.

The check integrates into `progressInterop()` roughly as:

```
// Pseudocode
lastResult := verifiedDB.Latest()

// Step 1: L1 reorg detection
if !isCanonical(lastResult.L1Inclusion) {
    rewindUntilConsistent()
    lastResult = verifiedDB.Latest()
}

// Step 2: Build frontier and check consistency  
frontier := getAllL2HeadsAndL1Sources(nextTimestamp)
if !allOnSameL1Chain(frontier.l1Sources) {
    return // wait and retry
}
if !onSameL1Chain(frontier.maxL1, lastResult.L1Inclusion) {
    return // wait and retry  
}

// Step 3: Existing verification pipeline
loadLogs(nextTimestamp)
verifyInteropMessages(...)
...
commit(VerifiedResult{...})
```

### PR DESCRIPTION
**Pull request by karlfloersch**
Closes https://github.com/ethereum-optimism/optimism/issues/19420

## Summary

This PR refactors the supernode interop activity around a single persisted transition model so that normal execution and crash recovery use the same apply path.

For a new reader, the important mental model is:

1. `progressAndRecord()` is the top-level interop tick.
2. If a `PendingTransition` already exists in `VerifiedDB`, interop replays it.
3. Otherwise interop observes the world, verifies the next timestamp, builds a `PendingTransition`, persists it, and applies it immediately.
4. The transition stays in the WAL until all of its side effects succeed.

This is the minimal-diff version of the stronger consistency work: it keeps the existing package structure, but makes the state transitions explicit and replayable.

Context: this work is informed by the Runtime Verification audit writeup here:
- https://github.com/runtimeverification/_audits_Ethereum-optimism_optimism_interopv2/issues/8

### 1. Unified normal execution and recovery

Interop no longer has separate "normal apply" and "startup recovery" logic for the important state transitions.

Instead, effectful decisions are represented as a generic `PendingTransition` stored in `VerifiedDB`, and both steady-state execution and restart recovery go through the same `applyPendingTransition()` path.

This covers:
- `DecisionAdvance`
- `DecisionInvalidate`
- `DecisionRewind`

### 2. Verification is now read-only

`verify()` no longer mutates `logsDB` while deciding whether a frontier is valid.

Instead:
- frontier verification uses an in-memory `frontierView`
- accepted-history lookups still come from `logsDB`
- frontier logs are only persisted later, during `DecisionAdvance` transition apply

That makes the WAL the real boundary for stateful changes.

### 3. Advance / invalidate / rewind are explicit transition kinds

`buildPendingTransition()` now constructs explicit transition payloads.

Notably:
- rewind uses an explicit `RewindPlan`
- advance persists exact frontier blocks during apply
- invalidation preserves the WAL until all invalidation side effects succeed

### 4. Replays are idempotent where they need to be

To support "persist first, clear last":
- `VerifiedDB.Commit()` is idempotent for exact duplicate replays
- rewind apply reports all failures, but keeps the WAL until the transition converges
- invalidation and rewind failures preserve the transition for retry
- invalid rewind WAL state now fails closed instead of being silently cleared

### 5. Top-level interop flow is easier to read again

The orchestration is back to a simpler shape:
- `progressAndRecord()` owns the transition lifecycle
- `progressInterop()` computes the next action
- `checkPreconditions()` gates verification
- `decideVerifiedResult()` interprets verification output

Dead wrappers and stale helper paths were removed along the way.

### 6. Reset callbacks are no longer part of interop correctness

Interop now treats `Reset()` as a no-op interface shim. The actual correctness path is the persisted transition apply logic.

The broader chain-container rewind/invalidation APIs are still powerful footguns, so this PR adds explicit comments/TODOs documenting that they should only be used from interop transition application until that interface is narrowed further.

### 7. Small cleanup and reviewability improvements

Also included in this branch:
- removed dead denylist clearing APIs (`ClearDenied`, `DenyList.Clear`)
- removed dead helpers/wrappers (`loadLogs`, `rewindAccepted`, `RewindAfter`, etc.)
- clarified the logsDB warning for chains with block times greater than one second
- cleaned up stale comments and compatibility artifacts

## Current Top-Level Flow

```text
Start
  -> progressAndRecord
     -> if pending transition exists:
          applyPendingTransition
     -> else:
          progressInterop
            -> observeRound
            -> checkPreconditions
            -> verify
            -> decideVerifiedResult
          -> if wait (DecisionWait):
               refreshCurrentL1OnWait
          -> if rewind with no prior verified state:
               return early (nothing to rewind)
          -> else (advance, invalidate, or rewind):
               buildPendingTransition
               SetPendingTransition
               applyPendingTransition
```

## Follow-Up

A follow-up PR should remove the ability to trigger rewinds/reorg side effects from outside interop until cross-activity concurrency between these stateful operations is fully designed and enforced.

Today the code documents those APIs as dangerous footguns, but the safer end state is to narrow that surface so interop transition application is the only place allowed to drive rewinds.

## Why This Is Better

Compared with `develop`, this branch moves the interop activity closer to an explicit transaction model:
- decisions are separated from side effects
- recovery and steady-state share the same apply path
- frontier verification no longer mutates durable state
- WAL clearing happens only after the transition has been applied

That makes the database/control-flow behavior much easier to review in one place.

Just as importantly, the consistency checks (L1 fork verification, accepted snapshot re-verification, stale logsDB detection) ensure that each virtual node's local data is internally consistent before interop cross-validates across chains. This means cross-validation only ever operates on trustworthy inputs.

## Files To Read First

If you are new to this diff, start here:
- `op-supernode/supernode/activity/interop/interop.go`
- `op-supernode/supernode/activity/interop/verified_db.go`
- `op-supernode/supernode/activity/interop/logdb.go`
- `op-supernode/supernode/activity/interop/verification_view.go`
- `op-supernode/supernode/chain_container/invalidation.go`

## Test Plan

Rerun coverage I checked while updating this branch:
- [x] `go test ./op-supernode/supernode/activity/interop/... -count=1`
- [x] `go test ./op-supernode/supernode/activity/superroot -count=1`

Focused regressions added/updated on this branch include:
- pending advance replay after commit succeeds idempotently
- pending invalidate/rewind transitions are preserved on failure
- rewind apply reports all failures
- invalid rewind WAL state fails closed
- frontier verification does not persist frontier logs

### CODE REVIEW

File: op-supernode/supernode/chain_container/invalidation.go [hunk 1]
```diff
@@ -133,25 +174,106 @@ func (d *DenyList) GetDeniedHashes(height uint64) ([]common.Hash, error) {
...
 // InvalidateBlock adds a block to the deny list and triggers a rewind if the chain
 // currently uses that block at the specified height.
+// WARNING: this should only be called by interop transition application.
+// Other callers risk triggering chain rewinds outside the interop WAL model.
+// TODO: remove this footgun by moving reorg-triggering operations behind a
+// smaller interop-owned interface.
 // Returns true if a rewind was triggered, false otherwise.
 // Note: Genesis block (height=0) cannot be invalidated as there is no prior block to rewind to.
-func (c *simpleChainContainer) InvalidateBlock(ctx context.Context, height uint64, payloadHash common.Hash) (bool, error) {
+func (c *simpleChainContainer) InvalidateBlock(ctx context.Context, height uint64, payloadHash common.Hash, decisionTimestamp uint64) (bool, error) {
```
Comment (wwared) [inline op-supernode/supernode/chain_container/invalidation.go:281]: There's some failing tests that need to be updated in `supernode_test.go` due to this new parameter

Comment (karlfloersch) [reply op-supernode/supernode/chain_container/invalidation.go:281]: Fixed in c7714bc284 — updated `mockCC.InvalidateBlock` signature and added `PruneDeniedAtOrAfterTimestamp` stub.

File: op-supernode/supernode/activity/interop/interop.go [hunk 2]
```diff
@@ -183,138 +224,180 @@ func (i *Interop) Resume() {
...
-		return Result{}, err
+		return obs, err
+	}
+	obs.ChainsReady = true
+	obs.BlocksAtTS = ready.blocks
+	obs.L1Heads = ready.l1Heads
+
+	// Check that all frontier L1 heads AND the accepted L1 head are on the same canonical fork.
+	obs.L1Consistent = true
+	if i.l1Checker != nil {
```
Comment (ajsutton) [inline op-supernode/supernode/activity/interop/interop.go:362]: Seems like the l1Checker is only ever nil in tests. It would probably be better to have the tests pass a no-op l1Checker and remove this if condition.  Not having an l1Checker in production would be a significant issue.

File: op-supernode/supernode/activity/interop/interop.go [hunk 3]
```diff
@@ -36,6 +37,41 @@ func init() {
...
+}
+
+// Decision represents the outcome of the pure decision function.
+type Decision int
+
+const (
+	DecisionWait Decision = iota
+	DecisionAdvance
+	DecisionInvalidate
+	DecisionRewind
```
Comment (ajsutton) [inline op-supernode/supernode/activity/interop/interop.go:66]: `Decision` is serialized to JSON as a bare integer (via iota). If the enum order is ever changed or a new variant is inserted before `DecisionRewind`, any pending WAL entry written by a previous binary would be silently misinterpreted on restart.

Consider assigning explicit numeric values or using string-based serialization (e.g., `MarshalJSON`/`UnmarshalJSON` returning `"advance"`, `"invalidate"`, etc.) to make the WAL format resilient to enum reordering.

File: op-supernode/supernode/activity/interop/verified_db.go [hunk 4]
```diff
@@ -92,24 +112,45 @@ func timestampToKey(ts uint64) []byte {
...
+					}
+					existing = append(existing[:0], val...)
+					return nil
+				})
+				if err != nil {
+					return fmt.Errorf("failed to read existing verified result at %d: %w", ts, err)
+				}
+				if bytes.Equal(existing, value) {
+					return nil
+				}
```
Comment (ajsutton) [inline op-supernode/supernode/activity/interop/verified_db.go:147]: The idempotent replay check uses `bytes.Equal` on JSON-serialized `VerifiedResult`. This works today because `json.Marshal` is deterministic for the same struct on the same binary.

However, Go's `encoding/json` does not guarantee byte-stable output across Go versions — whitespace or numeric formatting could change in a future release. If a node crashes after `Commit()` succeeds but before `ClearPendingTransition()`, and is then restarted on a newer Go version, the re-serialized value could differ from the stored bytes, turning an idempotent replay into a hard `ErrAlreadyCommitted` failure.

Comparing the deserialized structs rather than raw bytes would be the safest approach — unmarshal the stored value and use `reflect.DeepEqual` or a field-by-field comparison.

File: op-supernode/supernode/activity/interop/interop_test.go [hunk 5]
```diff
@@ -1344,6 +1377,433 @@ func testLogger() gethlog.Logger {
...
+	// The transition should NOT be cleared — it must survive for next restart.
+	got, err := h.interop.verifiedDB.GetPendingTransition()
+	require.NoError(t, err)
+	require.NotNil(t, got, "transition should be preserved when replay fails")
+	require.Equal(t, pending.Decision, got.Decision)
+	require.NotNil(t, got.Result)
+	require.Equal(t, pending.Result.InvalidHeads, got.Result.InvalidHeads)
+}
+
+func TestPendingTransition_RecoverRewindPreservedOnFailure(t *testing.T) {
```
Comment (ajsutton) [inline op-supernode/supernode/activity/interop/interop_test.go:1475]: This test verifies the WAL is preserved when rewind fails, but doesn't test the second attempt — the actual replay after the failure. Specifically: if chain A rewinds successfully and chain B fails, the WAL is preserved and replayed. On retry, `applyRewindPlan` calls `PruneDeniedAtOrAfterTimestamp` and `RewindEngine` on chain A again.

Consider adding a test that: (1) fails chain B on first attempt, (2) fixes chain B, (3) replays `applyPendingTransition` from `progressAndRecord`, and (4) verifies both chains end up in the correct state and the WAL is cleared. This would exercise the idempotency of the full rewind replay path end-to-end.

File: op-supernode/supernode/chain_container/invalidation.go [hunk 6]
```diff
@@ -26,6 +27,38 @@ type DenyList struct {
...
+		return nil, fmt.Errorf("invalid denylist record payload length %d", len(raw))
+	}
+	records = make([]DenyRecord, 0, len(raw)/common.HashLength)
+	for i := 0; i+common.HashLength <= len(raw); i += common.HashLength {
+		records = append(records, DenyRecord{
+			PayloadHash:       common.BytesToHash(raw[i : i+common.HashLength]),
+			DecisionTimestamp: 0,
+		})
+	}
+	return records, nil
```
Comment (ajsutton) [inline op-supernode/supernode/chain_container/invalidation.go]: Worth adding a comment explaining why legacy support matters and what the implications are. Legacy entries get `DecisionTimestamp: 0`, which means they are never removed by `PruneAtOrAfterTimestamp` (since rewind timestamps are always well above 0). This is the safe default — deny decisions from before provenance tracking was added should be preserved rather than silently dropped. A brief note here would help future readers understand this isn't just mechanical backward compat but a deliberate safety choice.

If this is for our existing internal devnet, might be worth logging an issue to remove this backwards compatibility once we reset the devnet - knowing that all DenyRecord instances have a DecisionTimestamp would make  reasoning about the code simpler.

File: op-supernode/supernode/activity/interop/interop_test.go [hunk 7]
```diff
@@ -1344,6 +1377,433 @@ func testLogger() gethlog.Logger {
...
+	pending, err := i.buildPendingTransition(output, obs)
+	if err != nil {
+		return err
+	}
+	if err := i.verifiedDB.SetPendingTransition(pending); err != nil {
+		return err
+	}
+	_, err = i.applyPendingTransition(pending)
+	return err
+}
```
Comment (ajsutton) [inline op-supernode/supernode/activity/interop/interop_test.go:1805]: These compat shims are used by `TestInterop_FullCycle` and most of the `TestProgressInterop*` tests, but they bypass the WAL entirely — `progressInteropCompat` calls `observeRound` + `verify` directly, and `applyResultCompat` manually builds and applies a pending transition without going through `progressAndRecord`.

As a result, the core correctness property of this PR — that `progressAndRecord` checks for a pending WAL entry on startup, persists before applying, and clears after success — is not exercised by the main integration tests.

Two suggestions:

1. **Add an integration test using `progressAndRecord` directly** for multiple advance cycles: verify each cycle writes and clears a pending transition, timestamps advance, and `currentL1` updates correctly.

2. **Add an end-to-end test for L1-inconsistency → rewind through `progressAndRecord`**: commit a couple of verified results, set up an L1 checker that reports inconsistency, call `progressAndRecord()`, and verify the `DecisionRewind` was persisted to the WAL, applied (verifiedDB rewound, chains reset), and the WAL cleared.

The individual components are well tested in isolation — this is about confirming the wiring between them works through the real entry point.

File: op-supernode/supernode/activity/interop/interop.go [hunk 8]
```diff
@@ -64,6 +100,9 @@ type Interop struct {
 	// When non-zero, progressInterop will return early without processing
 	// if the next timestamp to process is >= this value.
 	pauseAtTimestamp atomic.Uint64
+
+	l1Checker    *byNumberConsistencyChecker
+	frontierView *frontierVerificationView
```
Comment (ajsutton) [inline op-supernode/supernode/activity/interop/interop.go:105]: Nit, non-blocking: `frontierView` is only non-nil during `verify()` (set at the top, cleared via `defer`), but as a struct field it looks like persistent state. A later change could reasonably assume this is always available and dereference it outside the verify window, hitting a nil pointer.

Passing it through the call chain (`verify` → `verifyFn`/`cycleVerifyFn` → `verifyExecutingMessage`) would make the lifetime explicit in the type signatures. It'd require updating the `verifyFn`/`cycleVerifyFn` function types and ~10-12 test stubs — moderate but mechanical.

File: op-supernode/supernode/activity/interop/logdb.go [hunk 9]
```diff
@@ -82,67 +82,68 @@ func openLogsDB(logger log.Logger, chainID eth.ChainID, dataDir string) (LogsDB,
...
+	ErrStaleLogsDB = errors.New("logsDB has stale block data from a reorg")
 )
 
-// loadLogs loads and persists logs for the given timestamp for all chains.
-// The previous timestamp MUST already be sealed in the database; if not, an error is returned.
-// For the activation timestamp (first timestamp), the logsDB must be empty.
-func (i *Interop) loadLogs(ts uint64) error {
-	for chainID, chain := range i.chains {
+// persistFrontierLogs persists the exact accepted frontier blocks for a
+// timestamp. This is the only frontier logsDB write path once verification is
```
Comment (ajsutton) [inline op-supernode/supernode/activity/interop/logdb.go]: nit: I think verification is now read only so we should update this comment.

File: op-supernode/supernode/activity/interop/logdb.go [hunk 10]
```diff
@@ -82,67 +82,68 @@ func openLogsDB(logger log.Logger, chainID eth.ChainID, dataDir string) (LogsDB,
...
-		if err != nil {
-			return fmt.Errorf("chain %s: failed to get block at timestamp %d: %w", chainID, ts, err)
-		}
-
-		// Fetch receipts for the block
-		blockInfo, receipts, err := chain.FetchReceipts(i.ctx, block.ID())
+		blockInfo, receipts, err := chain.FetchReceipts(i.ctx, blockID)
 		if err != nil {
-			return fmt.Errorf("chain %s: failed to fetch receipts for block %d: %w", chainID, block.Number, err)
+			return fmt.Errorf("chain %s: failed to fetch receipts for block %d: %w", chainID, blockID.Number, err)
```
Comment (ajsutton) [inline op-supernode/supernode/activity/interop/logdb.go]: nit: Show the actual block ID not just the number since the lookup is by hash:
```suggestion
			return fmt.Errorf("chain %s: failed to fetch receipts for block %d: %w", chainID, blockID, err)
```

BlockID has a nice ToTerminalString() that works well for this use case.

File: op-supernode/supernode/activity/interop/logdb.go [hunk 11]
```diff
@@ -184,9 +185,11 @@ func (i *Interop) verifyCanAddTimestamp(chainID eth.ChainID, db LogsDB, ts uint6
 			chainID, ts-blockTime, ts, blockTime, seal.Timestamp, ErrPreviousTimestampNotSealed)
 	}
 
-	// if the gap is less than a block time, we can append the timestamp to the database, but warn the caller
+	// If the gap is less than a block time, we can still append the timestamp to the database.
+	// This is expected for chains whose block time is greater than one second, since the
+	// interop timestamp may legitimately fall between consecutive L2 blocks.
 	if gap < blockTime {
-		i.log.Warn("verifyCanAddTimestamp: requested for timestamp which is not a multiple of block time",
+		i.log.Warn("verifyCanAddTimestamp: timestamp falls between L2 blocks for this chain; this can be expected for chains with block times greater than one second",
```
Comment (ajsutton) [inline op-supernode/supernode/activity/interop/logdb.go]: Given this is expected, should it really be a warning? Seems like info at most and even then it would happen every two seconds on op-mainnet (and most chains) so debug is probably best.

File: op-supernode/supernode/chain_container/chain_container.go [hunk 12]
```diff
@@ -44,6 +44,11 @@ type ChainContainer interface {
 	OptimisticOutputAtTimestamp(ctx context.Context, ts uint64) (*eth.OutputResponse, error)
 	// RewindEngine rewinds the engine to the highest block with timestamp less than or equal to the given timestamp.
 	// invalidatedBlock is the block that triggered the rewind and is passed to reset callbacks.
+	// WARNING: this is a dangerous stateful operation and is intended to be called only
+	// by interop transition application. Other callers should not use it until the
+	// interface is refactored to make that ownership explicit.
+	// TODO: remove this footgun by moving reorg-triggering operations behind a
```
Comment (ajsutton) [inline op-supernode/supernode/chain_container/chain_container.go]: Can we log an issue and reference it in this TODO please?  ie `TODO(#xxxx):`

File: op-supernode/supernode/chain_container/chain_container.go [hunk 13]
```diff
@@ -44,6 +44,11 @@ type ChainContainer interface {
...
+	// smaller interop-owned interface.
```
Comment (ajsutton) [inline op-supernode/supernode/chain_container/chain_container.go:51]: This TODO appears four times across `chain_container.go` and `invalidation.go`. Could you file a tracking issue for narrowing the `ChainContainer` interface so that reorg-triggering operations are only accessible to interop transition application? That way the follow-up work is visible and doesn't get lost as a code comment.

**Review by ajsutton — APPROVED** [review]
LGTM. Changes seem like a definite improvement. There's a bunch of suggestions, mostly not super important and all of them could be handled as follow up if needed.  The potential for JSON serialisation to change and break the bytes comparison is probably the main concern but that is very likely a follow up thing as we may want to rethink exactly how we record things in the database a bit to make it more reliably comparable.

File: op-supernode/supernode/chain_container/chain_container.go [hunk 14]
```diff
@@ -495,7 +518,16 @@ func isCriticalRewindError(err error) bool {
 		errors.Is(err, engine_controller.ErrRewindOverFinalizedHead)
 }
 
+// WARNING: this should only be called by interop transition application.
```
Comment (geoknee) [inline op-supernode/supernode/chain_container/chain_container.go]: interop activity?
```suggestion
// WARNING: this should only be called by the interop activity.
```

**Comment by karlfloersch** [comment]
Filed follow-up issue for Adrian's review feedback: #19561

File: op-supernode/supernode/activity/interop/logdb.go (hunk 9 above)
Comment (karlfloersch) [reply op-supernode/supernode/activity/interop/logdb.go]: Fixed in 5ce2ed0b — updated comment to clarify verification is read-only.

File: op-supernode/supernode/activity/interop/logdb.go (hunk 10 above)
Comment (karlfloersch) [reply op-supernode/supernode/activity/interop/logdb.go]: Fixed in 5ce2ed0b — now shows full blockID (hash+number).

File: op-supernode/supernode/activity/interop/logdb.go (hunk 11 above)
Comment (karlfloersch) [reply op-supernode/supernode/activity/interop/logdb.go]: Fixed in 5ce2ed0b — changed Warn to Debug.

File: op-supernode/supernode/chain_container/invalidation.go (hunk 6 above)
Comment (karlfloersch) [reply op-supernode/supernode/chain_container/invalidation.go]: Added safety comment in 5ce2ed0b. Removing the backward compat after devnet reset is tracked in #19561 (item 8).

File: op-supernode/supernode/chain_container/chain_container.go (hunk 12 above)
Comment (karlfloersch) [reply op-supernode/supernode/chain_container/chain_container.go]: Filed #19561 and updated all TODOs with the issue reference in 5ce2ed0b.

File: op-supernode/supernode/chain_container/chain_container.go (hunk 13 above)
Comment (karlfloersch) [reply op-supernode/supernode/chain_container/chain_container.go:51]: Filed #19561 to track narrowing the ChainContainer interface. All 4 TODOs updated in 5ce2ed0b.

File: op-supernode/supernode/activity/interop/interop.go (hunk 2 above)
Comment (karlfloersch) [reply op-supernode/supernode/activity/interop/interop.go:362]: Tracked in #19561 (item 1) — will update tests to pass a no-op l1Checker and remove the nil guard.

File: op-supernode/supernode/activity/interop/interop.go (hunk 3 above)
Comment (karlfloersch) [reply op-supernode/supernode/activity/interop/interop.go:66]: Tracked in #19561 (item 2) — will switch to string-based serialization for WAL resilience.

File: op-supernode/supernode/activity/interop/verified_db.go (hunk 4 above)
Comment (karlfloersch) [reply op-supernode/supernode/activity/interop/verified_db.go:147]: Tracked in #19561 (item 3) — will compare deserialized structs instead of raw bytes.

File: op-supernode/supernode/activity/interop/interop_test.go (hunk 5 above)
Comment (karlfloersch) [reply op-supernode/supernode/activity/interop/interop_test.go:1475]: Tracked in #19561 (item 4) — will add end-to-end rewind replay test.

File: op-supernode/supernode/activity/interop/interop_test.go (hunk 7 above)
Comment (karlfloersch) [reply op-supernode/supernode/activity/interop/interop_test.go:1805]: Tracked in #19561 (item 5) — will add integration tests exercising progressAndRecord directly.

File: op-supernode/supernode/activity/interop/interop.go (hunk 8 above)
Comment (karlfloersch) [reply op-supernode/supernode/activity/interop/interop.go:105]: Tracked in #19561 (item 6) — will pass through call chain instead.
