### PR TITLE
fix(kona/derive): accept EIP-4844 type-3 batcher txs in CalldataSource

### LINKED ISSUE #19352: kona: CalldataSource silently drops EIP-4844 (type 3) batcher transactions pre-Ecotone
## Finding

**Review:** kona-node-vs-op-node  
**Component:** data-sources  
**Severity:** consensus-critical (low priority — Ecotone now activated on all supported chains)  
**Batcher:** honest  
**Confidence:** likely

## Description

`CalldataSource::load_calldata` in kona uses `_ => return None` as the catch-all arm, which silently skips EIP-4844 (type 3) batcher transactions. In contrast, op-node's `isValidBatchTx` explicitly allows transaction types 0–3 and 0x7E, and `DataFromEVMTransactions` extracts calldata from valid EIP-4844 batcher txs via `tx.Data()`.

In the pre-Ecotone window — where L1 has Cancun/EIP-4844 available but L2 Ecotone is not yet activated — an honest batcher could submit an EIP-4844 tx with calldata to the batch inbox. Op-node would include that calldata in the derivation stream; kona would skip the transaction entirely, producing divergent L2 chain state.

Note: the op-batcher has an explicit startup guard (`service.go:297-299`) preventing the reference op-batcher from reaching this case. However, the base derivation spec (`derivation.md:504`) explicitly lists type 3 as a valid batcher tx type with no pre-Ecotone exclusion, so the discrepancy is reachable by any spec-compliant alternative batcher and represents a genuine protocol-level gap in kona's calldata path.

**Priority note:** Ecotone is now activated on all supported chains, so this cannot be triggered on mainnet/testnets today. However it is a latent protocol conformance issue.

## Locations

| | Location |
|---|---|
| Reference (op-node) | [`op-node/rollup/derive/data_source.go#L99`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/op-node/rollup/derive/data_source.go#L99) |
| Reference (op-node) | [`op-node/rollup/derive/calldata_source.go#L82`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/op-node/rollup/derive/calldata_source.go#L82) |
| Subject (kona) | [`rust/kona/crates/protocol/derive/src/sources/calldata.rs#L52`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/rust/kona/crates/protocol/derive/src/sources/calldata.rs#L52) |

## Fix

In `calldata.rs`, add type 3 (EIP-4844) to the accepted transaction types list alongside types 0, 1, 2, and 0x7E.

### PR DESCRIPTION
**Pull request by ajsutton**
## Summary

`CalldataSource::load_calldata` uses `_ => return None` as the catch-all arm, silently dropping EIP-4844 (type 3) batcher transactions. This diverges from op-node which explicitly handles types 0–3 and 0x7E.

In the pre-Ecotone window an honest batcher could submit an EIP-4844 tx with calldata to the batch inbox; op-node would process it while kona would silently skip it, causing divergent chain state.

## Fix

Add `TxEnvelope::Eip4844` handling to the match arm in `load_calldata`, extracting the `to` address and `input` calldata from both `TxEip4844Variant::TxEip4844` and `TxEip4844Variant::TxEip4844WithSidecar`. Update the existing `test_load_calldata_blob_tx_ignored` test (renamed to `test_load_calldata_blob_tx_calldata_included`) to assert the correct post-fix behaviour.

Fixes https://github.com/ethereum-optimism/optimism/issues/19352

### CODE REVIEW

File: rust/kona/crates/protocol/derive/src/sources/calldata.rs [hunk 1]
```diff
@@ -49,6 +49,18 @@ impl<CP: ChainProvider + Send> CalldataSource<CP> {
                     TxEnvelope::Legacy(tx) => (tx.tx().to(), tx.tx().input()),
                     TxEnvelope::Eip2930(tx) => (tx.tx().to(), tx.tx().input()),
                     TxEnvelope::Eip1559(tx) => (tx.tx().to(), tx.tx().input()),
+                    // EIP-4844 (type 3) transactions are valid batcher transaction types per the
+                    // derivation spec (derivation.md:504). In the pre-Ecotone window an honest
```
Comment (ajsutton) [inline rust/kona/crates/protocol/derive/src/sources/calldata.rs]:
```suggestion
                    // derivation spec. In the pre-Ecotone window an honest
```

File: rust/kona/crates/protocol/derive/src/sources/calldata.rs [hunk 2]
```diff
@@ -236,8 +248,13 @@ mod tests {
         assert!(source.open);
     }
 
+    /// Regression test: EIP-4844 (type 3) batcher transactions must NOT be silently
+    /// dropped. Per the derivation spec (derivation.md:504) type 3 is a valid batcher tx type
+    /// with no pre-Ecotone exclusion. An honest batcher could submit an EIP-4844 tx carrying
+    /// calldata in the pre-Ecotone window; kona must include that calldata in the derivation
+    /// stream to remain consistent with op-node.
```
Comment (ajsutton) [inline rust/kona/crates/protocol/derive/src/sources/calldata.rs]:
```suggestion
    /// with no pre-Ecotone exclusion. 
```

File: rust/kona/crates/protocol/derive/src/sources/calldata.rs [hunk 3]
```diff
@@ -248,7 +265,8 @@ mod tests {
         assert!(
             source.load_calldata(&BlockInfo::default(), tx.recover_signer().unwrap()).await.is_ok()
         );
-        assert!(source.calldata.is_empty());
+        // EIP-4844 batcher tx calldata must be included, not silently dropped.
```
Comment (ajsutton) [inline rust/kona/crates/protocol/derive/src/sources/calldata.rs]:
```suggestion
```

**Review by ajsutton — COMMENTED** [review]
## Wrong code on this branch

The PR title/body and linked issue (#19352) describe fixing EIP-4844 type-3 batcher tx handling in `CalldataSource` — specifically adding a `TxEnvelope::Eip4844` match arm to `load_calldata` in `calldata.rs`.

However, the actual code change is a **completely different fix**: copying `origin` during the Holocene `BatchQueue`→`BatchValidator` transition in `batch_provider.rs`. This is the same fix as PR #19360.

- `calldata.rs` is not modified at all
- Issue #19352 (silent drop of type-3 txs) remains unfixed
- The branch name (`fix/ds-11-calldata-eip4844-type3`) also references the intended fix, not what's here

Looks like the wrong commits were pushed to this branch. The actual calldata fix still needs to be implemented.

**Review by sebastianst — APPROVED** [review]
