### PR TITLE
op-service/txmgr: fix `pending_txs` metric

### LINKED ISSUE #14109: op-batcher: pending transactions is never higher than 1
We are seeing this in production networks. With the current way the batcher works, it should send transactions asynchronously (but with nonces determined synchronously). 

We would therefore expect (particularly in times of high thoughput) that there would be multiple pending transactions (up to the configured limit, typically `5` or so). 

There could be a bug in the metrics, or the transactions are not actually being handled in the expected way (which would indicate that we are hamstringing the batcher's throughput unintentionally).

### PR DESCRIPTION
**Pull request by geoknee**
Closes #14109

### CODE REVIEW

File: op-service/txmgr/txmgr.go [hunk 1]
```diff
@@ -295,18 +293,19 @@ func (m *SimpleTxManager) SendAsync(ctx context.Context, candidate TxCandidate,
...
+	m.metr.RecordPendingTx(m.pending.Add(1))
+
 	go func() {
-		defer m.metr.RecordPendingTx(m.pending.Add(-1))
 		defer cancel()
 		receipt, err := m.sendTx(ctx, tx)
+		m.metr.RecordPendingTx(m.pending.Add(-1))
 		if err != nil {
 			m.resetNonce()
 		}
```
Comment (geoknee) [inline op-service/txmgr/txmgr.go]: This change is the operative one in getting the new test to pass. Without it, the pending transactions metric does not increase as expected. I don't yet fully understand why.

Comment (geoknee) [reply op-service/txmgr/txmgr.go]: I think the reason is that when using a `defer` statement, the arguments to the function call are determined immediately (not deferred). So we were committing to the value to set the "pending txs" metric to way ahead of time, before many network calls are mad inside of `m.sendTx`. Therefore if (meanwhile) the metric increases concurrently (perhaps it gets incremented twice), when the deferred call is mad we end up decrementing from an out-of-date value and incorrectly suppressing the pending txs metric.

Comment (geoknee) [reply op-service/txmgr/txmgr.go]: We could use an anonymous fn call and still use a `defer` metric.

File: op-service/txmgr/txmgr.go [hunk 2]
```diff
@@ -295,18 +293,19 @@ func (m *SimpleTxManager) SendAsync(ctx context.Context, candidate TxCandidate,
...
 		return
 	}
 
+	m.metr.RecordPendingTx(m.pending.Add(1))
+
 	go func() {
-		defer m.metr.RecordPendingTx(m.pending.Add(-1))
 		defer cancel()
 		receipt, err := m.sendTx(ctx, tx)
+		m.metr.RecordPendingTx(m.pending.Add(-1))
```
Comment (sebastianst) [inline op-service/txmgr/txmgr.go]: This was indeed the bug, `defer` evaluates all function calls but the outermost of course 😅 
I still think it's worth using `defer` so in case there's a panic in this goroutine, the counter still works.
```suggestion
		defer func() {m.metr.RecordPendingTx(m.pending.Add(-1))}()
```
(and move back to old location)

**Review by sebastianst — APPROVED** [review]
lgtm, one optional suggestion

File: op-service/txmgr/txmgr.go (hunk 2 above)
Comment (geoknee) [reply op-service/txmgr/txmgr.go]: [8c42d46](https://github.com/ethereum-optimism/optimism/pull/14168/commits/8c42d465217e374616c1cea3528193d09112ef32)
