### PR TITLE
op-node: Add pectra blob schedule fix kill-switch

### LINKED ISSUE #14920: op-node: Add kill-switch for Sepolia and Holesky if no pectra blob schedule fix is configured
Due to the pectra blob schedule bug, sepolia and holesky chains with a sequencer running op-node/v1.11.2 or earlier, while L1 activated Pectra, were running into a bug where the blob base fee of the L1 Info block wasn't correctly calculated. See release notes of [op-node/v1.12.0](https://github.com/ethereum-optimism/optimism/releases/tag/op-node%2Fv1.12.0) for details.

We have since then released op-node v1.12.0 and v1.12.1 with a fix included. However, that fix needs to be explicitly scheduled. Node operators just upgrading from 1.11.2 to one of these releases without their chain having the fix scheduled (as part of the SR) would chain-split. The fix always has to be scheduled. This is being warned about at the top of the releases, but node operators might still miss it.

So I proposer that we add a kill-switch to op-node, where at startup it checks
* if the chain's L1 is Sepolia or Holesky
* if the pectra block schedule fix does _not_ have a timestamp set
* if the L2 genesis timestamp is before the L1's activation of Pectra

If all of those conditions are true, the node exits with a warning explaining that this chain probably needs to schedule the fix. The warning can be deactivated with a hidden flag to force the node to start without the fix scheduled.

### PR DESCRIPTION
**Pull request by sebastianst**
**Description**

Adds a kill-switch to op-node, where at startup it checks
- if the chain's L1 is Sepolia or Holesky
- if the pectra block schedule fix does not have a timestamp set
- if the L2 genesis timestamp is before the L1's activation of Pectra

and if all of those conditions are true, the node exits with a warning explaining that this chain probably needs to schedule the fix. The warning can be deactivated with a hidden flag to force the node to start without the fix scheduled.

See https://github.com/ethereum-optimism/optimism/issues/14920 for more details.

I've decided to run this check as part of assembling the op-node configurations. While the logic is implemented as a method on the `rollup.Config`, it's not part of `rollup.Config.Check()` to avoid enshrining this check into generic rollup config handling. This can be changed if reviewers prefer to move the check into the rollup config's check.

**Tests**

Added unit test for the check logic on the rollup config.

**Metadata**

Fixes https://github.com/ethereum-optimism/optimism/issues/14920

### CODE REVIEW

File: op-node/node/config.go [hunk 1]
```diff
@@ -154,6 +156,9 @@ func (cfg *Config) Check() error {
 	if err := cfg.Rollup.Check(); err != nil {
 		return fmt.Errorf("rollup config error: %w", err)
 	}
+	if cfg.Rollup.ProbablyMissingPectraBlobSchedule() {
+		return ErrMissingPectraBlobSchedule
+	}
```
Comment (protolambda) [inline op-node/node/config.go]: If this returns an error early, and if it then gets ignored by config flag, then it ends up skipping all the config-checks that come after this.

I think we should put the `IgnoreMissingPectraBlobSchedule` bool inside of the node config.

Comment (sebastianst) [reply op-node/node/config.go]: Good catch. Yeah adding it as a bool field works, just tried to make the footprint of this as minimal as possible.

**Review by protolambda — APPROVED** [review]

**Comment by atenjin** [comment]
In fact I think if this rollup is using altda, then it does not need to set the hardfork... But based on this pr, even altda rollup must need to set..
