### PR TITLE
op-challenger: Support retrieving the oracle and prestate via game args.

### LINKED ISSUE #17810: Update op-challenger, dispute-mon to pull oracle correctly for v2 game contracts
## Description

The new v2 dispute game acceptance test is [failing at initialization](https://github.com/ethereum-optimism/optimism/blob/cdb9d1f4767c70c2e278f19b8874c5fd15ae41f2/op-acceptance-tests/tests/base/disputegame_v2/init_test.go#L10-L10) as of [the OPCM.deploy update PR](https://github.com/ethereum-optimism/optimism/pull/17408) due to the op-challenger attempting to [pull the vm oracle address from the game implementation contract](https://github.com/ethereum-optimism/optimism/blob/cdb9d1f4767c70c2e278f19b8874c5fd15ae41f2/op-challenger/game/fault/register_task.go#L390-L390) directly.  For v2 games, we'll need to pull the vm address from `DisputeGameFactory.gameArgs` to get the address of the VM, from which we'll be able to get the oracle address. 

We should fix op-challenger and dispute-mon to pull this data correctly for the new contracts.

### PR DESCRIPTION
**Pull request by ajsutton**
**Description**

The implementation contract doesn't always have the values embedded. It automatically switches between game args and reading from the implementation, as well as detecting versions that don't yet support game args for backwards compatibility.

The `GetGameImpl` method is now internal to `DisputeGameFactory` to ensure that nothing is grabbing the game implementation and depending on its behaviour. `DisputeGameFactory` exposes methods to get the VM or Prestate in a way that's compatible with game args.

**Tests**

Updated tests. Smoke test that detected this is now enabled.

**Metadata**

fixes https://github.com/ethereum-optimism/optimism/issues/17810

### CODE REVIEW

File: op-challenger/game/fault/contracts/gamefactory.go [hunk 1]
```diff
@@ -33,20 +36,56 @@ var (
 	ErrEventNotFound = errors.New("event not found")
 )
 
+//go:embed abis/DisputeGameFactory-1.2.0.json
+var disputeGameFactoryAbi121 []byte
```
Comment (mbaxter) [inline op-challenger/game/fault/contracts/gamefactory.go]:
```suggestion
var disputeGameFactoryAbi120 []byte
```
?

File: op-challenger/game/fault/contracts/gamefactory_test.go [hunk 2]
```diff
@@ -42,82 +76,94 @@ func TestDisputeGameFactorySimpleGetters(t *testing.T) {
...
-		t.Run(test.method, func(t *testing.T) {
-			stubRpc, factory := setupDisputeGameFactoryTest(t)
-			stubRpc.SetResponse(factoryAddr, test.method, rpcblock.ByHash(blockHash), nil, []interface{}{test.result})
-			status, err := test.call(factory)
-			require.NoError(t, err)
-			expected := test.expected
-			if expected == nil {
-				expected = test.result
+	for _, version := range factoryVersions {
+		t.Run(version.String(), func(t *testing.T) {
```
Comment (mbaxter) [inline op-challenger/game/fault/contracts/gamefactory_test.go:83]: Should we add some tests for `GetGameVm` and `GetGamePrestate`?

**Review by Inphi — APPROVED** [review]
Looks good.
Could we alsoupdate gamefactory_test.go to cover calls such as `DisputeGameFactoryContract.GetGamePrestate` for dispute-game v2 game args.

**Review by mbaxter — APPROVED** [review]

File: op-challenger/game/fault/contracts/gamefactory_test.go (hunk 2 above)
Comment (ajsutton) [reply op-challenger/game/fault/contracts/gamefactory_test.go:83]: Yes, good call, I meant to come back to that and then forgot.
