### PR TITLE
interop: supervisor: fix cycle detection logic

### LINKED ISSUE #15567: interop: revise cycle detection logic

### PR DESCRIPTION
**Pull request by pcw109550**
**Description**

Message dependency check is crucial and they are checked via cycle detection. Supervisor constructs a directed graph, which edges are message dependencies and nodes are message.

Every logs in block can be a message, and each adjacent logs have dependencies. So if a single block has 3 logs A0, A1, A2, there are two edges, and entire dependency graph be A0->A1->A2.

In interop, there are special messages called executing messages, and they depend on single log, or we call them initiating message. So if a single block from chain A contains logs, and its 3rd log is A2, and chain B attempts to execute message B3 at 4th log in its block for A2, the graph edge be A2->B3.

Supervisor gathers logs, group them in same timestamp, construct directed graph, and checks cycles. Supervisor must mark blocks which contain cyclic dependency as invalid, and spread that information to everyone.

The original graph building algorithm contained below code segment:
```go
			// Check if we care about the init message
			initChainMsgs, ok := execMsgs[m.Chain]
			if !ok {
				continue
			}
			if _, ok := initChainMsgs[m.LogIdx]; !ok {
				continue
			}
```
and made the final graph not to include some edges, resulting in wrong graph resulting in invalid cycle detection. This PR attempts to remove upper logic to construct a correct graph.

**Tests**

Unit tests added. `cycle through younger|older timestamp` test cases were not considered as cycle detection, but they contained cycle. Removed these tests. 

Added comments for explicit cycles.
 
**Metadata**

- Fixes https://github.com/ethereum-optimism/optimism/issues/15567

### CODE REVIEW

**Comment by axelKingsley** [comment]
> made the final graph not to include some edges, resulting in wrong graph resulting in invalid cycle detection. This PR attempts to remove upper logic to construct a correct graph.

Can you describe the input which causes missing edges? Looking at the code we're removing here, it looks intentionally included. There are a couple comments on this code in the [Original PR,](https://github.com/ethereum-optimism/optimism/pull/12530/files#r1818555770) but I'm not sure they're relevant to the misbehavior you're describing.

I'm reading over the test cases you've included but I'm not sure I understand what this removal changes -- seems like maybe removing this logic allows for adjacent logs to form edges?

File: op-supervisor/supervisor/backend/cross/cycle_test.go [hunk 1]
```diff
@@ -474,7 +470,10 @@ func TestHazardCycleChecksCycle(t *testing.T) {
 			msg:       "expected cycle detection error for cycle through executing messages",
 		},
 		{
-			name: "3-cycle in single chain",
+			// 1->2->1
+			// 2->3->2
+			// 1->3->2->1
+			name: "2,2,3-cycle in single chain",
```
Comment (axelKingsley) [inline op-supervisor/supervisor/backend/cross/cycle_test.go]: I'm not sure I understand why we are changing the name of this test. Looking at the messages in the test input,

```
					messages: map[uint32]*types.ExecutingMessage{
						1: execMsg("1", 2), // Points to log 2
						2: execMsg("1", 3), // Points to log 3
						3: execMsg("1", 1), // Points back to log 1
```

My reading of this is `1->2->3->1` and nothing else. What makes the `1->2->1` or `2->3->2` loop? I guess this is just their dependency due to being arranged in the same block?

Are we sure this isn't already handled by timestamp based comparisons?

Comment (pcw109550) [reply op-supervisor/supervisor/backend/cross/cycle_test.go]: There are 4 logs in that test case. Lets denote them `L0`, `L1`, `L2`, `L3`.

By default, `L1` depends on `L0`, `L2` depends on `L1`, `L3` depends on `L2`. I will denote this dependency as `L0->L1->L2->L3`.
`1: execMsg("1", 2)` means that, `L1` is the log for executing message, and that message points to initiating message `L2`. Since executing message depends on initiating message, `L1` depends on `L2`. We denote this as `L2->L1`.
Similarly, `2: execMsg("1", 3)` corresponds to `L3->L2`, and `3: execMsg("1", 1)` corresponds to `L1->L3`.

Now we gather all the edges: `L0->L1->L2->L3`, `L2->L1`,`L3->L2`, `L1->L3`.
We get 3 cycles:
- `L1->L2->L1`
- `L2->L3->L2`
- `L1->L3->L2->L1`

Diagram:
image

**Comment by pcw109550** [comment]
@axelKingsley The inspection started with below test case:
```go
			chainBlocks: map[string]chainBlockDef{
 				"1": {
 					logCount: 2,
 					messages: map[uint32]*types.ExecutingMessage{
 						0: execMsg("1", 1),
 					},
 				},
 			},
```
So `L0` depends on `L1` and `L1` depends on `L0`. Because of the original code block:
```go
			// Check if we care about the init message
			initChainMsgs, ok := execMsgs[m.Chain]
			if !ok {
				continue
			}
			if _, ok := initChainMsgs[m.LogIdx]; !ok {
				continue
			}
```
which i removed made the edge `L1->L0` not to be included in the directed graph, resulting in no error detection.

File: op-supervisor/supervisor/backend/cross/cycle_test.go (hunk 1 above)
Comment (axelKingsley) [reply op-supervisor/supervisor/backend/cross/cycle_test.go]: Ah, I see now. The key is in this explainer comment in `cycle.go`

```
// The edges of the graph are determined by:
//   - For all logs except the first in a block, there is an edge from the previous log.
//   - For all executing messages, there is an edge from the initiating message.
```
So indeed, it's about logs which are together in a block, edges should extend from previous logs. But this logic you've removed was previously jumping over those edges. now the 1-2-1 and 2-3-2 make sense.

File: op-supervisor/supervisor/backend/cross/cycle_test.go [hunk 2]
```diff
@@ -354,52 +356,41 @@ func TestHazardCycleChecksNoCycle(t *testing.T) {
...
-	runHazardCycleChecksTestCaseGroup(t, "NoCycle", tests)
-}
-
-func TestHazardCycleChecksCycle(t *testing.T) {
-	tests := []hazardCycleChecksTestCase{
 		{
-			name: "2-cycle in single chain with first log",
+			// 0->1->2->0
+			// 0->2->0
+			name: "3-cycle in single chain, 2-cycle in single chain with first log",
```
Comment (protolambda) [inline op-supervisor/supervisor/backend/cross/cycle_test.go]:
```suggestion
			// 0->2->0   - both the executing messages
			// 0->2->1->0  - first executing message combined with regular log-ordering dependencies
			name: "3-cycle in single chain, 2-cycle in single chain with first log",
```

Log 0 here never depends directly on log 1. It depends on log 2. I think this go comment needs an update.

File: op-supervisor/supervisor/backend/cross/cycle_test.go [hunk 3]
```diff
@@ -441,7 +434,9 @@ func TestHazardCycleChecksCycle(t *testing.T) {
 			msg:       "expected cycle detection error",
 		},
 		{
-			name: "2-cycle in single chain, not first, not adjacent",
+			// 1->3->1
+			// 1->2->3->1
+			name: "2,3-cycle in single chain, not first, not adjacent",
```
Comment (protolambda) [inline op-supervisor/supervisor/backend/cross/cycle_test.go]:
```suggestion
			// 1->3->1  - two executing messages
			// 1->3->2->1  - one executing message and regular log ordering
			name: "2,3-cycle in single chain, not first, not adjacent",
```

File: op-supervisor/supervisor/backend/cross/cycle_test.go [hunk 4]
```diff
@@ -474,7 +470,10 @@ func TestHazardCycleChecksCycle(t *testing.T) {
 			msg:       "expected cycle detection error for cycle through executing messages",
 		},
 		{
-			name: "3-cycle in single chain",
+			// 1->2->1
+			// 2->3->2
+			// 1->3->2->1
```
Comment (protolambda) [inline op-supervisor/supervisor/backend/cross/cycle_test.go]:
```suggestion
			// 1->2->1  - 1 executes the next log, forming a small cycle
			// 2->3->2  - 2 executes the next log, forming a small cycle
			// 3->1->2->3  - (3->1) is a valid executing message, but part of a larger cycle where 2 and 1 depend on the next future log.
			// 3->2->1->2->3  - we have the regular order of logs, and then multiple logs pointing to the future logs, making an even larger cycle.
```

Edit: updated the suggestion. The original old suggestion was:
```
			// 1->2->1
			// 2->3->2
```

I think you are flipping the initiating/executing side (or I am) in some of these comments. If the format is `exec -> init` message, then there is no such thing as `1` depending on `3` here. In the test-cases it's `3` that depends on `1`.

File: op-supervisor/supervisor/backend/cross/cycle_test.go [hunk 5]
```diff
@@ -489,6 +488,8 @@ func TestHazardCycleChecksCycle(t *testing.T) {
 			msg:       "expected cycle detection error for 3-node cycle",
 		},
 		{
+			// 1->2->3->4->5->1
+			// 1->2->5->1
```
Comment (protolambda) [inline op-supervisor/supervisor/backend/cross/cycle_test.go]:
```suggestion
			// 1->5->4->3->2->1  - executing message, and multiple regular log ordering steps
			// 1->5->2->1 - two executing messages and single regular log ordering dependency
```
The arrows seemed the other way around, compared to the other test case descriptions: `1` depends on `5`, and `5` then has prior logs. (assuming we are using `exec -> init` as format).

And the `5` depending on `2` part in the test is valid, not a cycle without the other 1->5 link.

File: op-supervisor/supervisor/backend/cross/cycle_test.go [hunk 6]
```diff
@@ -527,6 +529,54 @@ func TestHazardCycleChecksCycle(t *testing.T) {
...
+					messages: map[uint32]*types.ExecutingMessage{
+						0: execMsg("1", 1),
+					},
+				},
+			},
+			expectErr: ErrCycle,
+			msg:       "expected cycle detection error",
+		},
+		{
+			// 0->1->2->0
```
Comment (protolambda) [inline op-supervisor/supervisor/backend/cross/cycle_test.go]:
```suggestion
			// 0->2->1->0
```
(Assuming `exec -> init` format, the other way around is fine too, but need some consistency across comments)

File: op-supervisor/supervisor/backend/cross/cycle_test.go [hunk 7]
```diff
@@ -527,6 +529,54 @@ func TestHazardCycleChecksCycle(t *testing.T) {
...
+					messages: map[uint32]*types.ExecutingMessage{
+						0: execMsg("1", 2),
+					},
+				},
+			},
+			expectErr: ErrCycle,
+			msg:       "expected cycle detection error",
+		},
+		{
+			// A1->B0->A0->A1
```
Comment (protolambda) [inline op-supervisor/supervisor/backend/cross/cycle_test.go]:
```suggestion
			// A0->B0->A1->A0  - A may not depend on a log of B that depends on the future of A
```

File: op-supervisor/supervisor/backend/cross/cycle_test.go [hunk 8]
```diff
@@ -354,52 +356,41 @@ func TestHazardCycleChecksNoCycle(t *testing.T) {
...
+	}
+	runHazardCycleChecksTestCaseGroup(t, "NoCycle", tests)
+}
+
+func TestHazardCycleChecksCycle(t *testing.T) {
+	tests := []hazardCycleChecksTestCase{
 		{
-			name: "cycle through younger timestamp",
+			// 0->1->2->0
+			name: "3-cycle in single chain",
```
Comment (protolambda) [inline op-supervisor/supervisor/backend/cross/cycle_test.go]:
```suggestion
			// 0->2->1->0  - executing message pointing to the future, cycle completed by regular log ordering
			name: "3-cycle in single chain",
```

File: op-supervisor/supervisor/backend/cross/cycle_test.go [hunk 9]
```diff
@@ -354,52 +356,41 @@ func TestHazardCycleChecksNoCycle(t *testing.T) {
...
-			msg: "expected no cycle detection error for cycle through messages with different timestamps",
+			msg: "expected no cycle for different timestamp",
 		},
-		// This should be caught by earlier validations, but included for completeness.
+	}
+	runHazardCycleChecksTestCaseGroup(t, "NoCycle", tests)
+}
+
+func TestHazardCycleChecksCycle(t *testing.T) {
+	tests := []hazardCycleChecksTestCase{
```
Comment (protolambda) [inline op-supervisor/supervisor/backend/cross/cycle_test.go]:
```suggestion
func TestHazardCycleChecksCycle(t *testing.T) {
	// Comment cycle notation: `executing message -> corresponding initiating message`
	// The index of the log itself is used as name of the message.
	// For different chains, "A" or "B", etc. may be prefixed, to identify the chain with the corresponding chain index. (A=0, B=1, etc.)
	tests := []hazardCycleChecksTestCase{
```

**Review by protolambda — COMMENTED** [review]
The fix looks good, great catch! Just some nits on test comment annotation. Doing the `->` the other way around can work too, but it didn't seem consistent, and so I tried to update the comments the way I thought reads more easily, and added descriptions about the kind of dependencies themselves.

File: op-supervisor/supervisor/backend/cross/cycle_test.go (hunk 4 above)
Comment (pcw109550) [reply op-supervisor/supervisor/backend/cross/cycle_test.go]: I get this confusion, so we are saying that 3->1 does not count as cycle. But initially I still included this as a cycle, by merging 2,2 cycles. So 3->1->2->3 for completeness.

(3->1) + (1->2) + (2->3)

Comment (pcw109550) [reply op-supervisor/supervisor/backend/cross/cycle_test.go]: https://github.com/ethereum-optimism/optimism/pull/15568/files#r2060422854 this comment may be helpful although it uses the reverse notation.

Comment (protolambda) [reply op-supervisor/supervisor/backend/cross/cycle_test.go]: Oh I see now, there's indeed that larger cycle, where `(3->1)` is valid, but because `(1->2)` is an invalid pointer into the future, and `(2->3)` is an invalid pointer into the future, we end up with a cycle, even though `(1->2)` is already a cycle because of the `(2->1)` implied by regular order, and likewise for `(2->3)` being a cycle with `(3->2)` on its own.

Comment (protolambda) [reply op-supervisor/supervisor/backend/cross/cycle_test.go]: Updated the suggestion with clarification. There are 4 distinct cycles.

**Review by protolambda — APPROVED** [review]
