### PR TITLE
op-dispute-mon: node endpoint error metrics

### LINKED ISSUE #11020: dispute-mon: Multiple rollup node metrics
Once dispute-mon has support for reading from multiple rollup nodes (#11019), we need to expose additional metrics to support alerting when there are disagreements between nodes or some nodes failing. Each of these should be driven by adding fields to the `EnrichedGameData` to capture the data for a single game, then aggregated by adding a new [`Monitor`](https://github.com/ethereum-optimism/optimism/blob/bde6a96e65d812f33681069009cdf3fa4f1f87d7/op-dispute-mon/mon/monitor.go#L19) in `gameMonitor` that aggregates the data across all games and then reports it to metrics ([`L2ChallengesMonitor`](https://github.com/ethereum-optimism/optimism/blob/bde6a96e65d812f33681069009cdf3fa4f1f87d7/op-dispute-mon/mon/l2_challenges.go#L24) is an example of this kind of monitor implementation).

Metrics to report:
* Gauge of total number of endpoints that returned an error (other than not found) during the last update cycle - note this is the number of rpcs that had at least 1 failure, so if the same rpc gives an error on 10 games that still counts as 1.
* Gauge of total number of failures (other than not found) in the last update cycle. This counts each error from an rpc as a new event even if the rpc is the same (so one rpc giving 10 errors sets this to 10).
* Gauge of the total number of games where some nodes reported not found and others had the block in the last update cycle.
* Gauge of the total number of games where some nodes reported the output root as safe and others as unsafe in the last update cycle
* Gauge of the total number of games where nodes returned different expected output roots in the last update cycle

PRs:
- https://github.com/ethereum-optimism/optimism/pull/17622
- https://github.com/ethereum-optimism/optimism/pull/18105

### PR DESCRIPTION
**Pull request by pauldowman**
This PR adds the following prometheus metrics to dispute-mon:

* Gauge of total number of endpoints that returned an error (other than not found) during the last update cycle - note this is the number of rpcs that had at least 1 failure, so if the same rpc gives an error on 10 games that still counts as 1.
* Gauge of total number of failures (other than not found) in the last update cycle. This counts each error from an rpc as a new event even if the rpc is the same (so one rpc giving 10 errors sets this to 10).
* Gauge of the total number of games where some nodes reported not found and others had the block in the last update cycle.
* Gauge of the total number of games where some nodes reported the output root as safe and others as unsafe in the last update cycle
* Gauge of the total number of games where nodes returned different expected output roots in the last update cycle

Reviewers might want to look at each commit separately, there's one for each metric.

Part of #11020. Super agreement enricher should be done before we close that, I'll do it in a separate PR.

### CODE REVIEW

File: op-dispute-mon/mon/types/types.go [hunk 1]
```diff
@@ -59,13 +59,51 @@ type EnrichedGameData struct {
...
+		return false
+	}
+
+	successfulEndpoints := g.RollupEndpointTotalCount - g.RollupEndpointErrorCount - g.RollupEndpointNotFoundCount
+	return g.RollupEndpointNotFoundCount > 0 && successfulEndpoints > 0
+}
+
+// HasMixedSafety returns true if some rollup endpoints reported the root as safe and others as unsafe
+// for this game. This indicates inconsistent safety assessment across the rollup node network.
+func (g EnrichedGameData) HasMixedSafety() bool {
```
Comment (Inphi) [inline op-dispute-mon/mon/types/types.go:103]: Was this supposed to be recorded in a metric? I only see this function used by tests.

File: op-dispute-mon/mon/types/types.go [hunk 2]
```diff
@@ -59,13 +59,51 @@ type EnrichedGameData struct {
...
+	RollupEndpointTotalCount int
+
+	// RollupEndpointSafeCount tracks the number of rollup endpoints that reported the root as safe.
+	RollupEndpointSafeCount int
+
+	// RollupEndpointUnsafeCount tracks the number of rollup endpoints that reported the root as unsafe.
+	RollupEndpointUnsafeCount int
+
+	// RollupEndpointDifferentOutputRoots tracks whether rollup endpoints returned different output roots for this game.
+	RollupEndpointDifferentOutputRoots bool
```
Comment (Inphi) [inline op-dispute-mon/mon/types/types.go:82]: There's no way to observe the value of this field. I don't see a log or a metric set when this is updated.

File: op-dispute-mon/mon/node_endpoint_errors.go [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+		metrics: metrics,
+	}
+}
+
+func (m *NodeEndpointErrorsMonitor) CheckNodeEndpointErrors(games []*types.EnrichedGameData) {
+	// Use a set to track unique endpoint errors across all games
+	uniqueEndpointErrors := make(map[string]bool)
+
+	for _, game := range games {
+		if game.RollupEndpointErrors != nil {
```
Comment (Inphi) [inline op-dispute-mon/mon/node_endpoint_errors.go]:
```suggestion
		if len(game.RollupEndpointErrors) != 0 {
```
since the map is always initialized in `enrichGame`. Also, it's idiomatic to use `len` for emptiness because it also works when the map is nil.

File: op-dispute-mon/mon/node_endpoint_errors.go [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+		}
+	}
+
+	errorCount := len(uniqueEndpointErrors)
+	if errorCount > 0 {
+		m.logger.Warn("Found rollup node endpoint errors",
+			"unique_endpoint_count", errorCount,
+			"endpoints", getEndpointList(uniqueEndpointErrors))
+	} else {
+		m.logger.Debug("No rollup node endpoint errors found")
```
Comment (Inphi) [inline op-dispute-mon/mon/node_endpoint_errors.go]: nit: possibly noisy debug. Could use `Trace` instead.

File: op-dispute-mon/mon/node_endpoint_error_count.go [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+	for _, game := range games {
+		totalErrors += game.RollupEndpointErrorCount
+	}
+
+	if totalErrors > 0 {
+		m.logger.Warn("Found rollup node endpoint errors",
+			"total_error_count", totalErrors,
+			"games_with_errors", countGamesWithErrors(games))
+	} else {
+		m.logger.Debug("No rollup node endpoint errors found")
```
Comment (Inphi) [inline op-dispute-mon/mon/node_endpoint_error_count.go]: nit: Noisy debug. Consider using `Trace`

File: op-dispute-mon/mon/mixed_availability.go [hunk 6]
```diff
@@ -0,0 +1,42 @@
...
+				"totalEndpoints", game.RollupEndpointTotalCount,
+				"notFoundCount", game.RollupEndpointNotFoundCount,
+				"errorCount", game.RollupEndpointErrorCount)
+		}
+	}
+
+	m.metrics.RecordMixedAvailabilityGames(count)
+
+	if count > 0 {
+		m.logger.Info("Mixed availability summary", "gamesWithMixedAvailability", count, "totalGames", len(games))
```
Comment (Inphi) [inline op-dispute-mon/mon/mixed_availability.go]: worth logging this as a `Warn`. It's far from ideal when this occurs.

**Review by Inphi — COMMENTED** [review]
Looks good overall. There is some unused code that needs to be fixed.

an `op-dispute-mon/main` file was accidentally checked in. It should be removed.

File: op-dispute-mon/mon/mixed_availability.go (hunk 6 above)
Comment (pauldowman) [reply op-dispute-mon/mon/mixed_availability.go]: Done.

File: op-dispute-mon/mon/node_endpoint_error_count.go (hunk 5 above)
Comment (pauldowman) [reply op-dispute-mon/mon/node_endpoint_error_count.go]: I removed it completely, it was kind of a useless thing to log.

File: op-dispute-mon/mon/node_endpoint_errors.go (hunk 3 above)
Comment (pauldowman) [reply op-dispute-mon/mon/node_endpoint_errors.go]: Changed, thanks.

File: op-dispute-mon/mon/node_endpoint_errors.go (hunk 4 above)
Comment (pauldowman) [reply op-dispute-mon/mon/node_endpoint_errors.go]: Removed it completely.

**Comment by ajsutton** [comment]
Moving the goal posts on this one but with https://github.com/ethereum-optimism/optimism/pull/17831 it would be good to add a metric to report the number of out of sync RPCs (maybe with just the number of RPCs and the total number of out of sync responses like we have for errors).  Probably better to do in a follow up PR though.

File: op-dispute-mon/mon/node_endpoint_error_count.go [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+	totalErrors := 0
+
+	for _, game := range games {
+		totalErrors += game.RollupEndpointErrorCount
+	}
+
+	if totalErrors > 0 {
+		m.logger.Warn("Found rollup node endpoint errors",
+			"total_error_count", totalErrors,
+			"games_with_errors", countGamesWithErrors(games))
```
Comment (ajsutton) [inline op-dispute-mon/mon/node_endpoint_error_count.go]: Wouldn't we have already logged the errors when they happened? Seems like this will just make more noise in the logs and we should just let the metrics report the total numbers.

File: op-dispute-mon/mon/node_endpoint_errors.go [hunk 8]
```diff
@@ -0,0 +1,53 @@
...
+				uniqueEndpointErrors[endpointID] = true
+			}
+		}
+	}
+
+	errorCount := len(uniqueEndpointErrors)
+	if errorCount > 0 {
+		m.logger.Warn("Found rollup node endpoint errors",
+			"unique_endpoint_count", errorCount,
+			"endpoints", getEndpointList(uniqueEndpointErrors))
```
Comment (ajsutton) [inline op-dispute-mon/mon/node_endpoint_errors.go]: These have probably also been logged from the individual game.

File: op-dispute-mon/mon/service.go [hunk 9]
```diff
@@ -125,6 +131,18 @@ func (s *Service) initWithdrawalMonitor() {
...
+	s.mixedAvailability = NewMixedAvailability(s.logger, s.metrics)
+}
+
+func (s *Service) initMixedSafetyMonitor() {
+	s.mixedSafety = NewMixedSafetyMonitor(s.logger, s.metrics)
+}
+
+func (s *Service) initDifferentOutputRootMonitor() {
+	s.differentOutputRoot = NewDifferentOutputRootMonitor(s.logger, s.metrics)
+}
```
Comment (ajsutton) [inline op-dispute-mon/mon/service.go]: Do we need these to be set as fields or could they just be created in the method that needs them? Typically we only want to expose things as fields if they are used by multiple things or need life cycle management.

**Review by ajsutton — APPROVED** [review]
LGTM just a couple of small nits.

**Comment by opgitgovernance** [comment]
This pr has been automatically marked as stale and will be closed in 5 days if no updates

**Comment by pauldowman** [comment]
Ouch. Will wrap up ASAP.

File: op-dispute-mon/mon/service.go (hunk 9 above)
Comment (pauldowman) [reply op-dispute-mon/mon/service.go]: Actually I don't see why most of the existing ones are fields either. I refactored them all... hope I'm not missing something. 🤔

File: op-dispute-mon/mon/node_endpoint_errors.go (hunk 8 above)
Comment (pauldowman) [reply op-dispute-mon/mon/node_endpoint_errors.go]: Removed.

File: op-dispute-mon/mon/node_endpoint_error_count.go (hunk 7 above)
Comment (pauldowman) [reply op-dispute-mon/mon/node_endpoint_error_count.go]: Removed.

**Comment by pauldowman** [comment]
> Moving the goal posts on this one but with #17831 it would be good to add a metric to report the number of out of sync RPCs (maybe with just the number of RPCs and the total number of out of sync responses like we have for errors). Probably better to do in a follow up PR though.

Done in https://github.com/ethereum-optimism/optimism/pull/18105
