### PR TITLE
fix:fix wrong hex test data

### LINKED ISSUE #8647: Wrong length hex data in ssz_test.go
**Describe the bug**
Some test hex data has wrong length. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Specs:**
 - OS:
 - Package Version (or commit hash):

**Additional context**

### PR DESCRIPTION
**Pull request by GrapeBaBa**
**Description**

Some hex test data actual has wrong length, the test not check the actual value.

**Tests**

I only change some codes in test and also add some checking.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #8647 8647

### CODE REVIEW

File: op-service/eth/ssz_test.go [hunk 1]
```diff
@@ -250,21 +250,21 @@ func TestOPB04(t *testing.T) {
 
 func createPayloadWithWithdrawals(w *types.Withdrawals) *ExecutionPayload {
 	return &ExecutionPayload{
-		ParentHash:    common.HexToHash("0x123"),
-		FeeRecipient:  common.HexToAddress("0x456"),
-		StateRoot:     Bytes32(common.HexToHash("0x789")),
-		ReceiptsRoot:  Bytes32(common.HexToHash("0xabc")),
+		ParentHash:    common.HexToHash("0x1234"),
+		FeeRecipient:  common.HexToAddress("0x4567"),
```
Comment (ajsutton) [inline op-service/eth/ssz_test.go]: Hashes and addresses are always a fixed size so there's no need to change these values - they'll always wind up as 32 or 20 bytes long regardless and the existing values parse just fine.

File: op-service/eth/ssz_test.go [hunk 2]
```diff
@@ -330,6 +330,8 @@ func TestMarshalUnmarshalWithdrawals(t *testing.T) {
 			} else {
 				require.NoError(t, err)
 				require.Equal(t, input, output)
+				require.Equal(t, output.ParentHash, common.HexToHash("0x1234"))
+				require.Equal(t, output.ExtraData, BytesMax32(common.Hex2Bytes("0x6666")))
```
Comment (ajsutton) [inline op-service/eth/ssz_test.go]: The `require.Equal(t, input, output)` already checks the fields match. This test is focussed on ensuring withdrawals are preserved so has an explicit check for them, but we don't need these additional checks.

File: op-service/eth/ssz_test.go [hunk 3]
```diff
@@ -250,21 +250,21 @@ func TestOPB04(t *testing.T) {
...
+		ReceiptsRoot:  Bytes32(common.HexToHash("0xabcd")),
 		LogsBloom:     Bytes256{byte(13), byte(14), byte(15)},
-		PrevRandao:    Bytes32(common.HexToHash("0x111")),
+		PrevRandao:    Bytes32(common.HexToHash("0x1111")),
 		BlockNumber:   Uint64Quantity(222),
 		GasLimit:      Uint64Quantity(333),
 		GasUsed:       Uint64Quantity(444),
 		Timestamp:     Uint64Quantity(555),
-		ExtraData:     common.Hex2Bytes("0x666"),
+		ExtraData:     common.Hex2Bytes("0x6666"),
```
Comment (ajsutton) [inline op-service/eth/ssz_test.go]: This still winds up as an empty slice because `Hex2Bytes` doesn't support the `0x` prefix.

File: op-service/eth/ssz_test.go [hunk 4]
```diff
@@ -250,21 +250,21 @@ func TestOPB04(t *testing.T) {
...
 		BaseFeePerGas: *uint256.NewInt(777),
-		BlockHash:     common.HexToHash("0x888"),
+		BlockHash:     common.HexToHash("0x8888"),
 		Withdrawals:   w,
-		Transactions:  []Data{common.Hex2Bytes("0x999")},
+		Transactions:  []Data{common.Hex2Bytes("0x9999")},
```
Comment (ajsutton) [inline op-service/eth/ssz_test.go]: Similarly this `Hex2Bytes` call should not have an `0x` prefix.

Comment (GrapeBaBa) [reply op-service/eth/ssz_test.go]: oh, i see it. It is wired this method not support `0x` prefix except `HexToHash` and `HexToAddress`. Should we change `Hex2Bytes` and make the behavior consistent? I also see some other test file not use it correct.

Comment (ajsutton) [reply op-service/eth/ssz_test.go]: `Hex2Bytes` comes from upstream geth so it's not something we'd change like this (we try to minimise the diff). It is a real catch though so it may be worth asking the geth maintainers if they'd accept it as a change.

A semgrep or go-lint rule that at least flagged cases where a constant string with `0x` prefix used like this would make a lot of sense though.

**Review by ajsutton — APPROVED** [review]
LGTM. Thanks.

**Comment by EvanJRichard** [comment]
Bumped from the queue due to a test flake, looks like. Recording flake and re-adding to queue.
