### PR TITLE
fix(kona/derive): return Reset instead of Critical on blob under-fill in BlobData::fill

### LINKED ISSUE #19359: kona: BlobData::fill returns Critical on blob under-fill instead of Reset, causing permanent pipeline halt
## Summary

In kona's derivation pipeline, when the blob provider returns fewer blobs than there are blob-hash placeholders ("under-fill"), `BlobData::fill` returns `BlobDecodingError::InvalidLength`. This error maps through `BlobProviderError::BlobDecoding(_)` to `PipelineErrorKind::Critical` — a non-recoverable error that permanently terminates the pipeline and requires operator intervention to restart.

The Go implementation (`op-node`) wraps the equivalent condition as `NewResetError`, which is auto-recoverable: the pipeline automatically retries at the last safe L1 block.

## Under-fill is Common in Practice

This is not merely a theoretical concern. L1 providers commonly return fewer blobs than requested in two real-world scenarios:

1. **Blobs not yet available**: The provider may not have all blobs cached/synced when the pipeline first tries to fetch them for a newly confirmed L1 block.
2. **L1 block reorged out**: If the L1 block containing the blob transactions has been reorged away, the provider may return fewer (or zero) blobs. The pipeline should reset to discover the new canonical chain, not halt permanently.

In both cases the correct behavior is to reset and retry — exactly what Go does.

## Current Behavior

**kona (Rust):**
- [`blob_data.rs:155-157`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/rust/kona/crates/protocol/derive/src/sources/blob_data.rs#L155): `if index >= blobs.len() { return Err(BlobDecodingError::InvalidLength); }`
- [`sources.rs:54-56`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/rust/kona/crates/protocol/derive/src/errors/sources.rs#L54): `BlobProviderError::BlobDecoding(_) => PipelineError::Provider(val.to_string()).crit()`
- Result: **Critical** — pipeline terminates permanently, operator must restart

**op-node (Go):**
- [`blob_data_source.go:108-111`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/op-node/rollup/derive/blob_data_source.go#L108): under-fill is returned as `NewResetError`
- [`blob_data_source.go:153-155`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/op-node/rollup/derive/blob_data_source.go#L153): wrapping as reset error
- Result: **Reset** — pipeline rewinds to last safe point and retries automatically

## Proposed Fix

Change the under-fill path in `BlobData::fill` to return a Reset-level error rather than a `BlobDecodingError` (which always maps to Critical). The cleanest approach is either:

1. Return a new `BlobProviderError` variant (e.g. `BlobsUnavailable`) that maps to `Reset` in the `From<BlobProviderError> for PipelineErrorKind` impl — consistent with how `BlobNotFound` already maps to Reset, or
2. Change `BlobData::fill` to return a `PipelineErrorKind` directly for the under-fill case (bypassing `BlobDecodingError`).

Note that `BlobNotFound` already sets the correct precedent: a 404 from the beacon node maps to `ResetError::BlobsUnavailable(slot).reset()`. Under-fill should be treated similarly.

## Impact

- **Severity:** Liveness — kona derivation pipeline halts permanently on blob under-fill; op-node recovers automatically
- **Affected component:** `kona/crates/protocol/derive` — `BlobData::fill` and error mapping in `sources.rs`

## References

Found during conformance review `kona-node-vs-op-node` (issue LR-13).

### PR DESCRIPTION
**Pull request by ajsutton**
## Summary

When a blob provider returns fewer blobs than there are blob-hash placeholders (under-fill), `BlobData::fill` currently returns `BlobDecodingError::InvalidLength` which maps to `PipelineErrorKind::Critical` — permanently terminating the derivation pipeline.

This is wrong. Under-fill is a **transient, recoverable condition**:
- The provider may not have all blobs cached/synced yet for a newly confirmed L1 block
- The L1 block may have been reorged out, causing the provider to return fewer blobs

In both cases the pipeline should **reset and retry** from the last safe L1 block. This is exactly what op-node does: `fillBlobPointers` wraps the same under-fill error as `NewResetError` at [`blob_data_source.go:110`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/op-node/rollup/derive/blob_data_source.go#L108-L111), giving automatic recovery.

Without this fix, any blob under-fill in kona causes permanent pipeline halt requiring operator restart.

## Changes

- `errors/pipeline.rs`: Add `ResetError::BlobsUnderFill(usize, usize)` — a named reset error for this condition
- `errors/sources.rs`: Add `BlobProviderError::NotEnoughBlobs(usize, usize)` mapped to `ResetError::BlobsUnderFill.reset()` in `From<BlobProviderError> for PipelineErrorKind`
- `sources/blob_data.rs`: Change `BlobData::fill` return type from `Result<bool, BlobDecodingError>` to `Result<bool, BlobProviderError>`, returning `NotEnoughBlobs` on under-fill
- `sources/blobs.rs`: Simplify the `fill` error conversion to `.into()` (now that `fill` directly returns `BlobProviderError`)
- Tests updated to assert under-fill produces `Reset` not `Critical`

## Testing

```
cargo test --package kona-derive --lib test_fill_oob_index
cargo test --package kona-derive --lib test_from_blob_provider_error
cargo test --package kona-derive --lib test_reset_error_kinds
```

All pass. No new test failures introduced (the one pre-existing failure is a `tracing-subscriber` global state conflict unrelated to this change).

## Related

Fixes https://github.com/ethereum-optimism/optimism/issues/19359

Found during conformance review `kona-node-vs-op-node`.

### CODE REVIEW

**Review by ajsutton — COMMENTED** [review]
Remove references to matching op-node behaviour.

Reduce the number of comments - there's no need to repeat the explanation everywhere.

File: rust/kona/crates/protocol/derive/src/errors/pipeline.rs [hunk 1]
```diff
@@ -353,6 +353,9 @@ pub enum ResetError {
     /// typically because an L1 reorg removed it. The pipeline must reset to recover.
     #[error("Block not found: {0}")]
     BlockNotFound(BlockId),
+    /// The blob provider returned fewer blobs than expected (under-fill).
+    #[error("Blob provider under-fill: expected blob at index {0} but only {1} blobs returned")]
+    BlobsUnderFill(usize, usize),
```
Comment (theochap) [inline rust/kona/crates/protocol/derive/src/errors/pipeline.rs]: We can just wrap the BlobProviderError here

File: rust/kona/crates/protocol/derive/src/errors/sources.rs [hunk 2]
```diff
@@ -33,6 +33,9 @@ pub enum BlobProviderError {
     /// Blob decoding error.
     #[error("Blob decoding error: {0}")]
     BlobDecoding(#[from] BlobDecodingError),
+    /// The blob provider returned fewer blobs than requested (under-fill).
+    #[error("Not enough blobs: expected blob at index {0} but provider returned only {1} blobs")]
+    NotEnoughBlobs(usize, usize),
```
Comment (theochap) [inline rust/kona/crates/protocol/derive/src/errors/sources.rs]: Let's use named fields

File: rust/kona/crates/protocol/derive/src/sources/blobs.rs [hunk 3]
```diff
@@ -165,9 +165,8 @@ where
         // Fill the blob pointers.
         let mut blob_index = 0;
         for blob in &mut data {
-            let should_increment = blob
-                .fill(&blobs, blob_index)
-                .map_err(|e| -> PipelineErrorKind { BlobProviderError::from(e).into() })?;
+            let should_increment =
+                blob.fill(&blobs, blob_index).map_err(Into::<PipelineErrorKind>::into)?;
```
Comment (theochap) [inline rust/kona/crates/protocol/derive/src/sources/blobs.rs]: We shouldn't need the map_err

File: rust/kona/crates/protocol/derive/src/sources/blob_data.rs [hunk 4]
```diff
@@ -146,18 +146,18 @@ impl BlobData {
...
         blobs: &[Box<Blob>],
         index: usize,
-    ) -> Result<bool, BlobDecodingError> {
+    ) -> Result<bool, BlobProviderError> {
         // Do not fill if there is calldata here
         if self.calldata.is_some() {
             return Ok(false);
         }
 
         if index >= blobs.len() {
```
Comment (theochap) [inline rust/kona/crates/protocol/derive/src/sources/blob_data.rs:155]: Independent of this pr, but "index" is more "expected_blobs". "Index" doesn't carry a lot of information

**Review by theochap — APPROVED** [review]
Looks good a few nits

File: rust/kona/crates/protocol/derive/src/sources/blob_data.rs (hunk 4 above)
Comment (ajsutton) [reply rust/kona/crates/protocol/derive/src/sources/blob_data.rs:155]: Actually I'm pretty sure index is right in this case.  It's the index of the blob to fill in the blobs array.
