### PR TITLE
batcher: fix state inconsistency

### LINKED ISSUE #13061: batcher: live-lock caused by incomplete state clearing when sequencer restarts
### High level description of project.

The new batcher got into a bad state when rolled out to devnet.

1. The batcher started up and behaved normally
2. The sequencer restarted
3. When it came back up, it's safe head went backwards
4. The batcher detected this, and tried to clear out its state and start work from the new safe head
5. It did not clear its state properly, and the consistency caused it to constantly run into 4 over and over.

This line https://github.com/ethereum-optimism/optimism/blob/042433b89ce38ccc15456e9673829f6783bb97ac/op-batcher/batcher/channel_manager.go#L480-L488 only clears part of the batcher's state. In particular it does not clear this state:
https://github.com/ethereum-optimism/optimism/blob/042433b89ce38ccc15456e9673829f6783bb97ac/op-batcher/batcher/driver.go#L117-L118, which is used to control how new blocks are fetched from the sequencer. 

### Label Checks

- [x] I have added the team label for this project (CH, TH, Contributions).
- [x] I have added the timeline for this project to the issue.

### PR DESCRIPTION
**Pull request by geoknee**
The new batcher got into a bad state when rolled out to devnet. 

1. The batcher started up and behaved normally
2. The sequencer restarted
3. When it came back up, it's safe head went backwards
4. The batcher detected this, and tried to clear out its state and start work from the new safe head
5. It did not clear its state properly, and the consistency caused it to constantly run into 4 over and over. 

This PR removes some redundant state which was not being cleared, which should fix the problem.

### CODE REVIEW

File: op-batcher/batcher/driver.go [hunk 1]
```diff
@@ -373,22 +366,23 @@ func (l *BatchSubmitter) calculateL2BlockRangeToStore(syncStatus eth.SyncStatus)
...
-		l.lastStoredBlock = syncStatus.SafeL2.ID()
-	} else if l.lastStoredBlock.Number < syncStatus.SafeL2.Number {
-		l.Log.Warn("Last submitted block lagged behind L2 safe head: batch submission will continue from the safe head now", "last", l.lastStoredBlock, "safe", syncStatus.SafeL2)
-		l.lastStoredBlock = syncStatus.SafeL2.ID()
+	if lastStoredBlock == (eth.BlockID{}) {
+		l.Log.Info("Resuming batch-submitter work at safe-head", "safe", syncStatus.SafeL2)
+		lastStoredBlock = syncStatus.SafeL2.ID()
+	} else if lastStoredBlock.Number < syncStatus.SafeL2.Number {
+		l.Log.Warn("Last submitted block lagged behind L2 safe head: batch submission will continue from the safe head now", "last", lastStoredBlock, "safe", syncStatus.SafeL2)
+		lastStoredBlock = syncStatus.SafeL2.ID()
```
Comment (geoknee) [inline op-batcher/batcher/driver.go]: Need to think carefully about whether setting this here is safe / makes sense now. Seems like `pruneSafeBlocks` and `calculateL2BlockRangeToStore` might be stepping on each others toes, maybe they should be combined into one function.

Comment (axelKingsley) [reply op-batcher/batcher/driver.go]: This is my only remaining concern about this PR --where `calculateL2BlockRangeToStore` had been modifying the state, it now appears to first consult the state, but then only modifies and returns a local. The two questions I would have are:
* Do callers to this function expect to be setting a value? If so, they're now broken.
* Do other methods have a way of setting the state's LastStoredBlock? If not, the variable isn't functional here.

I would *hope* either of these issues would be discovered via existing tests, but you could also try tracing references back from this function.

Comment (geoknee) [reply op-batcher/batcher/driver.go]: Pushed another commit to clarify this [d2a77a4](https://github.com/ethereum-optimism/optimism/pull/12981/commits/d2a77a4b90b0d66f6bd60dc6786b55fab310622e). There is only one caller of this function -- it doesn't expect to be setting a value, and I have clarified the godoc to that effect. It's about loading blocks, and now the "last stored block" really is the last stored block (modified via the channel manager), not a separate variable that we have to work to keep in sync. 

It makes sense to me that `calculateL2BlockRangeToStore` is a "view" function.

**Review by axelKingsley — APPROVED** [review]
