### PR TITLE
op-node: fetch l1 block with retry

### LINKED ISSUE #9347: OP Node `Walking back L1Block by hash` will start from the beginning if it hits a 429 rate limit error
**Describe the bug**
After a node restart, op-node will walk back to the last finalized head and emit's the log `Walking back L1Block by hash` at each step. During this phase, if the L1 RPC gets rate limited it will restart the process from the beginning. This can cause a node to never get sync'd after a restart.

**To Reproduce**
1. Get an L1 RPC that has a fairly low rate limit or run a side process that will spam the L1 RPC so that it's close to getting rate limited
2. Restart OP node with the same L1 RPC
3. Should see `Walking back L1Block by hash` start from the beginning after it hits a 429 error.

**Expected behavior**
It should retry the L1 RPC with an exponential back-off and continue where it left off rather than start from the beginning.

**System Specs:**
 - OS: Ubuntu
 - Package Version (or commit hash): op-node v1.5.0 and op-geth v1.101305.3

**Additional context**
We run multiple OP nodes in production. Ran into this issue when attempting to update multiple nodes in parallel using the same L1 RPC. Issue resolved once I switched to updating nodes sequentially.

### PR DESCRIPTION
**Pull request by jsvisa**
**Description**

fetch l1block with retry, in case of a HTTP error

**Metadata**

- Fixes https://github.com/ethereum-optimism/optimism/issues/9347

### CODE REVIEW

File: op-node/rollup/sync/start.go [hunk 1]
```diff
@@ -133,7 +136,7 @@ func FindL2Heads(ctx context.Context, cfg *rollup.Config, l1 L1Chain, l2 L2Chain
 		// Fetch L1 information if we never had it, or if we do not have it for the current origin.
 		// Optimization: as soon as we have a previous L1 block, try to traverse L1 by hash instead of by number, to fill the cache.
 		if n.L1Origin.Hash == l1Block.ParentHash {
-			b, err := l1.L1BlockRefByHash(ctx, n.L1Origin.Hash)
+			b, err := fetchBlockWithHTTPRetry(func() (eth.L1BlockRef, error) { return l1.L1BlockRefByHash(ctx, n.L1Origin.Hash) }, lgr)
```
Comment (tynes) [inline op-node/rollup/sync/start.go]: We have a way to do this already, there is a client with retries built into it. We should make sure to use that instead of introducing something new. Its possible we may already be using it here

Comment (trianglesphere) [reply op-node/rollup/sync/start.go]: If we are not doing this in the client, we should use the retry package which exists in `op-service` rather than re-implementing the retry logic.

Comment (jsvisa) [reply op-node/rollup/sync/start.go]: replaced with `op-service/retry`, please take another look

**Review by trianglesphere — APPROVED** [review]
