### PR TITLE
op-dispute-mon: Identify unclaimed credits based on the withdrawal request timestamp

### LINKED ISSUE #11487: op-dispute-mon: Incorrectly reporting unclaimed funds
In the game https://sepolia.etherscan.io/address/0x5e0264dB3CA589C028c89644bAaF6692Ec2598C8 dispute-mon was warning about unclaimed bonds as early as 2024-08-09T06:22:03.703315019Z and they were actually claimed on Aug-10-2024 07:31:48 AM UTC.

The claims were resolved as soon as possible and bonds claimed as soon as possible, just the warning from dispute-mon is incorrect.

This occurs when a proposal is countered with the incorrect warning lasting for the amount of time used on the challengers clock.  Currently it assumes that claims can be resolved after `MaxClockDuration` and then bonds claimed after the DelayedWETH delay completes.  However that identifies the minimum possible time for any bonds to be reclaimed.  If the proposal is challenged the full `MaxClockDuration` has to elapse for the defenders claims, but the defender's clock is paused while the challenger's clock runs so the claim resolution is delayed by the time taken by the challenger.

We will need to keep tracking the minimum possible time for bonds to be claimed to alert on early withdrawal of bonds but need a better system for identifying unclaimed bonds - simplest version would be `2 * MaxClockDuration + WethDelay` which would work for everything except games that use clock extension.  Alternatively since this check is primarily about identifying faults with op-challenger not claiming honest bonds back, it would be reasonable to use the actual `WithdrawalRequest` information and trust it to be accurate.  The early withdrawal alert avoids depending on this data as its design to detect bugs where the withdrawal delay is calculated incorrectly.

### PR DESCRIPTION
**Pull request by ajsutton**
**Description**

Moves detection of unclaimed credits from the bonds monitor to the withdrawals monitor. It now uses the actual withdrawal request timestamp to calculate if the credit is withdrawable. 

**Tests**

Moved tests over to the withdrawals monitor.

**Metadata**

- Fixes https://github.com/ethereum-optimism/optimism/issues/11487

### CODE REVIEW

File: op-dispute-mon/mon/withdrawals.go [hunk 1]
```diff
@@ -48,6 +62,16 @@ func (w *WithdrawalMonitor) validateGameWithdrawals(game *types.EnrichedGameData
...
 			w.logger.Error("Withdrawal request amount does not match credit", "game", game.Proxy, "recipient", recipient, "credit", game.Credits[recipient], "withdrawal", game.WithdrawalRequests[recipient].Amount)
 		}
+
+		if withdrawalAmount.Amount.Cmp(big.NewInt(0)) > 0 && w.honestActors.Contains(recipient) {
+			if time.Unix(withdrawalAmount.Timestamp.Int64(), 0).Add(game.WETHDelay).Before(now) {
+				// Credits are withdrawable
+				total := honestWithdrawableAmounts[recipient]
+				total = new(big.Int).Add(total, withdrawalAmount.Amount)
+				honestWithdrawableAmounts[recipient] = total
+				w.logger.Warn("Found unclaimed credit", "recipient", recipient, "game", game.Proxy, "amount", withdrawalAmount.Amount)
```
Comment (Inphi) [inline op-dispute-mon/mon/withdrawals.go:72]: nit: This logs as soon as it's withdrawable and the op-challenger does take a little bit of time to send withdraw transaction. Which is OK as the dispute-mon loop doesn't run that often to catch this at the exact time the bond is withdrawable.
Consider adding a 24 second grace period before logging here.

**Review by Inphi — APPROVED** [review]

File: op-dispute-mon/mon/withdrawals.go (hunk 1 above)
Comment (ajsutton) [reply op-dispute-mon/mon/withdrawals.go:72]: Yeah we've consistently done that with op-dispute-mon - it will log a warning immediately and the delay is configured in the alerts. It seems to work pretty well since you can clearly see the update cycles in the logs as well and see which alerts are coming from each update and when the update cycle then is giving no warnings etc.
