### PR TITLE
Move Proposed Sequence Number into Prometheus Factory

### LINKED ISSUE #16706: op-proposer: Fix super root metrics
When the op-proposer is configured to use super roots, it fails to update the `proposed_sequence_number` metric when publishing super roots.

The `proposed_sequence_number` is a gauge metric that tracks the last posted proposal's sequence number. For an output root configured op-proposer, this is the L2 block number of the proposal. Otherwise, it's the timestamp of the super root.

### PR DESCRIPTION
**Pull request by jtriley2p**
## Description

Per the issue below, `propsed_sequence_number` is a "gauge" value captured by the `prometheus`. The number was correctly being tracked, but instead of recording through the `opmetrics.Factory` (which encapsulates the Optimism-specific collector logic), it was being recorded through `prometheus` directly, which in turn would not show up in the dashboard or proper logs.

This PR moves the gauge to the factory.

## Tests

So there weren't tests in general for `op-proposer` metrics; so there's now a unit test which constructs the metric object and calls the methods which log each metric (`proposed_sequence_number`, `info`, and `up`).

An integration test would be great but this will require a much deeper understanding of the different op components, so maybe we do this later (pls).

## Metadata

Fixes #16706

### CODE REVIEW

File: op-proposer/metrics/metrics_test.go [hunk 1]
```diff
@@ -0,0 +1,22 @@
+package metrics
+
+import (
+	"testing"
+
+	opmetrics "github.com/ethereum-optimism/optimism/op-service/metrics"
+)
+
+func TestMetrics(test *testing.T) {
```
Comment (mbaxter) [inline op-proposer/metrics/metrics_test.go:10]: nice 🎉

File: op-proposer/metrics/metrics_test.go [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+
+	metrics := NewMetrics(procName)
+	metrics.RecordL2Proposal(1)
+	metrics.RecordInfo("test")
+	metrics.RecordUp()
+
+	checker := opmetrics.NewMetricChecker(test, metrics.Registry())
+	checker.FindByName(prefix + "proposed_sequence_number")
+	checker.FindByName(prefix + "info")
+	checker.FindByName(prefix + "up")
```
Comment (mbaxter) [inline op-proposer/metrics/metrics_test.go]: (optional) If it's relatively straightforward, would be nice to validate the metric values as well.

**Review by mbaxter — APPROVED** [review]

File: op-proposer/metrics/metrics_test.go (hunk 2 above)
Comment (jtriley2p) [reply op-proposer/metrics/metrics_test.go]: found a way to do it!

**Review by mbaxter — APPROVED** [review]
