### PR TITLE
op-{acceptance-tests|devstack}: sync test: op-node ahead of op-supervisor with DSL

### LINKED ISSUE #15098: Test that supervisor resets node when it is ahead
op-node ahead of supervisor, aka supervisor needs to reset the op-node, to reproduce old data. Currently supervisor has only managed mode implemented, so the supervisor will ask the op-node to reset back.

### PR DESCRIPTION
**Pull request by pcw109550**
**Description**

Builds on top of https://github.com/ethereum-optimism/optimism/pull/15878.

Adds `MultiSupervisorInteropSystem` sysgo system which has supervisor redundancy and L2{EL|CL} redundancy per every L2 chains.

Adds `MultiSupervisorInterop` preset to consume `MultiSupervisorInteropSystem`.
- I embed `stack.ExtensibleSystem` to the preset struct by default.

Fixes sysgo+stack+shim+dsl L2CL to expose interop endpoint and jwt token, which is used to reconnect L2CL to supervisor using DSL.

Adds `second` matcher for supervisor because this PR introduces secondary supervisor, and to select it in DSL.

Adds multiple DSL helpers:
- Supervisor::Start and Stop. To do this, supervisor DSL now embeds control plane.
- Supervisor::AddManagedL2CL: calls `admin_addL2RPC` using the exposed L2CL interop endpoints and jwts.
- L2CL::{DoesNotAdvance,Rewind}: DSL to check sync status

Adds test which tests below supervisor<>L2CL out of sync scenario:
```
// TestL2CLAheadOfSupervisor tests the below scenario:
// L2CL ahead of supervisor, aka supervisor needs to reset the L2CL, to reproduce old data. Currently supervisor has only managed mode implemented, so the supervisor will ask the L2CL to reset back.
// To create this out-of-sync scenario, we follow the steps below:
// 0. System setup
// - Two supervisor initialized, each managing two L2CLs per chains.
// - Primary supervisor manages sequencer L2CLs for chain A, B.
// - Secondary supervisor manages verifier L2CLs for chain A, B.
// - Each L2CLs per chain is connected via P2P.
// 1. Make sequencers (L2CL), verifiers (L2CL), and supervisors sync for a few blocks.
// - Sequencer and verifier are connected via P2P, which makes their unsafe heads in sync.
// - Both L2CLs are in managed mode, digesting L1 blocks from the supervisor and reporting unsafe and safe blocks back to the supervisor.
// - Wait enough for both L2CLs advance unsafe heads.
// 2. Stop Secondary supervisor.
// - Verifiers stops advancing safe heads because there is no supervisor to provide them L1 data.
// - Verifiers advances unsafe head because they still have P2P connection with each sequencers.
// - Wait enough to make sequencers and primary supervisor advance safe head enough.
// 3. Connect verifiers (L2CL) to primary supervisor.
// - Primary supervisor has safe heads synced with sequencers.
// - After connection, verifiers will sync with primary supervisor, matching supervisor safe head view.
// - Secondary supervisor and verifiers becomes out-of-sync with safe heads.
// - Every L2CLs advance safe head.
// 4. Stop primary supervisor.
// - Every L2CL safe heads will stop advancing.
// - For disconnecting every L2CLs from the supervisor.
// 5. Restart primary supervisor and reconnect sequencers (L2CL) to primary supervisor.
// - Sequencers will resume advancing safe heads, but not verifiers.
// 6. Restart Secondary supervisor and reconnect verifiers (L2CL) to Secondary supervisor.
// - Secondary supervisor will compare its safe head knowledge with L2CLs, and find out L2CLs are ahead of the Secondary supervisor.
// - Secondary supervisor asks the verifiers (L2CL) to rewind(reset) back to match Secondary supervisor safe head view.
// - After rewinding(reset), verifier will advance safe heads again because Secondary supervisor gives L1 data to the verifiers.
// - Wait until verifiers advance safe head enough
```

**Tests**

Test Logs(Partial):

```

=== RUN   TestL2CLAheadOfSupervisor
    interop_sync_test.go:50:    INFO [05-14|20:11:13.907] make sure verifiers advances unsafe head Test=TestL2CLAheadOfSupervisor delta=10
    l2_cl.go:111:               INFO [05-14|20:11:13.907] expecting chain to reach                 id=L2CLNode-verifier-902 chain=902 label=UnsafeL2 target=10
    l2_cl.go:111:               INFO [05-14|20:11:13.907] expecting chain to reach                 id=L2CLNode-verifier-901 chain=901 label=UnsafeL2 target=10
    l2_cl.go:111:               INFO [05-14|20:11:13.907] expecting chain to reach                 id=L2CLNode-sequencer-901 chain=901 label=UnsafeL2 target=10
    l2_cl.go:111:               INFO [05-14|20:11:13.907] expecting chain to reach                 id=L2CLNode-sequencer-902 chain=902 label=UnsafeL2 target=10
    l2_cl.go:119:               INFO [05-14|20:11:13.908] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=UnsafeL2 target=10 current=0
    l2_cl.go:119:               INFO [05-14|20:11:13.908] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=UnsafeL2 target=10 current=0
    l2_cl.go:119:               INFO [05-14|20:11:13.908] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=UnsafeL2 target=10 current=0
    l2_cl.go:119:               INFO [05-14|20:11:13.908] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=UnsafeL2 target=10 current=0
    l2_cl.go:119:               INFO [05-14|20:11:15.909] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=UnsafeL2 target=10 current=0
    l2_cl.go:119:               INFO [05-14|20:11:15.909] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=UnsafeL2 target=10 current=0
    l2_cl.go:119:               INFO [05-14|20:11:15.909] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=UnsafeL2 target=10 current=0
    l2_cl.go:119:               INFO [05-14|20:11:15.909] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=UnsafeL2 target=10 current=0
    l2_cl.go:119:               INFO [05-14|20:11:17.911] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=UnsafeL2 target=10 current=0
    l2_cl.go:119:               INFO [05-14|20:11:17.911] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=UnsafeL2 target=10 current=0
    l2_cl.go:119:               INFO [05-14|20:11:17.911] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=UnsafeL2 target=10 current=0
    l2_cl.go:119:               INFO [05-14|20:11:17.911] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=UnsafeL2 target=10 current=0
    l2_cl.go:119:               INFO [05-14|20:11:19.913] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=UnsafeL2 target=10 current=3
    l2_cl.go:119:               INFO [05-14|20:11:19.913] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=UnsafeL2 target=10 current=3
    l2_cl.go:119:               INFO [05-14|20:11:19.913] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=UnsafeL2 target=10 current=3
    l2_cl.go:119:               INFO [05-14|20:11:19.913] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=UnsafeL2 target=10 current=3
    l2_cl.go:119:               INFO [05-14|20:11:21.914] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=UnsafeL2 target=10 current=4
    l2_cl.go:119:               INFO [05-14|20:11:21.914] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=UnsafeL2 target=10 current=4
    l2_cl.go:119:               INFO [05-14|20:11:21.914] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=UnsafeL2 target=10 current=4
    l2_cl.go:119:               INFO [05-14|20:11:21.914] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=UnsafeL2 target=10 current=4
    l2_cl.go:119:               INFO [05-14|20:11:23.918] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=UnsafeL2 target=10 current=5
    l2_cl.go:119:               INFO [05-14|20:11:23.918] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=UnsafeL2 target=10 current=5
    l2_cl.go:119:               INFO [05-14|20:11:23.918] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=UnsafeL2 target=10 current=5
    l2_cl.go:119:               INFO [05-14|20:11:23.918] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=UnsafeL2 target=10 current=5
    l2_cl.go:119:               INFO [05-14|20:11:25.920] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=UnsafeL2 target=10 current=6
    l2_cl.go:119:               INFO [05-14|20:11:25.920] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=UnsafeL2 target=10 current=6
    l2_cl.go:119:               INFO [05-14|20:11:25.920] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=UnsafeL2 target=10 current=6
    l2_cl.go:119:               INFO [05-14|20:11:25.920] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=UnsafeL2 target=10 current=6
    l2_cl.go:119:               INFO [05-14|20:11:27.921] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=UnsafeL2 target=10 current=7
    l2_cl.go:119:               INFO [05-14|20:11:27.921] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=UnsafeL2 target=10 current=7
    l2_cl.go:119:               INFO [05-14|20:11:27.921] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=UnsafeL2 target=10 current=7
    l2_cl.go:119:               INFO [05-14|20:11:27.921] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=UnsafeL2 target=10 current=7
    l2_cl.go:119:               INFO [05-14|20:11:29.921] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=UnsafeL2 target=10 current=8
    l2_cl.go:119:               INFO [05-14|20:11:29.921] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=UnsafeL2 target=10 current=8
    l2_cl.go:119:               INFO [05-14|20:11:29.921] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=UnsafeL2 target=10 current=8
    l2_cl.go:119:               INFO [05-14|20:11:29.921] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=UnsafeL2 target=10 current=8
    l2_cl.go:119:               INFO [05-14|20:11:31.922] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=UnsafeL2 target=10 current=9
    l2_cl.go:119:               INFO [05-14|20:11:31.922] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=UnsafeL2 target=10 current=9
    l2_cl.go:119:               INFO [05-14|20:11:31.922] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=UnsafeL2 target=10 current=9
    l2_cl.go:119:               INFO [05-14|20:11:31.922] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=UnsafeL2 target=10 current=9
    l2_cl.go:116:               INFO [05-14|20:11:33.922] chain advanced                           id=L2CLNode-sequencer-902 chain=902 label=UnsafeL2 target=10
    l2_cl.go:116:               INFO [05-14|20:11:33.923] chain advanced                           id=L2CLNode-sequencer-901 chain=901 label=UnsafeL2 target=10
    l2_cl.go:116:               INFO [05-14|20:11:33.923] chain advanced                           id=L2CLNode-verifier-902  chain=902 label=UnsafeL2 target=10
    l2_cl.go:116:               INFO [05-14|20:11:33.923] chain advanced                           id=L2CLNode-verifier-901  chain=901 label=UnsafeL2 target=10
    interop_sync_test.go:59:    INFO [05-14|20:11:33.924] stop secondary supervisor                Test=TestL2CLAheadOfSupervisor
    interop_sync_test.go:66:    INFO [05-14|20:11:33.925] secondary supervisor(stopped) safe head view Test=TestL2CLAheadOfSupervisor chainA=be5c9a..ed7d34:3 chainB=f12ea4..f31c96:3
    interop_sync_test.go:68:    INFO [05-14|20:11:33.925] sequencers advances safe heads but not verifiers Test=TestL2CLAheadOfSupervisor delta=10
    l2_cl.go:95:                INFO [05-14|20:11:33.926] expecting chain not to advance           id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3
    l2_cl.go:111:               INFO [05-14|20:11:33.926] expecting chain to reach                 id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13
    l2_cl.go:111:               INFO [05-14|20:11:33.926] expecting chain to reach                 id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13
    l2_cl.go:95:                INFO [05-14|20:11:33.926] expecting chain not to advance           id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3
    l2_cl.go:119:               INFO [05-14|20:11:33.926] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=3
    l2_cl.go:119:               INFO [05-14|20:11:33.926] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=3
    l2_cl.go:119:               INFO [05-14|20:11:35.927] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=3
    l2_cl.go:119:               INFO [05-14|20:11:35.927] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=3
    l2_cl.go:99:                INFO [05-14|20:11:35.927] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:11:35.927] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:11:37.931] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=3
    l2_cl.go:99:                INFO [05-14|20:11:37.931] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:11:37.931] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=3
    l2_cl.go:99:                INFO [05-14|20:11:37.931] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:11:39.931] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=3
    l2_cl.go:99:                INFO [05-14|20:11:39.931] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:11:39.931] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:11:39.931] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=3
    l2_cl.go:119:               INFO [05-14|20:11:41.932] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=3
    l2_cl.go:119:               INFO [05-14|20:11:41.933] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=3
    l2_cl.go:99:                INFO [05-14|20:11:41.933] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:11:41.933] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:11:43.934] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:11:43.934] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=3
    l2_cl.go:99:                INFO [05-14|20:11:43.934] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:11:43.934] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=3
    l2_cl.go:119:               INFO [05-14|20:11:45.934] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=6
    l2_cl.go:99:                INFO [05-14|20:11:45.935] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:11:45.935] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:11:45.935] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=6
    l2_cl.go:99:                INFO [05-14|20:11:47.935] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:11:47.935] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=6
    l2_cl.go:99:                INFO [05-14|20:11:47.935] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:11:47.935] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=6
    l2_cl.go:119:               INFO [05-14|20:11:49.936] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=6
    l2_cl.go:99:                INFO [05-14|20:11:49.936] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:11:49.936] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=6
    l2_cl.go:99:                INFO [05-14|20:11:49.936] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:11:51.937] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=7
    l2_cl.go:99:                INFO [05-14|20:11:51.937] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:11:51.937] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:11:51.937] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=7
    l2_cl.go:99:                INFO [05-14|20:11:53.938] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:11:53.938] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:11:53.938] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=7
    l2_cl.go:119:               INFO [05-14|20:11:53.938] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=7
    l2_cl.go:119:               INFO [05-14|20:11:55.939] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=7
    l2_cl.go:99:                INFO [05-14|20:11:55.939] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:11:55.939] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:11:55.939] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=7
    l2_cl.go:99:                INFO [05-14|20:11:57.941] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:11:57.941] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=8
    l2_cl.go:119:               INFO [05-14|20:11:57.941] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=8
    l2_cl.go:99:                INFO [05-14|20:11:57.941] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:11:59.942] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=8
    l2_cl.go:119:               INFO [05-14|20:11:59.942] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=8
    l2_cl.go:99:                INFO [05-14|20:11:59.942] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:11:59.942] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:12:01.944] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=8
    l2_cl.go:99:                INFO [05-14|20:12:01.944] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:01.944] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:12:01.944] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=8
    l2_cl.go:119:               INFO [05-14|20:12:03.945] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=11
    l2_cl.go:119:               INFO [05-14|20:12:03.945] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=11
    l2_cl.go:99:                INFO [05-14|20:12:03.945] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:03.945] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:12:05.947] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=11
    l2_cl.go:99:                INFO [05-14|20:12:05.947] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:12:05.947] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=11
    l2_cl.go:99:                INFO [05-14|20:12:05.948] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:12:07.951] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13 current=11
    l2_cl.go:99:                INFO [05-14|20:12:07.952] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:119:               INFO [05-14|20:12:07.952] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13 current=11
    l2_cl.go:99:                INFO [05-14|20:12:07.952] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:09.961] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:09.961] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:116:               INFO [05-14|20:12:09.961] chain advanced                           id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=13
    l2_cl.go:116:               INFO [05-14|20:12:09.962] chain advanced                           id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=13
    l2_cl.go:99:                INFO [05-14|20:12:11.962] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:11.962] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:13.963] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:13.963] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:15.965] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:15.965] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:17.968] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:17.968] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:19.971] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:19.971] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:21.971] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:21.971] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:23.981] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:23.982] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:25.984] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:25.984] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:27.986] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:27.986] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:29.988] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:29.988] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:31.989] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:31.989] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:33.991] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=3  current=3
    l2_cl.go:99:                INFO [05-14|20:12:33.991] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=3  current=3
    interop_sync_test.go:76:    INFO [05-14|20:12:33.991] connect verifier CLs to primary supervisor to advance verifier safe heads Test=TestL2CLAheadOfSupervisor
    interop_sync_test.go:81:    INFO [05-14|20:12:33.998] every CLs advance safe heads             Test=TestL2CLAheadOfSupervisor delta=10 target=36
    l2_cl.go:111:               INFO [05-14|20:12:33.998] expecting chain to reach                 id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=36
    l2_cl.go:111:               INFO [05-14|20:12:33.998] expecting chain to reach                 id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=36
    l2_cl.go:111:               INFO [05-14|20:12:33.998] expecting chain to reach                 id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=36
    l2_cl.go:111:               INFO [05-14|20:12:33.998] expecting chain to reach                 id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=36
    l2_cl.go:119:               INFO [05-14|20:12:33.998] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=36 current=3
    l2_cl.go:119:               INFO [05-14|20:12:33.998] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=36 current=3
    l2_cl.go:119:               INFO [05-14|20:12:33.999] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=36 current=26
    l2_cl.go:119:               INFO [05-14|20:12:33.999] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=36 current=26
    l2_cl.go:119:               INFO [05-14|20:12:36.000] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=36 current=26
    l2_cl.go:119:               INFO [05-14|20:12:36.000] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=36 current=26
    l2_cl.go:119:               INFO [05-14|20:12:36.000] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=36 current=3
    l2_cl.go:119:               INFO [05-14|20:12:36.000] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=36 current=3
    l2_cl.go:119:               INFO [05-14|20:12:38.001] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=36 current=3
    l2_cl.go:119:               INFO [05-14|20:12:38.001] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=36 current=26
    l2_cl.go:119:               INFO [05-14|20:12:38.001] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=36 current=26
    l2_cl.go:119:               INFO [05-14|20:12:38.001] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=36 current=3
    l2_cl.go:119:               INFO [05-14|20:12:40.002] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=36 current=29
    l2_cl.go:119:               INFO [05-14|20:12:40.002] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=36 current=29
    l2_cl.go:119:               INFO [05-14|20:12:40.002] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=36 current=29
    l2_cl.go:119:               INFO [05-14|20:12:40.002] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=36 current=29
    l2_cl.go:119:               INFO [05-14|20:12:42.003] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=36 current=29
    l2_cl.go:119:               INFO [05-14|20:12:42.003] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=36 current=29
    l2_cl.go:119:               INFO [05-14|20:12:42.003] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=36 current=29
    l2_cl.go:119:               INFO [05-14|20:12:42.003] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=36 current=29
    l2_cl.go:119:               INFO [05-14|20:12:44.005] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=36 current=29
    l2_cl.go:119:               INFO [05-14|20:12:44.005] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=36 current=29
    l2_cl.go:119:               INFO [05-14|20:12:44.005] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=36 current=29
    l2_cl.go:119:               INFO [05-14|20:12:44.005] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=36 current=29
    l2_cl.go:119:               INFO [05-14|20:12:46.007] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=36 current=32
    l2_cl.go:119:               INFO [05-14|20:12:46.007] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=36 current=32
    l2_cl.go:119:               INFO [05-14|20:12:46.007] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=36 current=32
    l2_cl.go:119:               INFO [05-14|20:12:46.007] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=36 current=32
    l2_cl.go:119:               INFO [05-14|20:12:48.008] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=36 current=32
    l2_cl.go:119:               INFO [05-14|20:12:48.008] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=36 current=32
    l2_cl.go:119:               INFO [05-14|20:12:48.008] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=36 current=32
    l2_cl.go:119:               INFO [05-14|20:12:48.008] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=36 current=32
    l2_cl.go:119:               INFO [05-14|20:12:50.009] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=36 current=32
    l2_cl.go:119:               INFO [05-14|20:12:50.009] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=36 current=32
    l2_cl.go:119:               INFO [05-14|20:12:50.009] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=36 current=32
    l2_cl.go:119:               INFO [05-14|20:12:50.009] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=36 current=32
    l2_cl.go:119:               INFO [05-14|20:12:52.011] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=36 current=35
    l2_cl.go:119:               INFO [05-14|20:12:52.011] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=36 current=35
    l2_cl.go:119:               INFO [05-14|20:12:52.011] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=36 current=35
    l2_cl.go:119:               INFO [05-14|20:12:52.011] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=36 current=35
    l2_cl.go:119:               INFO [05-14|20:12:54.012] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=36 current=35
    l2_cl.go:119:               INFO [05-14|20:12:54.012] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=36 current=35
    l2_cl.go:119:               INFO [05-14|20:12:54.012] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=36 current=35
    l2_cl.go:119:               INFO [05-14|20:12:54.012] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=36 current=35
    l2_cl.go:119:               INFO [05-14|20:12:56.013] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=36 current=35
    l2_cl.go:119:               INFO [05-14|20:12:56.014] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=36 current=35
    l2_cl.go:119:               INFO [05-14|20:12:56.014] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=36 current=35
    l2_cl.go:119:               INFO [05-14|20:12:56.014] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=36 current=35
    l2_cl.go:116:               INFO [05-14|20:12:58.015] chain advanced                           id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=36
    l2_cl.go:116:               INFO [05-14|20:12:58.015] chain advanced                           id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=36
    l2_cl.go:116:               INFO [05-14|20:12:58.015] chain advanced                           id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=36
    l2_cl.go:116:               INFO [05-14|20:12:58.015] chain advanced                           id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=36
    interop_sync_test.go:87:    INFO [05-14|20:12:58.015] stop primary supervisor to disconnect every CL connection Test=TestL2CLAheadOfSupervisor
    interop_sync_test.go:90:    INFO [05-14|20:12:58.016] restart primary supervisor               Test=TestL2CLAheadOfSupervisor
    interop_sync_test.go:93:    INFO [05-14|20:12:58.029] no CL connected to supervisor so every CL safe head will not advance Test=TestL2CLAheadOfSupervisor
    l2_cl.go:95:                INFO [05-14|20:12:58.030] expecting chain not to advance           id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=38
    l2_cl.go:95:                INFO [05-14|20:12:58.030] expecting chain not to advance           id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=38
    l2_cl.go:95:                INFO [05-14|20:12:58.030] expecting chain not to advance           id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=38
    l2_cl.go:95:                INFO [05-14|20:12:58.030] expecting chain not to advance           id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=38
    l2_cl.go:99:                INFO [05-14|20:13:00.030] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=38 current=38
    l2_cl.go:99:                INFO [05-14|20:13:00.030] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=38 current=38
...
    l2_cl.go:99:                INFO [05-14|20:13:56.082] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=38 current=38
    l2_cl.go:99:                INFO [05-14|20:13:58.083] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=38 current=38
    l2_cl.go:99:                INFO [05-14|20:13:58.083] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=38 current=38
    l2_cl.go:99:                INFO [05-14|20:13:58.083] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=38 current=38
    l2_cl.go:99:                INFO [05-14|20:13:58.083] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=38 current=38
    interop_sync_test.go:99:    INFO [05-14|20:13:58.083] reconnect sequencer CLs to primary supervisor Test=TestL2CLAheadOfSupervisor
    interop_sync_test.go:103:   INFO [05-14|20:13:58.086] restart secondary supervisor             Test=TestL2CLAheadOfSupervisor
    interop_sync_test.go:106:   INFO [05-14|20:13:58.097] reconnect verifier CLs to secondary supervisor Test=TestL2CLAheadOfSupervisor
    interop_sync_test.go:111:   INFO [05-14|20:13:58.104] check verifier CLs safe head rewinded    Test=TestL2CLAheadOfSupervisor rewind=3
    l2_cl.go:139:               INFO [05-14|20:13:58.104] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=35 current=38
    l2_cl.go:139:               INFO [05-14|20:13:58.104] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=35 current=38
    l2_cl.go:139:               INFO [05-14|20:13:58.605] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=35 current=38
...
    l2_cl.go:139:               INFO [05-14|20:14:00.612] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=35 current=38
    l2_cl.go:139:               INFO [05-14|20:14:01.113] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=35 current=38
    interop_sync_test.go:118:   INFO [05-14|20:14:01.615] every CLs advance safe heads             Test=TestL2CLAheadOfSupervisor delta=10 target=57
    l2_cl.go:111:               INFO [05-14|20:14:01.615] expecting chain to reach                 id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=57
    l2_cl.go:111:               INFO [05-14|20:14:01.615] expecting chain to reach                 id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=57
    l2_cl.go:111:               INFO [05-14|20:14:01.616] expecting chain to reach                 id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=57
    l2_cl.go:111:               INFO [05-14|20:14:01.616] expecting chain to reach                 id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=57
    l2_cl.go:119:               INFO [05-14|20:14:01.616] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=57 current=3
    l2_cl.go:119:               INFO [05-14|20:14:01.616] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=57 current=3
    l2_cl.go:119:               INFO [05-14|20:14:01.616] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=57 current=47
    l2_cl.go:119:               INFO [05-14|20:14:01.617] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=57 current=47
    l2_cl.go:119:               INFO [05-14|20:14:03.617] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=57 current=3
    l2_cl.go:119:               INFO [05-14|20:14:03.617] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=57 current=3
    l2_cl.go:119:               INFO [05-14|20:14:03.617] Chain sync status                        id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=57 current=56
    l2_cl.go:119:               INFO [05-14|20:14:03.617] Chain sync status                        id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=57 current=56
    l2_cl.go:119:               INFO [05-14|20:14:05.617] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=57 current=6
    l2_cl.go:119:               INFO [05-14|20:14:05.617] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=57 current=6
    l2_cl.go:116:               INFO [05-14|20:14:05.617] chain advanced                           id=L2CLNode-sequencer-901 chain=901 label=SafeL2   target=57
    l2_cl.go:116:               INFO [05-14|20:14:05.617] chain advanced                           id=L2CLNode-sequencer-902 chain=902 label=SafeL2   target=57
    l2_cl.go:119:               INFO [05-14|20:14:07.618] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=57 current=11
    l2_cl.go:119:               INFO [05-14|20:14:07.619] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=57 current=11
    l2_cl.go:119:               INFO [05-14|20:14:09.620] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=57 current=17
    l2_cl.go:119:               INFO [05-14|20:14:09.621] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=57 current=17
    l2_cl.go:119:               INFO [05-14|20:14:11.622] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=57 current=23
    l2_cl.go:119:               INFO [05-14|20:14:11.622] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=57 current=23
    l2_cl.go:119:               INFO [05-14|20:14:13.622] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=57 current=32
    l2_cl.go:119:               INFO [05-14|20:14:13.622] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=57 current=29
    l2_cl.go:119:               INFO [05-14|20:14:15.623] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=57 current=38
    l2_cl.go:119:               INFO [05-14|20:14:15.623] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=57 current=38
    l2_cl.go:119:               INFO [05-14|20:14:17.631] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=57 current=44
    l2_cl.go:119:               INFO [05-14|20:14:17.631] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=57 current=44
    l2_cl.go:119:               INFO [05-14|20:14:19.632] Chain sync status                        id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=57 current=53
    l2_cl.go:119:               INFO [05-14|20:14:19.632] Chain sync status                        id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=57 current=53
    l2_cl.go:116:               INFO [05-14|20:14:21.633] chain advanced                           id=L2CLNode-verifier-901  chain=901 label=SafeL2   target=57
    l2_cl.go:116:               INFO [05-14|20:14:21.633] chain advanced                           id=L2CLNode-verifier-902  chain=902 label=SafeL2   target=57
--- PASS: TestL2CLAheadOfSupervisor (187.73s)
```

**Additional context**

This cannot be targeted to local interop kurtosis net since it does not support the redundancy topology(extra L2EL + L2CL for both L2 Chains + secondary supervisor)

Non-DSL version attempted at https://github.com/ethereum-optimism/optimism/pull/15714 but will be closed due to this PR.

**Metadata**

- Fixes https://github.com/ethereum-optimism/optimism/issues/15098

### CODE REVIEW

File: op-devstack/sysgo/system.go [hunk 1]
```diff
@@ -40,7 +40,7 @@ func NewDefaultInteropSystemIDs(l1ID, l2AID, l2BID eth.ChainID) DefaultInteropSy
 		L1CL:        stack.L1CLNodeID{Key: "l1", ChainID: l1ID},
 		Superchain:  "main", // TODO(#15244): hardcoded to match the deployer default ID
 		Cluster:     "main",
-		Supervisor:  "dev",
+		Supervisor:  "primary",
```
Comment (pcw109550) [inline op-devstack/sysgo/system.go]: The first supervisor was renamed to `primary` and second one as `secondary` to order them alphabetically. To make the matcher work.

File: op-devstack/dsl/l2_cl.go [hunk 2]
```diff
@@ -105,6 +122,26 @@ func (cl *L2CLNode) Reach(label string, target uint64, attempts int) CheckFunc {
 	}
 }
 
+func (cl *L2CLNode) Rewind(label string, delta uint64, attempts int) CheckFunc {
```
Comment (protolambda) [inline op-devstack/dsl/l2_cl.go]: Like the PR this depends on, let's use `SafetyLevel` enum typing.

File: op-acceptance-tests/tests/interop/sync/multisupervisor_interop/interop_sync_test.go [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+	logger.Info("make sure verifiers advances unsafe head", "delta", delta)
+	dsl.CheckAll(t,
+		sys.L2CLA.Advance("UnsafeL2", delta, 30), sys.L2CLA2.Advance("UnsafeL2", delta, 30),
+		sys.L2CLB.Advance("UnsafeL2", delta, 30), sys.L2CLB2.Advance("UnsafeL2", delta, 30),
+	)
+
+	safeHeadViewA2 := sys.SupervisorSecondary.SyncView(sys.L2CLA.ChainID(), "CrossSafe")
+	safeHeadViewB2 := sys.SupervisorSecondary.SyncView(sys.L2CLB.ChainID(), "CrossSafe")
+
+	logger.Info("stop secondary supervisor")
```
Comment (protolambda) [inline op-acceptance-tests/tests/interop/sync/multisupervisor_interop/interop_sync_test.go]: Nit: Ideally we start every log statement with a capitalized character. It's fine if we miss a few, but it improves readability nicely.

File: op-devstack/sysgo/system.go (hunk 1 above)
Comment (protolambda) [reply op-devstack/sysgo/system.go]: Can we instead number them? I'm worried the alphabetical thing breaks later once we add 3, 4, 5...

File: op-acceptance-tests/tests/interop/sync/multisupervisor_interop/interop_sync_test.go [hunk 4]
```diff
@@ -0,0 +1,127 @@
...
+
+import (
+	"testing"
+
+	"github.com/ethereum-optimism/optimism/op-devstack/devtest"
+	"github.com/ethereum-optimism/optimism/op-devstack/dsl"
+	"github.com/ethereum-optimism/optimism/op-devstack/presets"
+)
+
+// TestL2CLAheadOfSupervisor tests the below scenario:
```
Comment (protolambda) [inline op-acceptance-tests/tests/interop/sync/multisupervisor_interop/interop_sync_test.go:12]: I think it would be better if we summarize the go doc of the test more, and put the details as comments within the test. Otherwise we end up duplicating the whole test logic (since DSL ideally is not far off from the english way to describe the checks).

**Review by protolambda — COMMENTED** [review]
Really good! Just have some stylistic nits.

File: op-devstack/dsl/l2_cl.go (hunk 2 above)
Comment (pcw109550) [reply op-devstack/dsl/l2_cl.go]: Fixed at ~https://github.com/ethereum-optimism/optimism/pull/15908/commits/b84fb1a44e85e3b946e9f4fdbaaf99e0f2f98160~ https://github.com/ethereum-optimism/optimism/pull/15908/commits/f9c6b2ce8d7f8b3183cf02a5564d8bee8e68570c (rebase change)

File: op-acceptance-tests/tests/interop/sync/multisupervisor_interop/interop_sync_test.go (hunk 3 above)
Comment (pcw109550) [reply op-acceptance-tests/tests/interop/sync/multisupervisor_interop/interop_sync_test.go]: Fixed at ~https://github.com/ethereum-optimism/optimism/pull/15908/commits/1500e3eecc11c6b5780d837c3a689dbe61add332~ https://github.com/ethereum-optimism/optimism/pull/15908/commits/364ff4ae1d352f8b2030ce459c8f738e36076694 (rebase change)

File: op-devstack/sysgo/system.go (hunk 1 above)
Comment (pcw109550) [reply op-devstack/sysgo/system.go]: Fixed at ~https://github.com/ethereum-optimism/optimism/pull/15908/commits/fd196bc16e4fe215c93704398a472df0a21c7b52~ https://github.com/ethereum-optimism/optimism/pull/15908/commits/96040164d04edc00cdae3f118c58940151e03cb2 (rebase change)

File: op-acceptance-tests/tests/interop/sync/multisupervisor_interop/interop_sync_test.go (hunk 4 above)
Comment (pcw109550) [reply op-acceptance-tests/tests/interop/sync/multisupervisor_interop/interop_sync_test.go:12]: Fixed at https://github.com/ethereum-optimism/optimism/pull/15908/commits/415e359607887371b6a96e799192c5fdb0d42742

File: op-devstack/shim/l2_cl.go [hunk 5]
```diff
@@ -12,6 +13,9 @@ type L2CLNodeConfig struct {
 	CommonConfig
 	ID     stack.L2CLNodeID
 	Client client.RPC
+
+	InteropEndpoint  string
+	InteropJwtSecret eth.Bytes32
```
Comment (protolambda) [inline op-devstack/shim/l2_cl.go:18]: We deliberately don't put raw RPC strings and secrets into the `shim` package, but only ready RPC clients, see devstack readme.

Please instead register the RPC URL inside of the sysgo object that describes the node.

Not ever backend may have RPC in the same way, require different dial configurations, etc., hence it's the responsibility of the backend and not the shim to manage the RPC url.

**Review by protolambda — CHANGES_REQUESTED** [review]
Looks good, but there's one thing that breaks a design decision on the shim package, see review comment.

File: op-devstack/shim/l2_cl.go (hunk 5 above)
Comment (protolambda) [reply op-devstack/shim/l2_cl.go:18]: Hmm, actually now that I think more about it, we end up needing this RPC string, but only for the purposes to give it to the supervisor to connect to. Tests should not dial it directly themselves. Maybe you can add some comment about this being for supervisor connections, not for tests?

Comment (pcw109550) [reply op-devstack/shim/l2_cl.go:18]: Yes we do not manually create the client.RPC but only to use it to connect with the supervisor. I understand the design consideration about the shim, to unify the RPC backend config. Added comments about these interop fields at https://github.com/ethereum-optimism/optimism/pull/15908/commits/a60d279cfd756b16da1429bc8fde6be4db4de7c7

**Review by protolambda — APPROVED** [review]

**Review by protolambda — APPROVED** [review]
