### PR TITLE
fix(kona/derive): preserve error kind from chain provider in BlobSource

### LINKED ISSUE #19354: kona: BlobSource wraps all errors as Temporary, losing Reset classification on L1 reorg
## Summary

`BlobSource::load_blobs` in `rust/kona/crates/protocol/derive/src/sources/blobs.rs` wraps all errors from `chain_provider.block_info_and_transactions_by_hash` using `BlobProviderError::Backend(e.to_string()).into()`, which forces every error to `PipelineErrorKind::Temporary`. This loses the proper error classification from the underlying `ChainProvider::Error`'s `Into<PipelineErrorKind>` implementation.

## Impact

During an L1 reorg, when a blob-bearing L1 block hash disappears, `AlloyChainProvider::block_info_and_transactions_by_hash` returns `AlloyChainProviderError::BlockNotFound(hash)`, which maps to `ResetError::BlockNotFound` → `PipelineErrorKind::Reset`. However, the `Backend` wrapping in `BlobSource` downgrades this to `Temporary`, causing kona to spin retrying indefinitely instead of triggering a pipeline reset. This is a liveness bug: the derivation pipeline stalls rather than resetting and recovering.

## Regression Context

`AlloyChainProvider` was explicitly fixed in commit [`ee4d492a87`](https://github.com/ethereum-optimism/optimism/commit/ee4d492a87) to properly emit `Reset` for hash-based `BlockNotFound` errors. However, `BlobSource` bypasses that fix by wrapping the error in `Backend` before propagating it.

## Reference Implementation

The Go reference in [`op-node/rollup/derive/blob_data_source.go:82-85`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/op-node/rollup/derive/blob_data_source.go#L82) explicitly branches on `errors.Is(err, ethereum.NotFound)` and wraps it as `NewResetError`, ensuring a pipeline reset is triggered on block-not-found.

## Affected Code

**Subject (bug):** [`rust/kona/crates/protocol/derive/src/sources/blobs.rs:119-122`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/rust/kona/crates/protocol/derive/src/sources/blobs.rs#L119)

```rust
let info =
    self.chain_provider.block_info_and_transactions_by_hash(block_ref.hash).await.map_err(
        |e| -> PipelineErrorKind { BlobProviderError::Backend(e.to_string()).into() },
    )?;
```

**Reference (correct):** [`op-node/rollup/derive/blob_data_source.go:82-85`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/op-node/rollup/derive/blob_data_source.go#L82)

```go
if errors.Is(err, ethereum.NotFound) {
    return nil, NewResetError(fmt.Errorf("failed to fetch receipts of L1 block %s: %w", id, err))
}
```

## Unaffected Code

`CalldataSource` is unaffected — it correctly propagates error kind by returning `CP::Error` directly from `load_calldata` and calling `.map_err(Into::into)?` at the call site in `next()`, which preserves the Reset/Temporary/Critical classification from the underlying provider.

## Fix

Change the `map_err` closure on the `chain_provider` call in `BlobSource::load_blobs` from:

```rust
.map_err(|e| -> PipelineErrorKind { BlobProviderError::Backend(e.to_string()).into() })
```

to:

```rust
.map_err(Into::into)
```

This mirrors the pattern used by `CalldataSource` and preserves the error classification from the underlying `ChainProvider::Error` implementation.

### PR DESCRIPTION
**Pull request by ajsutton**
## Summary

`BlobSource::load_blobs` was wrapping all errors from `chain_provider.block_info_and_transactions_by_hash` with `BlobProviderError::Backend(e.to_string()).into()`, which forced every error to `PipelineErrorKind::Temporary` regardless of the underlying error classification.

This is a regression: `AlloyChainProvider` was fixed in `ee4d492a87` to emit `PipelineErrorKind::Reset` for `BlockNotFound` errors (mapping via `AlloyChainProviderError::BlockNotFound` → `ResetError::BlockNotFound` → `Reset`). However, the `Backend` wrapping in `BlobSource` bypassed that fix entirely.

**Impact:** During an L1 reorg, when a blob-bearing L1 block hash disappears, kona's `BlobSource` spins retrying as `Temporary` instead of triggering a pipeline reset. This causes a liveness stall — the derivation pipeline cannot make progress.

The Go reference ([`blob_data_source.go:82-85`](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/op-node/rollup/derive/blob_data_source.go#L82)) explicitly branches on `errors.Is(err, ethereum.NotFound)` → `NewResetError`, ensuring a pipeline reset is triggered.

## Fix

Change the `map_err` closure on the chain provider call from:

```rust
.map_err(|e| -> PipelineErrorKind { BlobProviderError::Backend(e.to_string()).into() })
```

to:

```rust
.map_err(Into::into)
```

This uses the `ChainProvider::Error`'s own `Into<PipelineErrorKind>` implementation to correctly route errors — exactly the pattern already used by `CalldataSource` (`calldata.rs:100`).

Also removes the now-unused `alloc::string::ToString` import.

## Testing

Existing tests continue to pass:
- `test_load_blobs_chain_provider_err`: still expects `Temporary` — `TestProviderError::BlockNotFound` maps to `Temporary` via its own `Into<PipelineErrorKind>` impl (not via `Backend`)
- `test_load_blobs_not_found_triggers_reset`: verifies that a missed beacon slot triggers `Reset`

Fixes https://github.com/ethereum-optimism/optimism/issues/19354

### CODE REVIEW

File: rust/kona/crates/protocol/derive/src/sources/blobs.rs [hunk 1]
```diff
@@ -116,10 +116,11 @@ where
...
 
-        let info =
-            self.chain_provider.block_info_and_transactions_by_hash(block_ref.hash).await.map_err(
-                |e| -> PipelineErrorKind { BlobProviderError::Backend(e.to_string()).into() },
-            )?;
+        let info = self
+            .chain_provider
+            .block_info_and_transactions_by_hash(block_ref.hash)
+            .await
+            .map_err(Into::into)?;
```
Comment (ajsutton) [inline rust/kona/crates/protocol/derive/src/sources/blobs.rs:123]: Can we add a unit test that confirms the pipeline is reset when a not found error occurs while retrieving a blob?

**Review by geoknee — APPROVED** [review]
