### PR TITLE
interop: Recursive hazard detection

### LINKED ISSUE #14425: op-program: Handle cyclic message cross-safety
There's a bug in the op-program (and the supervisor) where it fails to handle the case where cyclic, but valid, messages at a given timestamp. These messages should be considered cross safe but that's not what happens currently. As far as I can tell from the spec this should be allowed.

### PR DESCRIPTION
**Pull request by ghost**
- Abstracts the shared logic between Unsafe and Safe hazard collection.
- Makes the hazard collection recursive; when we find a new hazard block we check it for further hazards.

### CODE REVIEW

File: op-supervisor/supervisor/backend/cross/hazard_set.go [hunk 1]
```diff
@@ -0,0 +1,188 @@
...
+	"github.com/ethereum/go-ethereum/log"
+
+	"github.com/ethereum-optimism/optimism/op-service/eth"
+	"github.com/ethereum-optimism/optimism/op-supervisor/supervisor/backend/depset"
+	"github.com/ethereum-optimism/optimism/op-supervisor/supervisor/types"
+)
+
+// MaxHazardBlockChecks is the maximum number of blocks that can be processed when building a hazard set.
+// It is a safety limit to prevent potential infinite loops or excessive resource consumption.
+const MaxHazardBlockChecks = 10000
```
Comment (ghost) [inline op-supervisor/supervisor/backend/cross/hazard_set.go]: Is this a reasonable value for a stop-limit to prevent run-away looping? We shouldn't expect to exhaust the limit in normal operation.

File: op-program/client/interop/consolidate.go [hunk 2]
```diff
@@ -180,7 +181,7 @@ func checkHazards(
 		}
 	}
 
-	hazards, err := cross.CrossUnsafeHazards(deps, chainID, candidate, execMsgs)
+	hazards, err := cross.CrossUnsafeHazards(deps, logger, chainID, candidate)
```
Comment (ghost) [inline op-program/client/interop/consolidate.go:162]: My understanding is this code can't access the supervisor DBs, so this change in its current form will break this. We need to resolve this.

File: op-supervisor/supervisor/backend/cross/safe_update_test.go [hunk 3]
```diff
@@ -335,7 +335,7 @@ func TestScopedCrossSafeUpdate(t *testing.T) {
 		// but only on the second call (which will be used by HazardSafeFrontierChecks)
 		csd.deps.chainIDFromIndexfn = func() (eth.ChainID, error) {
 			defer func() { count++ }()
-			if count == 0 {
+			if count < 2 {
```
Comment (ghost) [inline op-supervisor/supervisor/backend/cross/safe_update_test.go:374]: Note: This changes because this test is now checking an additional block for hazards due the recursion, which means it calls ChainIDFromIndex twice before the place we want it to error.

File: op-supervisor/supervisor/backend/cross/hazard_set.go (hunk 1 above)
Comment (Inphi) [reply op-supervisor/supervisor/backend/cross/hazard_set.go]: Is this limit guaranteed to never get hit? This limit affects the op-program and if there's any possibility that it can be violated, then we should remove this or tweak the op-program to ignore this limit.

File: op-program/client/interop/consolidate.go [hunk 4]
```diff
@@ -180,7 +181,8 @@ func checkHazards(
 		}
 	}
 
-	hazards, err := cross.CrossUnsafeHazards(deps, chainID, candidate, execMsgs)
+	hazardDeps := &cross.UnsafeHazardDeps{UnsafeStartDeps: deps}
```
Comment (Inphi) [inline op-program/client/interop/consolidate.go]: this adapter isn't needed. As `cross.CrossUnsafeHazards` already wraps the `UnsafeStartDeps` input as `CrossUnsafeHazards`.

File: op-supervisor/supervisor/backend/cross/hazard_set.go (hunk 1 above)
Comment (axelKingsley) [reply op-supervisor/supervisor/backend/cross/hazard_set.go]: > if there's any possibility that it can be violated

If this limit is never going to be hit, then we should remove it. And if the limit *is* going to be hit, we should remove it (so the op-program is correct).

A supervisor which has stalled because it is somehow in an infinite hazard-checking loop is equally as healthy as a supervisor that is halted because it hit the `MaxHazardBlockChecks`.

File: op-supervisor/supervisor/backend/cross/cycle_test.go [hunk 5]
```diff
@@ -179,59 +179,37 @@ func TestHazardCycleChecksFailures(t *testing.T) {
...
+						1: execMsg("2", 1),
 					},
 				},
-			},
-			expectErr: types.ErrConflict,
-			msg:       "expected self reference detection error",
-		},
-		{
-			name: "unknown chain",
-			chainBlocks: map[string]chainBlockDef{
```
Comment (axelKingsley) [inline op-supervisor/supervisor/backend/cross/cycle_test.go]: Looks like we are dropping tests without adding new ones in?

EDIT: Actually i think they are covered by the tests which now exercise `build`. is that right @tyler-smith ?

File: op-supervisor/supervisor/backend/cross/hazard_set_test.go [hunk 6]
```diff
@@ -0,0 +1,802 @@
...
+			},
+		},
+		{
+			name: "Multiple Independent Chains",
+			blocks: []blockDef{
+				makeBlock(0, 100, 1, makeMessage(1, 100, 1, 1), makeMessage(2, 100, 1, 1)),
+				// Chain 1: A -> B -> C
+				makeBlock(1, 100, 1, makeMessage(3, 100, 1, 1)),
+				makeBlock(3, 100, 1),
+				// Chain 2: X -> Y -> Z
```
Comment (axelKingsley) [inline op-supervisor/supervisor/backend/cross/hazard_set_test.go]: are these comments accurate? looks to me like what is actually happening is

// Chain 0 -> Chain 2 -> Chain 4
...
// Chain 1 -> Chain 3

File: op-supervisor/supervisor/backend/cross/safe_start.go [hunk 7]
```diff
@@ -15,100 +15,32 @@ type SafeStartDeps interface {
...
-	hazards = make(map[types.ChainIndex]types.BlockSeal)
-
-	// Warning for future: If we have sub-second distinct blocks (different block number),
-	// we need to increase precision on the above timestamp invariant.
-	// Otherwise a local block can depend on a future local block of the same chain,
-	// simply by pulling in a block of another chain,
-	// which then depends on a block of the original chain,
-	// all with the same timestamp, without message cycles.
+func CrossSafeHazards(d SafeStartDeps, logger log.Logger, chainID eth.ChainID, inL1Source eth.BlockID,
+	candidate types.BlockSeal) (*HazardSet, error) {
```
Comment (axelKingsley) [inline op-supervisor/supervisor/backend/cross/safe_start.go]: nit: I think I'm the only person around who cares about this (so feel free to totally ignore me), but I prefer when signatures follow one of:
- Whole signature on one line
- One argument per line
- arguments logically grouped per line (like pairs of arguments where applicable)
- arguments packaged into a struct (when there are a *lot* of related arguments and similar signatures in multiple places)

When linting complains about line-length, it is because the code may not be readable. While arbitrary line breaks satisfy the linter, I'm not sure they satisfy the purpose of the lint.

File: op-supervisor/supervisor/backend/cross/safe_update_test.go (hunk 3 above)
Comment (axelKingsley) [inline op-supervisor/supervisor/backend/cross/safe_update_test.go:374]: I feel like this would totally change the test, but then I see the *existing* comment mentioning the second call -- what's up with this change?

**Comment by Inphi** [comment]
Needs a rebase on the recently merged message expiry checks in develop.

File: op-supervisor/supervisor/backend/cross/unsafe_update_test.go [hunk 8]
```diff
@@ -114,7 +114,7 @@ func TestCrossUnsafeUpdate(t *testing.T) {
 		// (the first one is in CrossSafeHazards)
 		usd.deps.chainIDFromIndexfn = func() (eth.ChainID, error) {
 			defer func() { count++ }()
-			if count == 1 {
+			if count < 2 {
```
Comment (axelKingsley) [inline op-supervisor/supervisor/backend/cross/unsafe_update_test.go]: the comment says "by failing the second ChainIDFromIndex call", but this appears to only fail starting at the 3rd call?

**Review by axelKingsley — COMMENTED** [review]
Looking good. I'm about to do another pass on the `build` function to make sure I understand it. I see lots of good unit tests to confirm various recursive outlays get calculated correctly.

Lots of files, so I'm annotating a bit:

- `consolidate.go`: just wiring in a logger
- `cycle.go` - `HazardSet` is now used instead of a map (`HazardSet` is just a wrapper for a map)
- `cycle_test.go` - removing some tests?
- `hazard_set.go` - `HazardSet`s are new structs. Looks like the most important feature of them is `build`, which takes a block and adds it any any recursive dependencies onto the set. The `build` function is *long*. I'll do a deeper read on it and leave comments directly.
- `hazard_set_test.go` - yay tests. Looks like a good range of situations are covered that show that recursive dependencies are now indeed pulled :D
- `safe_frontier.go` - map -> HazardSet
- `safe_frontier_test.go` - ditto
- `safe_start.go` - DRYed up, no longer needs to do its own hazard detection 👍 
- `safe_start_test.go` - added a needed mock function to existing tests
- `safe_update.go` - also DRYed up.
- `safe_update_test.go` - see comment.
- `unsafe_frontier.go` - map -> HazardSet and a typo fix (ty!)
- `unsafe_frontier_test.go` - using HazardSet instead of map
- `unsafe_start.go` - DRYed up just like `safe_start`
- `unsafe_start_test.go` - signature updates and a required mock
- `unsafe_update.go` - no longer collects `execMsgs` for the CrossUnsafeHazards, since it is now handled from the `candidate`
- `unsafe_update_test.go` - see comment
- `depset.go` - no more `ChainIndexFromID` - removed a redundant `ChainIndexFromID` interface signature

File: op-supervisor/supervisor/backend/cross/hazard_set.go [hunk 9]
```diff
@@ -0,0 +1,178 @@
...
+				// log events to ensure non-cyclic cross-chain message ordering.
+				// And since we may have back-and-forth messaging, we cannot wait till the initiating side is cross-safe.
+				// Thus check that it was included in a local-safe block,
+				// and then proceed with transitive block checks,
+				// to ensure the local block we depend on is becoming cross-safe also.
+				logger.Debug("Checking message with current timestamp", "msg", msg, "candidate", candidate)
+
+				if existing, ok := h.entries[msg.Chain]; ok {
+					if existing.ID() != includedIn.ID() {
+						return fmt.Errorf("found dependency on %s (chain %d), but already depend on %s", includedIn, initChainID, chainID)
```
Comment (axelKingsley) [inline op-supervisor/supervisor/backend/cross/hazard_set.go]: Same with these stanzas, depending on the timestamps, there is different processing done, and each can return errors. Could these be factored into helper methods?

File: op-supervisor/supervisor/backend/cross/hazard_set.go [hunk 10]
```diff
@@ -0,0 +1,178 @@
...
+			if ok, err := depSet.CanInitiateAt(initChainID, msg.Timestamp); err != nil {
+				return fmt.Errorf("cannot check message initiation of msg %s (chain %s): %w", msg, chainID, err)
+			} else if !ok {
+				return fmt.Errorf("cannot allow initiating message %s (chain %s): %w", msg, chainID, types.ErrConflict)
+			}
+
+			// invariant: the message must not be in the future
+			if msg.Timestamp > candidate.Timestamp {
+				return fmt.Errorf("executing message %s in %s breaks timestamp invariant", msg, candidate)
+			}
```
Comment (axelKingsley) [inline op-supervisor/supervisor/backend/cross/hazard_set.go]: Could invariant checks be something factored out of this function?

**Review by axelKingsley — COMMENTED** [review]
I read over the `build` function, and it makes sense to me how it explores dependencies depth-first using a stack. I left some comments suggesting ways to organize the function by factoring out large chunks of the function, but it's not blocking.

A couple things I am hoping to see before merge:
- There was an E2E test which @ajsutton showed off to demonstrate this issue in the first place -- could we please un-skip that test (at least the first skip)?
- Please take a look at my comments from the previous review pass
- Rebase is needed

Other than that, looking good!

File: op-supervisor/supervisor/backend/cross/cycle_test.go (hunk 5 above)
Comment (ghost) [reply op-supervisor/supervisor/backend/cross/cycle_test.go]: These changes were erroneous and have been fixed.

File: op-supervisor/supervisor/backend/cross/safe_update_test.go (hunk 3 above)
Comment (ghost) [reply op-supervisor/supervisor/backend/cross/safe_update_test.go:374]: I fixed the comments. The change in behavior is because the additional block check due to the new recursion creates a second call to ChainIDFromIndex so this needs to succeed an additional time than before. Same in the unsafe_update_test.go case.

File: op-e2e/actions/interop/proofs_test.go [hunk 11]
```diff
@@ -478,7 +474,7 @@ func TestInteropFaultProofs_CascadeInvalidBlock(gt *testing.T) {
 	// as an invalid message.
 	system.AddL2Block(actors.ChainA,
 		dsl.WithL2BlockTransactions(system.InboxContract.Execute(alice, chainBInitTx)),
-		// Block becomes cross-unsafe because the init msg is currently present, but it should not become cross-safe.
+		dsl.WithL1BlockCrossUnsafe(),
```
Comment (ghost) [inline op-e2e/actions/interop/proofs_test.go:482]: This comment says we should be cross-unsafe because we know of the init msg, but the payload is (intentionally) wrong so we're correctly not promoting the block to cross-unsafe. I think this change is correct but not 100% sure.

File: op-program/client/interop/consolidate.go [hunk 12]
```diff
@@ -157,13 +158,19 @@ type ConsolidateCheckDeps interface {
...
+	// TODO(#14234): remove this check once the supervisor is updated handle msg expiry
+	messageExpiryTimeSeconds := deps.DependencySet().MessageExpiryWindow()
+	for _, msg := range execMsgs {
+		if msg.Timestamp+messageExpiryTimeSeconds < candidate.Timestamp {
+			return fmt.Errorf(
+				"message timestamp is too old: %d < %d: %w",
+				msg.Timestamp+messageExpiryTimeSeconds, candidate.Timestamp, supervisortypes.ErrConflict,
+			)
+		}
+	}
```
Comment (Inphi) [inline op-program/client/interop/consolidate.go]: conflict with develop. That TODO has been fixed as message checks are now handled by the supervisor logic. So we don't need to do this here.

**Review by axelKingsley — APPROVED** [review]
Please see @Inphi 's comment about removing the Expiry Window Check, but then LGTM.

File: op-e2e/actions/interop/proofs_test.go (hunk 11 above)
Comment (ghost) [reply op-e2e/actions/interop/proofs_test.go:482]: Determined offline that this change is what we want.
