### PR TITLE
fix(ct): improve bundle size

### LINKED ISSUE #3329: massive increase in bundle size between `@eth-optimism/contracts` versions `0.5.29` --> `0.5.33`
**Describe the bug**
Somewhere strictly after the release `0.5.29` and on-or-before the release `0.5.33`, the bundle size of [@eth-optimism/contracts](https://github.com/ethereum-optimism/optimism/releases/tag/@eth-optimism%2Fcontracts@0.5.0) increased enormously, from over 2MB to over 4.4MB.

As of now, `@eth-optimism` is essentially an order of magnitude larger than anything else in my project, which is crazy! it was already bizarrely large before this, but this is essentially not tolerable. Please look into this and address this, or I may have to downgrade. many thanks in advance.

**To Reproduce**
add
```javascript
"dependencies": {
    ...
    "@eth-optimism/sdk": "^1.2.0",
    ...
}
```
to `package.json` of any project; then run the project through [Webpack Bundle Analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer).

**Expected behavior**
The bundle size should be < 1MB.

**Screenshots**
this is a screenshot of the relevant portion of Webpack Bundle Analyzer.
Screen Shot 2022-08-27 at 1 06 41 PM

**System Specs:**
 - OS: Mac OS 12.5.1
 - Package Version (or commit hash): relevant section of current `yarn.lock` file is below
```javascript
"@eth-optimism/contracts-bedrock@0.5.4":
  version "0.5.4"
  resolved "https://registry.yarnpkg.com/@eth-optimism/contracts-bedrock/-/contracts-bedrock-0.5.4.tgz#d2dbdc7fcb7ef729d2682b898d742fd2f1482bb8"
  integrity sha512-+1dnI17DF+p3Q80qNhvfmMF0/HIb7PhAw4eJLjBWUbyGVVmUffZC4XiVYt5Rx3kFGUc50gDzPo30rUtdj4zE5w==
  dependencies:
    "@eth-optimism/core-utils" "^0.9.3"
    "@openzeppelin/contracts" "4.7.3"
    "@openzeppelin/contracts-upgradeable" "4.7.3"
    ethers "^5.6.8"
    hardhat "^2.9.6"

"@eth-optimism/contracts@0.5.33":
  version "0.5.33"
  resolved "https://registry.yarnpkg.com/@eth-optimism/contracts/-/contracts-0.5.33.tgz#1adeb902ff849152ecdb8639af5ba76dfc27c213"
  integrity sha512-lOj0psjl/7oydUXuSXhZ3P55zAXBNSgK6OzZeCW6JQ+drN+1OEdyp/MYKrSh8Cw8fW2k9MMdWbOuTa7/Blb0hA==
  dependencies:
    "@eth-optimism/core-utils" "0.9.3"
    "@ethersproject/abstract-provider" "^5.6.1"
    "@ethersproject/abstract-signer" "^5.6.2"

"@eth-optimism/core-utils@0.9.3", "@eth-optimism/core-utils@^0.9.3":
  version "0.9.3"
  resolved "https://registry.yarnpkg.com/@eth-optimism/core-utils/-/core-utils-0.9.3.tgz#40c0271f815af68e0a4715e97a045a96462df7b6"
  integrity sha512-b3V8qBgM0e85wdp3CNdJ6iSUvjT2k86F9oCAYeCIXQcQ6+EPaetjxP0T6ct6jLVepnJjoPRlW/lvWslKk1UBGg==
  dependencies:
    "@ethersproject/abstract-provider" "^5.6.1"
    "@ethersproject/properties" "^5.6.0"
    "@ethersproject/providers" "^5.6.8"
    "@ethersproject/transactions" "^5.6.2"
    "@ethersproject/web" "^5.6.1"
    bufio "^1.0.7"
    chai "^4.3.4"
    ethers "^5.6.8"

"@eth-optimism/sdk@^1.2.0":
  version "1.6.0"
  resolved "https://registry.yarnpkg.com/@eth-optimism/sdk/-/sdk-1.6.0.tgz#18acaf2e9ccf0dff90e5629e8b1cd191b53e6629"
  integrity sha512-Z/NnZskaqeSHr6iQEcdOgmC4QoEGFqglkMmk0cwgN9TGbSd+gz65U6gQRh/MaX4r4ZV6uQEkOCmdHeXWfhlj+Q==
  dependencies:
    "@eth-optimism/contracts" "0.5.33"
    "@eth-optimism/contracts-bedrock" "0.5.4"
    "@eth-optimism/core-utils" "0.9.3"
    lodash "^4.17.21"
    merkletreejs "^0.2.27"
    rlp "^2.2.7"
```

**Additional context**
let me know if i can provide any further diagnostic information. many thanks in advance.

### PR DESCRIPTION
**Pull request by smartcontracts**
**Description**
Significantly improves the bundle size of the contracts package by
exporting deployments more intentionally and by removing certain
unnecessary exports.

**Metadata**
- Fixes #3329

### CODE REVIEW

File: packages/contracts/scripts/generate-deployed-artifacts.ts [hunk 1]
```diff
@@ -50,7 +50,11 @@ const main = async () => {
       )
       artifactNames.push(artifactName)
 
-      content += `const ${artifactName} = require('${relPath}')\n`
+      // eslint-disable-next-line @typescript-eslint/no-var-requires
+      const artifact = require(relPath)
+      content += `const ${artifactName} = { abi: ${JSON.stringify(
```
Comment (smartcontracts) [inline packages/contracts/scripts/generate-deployed-artifacts.ts:55]: No longer include the entire artifact, just the address and the ABI. We never use the entire artifact anywhere.

**Review by mslipper — APPROVED** [review]
