### PR TITLE
fix(op-acceptance): default cannon-kona challenger on

### LINKED ISSUE #19092: op-acceptance: Enable cannon-kona game types by default in op-acceptance
Now that kona is in the monorepo and U18 is enabling cannon-kona in production, we should update the op-acceptance deployment to default to having kona enabled.

### PR DESCRIPTION
**Pull request by wwared**
## Summary

- ~Default op-devstack challenger runtimes to cannon-kona enabled by replacing `EnableCannonKonaForChall` with `DisableCannonKonaForChall` that defaults to `false`.~
- Delete the now-dead `presets.WithChallengerCannonKonaEnabled` and `presets.WithCannonKonaGameTypeAdded` helpers and their option-kind validation.
- Remove the repeated op-acceptance test opt-ins, keeping explicit `WithGameTypeAdded(gameTypes.CannonKonaGameType)` registration where single-chain tests still need the game type added on-chain.
- Removes `EnableCannonKonaForChall` flag and unconditionally enables cannon kona.

Fixes https://github.com/ethereum-optimism/optimism/issues/19092

~I chose not to add a `WithChallengerCannonKonaDisabled` preset option since we don't really want to support that, but I kept `DisableCannonKonaForChall` in `PresetConfig` in case we need to override this behavior somewhere though. I can remove it entirely instead if anyone thinks that'd be a better idea.~

## Test Plan

- [x] `mise exec -- just lint-go-fix`
- [x] `mise exec -- just lint-go`
- [x] `mise exec -- go test ./op-devstack/presets/... ./op-devstack/sysgo/...`
- [x] `mise exec -- go test ./op-devstack/...`
- [x] `mise exec -- just reproducible-prestate-kona`
- [x] Cutover grep: no matches for `EnableCannonKonaForChall|WithChallengerCannonKonaEnabled|WithCannonKonaGameTypeAdded|optionKindChallengerCannonKona`
- [x] CI guard: no `.circleci/continue/main.yml` additions for kona build/prestate dependencies
- [x] `RUST_JIT_BUILD=1 mise exec -- just -f op-acceptance-tests/justfile test -timeout=0 ./op-acceptance-tests/tests/proofs/cannon/...`
- [x] `RUST_JIT_BUILD=1 mise exec -- just -f op-acceptance-tests/justfile test -timeout=0 ./op-acceptance-tests/tests/base/withdrawal/cannon_kona/...`
- [x] `RUST_JIT_BUILD=1 mise exec -- just -f op-acceptance-tests/justfile test -timeout=0 ./op-acceptance-tests/tests/interop/proofs/...`

Note: the acceptance tests timed out locally, and I am rerunning them locally without the default timeout.

Edit: The acceptance tests only timed out because I didn't set `DEVSTACK_L2EL_KIND=op-reth`, which tried running the cannon tests with default op-reth EL which is a known hang. They actually worked fine locally after that.

### CODE REVIEW

File: op-devstack/sysgo/preset_config.go [hunk 1]
```diff
@@ -25,12 +25,13 @@ type PresetConfig struct {
...
 	AddedGameTypes             []gameTypes.GameType
 	RespectedGameTypes         []gameTypes.GameType
-	EnableCannonKonaForChall   bool
-	EnableTimeTravel           bool
-	MaxSequencingWindow        *uint64
-	RequireInteropNotAtGen     bool
-	MessageExpiryWindow        *uint64
-	UseInteropFilter           bool
+	// DisableCannonKonaForChall disables cannon-kona support in the op-challenger; cannon-kona is enabled by default.
+	DisableCannonKonaForChall bool
```
Comment (ajsutton) [inline op-devstack/sysgo/preset_config.go]: Does anything actually use this? Seems like we could just drop it and always enable cannon-kona support.

**Review by ajsutton — APPROVED** [review]
LGTM.

File: op-devstack/sysgo/preset_config.go (hunk 1 above)
Comment (wwared) [reply op-devstack/sysgo/preset_config.go]: Nothing uses it and it could be dropped, I left it in "just in case" we'd need it but after sleeping on it I think it'd be better to remove it
