### PR TITLE
op-conductor: use op-service HTTP Server for Flashblocks ; fix test flake

### LINKED ISSUE #17879: Conductor: Allow flashblocks port auto-assignment
In the triage of `TestControlLoop/TestFlashblocksHandlerIntegration`, I found the likely culprit was the way in which the port was being bound:
- Test gets a random port
- Test releases the port
- (In the meantime, other things are likely to be assigned the port)
- Test spins up the conductor with the port
- Port in use, test fails

In attempting to fix this, I discovered that there is *no way* to enable port auto-assignment for `WebsocketServerPort`:

https://github.com/ethereum-optimism/optimism/blob/25032f2e17e8d0c085697a4ad75e13f3787ad535/op-conductor/conductor/service.go#L326-L333

### PR DESCRIPTION
**Pull request by axelKingsley**
Fixes: https://github.com/ethereum-optimism/optimism/issues/17879

- Replaces direct golang http server with `op-service` utility version, which contains bound port exposing
- Removes logic which directs `port=0` to semantically mean disable the feature. Port 0 is used for auto assignment.
- Retains checks for invalid port numbers (negative)
- Updates test to await bound port as part of test procedure. This fixes flakes where port contention during CI leads to failures.

### CODE REVIEW

File: op-conductor/rpc/ws/flashblocks_handler.go [hunk 1]
```diff
@@ -148,33 +157,48 @@ func (h *Handler) BroadcastMessage(message []byte) {
...
-	h.server = &http.Server{
-		Addr:    fmt.Sprintf(":%d", h.cfg.WebsocketServerPort),
-		Handler: mux,
+	// Bind listener (supports port=0 for dynamic assignment)
+	ln, err := net.Listen("tcp", fmt.Sprintf(":%d", h.cfg.WebsocketServerPort))
+	if err != nil {
+		return err
+	}
+	h.listener = ln
+	if tcpAddr, ok := ln.Addr().(*net.TCPAddr); ok {
```
Comment (yashvardhan-kukreja) [inline op-conductor/rpc/ws/flashblocks_handler.go]: think we should panic or something on `!ok`

File: op-conductor/rpc/ws/flashblocks_handler.go [hunk 2]
```diff
@@ -148,33 +157,48 @@ func (h *Handler) BroadcastMessage(message []byte) {
 }
 
 func (h *Handler) startWebSocketServer(_ context.Context) error {
-	if h.cfg.WebsocketServerPort <= 0 {
```
Comment (yashvardhan-kukreja) [inline op-conductor/rpc/ws/flashblocks_handler.go:151]: nit: I think we should still have this section. Just replacing `<=` with `<`

File: op-conductor/rpc/ws/flashblocks_handler.go [hunk 3]
```diff
@@ -55,15 +60,18 @@ type Handler struct {
...
+	listener            net.Listener
 	hub                 *Hub
+	ready               chan struct{}
+	boundPort           int
 }
 
 // NewHandler creates a new flashblocks handler
 func NewHandler(cfg Config, log log.Logger, isLeaderFn func(context.Context) bool, m metrics.Metricer) (FlashblockHandler, error) {
 	// Validate configuration
-	if cfg.RollupBoostWsURL == "" || cfg.WebsocketServerPort <= 0 {
```
Comment (yashvardhan-kukreja) [inline op-conductor/rpc/ws/flashblocks_handler.go:64]: Same as https://github.com/ethereum-optimism/optimism/pull/17880/files#r2433818338

File: op-conductor/rpc/ws/flashblocks_handler.go (hunk 1 above)
Comment (axelKingsley) [reply op-conductor/rpc/ws/flashblocks_handler.go]: I am not totally sure about that, but in the interest of this component behaving to your expectations, I've made that update.

File: op-conductor/rpc/ws/flashblocks_handler.go (hunk 2 above)
Comment (axelKingsley) [reply op-conductor/rpc/ws/flashblocks_handler.go:151]: Conductor could also use unsigned int for this so negatives aren't supplied anyway, or just rely on the failure of the http.

But I have re-established this, and made it just say that the port is *invalid*.

**Review by yashvardhan-kukreja — DISMISSED** [review]

File: op-conductor/rpc/ws/flashblocks_handler.go [hunk 4]
```diff
@@ -148,33 +153,40 @@ func (h *Handler) BroadcastMessage(message []byte) {
...
+	srv, err := httputil.StartHTTPServer(addr, mux)
+	if err != nil {
+		return err
+	}
+	h.httpServer = srv
+	// Determine bound port
+	if port, err := h.httpServer.Port(); err == nil {
+		h.boundPort = port
+	} else {
+		h.log.Warn("failed to determine bound port", "err", err)
```
Comment (yashvardhan-kukreja) [inline op-conductor/rpc/ws/flashblocks_handler.go]: we should exit here fatatly/ with a panic imo

File: op-conductor/rpc/ws/flashblocks_handler.go [hunk 5]
```diff
@@ -148,33 +153,41 @@ func (h *Handler) BroadcastMessage(message []byte) {
...
+	if err != nil {
+		return err
+	}
+	h.httpServer = srv
+	// Determine bound port
+	if port, err := h.httpServer.Port(); err == nil {
+		h.boundPort = port
+	} else {
+		h.log.Error("failed to determine bound port", "err", err)
+		panic(err)
```
Comment (yashvardhan-kukreja) [inline op-conductor/rpc/ws/flashblocks_handler.go]:
```suggestion
		return fmt.Errorf("failed to determine bound port: %w", err)
```
nit (apologies, now that I realise, it's better than panicking)

File: op-conductor/conductor/service_test.go [hunk 6]
```diff
@@ -1085,8 +1080,9 @@ func (s *OpConductorTestSuite) TestFlashblocksHandlerIntegration() {
 	err = conductor.Start(s.ctx)
 	s.NoError(err)
 
-	// Wait for conductor to be ready using its internal state
+	// Wait for handler readiness and capture bound port
 	s.NotNil(conductor.flashblocksHandler, "flashblocks handler should be initialized")
+	boundPort := conductor.flashblocksHandler.BoundPort()
```
Comment (yashvardhan-kukreja) [inline op-conductor/conductor/service_test.go:1085]:
```suggestion
	s.NotNil(conductor.flashblocksHandler, "flashblocks handler should be initialized before starting the conductor")
	err = conductor.Start(s.ctx)
	s.NoError(err)

	boundPort := conductor.flashblocksHandler.BoundPort()
	s.NotZero(boundPort, "bound port should be non-zero")
```

**Review by yashvardhan-kukreja — APPROVED** [review]
