### PR TITLE
op-node: Fix p2p data races

### LINKED ISSUE #11328: op-node: Race in p2p
Run op-node from develop with the build flag `-race`.

<details>
<summary>Enormous DATA RACE stack trace</summary>

```
==================
WARNING: DATA RACE
Write at 0x00c0024a9850 by goroutine 395:
  github.com/ethereum-optimism/optimism/op-node/p2p/store.(*DecayApplicationScores).Apply()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/store/iface.go:78 +0x19c
  github.com/ethereum-optimism/optimism/op-node/p2p/store.(*recordsBook[go.shape.string,go.shape.*uint8]).SetRecord()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/store/records_book.go:137 +0x224
  github.com/ethereum-optimism/optimism/op-node/p2p/store.(*scoreBook).SetScore()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/store/scorebook.go:92 +0xc8
  github.com/ethereum-optimism/optimism/op-node/p2p/store.(*extendedStore).SetScore()
      <autogenerated>:1 +0x3c
  github.com/ethereum-optimism/optimism/op-node/p2p.(*peerApplicationScorer).decayScores()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/app_scores.go:91 +0x1ac
  github.com/ethereum-optimism/optimism/op-node/p2p.(*peerApplicationScorer).decayConnectedPeerScores()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/app_scores.go:105 +0x78
  github.com/ethereum-optimism/optimism/op-node/p2p.(*peerApplicationScorer).start.func1()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/app_scores.go:120 +0x15c

Previous read at 0x00c0024a9850 by goroutine 394:
  github.com/ethereum-optimism/optimism/op-node/p2p/store.(*scoreBook).GetPeerScores()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/store/scorebook.go:80 +0x134
  github.com/ethereum-optimism/optimism/op-node/p2p/store.(*scoreBook).GetPeerScore()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/store/scorebook.go:84 +0x58
  github.com/ethereum-optimism/optimism/op-node/p2p/store.(*extendedStore).GetPeerScore()
      <autogenerated>:1 +0x30
  github.com/ethereum-optimism/optimism/op-node/p2p.(*NodeP2P).GetPeerScore()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/node.go:216 +0x58
  github.com/ethereum-optimism/optimism/op-node/p2p/monitor.(*PeerMonitor).checkNextPeer()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/monitor/peer_monitor.go:85 +0x1c8
  github.com/ethereum-optimism/optimism/op-node/p2p/monitor.(*PeerMonitor).checkNextPeer-fm()
      <autogenerated>:1 +0x34
  github.com/ethereum-optimism/optimism/op-node/p2p/monitor.(*PeerMonitor).background()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/monitor/peer_monitor.go:113 +0x1ac
  github.com/ethereum-optimism/optimism/op-node/p2p/monitor.(*PeerMonitor).Start.gowrap1()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/monitor/peer_monitor.go:61 +0x40

Goroutine 395 (running) created at:
  github.com/ethereum-optimism/optimism/op-node/p2p.(*peerApplicationScorer).start()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/app_scores.go:111 +0x98
  github.com/ethereum-optimism/optimism/op-node/p2p.(*NodeP2P).init()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/node.go:166 +0x11ec
  github.com/ethereum-optimism/optimism/op-node/p2p.NewNodeP2P()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/node.go:60 +0x100
  github.com/ethereum-optimism/optimism/op-node/node.(*OpNode).initP2P()
      /Users/anacrolix/optimism/src/optimism/op-node/node/node.go:489 +0x13c
  github.com/ethereum-optimism/optimism/op-node/node.(*OpNode).init()
      /Users/anacrolix/optimism/src/optimism/op-node/node/node.go:139 +0x508
  github.com/ethereum-optimism/optimism/op-node/node.New()
      /Users/anacrolix/optimism/src/optimism/op-node/node/node.go:107 +0x2d4
  main.RollupNodeMain()
      /Users/anacrolix/optimism/src/optimism/op-node/cmd/main.go:95 +0x3ec
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  github.com/syndtr/goleveldb/leveldb.(*DB).checkAndCleanFiles()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db_util.go:52 +0x1d0
  github.com/syndtr/goleveldb/leveldb.openDB()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:137 +0x674
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x1ec
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:665 +0x138
  fmt.(*ss).doScanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:1230 +0x328
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:492 +0x84
  github.com/syndtr/goleveldb/leveldb.openDB()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:132 +0x668
  github.com/syndtr/goleveldb/leveldb.Open()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:205 +0x274
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.fsParseNamePtr()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:674 +0x124
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).GetMeta.func1()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:339 +0xb8
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).GetMeta.func2()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:363 +0xb0
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).GetMeta()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:414 +0x638
  github.com/syndtr/goleveldb/leveldb.(*session).recover()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/session.go:140 +0xc0
  github.com/syndtr/goleveldb/leveldb.Open()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:191 +0xb0
  github.com/syndtr/goleveldb/leveldb.OpenFile()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:227 +0x6c
  github.com/ipfs/go-ds-leveldb.NewDatastore()
      /Users/anacrolix/go/pkg/mod/github.com/ipfs/go-ds-leveldb@v0.5.0/datastore.go:47 +0x194
  github.com/ethereum-optimism/optimism/op-node/p2p/cli.loadLibp2pOpts()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/cli/load_config.go:273 +0x10a4
  github.com/ethereum-optimism/optimism/op-node/p2p/cli.NewConfig()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/cli/load_config.go:51 +0x294
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x1ec
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:665 +0x138
  fmt.(*ss).doScanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:1230 +0x328
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  github.com/syndtr/goleveldb/leveldb.(*DB).checkAndCleanFiles()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db_util.go:52 +0x1d0
  github.com/syndtr/goleveldb/leveldb.openDB()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:137 +0x674
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x1ec
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:665 +0x138
  fmt.(*ss).doScanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:1230 +0x328
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:492 +0x84
  github.com/syndtr/goleveldb/leveldb.openDB()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:132 +0x668
  github.com/syndtr/goleveldb/leveldb.Open()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:205 +0x274
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.fsParseNamePtr()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:674 +0x124
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).GetMeta.func1()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:339 +0xb8
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).GetMeta.func2()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:363 +0xb0
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).GetMeta()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:414 +0x638
  github.com/syndtr/goleveldb/leveldb.(*session).recover()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/session.go:140 +0xc0
  github.com/syndtr/goleveldb/leveldb.Open()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:191 +0xb0
  github.com/syndtr/goleveldb/leveldb.OpenFile()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:227 +0x6c
  github.com/ethereum/go-ethereum/p2p/enode.newPersistentDB()
      /Users/anacrolix/go/pkg/mod/github.com/ethereum-optimism/op-geth@v1.101315.3-rc.1/p2p/enode/nodedb.go:100 +0x90
  github.com/ethereum/go-ethereum/p2p/enode.OpenDB()
      /Users/anacrolix/go/pkg/mod/github.com/ethereum-optimism/op-geth@v1.101315.3-rc.1/p2p/enode/nodedb.go:84 +0x64
  github.com/ethereum-optimism/optimism/op-node/p2p/cli.loadDiscoveryOpts()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/cli/load_config.go:175 +0x4ac
  github.com/ethereum-optimism/optimism/op-node/p2p/cli.NewConfig()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/cli/load_config.go:47 +0x204
  github.com/ethereum-optimism/optimism/op-node.NewConfig()
      /Users/anacrolix/optimism/src/optimism/op-node/service.go:56 +0x19c
  main.RollupNodeMain()
      /Users/anacrolix/optimism/src/optimism/op-node/cmd/main.go:82 +0x200
  main.main.LifecycleCmd.func1()
      /Users/anacrolix/optimism/src/optimism/op-service/cliapp/lifecycle.go:56 +0x1e8
  github.com/urfave/cli/v2.(*Command).Run()
      /Users/anacrolix/go/pkg/mod/github.com/urfave/cli/v2@v2.27.3/command.go:276 +0xeb4
  github.com/urfave/cli/v2.(*App).RunContext()
      /Users/anacrolix/go/pkg/mod/github.com/urfave/cli/v2@v2.27.3/app.go:333 +0xd98
  main.main()
      /Users/anacrolix/optimism/src/optimism/op-node/cmd/main.go:68 +0xb38

Goroutine 394 (running) created at:
  github.com/ethereum-optimism/optimism/op-node/p2p/monitor.(*PeerMonitor).Start()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/monitor/peer_monitor.go:61 +0x134
  github.com/ethereum-optimism/optimism/op-node/p2p.(*NodeP2P).init()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/node.go:164 +0x11d0
  github.com/ethereum-optimism/optimism/op-node/p2p.NewNodeP2P()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/node.go:60 +0x100
  github.com/ethereum-optimism/optimism/op-node/node.(*OpNode).initP2P()
      /Users/anacrolix/optimism/src/optimism/op-node/node/node.go:489 +0x13c
  github.com/ethereum-optimism/optimism/op-node/node.(*OpNode).init()
      /Users/anacrolix/optimism/src/optimism/op-node/node/node.go:139 +0x508
  github.com/ethereum-optimism/optimism/op-node/node.New()
      /Users/anacrolix/optimism/src/optimism/op-node/node/node.go:107 +0x2d4
  main.RollupNodeMain()
      /Users/anacrolix/optimism/src/optimism/op-node/cmd/main.go:95 +0x3ec
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  github.com/syndtr/goleveldb/leveldb.(*DB).checkAndCleanFiles()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db_util.go:52 +0x1d0
  github.com/syndtr/goleveldb/leveldb.openDB()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:137 +0x674
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x1ec
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:665 +0x138
  fmt.(*ss).doScanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:1230 +0x328
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:492 +0x84
  github.com/syndtr/goleveldb/leveldb.openDB()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:132 +0x668
  github.com/syndtr/goleveldb/leveldb.Open()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:205 +0x274
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.fsParseNamePtr()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:674 +0x124
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).GetMeta.func1()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:339 +0xb8
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).GetMeta.func2()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:363 +0xb0
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).GetMeta()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:414 +0x638
  github.com/syndtr/goleveldb/leveldb.(*session).recover()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/session.go:140 +0xc0
  github.com/syndtr/goleveldb/leveldb.Open()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:191 +0xb0
  github.com/syndtr/goleveldb/leveldb.OpenFile()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:227 +0x6c
  github.com/ipfs/go-ds-leveldb.NewDatastore()
      /Users/anacrolix/go/pkg/mod/github.com/ipfs/go-ds-leveldb@v0.5.0/datastore.go:47 +0x194
  github.com/ethereum-optimism/optimism/op-node/p2p/cli.loadLibp2pOpts()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/cli/load_config.go:273 +0x10a4
  github.com/ethereum-optimism/optimism/op-node/p2p/cli.NewConfig()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/cli/load_config.go:51 +0x294
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x1ec
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:665 +0x138
  fmt.(*ss).doScanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:1230 +0x328
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  github.com/syndtr/goleveldb/leveldb.(*DB).checkAndCleanFiles()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db_util.go:52 +0x1d0
  github.com/syndtr/goleveldb/leveldb.openDB()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:137 +0x674
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x1ec
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:665 +0x138
  fmt.(*ss).doScanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:1230 +0x328
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:465 +0x364
  github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:492 +0x84
  github.com/syndtr/goleveldb/leveldb.openDB()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:132 +0x668
  github.com/syndtr/goleveldb/leveldb.Open()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:205 +0x274
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.22.5/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:651 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.fsParseNamePtr()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:674 +0x124
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).GetMeta.func1()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:339 +0xb8
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).GetMeta.func2()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:363 +0xb0
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).GetMeta()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/storage/file_storage.go:414 +0x638
  github.com/syndtr/goleveldb/leveldb.(*session).recover()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/session.go:140 +0xc0
  github.com/syndtr/goleveldb/leveldb.Open()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:191 +0xb0
  github.com/syndtr/goleveldb/leveldb.OpenFile()
      /Users/anacrolix/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20220614013038-64ee5596c38a/leveldb/db.go:227 +0x6c
  github.com/ethereum/go-ethereum/p2p/enode.newPersistentDB()
      /Users/anacrolix/go/pkg/mod/github.com/ethereum-optimism/op-geth@v1.101315.3-rc.1/p2p/enode/nodedb.go:100 +0x90
  github.com/ethereum/go-ethereum/p2p/enode.OpenDB()
      /Users/anacrolix/go/pkg/mod/github.com/ethereum-optimism/op-geth@v1.101315.3-rc.1/p2p/enode/nodedb.go:84 +0x64
  github.com/ethereum-optimism/optimism/op-node/p2p/cli.loadDiscoveryOpts()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/cli/load_config.go:175 +0x4ac
  github.com/ethereum-optimism/optimism/op-node/p2p/cli.NewConfig()
      /Users/anacrolix/optimism/src/optimism/op-node/p2p/cli/load_config.go:47 +0x204
  github.com/ethereum-optimism/optimism/op-node.NewConfig()
      /Users/anacrolix/optimism/src/optimism/op-node/service.go:56 +0x19c
  main.RollupNodeMain()
      /Users/anacrolix/optimism/src/optimism/op-node/cmd/main.go:82 +0x200
  main.main.LifecycleCmd.func1()
      /Users/anacrolix/optimism/src/optimism/op-service/cliapp/lifecycle.go:56 +0x1e8
  github.com/urfave/cli/v2.(*Command).Run()
      /Users/anacrolix/go/pkg/mod/github.com/urfave/cli/v2@v2.27.3/command.go:276 +0xeb4
  github.com/urfave/cli/v2.(*App).RunContext()
      /Users/anacrolix/go/pkg/mod/github.com/urfave/cli/v2@v2.27.3/app.go:333 +0xd98
  main.main()
      /Users/anacrolix/optimism/src/optimism/op-node/cmd/main.go:68 +0xb38
==================
```
</details>

Possibly related to https://github.com/ethereum-optimism/optimism/issues/8086#issuecomment-1804565448 but dubious.

### PR DESCRIPTION
**Pull request by anacrolix**
Fixes https://github.com/ethereum-optimism/optimism/issues/11328.

There's probably other races but I tested with these fixes and they went away.

I considered some more involved type parameter shenanigans but it wasn't worth it.

I snuck a generic constructor in to remove some of the boilerplate in creating recordsBooks.

### CODE REVIEW

**Comment by anacrolix** [comment]
I added fixes for the data races in the tests too.

File: op-node/p2p/store/peer_ban_book.go [hunk 1]
```diff
@@ -80,6 +76,8 @@ func (d *peerBanBook) SetPeerBanExpiration(id peer.ID, expirationTime time.Time)
 	if expirationTime == (time.Time{}) {
 		return d.book.deleteRecord(id)
 	}
+	d.book.Lock()
+	defer d.book.Unlock()
```
Comment (sebastianst) [inline op-node/p2p/store/peer_ban_book.go]: As you noted in another comment, we probably also want to include the delete in the lock.

File: op-node/p2p/store/ip_ban_book.go [hunk 2]
```diff
@@ -84,6 +80,9 @@ func (d *ipBanBook) SetIPBanExpiration(ip net.IP, expirationTime time.Time) erro
 	if expirationTime == (time.Time{}) {
 		return d.book.deleteRecord(ip.To16().String())
 	}
+	// Should these move up to include the delete?
+	d.book.Lock()
+	defer d.book.Unlock()
```
Comment (sebastianst) [inline op-node/p2p/store/ip_ban_book.go]: I think that makes sense, as deleting a write operation.

**Review by sebastianst — COMMENTED** [review]
For my understanding, you move the responsibility of locking around the `recordsBook` to the callers, by removing the mutex locking calls from the getters and setters? Why is that fixing the problem? Because some functions were reading from the returned value references and then returning a copy outside of the lock?

Are there now possibly other places where we need to add the explicit lock/unlock calls?

E.g. I see that there is `func (m *metadataBook) GetPeerMetadata(id peer.ID) (PeerMetadata, error)` which was already accessing the getter without a lock, would we want to read-lock here?

One pattern to force the callers of getters and setters to handle the mutex could be to leave the mutex locks in the public getters and setters, but then add additional getters and setters like
```go
func (d *recordsBook[K, V]) SetRecord(key K, diff recordDiff[V]) (V, error) {
	d.Lock()
	defer  d.Unlock()
	return d.setRecord(key, diff)
}

// SetRecordUnlocked locks the mutex and sets the record, but then returns with the mutex still locked, and the unlocker function. The caller must unlock the mutex by calling the unlocker, ideally in a defer statement.
func (d *recordsBook[K, V]) SetRecordUnlocked(key K, diff recordDiff[V]) (v V, err error, unlocker func()) {
	d.Lock()
	unlocker = func() { d.Unlock() }
	v, err = d.setRecord(key, diff)
	return
}
```
This way, using the public api, locked access would always be guaranteed and callers cannot accidentally forget about their responsibility to lock.

File: op-node/p2p/store/ip_ban_book.go (hunk 2 above)
Comment (anacrolix) [reply op-node/p2p/store/ip_ban_book.go]: I double checked. Because store and cache are both self-synchronized, it's "safe". However it's also possible to end up caching a value right after deleting it. I think putting the lock around this better overall.

**Comment by anacrolix** [comment]
> For my understanding, you move the responsibility of locking around the `recordsBook` to the callers, by removing the mutex locking calls from the getters and setters? Why is that fixing the problem? Because some functions were reading from the returned value references and then returning a copy outside of the lock?

Yes they're extracting values after they drop exclusive write access.

> Are there now possibly other places where we need to add the explicit lock/unlock calls?

There are a few places, but I didn't add them because I couldn't find any issues with them and I am trying to be conservative. I'll add them in a separate commit.

> E.g. I see that there is `func (m *metadataBook) GetPeerMetadata(id peer.ID) (PeerMetadata, error)` which was already accessing the getter without a lock, would we want to read-lock here?

Yeah that's one of the above.

> One pattern to force the callers of getters and setters to handle the mutex could be to leave the mutex locks in the public getters and setters, but then add additional getters and setters like
> 
> ```go
> func (d *recordsBook[K, V]) SetRecord(key K, diff recordDiff[V]) (V, error) {
> 	d.Lock()
> 	defer  d.Unlock()
> 	return d.setRecord(key, diff)
> }

I don't think it's worth the extra abstraction, the record book is already internal to the implementation.

> // SetRecordUnlocked locks the mutex and sets the record, but then returns with the mutex still locked, and the unlocker function. The caller must unlock the mutex by calling the unlocker, ideally in a defer statement.
> func (d *recordsBook[K, V]) SetRecordUnlocked(key K, diff recordDiff[V]) (v V, err error, unlocker func()) {
> 	d.Lock()
> 	unlocker = func() { d.Unlock() }
> 	v, err = d.setRecord(key, diff)
> 	return
> }
> ```
> 
> This way, using the public api, locked access would always be guaranteed and callers cannot accidentally forget about their responsibility to lock.

I considered passing an extractor/setter function to getRecord/setRecord to obtain what you want in the context of the book but again I don't think it's worth the abstraction because recordsBook is internal to all the wrappers and in the same package.

File: op-node/p2p/store/records_book.go [hunk 3]
```diff
@@ -80,26 +84,24 @@ func (d *recordsBook[K, V]) startGC() {
...
-	d.cache.Remove(key)
+	// If access to this isn't synchronized, removing from the cache first can result in the stored
+	// item being cached again before it is deleted.
 	err := d.store.Delete(d.ctx, d.dsKey(key))
+	d.cache.Remove(key)
 	if err == nil || errors.Is(err, ds.ErrNotFound) {
 		return nil
 	}
 	return fmt.Errorf("failed to delete entry with key %v: %w", key, err)
 }
```
Comment (tynes) [inline op-node/p2p/store/records_book.go:100]: Smal nit on godoc style - it usually starts with the name of the function as the first word in the description with an explanation of what the function does and anything extra somebody calling the function should know. This is not done perfectly throughout the codebase right now

File: op-node/p2p/store/records_book.go [hunk 4]
```diff
@@ -80,26 +84,24 @@ func (d *recordsBook[K, V]) startGC() {
...
 
+// You must read lock the recordsBook before calling this, and only unlock when you have extracted
+// the values you want from the value of type V. There's no way to conveniently pass an extractor
+// function parameterized on V here without breaking this out into a top-level function.
 func (d *recordsBook[K, V]) getRecord(key K) (v V, err error) {
 	if val, ok := d.cache.Get(key); ok {
```
Comment (tynes) [inline op-node/p2p/store/records_book.go:105]: Is there a reason as to why the lock cannot be grabbed internal to this function? That would remove the footgun around callers forgetting

File: op-node/p2p/store/records_book.go (hunk 3 above)
Comment (anacrolix) [reply op-node/p2p/store/records_book.go:100]: I think it was a mistake to recommend that style in Go. See https://groups.google.com/g/golang-nuts/c/_SuyQsr6tuA/m/rA-d07S9oh0J for some of the original benefits. I usually avoid naming the thing at all if I can. I can add it if you think it's better.

File: op-node/p2p/store/records_book.go (hunk 4 above)
Comment (anacrolix) [reply op-node/p2p/store/records_book.go:105]: Yeah see above, the reason is a pointer to the value is held after the function returns and then values extracted from it. The recordsBook is an internal type to the package anyway so it's harmless and clearer to allow callers to specify the kind of locking they need and when. (For example SetRecord also needs to lock with write permission, and then calls getRecord so that's a bad day if it locks internally).

**Comment by sebastianst** [comment]
> > For my understanding, you move the responsibility of locking around the `recordsBook` to the callers, by removing the mutex locking calls from the getters and setters? Why is that fixing the problem? Because some functions were reading from the returned value references and then returning a copy outside of the lock?
> 
> Yes they're extracting values after they drop exclusive write access.
> 

Since we now shift the responsibility of locking the records book to the surrounding code, I think it would be clearer to remove the mutex altogether from the `recordsBook` and have the calling structs maintain their own `bookMu sync.RWMutex` or so. It's a confusing pattern to put a mutex inside a struct, but then have the users of that struct maintain the locks. Usually the struct containing the mutex is responsible for maintaining the locks. This would also make it clearer that the records book is now by default _not_ concurrency safe, and if concurrency safety is needed, it's the surrounding code's responsibility to take care of it.

> > Are there now possibly other places where we need to add the explicit lock/unlock calls?
> 
> There are a few places, but I didn't add them because I couldn't find any issues with them and I am trying to be conservative. I'll add them in a separate commit.

Since we're fixing concurrent access to the book here, I think it's worth going over all read and write accesses to it, and its returned values, and guarantee consistent locking. If there is access to the book outside of concurrent code paths, then we can ignore locking of course.

**Comment by anacrolix** [comment]
It's kinda grown beyond what I originally planned but it's all technically correct, and it does still fix my original actual problem of data races in the p2p stuff (but now includes fixes to races in the tests to do with p2p, and a general fix to the incomplete locking in the recordsBook wrappers).

File: op-node/p2p/store/records_book.go (hunk 3 above)
Comment (sebastianst) [reply op-node/p2p/store/records_book.go:100]: We still follow that convention generally, but not perfectly, so I'd try in general to follow it. Since this is an internal function, it's not super important so I'm fine with either. We can have an internal discussion on whether we want to continue following it. At least for exported functions I think it's necessary to generate correct godoc and linters will fail otherwise.

File: op-node/p2p/pings.go [hunk 5]
```diff
@@ -41,7 +41,13 @@ type PingService struct {
...
 }
 
-func NewPingService(log log.Logger, ping PingFn, peers PeersFn, clock clock.Clock) *PingService {
+func NewPingService(
+	log log.Logger,
+	ping PingFn,
+	peers PeersFn,
+	clock clock.Clock,
+	trace func(work string),
+) *PingService {
```
Comment (sebastianst) [inline op-node/p2p/pings.go]: The `trace` field is only used in tests, in `op-node/p2p/pings_test.go`, so I think it's better to keep the old code to shield the `trace` from the public api and only set the field in the test manually. That's better than passing a `nil` in the prod code at `op-node/p2p/host.go`.

Comment (anacrolix) [reply op-node/p2p/pings.go]: This fixes an actual race because otherwise pingPeersBackground starts before the trace is set. I'll make a private constructor for the tests with the trace parameter.

Comment (anacrolix) [reply op-node/p2p/pings.go]: Fixed

**Review by tynes — APPROVED** [review]
I don't own this code but it generally looks good to me
