### PR TITLE
Fix reverse proxy setup in kurtosis

### LINKED ISSUE #16127: op-acceptor: L1 Network is not accessible when running under devnet-sdk
**Bug Description**
L1 Networks are not accessible when running under devnet-sdk on devstack.

**Steps to Reproduce**

Have a test with:

```
sys.L1Network.WaitForBlock()
```

**Expected behavior**
The Network should be accessible

**Logs:**
[Sample Run](https://discord.com/channels/1244729134312198194/1374114479163576493/1374453389890687047)

### PR DESCRIPTION
**Pull request by serpixel**
**Description**
Sometimes kurtosis would setup a non-working reverse proxy. This is because there always two networks setup, bridge and the kt-interop-devnet (or isthmus, etc) and kurtosis only sets up traefik to watch the first network (bridge, most of the times).

Additonally, ethereum-package configures the RPC endpoints as not having application_kind=http. This causes kurtosis to not assign them labels for traefik, which in turn makes these not available on the reverse proxy.

This PR patches the traefik configuration so that it also watches the second network, thus making the containers available for reverse proxy. Additionally, it adds a configuration for the L1 containers so that they can be accessed through the reverse proxy.

You can see all the containers detected by traefik in `http://127.0.0.1:9731/dashboard`

**Tests**

**Additional context**

**Metadata**

### CODE REVIEW

File: kurtosis-devnet/pkg/util/docker.go [hunk 1]
```diff
@@ -133,3 +176,558 @@ func DestroyDockerResources(ctx context.Context, enclave ...string) error {
...
+		return fmt.Errorf("failed to recreate container: %w", err)
+	}
+
+	fmt.Printf("Created new Traefik container: %s\n", newContainer.ID[:12])
+	for _, networkName := range networks {
+		if err := apiClient.NetworkConnect(ctx, networkName, newContainer.ID, nil); err != nil {
+			return fmt.Errorf("failed to connect to network %s: %w", networkName, err)
+		}
+	}
+	time.Sleep(3 * time.Second)
```
Comment (janjakubnanista) [inline kurtosis-devnet/pkg/util/docker.go]: This don't look so good, why the `sleep`?

File: kurtosis-devnet/pkg/util/docker.go [hunk 2]
```diff
@@ -133,3 +176,558 @@ func DestroyDockerResources(ctx context.Context, enclave ...string) error {
...
+    address: ":9730"
+  traefik:
+    address: ":9731"
+
+providers:
+`)
+
+	for _, net := range networks {
+		// Only include Kurtosis networks (skip bridge, host, none)
+		if !strings.HasPrefix(net.Name, "kt-") {
```
Comment (janjakubnanista) [inline kurtosis-devnet/pkg/util/docker.go]: I would then revert the condition since you have a known list of the negative cases:

```go
switch net.Name {
 case "bridge", "host", "none":
   continue
}
```

**Review by janjakubnanista — CHANGES_REQUESTED** [review]

File: kurtosis-devnet/pkg/util/docker.go (hunk 1 above)
Comment (serpixel) [reply kurtosis-devnet/pkg/util/docker.go]: Removed it 👍

**Review by janjakubnanista — APPROVED** [review]
