### PR TITLE
cannon: Add more 64-bit tests

### LINKED ISSUE #12598: Cannon64: Migrate 32-bit tests to be forward-compatible
## Description

After enabling 64-bit tests in CI (https://github.com/ethereum-optimism/optimism/issues/12252),  which will likely involve skipping failing tests temporarily, rework failing 32-bit tests to be forward-compatible with 64-bit Cannon. 

When this ticket is complete, we should no longer be skipping any relevant tests for the 64-bit VM.

### PR DESCRIPTION
**Pull request by Inphi**
Add differential tests for 64-bit functionality. This modifies the `TestEVM...` and `FuzzState...` tests in two ways:

- Fixing existing 32-bit tests to be also compatible with cannon64.
- Creating 64-bit specific implementations based on existing 32-bit tests

The latter approach is used for tests that have noticeable different behavior (usually due to full-word register ops and sign-extension). So most of the changes here is a refactor the existing test setups so they can be used by the cannon32 and cannon64 tests.
The tests suffixed with `32` run only on `cannon32` builds. While tests suffixed with `64` run only on `cannon64`. The rest run on both 32/64-bit VMs.

The complete list of tests updated can be found using  `go test -tags=cannon64 -list=. ./mipsevm/tests/... | grep -E '(TestEVM|FuzzState)' | sort`:

FuzzStateConsistencyMulOp
FuzzStateConsistencyMultOp
FuzzStateConsistencyMultuOp
FuzzStateHintRead
FuzzStateHintWrite
FuzzStatePreimageRead
FuzzStatePreimageWrite
FuzzStateSyscallBrk
FuzzStateSyscallCloneMT
FuzzStateSyscallExitGroup
FuzzStateSyscallFcntl
FuzzStateSyscallMmap
TestEVM_ClaimProgram
TestEVM_EmptyThreadStacks
TestEVM_EntryProgram
TestEVM_Fault
TestEVM_HelloProgram
TestEVM_MMap
TestEVM_MT64_LL
TestEVM_MT64_LLD
TestEVM_MT64_SC
TestEVM_MT64_SCD
TestEVM_MT_LL
TestEVM_MT_SC
TestEVM_MT_StoreOpsClearMemReservation32
TestEVM_MT_StoreOpsClearMemReservation64
TestEVM_MT_SysRead_Preimage32
TestEVM_MT_SysRead_Preimage64
TestEVM_NoopSyscall32
TestEVM_NoopSyscall64
TestEVM_NormalTraversalStep_HandleWaitingThread
TestEVM_NormalTraversal_Full
TestEVM_OpenMIPS
TestEVM_PopExitedThread
TestEVM_SchedQuantumThreshold
TestEVM_SingleStep_Bitwise32
TestEVM_SingleStep_Bitwise64
TestEVM_SingleStep_Branch32
TestEVM_SingleStep_Branch64
TestEVM_SingleStep_Jump
TestEVM_SingleStep_LoadStore32
TestEVM_SingleStep_LoadStore64
TestEVM_SingleStep_MfhiMflo
TestEVM_SingleStep_MovzMovn
TestEVM_SingleStep_MthiMtlo
TestEVM_SingleStep_MulDiv
TestEVM_SingleStep_MulDiv64
TestEVM_SingleStep_Operators
TestEVM_SingleStep_Operators64
TestEVM_SingleStep_Shift64
TestEVM_SysClockGettimeMonotonic
TestEVM_SysClockGettimeNonMonotonic
TestEVM_SysClockGettimeRealtime
TestEVM_SysClone_FlagHandling
TestEVM_SysClone_Successful
TestEVM_SysExit
TestEVM_SysFutex_UnsupportedOp
TestEVM_SysFutex_WaitPrivate
TestEVM_SysFutex_WakePrivate
TestEVM_SysGetPID
TestEVM_SysGetTID
TestEVM_SysNanosleep
TestEVM_SysOpen
TestEVM_SysWriteHint
TestEVM_SysYield
TestEVM_UnsupportedSyscall32
TestEVM_UnsupportedSyscall64
TestEVM_WakeupTraversalStep
TestEVM_WakeupTraversal_Full
TestEVM_WakeupTraversal_WithExitedThreads

## Meta

Fixes https://github.com/ethereum-optimism/optimism/issues/12598

### CODE REVIEW

File: cannon/mipsevm/tests/fuzz_evm_common_test.go [hunk 1]
```diff
@@ -270,15 +225,7 @@ func doFuzzStateHintRead(f *testing.F) {
...
-}
-
-func FuzzStatePreimageRead64(f *testing.F) {
-	doFuzzStatePreimageRead(f)
-}
-
-func doFuzzStatePreimageRead(f *testing.F) {
+func FuzzStatePreimageRead(f *testing.F) {
 	versions := GetMipsVersionTestCases(f)
 	f.Fuzz(func(t *testing.T, addr arch.Word, pc arch.Word, count arch.Word, preimageOffset arch.Word, seed int64) {
```
Comment (mbaxter) [inline cannon/mipsevm/tests/fuzz_evm_common_test.go:230]: When I tried to run these previously across 32- and 64-bit vms I was getting errors like:
```
mismatched types in corpus entry: [uint64 uint64 uint64 uint64 int64], want [uint32 uint32 uint32 uint32 int64]
```
But now it seems to run fine - any idea why?  I don't actually see any new fuzzdata persisted in the normal directory  but I don't see why its behaving differently.

File: cannon/mipsevm/tests/testfuncs_test.go [hunk 2]
```diff
@@ -0,0 +1,502 @@
...
+
+// randomizeUpperWord is used to assert that 32-bit operations use the lower word only
+func randomizeUpperWord(w Word) Word {
+	if arch.IsMips32 {
+		return w
+	} else {
+		if w>>32 == 0x0 { // nolint:staticcheck
+			rnd := rand.Uint32()
+			mask := (uint64(rnd) << 32) | 0xFF_FF_FF_FF
+			return Word((uint64(w) | (0xFF_FF_FF_FF << 32)) & mask)
```
Comment (mbaxter) [inline cannon/mipsevm/tests/testfuncs_test.go]: (nit) The mask terminology is a little confusing - what about something like?:
```suggestion
			upper := Word(uint64(rnd) << 32) 
			return upper | w
```

File: cannon/mipsevm/tests/evm_common64_test.go [hunk 3]
```diff
@@ -93,52 +83,27 @@ func TestEVMSingleStep_Operators64(t *testing.T) {
...
+	cases := []operatorTestCase{
+		{name: "and", funct: 0x24, isImm: false, rs: Word(1200), rt: Word(490), expectRes: Word(160)},                          // and t0, s1, s2
+		{name: "andi", opcode: 0xc, isImm: true, rs: Word(4), rt: Word(1), imm: uint16(40), expectRes: Word(0)},                // andi t0, s1, 40
+		{name: "or", funct: 0x25, isImm: false, rs: Word(1200), rt: Word(490), expectRes: Word(1530)},                          // or t0, s1, s2
+		{name: "ori", opcode: 0xd, isImm: true, rs: Word(4), rt: Word(1), imm: uint16(40), expectRes: Word(44)},                // ori t0, s1, 40
+		{name: "xor", funct: 0x26, isImm: false, rs: Word(1200), rt: Word(490), expectRes: Word(1370)},                         // xor t0, s1, s2
+		{name: "xori", opcode: 0xe, isImm: true, rs: Word(4), rt: Word(1), imm: uint16(40), expectRes: Word(44)},               // xori t0, s1, 40
+		{name: "nor", funct: 0x27, isImm: false, rs: Word(0x4b0), rt: Word(0x1ea), expectRes: Word(0xFF_FF_FF_FF_FF_FF_FA_05)}, // nor t0, s1, s2
+		{name: "nor", funct: 0x27, isImm: false, rs: Word(0x4b0), rt: Word(0x1ea), expectRes: Word(0xFF_FF_FF_FF_FF_FF_FA_05)}, // nor t0, s1, s2
```
Comment (mbaxter) [inline cannon/mipsevm/tests/evm_common64_test.go]: This test case looks like a duplicate

File: cannon/mipsevm/tests/evm_common_test.go [hunk 4]
```diff
@@ -1010,25 +854,16 @@ func TestEntryEVM(t *testing.T) {
...
+	testutil.Cannon32OnlyTest(t, "These tests are fully covered for 64-bits in TestEVM_SingleStep_Branch64")
+	t.Parallel()
+	cases := []branchTestCase{
 		// blez
 		{name: "blez", pc: 0, opcode: 0x6, rs: 0x5, offset: 0x100, expectNextPC: 0x8},
 		{name: "blez large rs", pc: 0x10, opcode: 0x6, rs: 0x7F_FF_FF_FF, offset: 0x100, expectNextPC: 0x18},
 		{name: "blez zero rs", pc: 0x10, opcode: 0x6, rs: 0x0, offset: 0x100, expectNextPC: 0x414},
 		{name: "blez sign rs", pc: 0x10, opcode: 0x6, rs: -1, offset: 0x100, expectNextPC: 0x414},
-		{name: "blez rs only sign bit set", pc: 0x10, opcode: 0x6, rs: testutil.ToSignedInteger(0x80_00_00_00), offset: 0x100, expectNextPC: 0x414},
+		{name: "bexpectRevertlez rs only sign bit set", pc: 0x10, opcode: 0x6, rs: testutil.ToSignedInteger(0x80_00_00_00), offset: 0x100, expectNextPC: 0x414},
```
Comment (mbaxter) [inline cannon/mipsevm/tests/evm_common_test.go]: oops - looks like a find/replace typo :D
```suggestion
		{name: "blez rs only sign bit set", pc: 0x10, opcode: 0x6, rs: testutil.ToSignedInteger(0x80_00_00_00), offset: 0x100, expectNextPC: 0x414},
```

File: cannon/mipsevm/tests/evm_multithreaded64_test.go [hunk 5]
```diff
@@ -360,3 +363,125 @@ func TestEVM_MT64_SCD(t *testing.T) {
...
+		{name: "Store word left", opcode: 0b10_1010, base: 0xFF_00_00_00, offset: 0x10, effAddr: 0xFF_00_00_10, preMem: ^Word(0), postMem: 0x12_34_56_78_FF_FF_FF_FF},
+		{name: "Store word left lower", opcode: 0b10_1010, base: 0xFF_00_00_00, offset: 0x14, effAddr: 0xFF_00_00_10, preMem: ^Word(0), postMem: 0xFF_FF_FF_FF_12_34_56_78},
+		{name: "Store word", opcode: 0b10_1011, base: 0xFF_00_00_00, offset: 0x10, effAddr: 0xFF_00_00_10, preMem: ^Word(0), postMem: 0x12_34_56_78_FF_FF_FF_FF},
+		{name: "Store word lower", opcode: 0b10_1011, base: 0xFF_00_00_00, offset: 0x14, effAddr: 0xFF_00_00_10, preMem: ^Word(0), postMem: 0xFF_FF_FF_FF_12_34_56_78},
+		{name: "Store word right", opcode: 0b10_1110, base: 0xFF_00_00_00, offset: 0x10, effAddr: 0xFF_00_00_10, preMem: ^Word(0), postMem: 0x78_FF_FF_FF_FF_FF_FF_FF},
+		{name: "Store word right lower", opcode: 0b10_1110, base: 0xFF_00_00_00, offset: 0x14, effAddr: 0xFF_00_00_10, preMem: ^Word(0), postMem: 0xFF_FF_FF_FF_78_FF_FF_FF},
+	}
+	preimageValue := make([]byte, 0, 8)
+	preimageValue = binary.BigEndian.AppendUint32(preimageValue, 0x12_34_56_78)
+	preimageValue = binary.BigEndian.AppendUint32(preimageValue, 0x98_76_54_32)
```
Comment (mbaxter) [inline cannon/mipsevm/tests/evm_multithreaded64_test.go]: Looks like dead code here?

File: cannon/mipsevm/tests/testfuncs_test.go [hunk 6]
```diff
@@ -0,0 +1,502 @@
...
+	rs           Word
+	rt           Word
+	funct        uint32
+	opcode       uint32
+	expectHi     Word
+	expectLo     Word
+	expectRes    Word
+	rdReg        uint32
+	expectRevert string
+	errMsg       string
```
Comment (mbaxter) [inline cannon/mipsevm/tests/testfuncs_test.go]: (nit) Naming nits - the meaning of these is a little confusing given how they're handled in the test.  Maybe:
```suggestion
	panicMsg        string
	revertMsg       string
```

File: cannon/mipsevm/tests/evm_common_test.go [hunk 7]
```diff
@@ -20,7 +20,9 @@ import (
 	"github.com/ethereum-optimism/optimism/cannon/mipsevm/testutil"
 )
 
-func TestEVM(t *testing.T) {
+func TestEVM_OpenMIPS(t *testing.T) {
+	testutil.Cannon32OnlyTest(t, "Skipping MIPS32 assembly test vectors for cannon64")
```
Comment (mbaxter) [inline cannon/mipsevm/tests/evm_common_test.go:24]: Are these OpenMIPS tests are failing because they're compiled for 32-bit?  Should we add a follow-up ticket that compiles them for 64-bit?

**Review by mbaxter — APPROVED** [review]

File: cannon/mipsevm/tests/fuzz_evm_common_test.go (hunk 1 above)
Comment (Inphi) [reply cannon/mipsevm/tests/fuzz_evm_common_test.go:230]: This occurs when running the same fuzz test for different builds and one of them fails. So clearing out the cached corpus should resolve.

I think there are other fuzz directories Go uses as a cache. I've seen corpuses in /tmp, in addition to the cwd, that are incompatible with the fuzz test. I don't know when and why Go uses either directory.

File: cannon/mipsevm/tests/evm_common_test.go (hunk 7 above)
Comment (Inphi) [reply cannon/mipsevm/tests/evm_common_test.go:24]: They are failing for various reasons, including 64-bit misaligned return addresses and mips32 syscall abi usage.

However, I don't think it's worth it to port these to 64-bits. The diff tests are more comprehensive than openmips. So once mips64 is the default vm, we should delete the openmips test vectors.
