### PR TITLE
op-conductor: Remove block time check for unsafe head progress

### LINKED ISSUE #14585: OP-Conductor health check ignores the `OP_CONDUCTOR_HEALTHCHECK_UNSAFE_INTERVAL` configuration option
**Bug Description**

The op-conductor health check ignores the `OP_CONDUCTOR_HEALTHCHECK_UNSAFE_INTERVAL` configuration option.

**Steps to Reproduce**

To exacerbate the problem for reproducibility's sake start a local devnet with a 1 second block time and `OP_CONDUCTOR_HEALTHCHECK_UNSAFE_INTERVAL` set to 60 seconds. Give the batcher a max time of 1.5 hours.

In the conductor logs you will find:

```
t=2025-02-27T22:12:39+0000 lvl=error msg="unsafe head is not progressing as expected" now=1740694359 unsafe_head_num=522782 last_seen_unsafe_num=522782 last_seen_unsafe_time=1740694357 unsafe_interval=60 time_diff=2 block_diff=0 expected_blocks=1
```

And then the conductor will select a new leader. You will notice that op-conductor fails over to new sequencers alarmingly often.

**Expected behavior**

There should be no sequencer failover.

In the example above op-conductor evaluates that it expected 1 block and got 0 so it should pick a new leader. This ignores the `OP_CONDUCTOR_HEALTHCHECK_UNSAFE_INTERVAL` option which should allow the sequencer to be up to 60 seconds behind.

**Environment Information:**

- Operating System: Ubuntu 20.04.6 LTS (Focal Fossa)
- Package Version (or commit hash): op-node v1.10.2, op-conductor v0.2.0

**Configurations:**

OP_CONDUCTOR_HEALTHCHECK_INTERVAL: "1"
OP_CONDUCTOR_HEALTHCHECK_MIN_PEER_COUNT: "1"
OP_CONDUCTOR_HEALTHCHECK_UNSAFE_INTERVAL: "60"

**Logs:**

```
t=2025-02-27T22:12:39+0000 lvl=error msg="unsafe head is not progressing as expected" now=1740694359 unsafe_head_num=522782 last_seen_unsafe_num=522782 last_seen_unsafe_time=1740694357 unsafe_interval=60 time_diff=2 block_diff=0 expected_blocks=1
```

**Additional context**

This [PR](https://github.com/ethereum-optimism/optimism/pull/9248) introduced the bug in the health check.

### PR DESCRIPTION
**Pull request by dpulitano**
**Description**

Addresses the issue reported in https://github.com/ethereum-optimism/optimism/issues/14585 where op-conductor's UNSAFE_INTERVAL is effectively ignored in health checks whenever it is larger than the block time. 

The agreed on solution is to remove the health check that enforces sequencers create blocks in a span no longer than the block time, so the UNSAFE_INTERVAL check gets used

**Tests**

Updating `TestUnhealthyUnsafeHeadNotProgressing` to expect the monitor to return no error for each second that passes without an unsafe head update -- until **after** `unsafeBlocksInterval` time passes.

Also renaming the variable name `healthy` to `healthFailure` in that test suite to help with clarity

**Additional context**

**Metadata**

Fixes #14585

### CODE REVIEW

File: op-conductor/health/monitor_test.go [hunk 1]
```diff
@@ -105,21 +105,23 @@ func (s *HealthMonitorTestSuite) TestUnhealthyUnsafeHeadNotProgressing() {
 
 	rc := &testutils.MockRollupClient{}
 	ss1 := mockSyncStatus(now, 5, now-8, 1)
-	for i := 0; i < 5; i++ {
+	unsafeBlocksInterval := 10
+	for i := 0; i < unsafeBlocksInterval+2; i++ {
```
Comment (dpulitano) [inline op-conductor/health/monitor_test.go:109]: The reason for the extra tick past unsafeBlocksInterval + 1 is just that the "unsafe head is falling behind the unsafe interval" log message isn't displayed until the last tick and it's nice to see that when running locally.

**Review by 0x00101010 — APPROVED** [review]

**Review by zhwrd — APPROVED** [review]
