### PR TITLE
op-proposer: (DFG) skip new game creation if outputRoot is unchanged

### LINKED ISSUE #13262: op-proposer: create new game fail if outputRoot is unchanged
**Bug Description**

In a staging environment with permissioned fault proofs, when no transactions are received for a period longer than `proposal-interval`, the proposer transaction fails with `GameAlreadyExists`. The op-proposer logs show this error repeating every proposal-interval:

```shell
msg="Failed to send proposal transaction" err="failed to create the tx: operation failed permanently after 30 attempts: failed to estimate gas: execution reverted, reason: 0x014f6fe5b1915a2b357e091ddbe16c95c0ca28488326b894aa1dbc7ca249712ce2ba619a" l1blocknum=7210390 l1blockhash=0x443ccd38f29b4971458d4519c56ef7eae1cdc0e2375bba58581638ec78f7ed8b l1head=7210400
```

**Steps to Reproduce**

Run `op-prosposer` with permissioned fault proof and don't send transactions.

**Expected behavior**

The op-proposer should:

1. Check if the new outputRoot matches the latest output from DGF
2. If they match:
- Log a debug message 
- return `shouldPropose = false`
3. Skip proposal attempt instead of failing with GameAlreadyExists

**Environment Information:**

**Configurations:**

**Logs:**

**Additional context**

I've committed a potential fix here: [Commit](https://github.com/PierreOssun/optimism/commit/da7a97023d0e713ee9ee79a177f538e310442d07#diff-80c3f3adf66ddb226563d36a0cd6bcd1220d22e123364eefa3fb624377730372L87)
Please have a look and I will add tests and open PR after your first look

Thanks

### PR DESCRIPTION
**Pull request by PierreOssun**
**Description**

Fixes #13262
The goal is to prevent proposer to dispatch a call to create a new game, when the outpurRoot queired from the latest game is unchanged (no value in proposing the same output root again)

**Tests**

Added `claim` checks on tests.

### CODE REVIEW

File: op-proposer/contracts/disputegamefactory.go [hunk 1]
```diff
@@ -137,11 +138,13 @@ func (f *DisputeGameFactory) gameAtIndex(ctx context.Context, idx uint64) (gameM
 	}
 	// We don't need most of the claim data, only the claimant which is the game proposer
```
Comment (ajsutton) [inline op-proposer/contracts/disputegamefactory.go]: nit: Should update this comment since we now load the claimant and the claim.

File: op-proposer/proposer/driver.go [hunk 2]
```diff
@@ -296,6 +295,13 @@ func (l *L2OutputSubmitter) FetchDGFOutput(ctx context.Context) (*eth.OutputResp
 		return nil, false, fmt.Errorf("could not fetch output at current block number %d: %w", currentBlockNumber, err)
 	}
 
+	if claim == output.StateRoot {
```
Comment (ajsutton) [inline op-proposer/proposer/driver.go]: This is the wrong comparison. The `StateRoot` is the world state root but the proposal is actually the `output.OutputRoot`.

**Review by ajsutton — COMMENTED** [review]
Sorry for the slow review - looks good except that it needs to change the value being compared.

**Comment by PierreOssun** [comment]
Thanks for the review @ajsutton, pushed your comments

File: op-proposer/proposer/driver.go [hunk 3]
```diff
@@ -296,6 +295,13 @@ func (l *L2OutputSubmitter) FetchDGFOutput(ctx context.Context) (*eth.OutputResp
 		return nil, false, fmt.Errorf("could not fetch output at current block number %d: %w", currentBlockNumber, err)
 	}
 
+	if claim == common.Hash(output.OutputRoot) {
+		l.Log.Debug("Skipping proposal: output root unchanged since last porposed game", "last proposed claim", claim, "output_root", output.StateRoot)
```
Comment (ajsutton) [inline op-proposer/proposer/driver.go]:
```suggestion
		l.Log.Debug("Skipping proposal: output root unchanged since last proposed game", "last_proposed_root", claim, "output_root", output.OutputRoot)
```

**Review by ajsutton — APPROVED** [review]
LGTM, just a small fix for logs.

**Comment by ajsutton** [comment]
/ci authorize https://github.com/ethereum-optimism/optimism/pull/13288/commits/8c001bf77cb852041b90a8fe7f2e2d3134c8b7ec

**Comment by ajsutton** [comment]
Merged in latest develop to see if that fixes the fuzz test failure. It doesn't seem related to these changes.

**Comment by ajsutton** [comment]
/ci authorize https://github.com/ethereum-optimism/optimism/pull/13288/commits/bd1fb2a35e671cfb54e69b949aca0a56c64a5271

**Comment by PierreOssun** [comment]
@ajsutton merged develop branch again. Can you try CI again ?
