### PR TITLE
`op-chain-ops`:  invert lookup from chainID to superchain

### LINKED ISSUE #9202: `op-version-check`: cannot get addresses for internal devnet
**Describe the bug**
Running `op-version-check` against the internal devnet fails with "Ignoring L1/L2"

**To Reproduce**

```
> L1_RPC_URLS=https://ethereum-goerli.publicnode.com L2_RPC_URLS=<internal-devnet-rpc> ./bin/op-version-check
INFO [01-26|11:44:01.034] Ignoring L1/L2                           l1-chain-id=5 l2-chain-id=997
[]
```

**Expected behavior**
The tool should printthe contract version information correctly with the above input. 
```
>  L1_RPC_URLS=https://ethereum-goerli.publicnode.com L2_RPC_URLS=<internal-devnet-rpc> ./bin/op-version-check
WARN [01-26|11:46:46.087] goerli
WARN [01-26|11:46:46.087] goerli-dev-0
INFO [01-26|11:46:46.087] OP Labs devnet 0                         l1-chain-id=5 l2-chain-id=997
INFO [01-26|11:46:46.087] Detecting on chain contracts
INFO [01-26|11:46:46.605] Successfully processed contract versions chain="OP Labs devnet 0" l1-chain-id=5 l2-chain-id=997
[
  {
    "Name": "OP Labs devnet 0",
    "ChainID": 997,
    "Contracts": {
      "AddressManager": {
        "Version": "null",
        "Address": "0xf3a31b72d030e1916afeb3abba90e7e104818b9b"
      },
      "L1CrossDomainMessenger": {
        "Version": "1.1.0",
        "Address": "0x12371d047382bb3a4b1891e8474ddaee983d08ec"
      },
      "L1ERC721Bridge": {
        "Version": "1.1.0",
        "Address": "0xab598ffd07bdf497fce58e36138573ccba6b7a8b"
      },
      "L1StandardBridge": {
        "Version": "1.1.0",
        "Address": "0x0178b1f72eb1e61e1847f8fd36c791822623fb42"
      },
      "L2OutputOracle": {
        "Version": "1.2.0",
        "Address": "0xddb2e0c86ae08f1249d528f1a810cebd1b4c4d72"
      },
      "OptimismMintableERC20Factory": {
        "Version": "1.1.0",
        "Address": "0x00b75ed2e46c4c29bc363a75a6d97791018b3903"
      },
      "OptimismPortal": {
        "Version": "1.2.0",
        "Address": "0xc6170e048b7daef6d0b6cbbad9aca0e5370ddbbc"
      },
      "ProxyAdmin": {
        "Version": "null",
        "Address": "0xd98bd7a1f2384d890d0d6153cb6f813ab6ccfccf"
      },
      "SystemConfig": {
        "Version": "1.0.1",
        "Address": "0x78c9876a3621b97cc9b3c13ad0f35091db49e8e3"
      }
    }
  }
]
```

**Additional context**

 I think the underlying issue is tied to looking up superchain name from L1 chain id. There are technically two superchains on Goerli, so such a lookup can't work in all cases: 

https://github.com/ethereum-optimism/optimism/blob/1eb56be09f45a996a144509e5bb9bd63045a8b57/op-chain-ops/cmd/op-version-check/main.go#L108

### PR DESCRIPTION
**Pull request by geoknee**
**Description**
Replaces `ToSuperchainName(chainID uint64) (string, error)` utility with `SuperChainID(superchain string) (uint64, error)` and makes follow-on changes.

**Tests**
I manually verified that this fixes #9209

**Additional context**

There can be (and are) more than one superchain with a given id. Conversely, each superchain will have exactly one id.

**Metadata**

- Fixes #9202

### CODE REVIEW

**Review by mslipper — APPROVED** [review]
LGTM

File: op-chain-ops/upgrades/check.go [hunk 1]
```diff
@@ -123,16 +123,17 @@ func cmpVersion(v1, v2 string) bool {
...
-	if chainID == 5 {
-		return "goerli", nil
-	}
-	if chainID == 11155111 {
-		return "sepolia", nil
-	}
-	return "", fmt.Errorf("unsupported chain ID %d", chainID)
+// SuperChainID returns the chain ID for the supplied superchain name, or an error
+// if no such superchain is known.
+func SuperChainID(superchain string) (uint64, error) {
```
Comment (tynes) [inline op-chain-ops/upgrades/check.go]: This function is a bit of duct tape, this functionality should ideally live in the registry, like if a new target is added then we may forget to update this and there are no checks on this function in CI

Comment (geoknee) [reply op-chain-ops/upgrades/check.go]: Agreed. I removed this in [b3e4bbf](https://github.com/ethereum-optimism/optimism/pull/9203/commits/b3e4bbfd60bd3267542f4cc9cea2447cb36db621).

**Review by tynes — APPROVED** [review]
Looks good to me altho i haven't ran it

File: op-chain-ops/cmd/op-upgrade/main.go [hunk 2]
```diff
@@ -79,11 +79,11 @@ func entrypoint(ctx *cli.Context) error {
 	}
 
 	superchainName := ctx.String("superchain-target")
-	if superchainName == "" {
-		superchainName, err = upgrades.ToSuperchainName(l1ChainID.Uint64())
-		if err != nil {
-			return err
-		}
+	declaredChainID := superchain.Superchains[superchainName].Config.L1.ChainID
```
Comment (refcell) [inline op-chain-ops/cmd/op-upgrade/main.go]: If the specified `superchain-target` DNE, this is going to panic. Perhaps it'd make more sense to check for existence and gracefully error here?
```suggestion
    declaredSuperchain, ok := superchain.Superchains[superchainName]
    if !ok {
        return fmt.Errorf("superchain-target %s not registered", superchainName)
    }
	declaredChainID := declaredSuperchain.Config.L1.ChainID
```

File: op-chain-ops/cmd/op-version-check/main.go [hunk 3]
```diff
@@ -105,12 +105,9 @@ func entrypoint(ctx *cli.Context) error {
 				return fmt.Errorf("cannot fetch L1 chain ID: %w", err)
 			}
 
-			superchainName, err := upgrades.ToSuperchainName(l1ChainID.Uint64())
-			if err != nil {
-				return fmt.Errorf("error getting superchain name: %w", err)
-			}
+			declaredL1ChainID := superchain.Superchains[chainConfig.Superchain].Config.L1.ChainID
```
Comment (refcell) [inline op-chain-ops/cmd/op-version-check/main.go]: ibid, check for existence?

File: op-chain-ops/cmd/op-upgrade/main.go (hunk 2 above)
Comment (geoknee) [reply op-chain-ops/cmd/op-upgrade/main.go]: Good shout. [7c8bd5d](https://github.com/ethereum-optimism/optimism/pull/9203/commits/7c8bd5da12772f65f40dbe04b1c17ba6e4c7fb09)

File: op-chain-ops/cmd/op-version-check/main.go (hunk 3 above)
Comment (geoknee) [reply op-chain-ops/cmd/op-version-check/main.go]: [7c8bd5d](https://github.com/ethereum-optimism/optimism/pull/9203/commits/7c8bd5da12772f65f40dbe04b1c17ba6e4c7fb09)
