### PR TITLE
op-batcher: add `TestBatchSubmitter_sendTx_FloorDataGas` and patch `driver.sendTx`

### LINKED ISSUE #14513: op-batcher doesn't take into account pectra gas floor when posting calldata
**Bug Description**
After the holesky hard fork our batcher that uses a custom DA (so only posts a few bytes per tx) started getting this error:
```
t=2025-02-24T23:18:31+0000 lvl=warn msg="Failed to create a transaction, will retry" service=batcher err="failed to call: err: insufficient gas for floor data gas cost: have 21592, want 22480 (supplied gas 21592), reason: <nil>"
```

**Steps to Reproduce**
Try to send a batcher tx with 37 bytes as data

**Expected behavior**
Transaction is created properly
**Environment Information:**
Fraxtal op-batcher based on v1.11.1

**Additional context**

I've [copied](https://github.com/FraxFinance/fraxtal/commit/a09fd6ba27fee24e88f02819643bd36eadc76bfc) the go-ethereum `FloorDataGas` function and used that as a min gaslimit when sending the tx and the issue was resolved

### PR DESCRIPTION
**Pull request by geoknee**
Closes #14513

### CODE REVIEW

File: op-batcher/batcher/driver.go [hunk 1]
```diff
@@ -867,9 +873,34 @@ func (l *BatchSubmitter) sendTx(txdata txData, isCancel bool, candidate *txmgr.T
 		candidate.GasLimit = intrinsicGas
 	}
 
+	floorDataGas, err := floorDataGas(candidate.TxData)
+	if err == nil && floorDataGas > candidate.GasLimit {
+		candidate.GasLimit = floorDataGas
+	}
```
Comment (sebastianst) [inline op-batcher/batcher/driver.go]: This works as a quick fix. We could add more logging to not silently ignore errors, like I just did in https://github.com/ethereum-optimism/optimism/commit/6d31e62e9ee6490da6e4548f4993ebf5149a750b

File: op-batcher/batcher/driver.go [hunk 2]
```diff
@@ -867,9 +873,34 @@ func (l *BatchSubmitter) sendTx(txdata txData, isCancel bool, candidate *txmgr.T
...
+
 	queue.Send(txRef{id: txdata.ID(), isCancel: isCancel, isBlob: txdata.asBlob}, *candidate, receiptsCh)
 }
 
+// Copypaste from upstream geth
+// TODO replace with import once it's available https://github.com/ethereum-optimism/op-geth/pull/507
```
Comment (sebastianst) [inline op-batcher/batcher/driver.go]:
```suggestion
// TODO remove in #14500
```
I'll do it in my upstream merge.

File: op-batcher/batcher/driver.go (hunk 1 above)
Comment (geoknee) [reply op-batcher/batcher/driver.go]: [9c05eca](https://github.com/ethereum-optimism/optimism/pull/14517/commits/9c05eca088d4f39029ca2e0650a198e190c54ca4)

**Review by sebastianst — APPROVED** [review]

**Comment by sebastianst** [comment]
There are several other places where we compute the gas limit and still only use the intrinsic gas. I will fix it everywhere in #14500.

**Review by sebastianst — COMMENTED** [review]
I just realize that we can probably just _replace_ the usage of `IntrinsicGas` with that of `FloorDataGas` everywhere where we estimate the gas limit for calldata-only batcher txs.
