### PR TITLE
fix(op-supernode): guard chain container vn against torn interface read

### LINKED ISSUE #19573: op-supernode: simpleChainContainer.vn field accessed without synchronization
## Summary

The `c.vn` field on `simpleChainContainer` is a plain pointer accessed from multiple goroutines without mutex protection or `atomic.Pointer`. This is a data race.

## Details

**Writers:**
- `Start()` restart loop goroutine — assigns `c.vn` when creating a new VirtualNode

**Readers (from other goroutines):**
- `PauseAndStopVN()` — reads `c.vn` to call Stop
- `Stop()` — reads `c.vn` to call Stop
- `SyncStatus()` — reads `c.vn`

The flow control uses atomic bools (`pause`, `stop`) which create memory barriers, but there is a check-then-act window between setting the pause flag and reading `c.vn`. For example, in `PauseAndStopVN`:

```go
c.Pause(ctx)       // sets pause=true
if c.vn == nil {   // reads c.vn — but Start() may have just assigned a new VN
    return nil
}
return c.vn.Stop() // could be a different VN than what was checked
```

Between `Pause()` and the `c.vn` read, the restart loop can create and assign a fresh VN (line 212 in `Start()`), then see the pause flag and sleep. The caller then stops this new VN, but the loop can wake and create yet another.

## Why it hasn't caused failures yet

1. `VirtualNode.Stop()` is idempotent (internal mutex, returns nil if already stopped)
2. Go GC prevents use-after-free on the old pointer
3. The window is very small in practice
4. The restart loop checks pause immediately after VN creation

## Suggested fix

Protect `c.vn` with a `sync.Mutex` or use `atomic.Pointer[virtual_node.VirtualNode]` (Go 1.19+). The mutex approach is simpler since `Start()` already holds the only write path.

## Context

Found during review of #19571. The `Stop()` method has the same pre-existing pattern — `PauseAndStopVN` just inherits it. Not a regression, but worth fixing.

**File:** `op-supernode/supernode/chain_container/chain_container.go`

### PR DESCRIPTION
**Pull request by nonsense**
Fixes panic at: https://app.circleci.com/pipelines/github/ethereum-optimism/optimism/123123/workflows/65b0b312-f33d-4a35-b114-b5941ee8719b/jobs/4873005

---

Supernode.Start fires the Interop activity and chain-container goroutines in parallel. Interop's checkChainsReady immediately calls c.OptimisticAt -> c.SyncStatus, which reads c.vn while the chain container is concurrently assigning it in its restart loop. A torn two-word interface read can yield (type=*simpleVirtualNode, data=nil); the `c.vn == nil` guard returns false, the method dispatches on a nil receiver, and v.mu.Lock() panics at offset 0x58 (the mu field inside simpleVirtualNode).

Protect c.vn with a sync.RWMutex and route all reads/writes through getVN/setVN helpers so every method takes one consistent snapshot. Also add nil-receiver guards on the *simpleVirtualNode methods as a defense against typed-nil interfaces slipping through in tests or future refactors.

fixes https://github.com/ethereum-optimism/optimism/issues/19573

### CODE REVIEW

File: op-supernode/supernode/chain_container/virtual_node/virtual_node.go [hunk 1]
```diff
@@ -216,6 +225,9 @@ var ErrL1AtSafeHeadNotFound = errors.New("l1 at safe head not found")
 // L1AtSafeHead finds the earliest L1 block at which the provided L2 block became local safe,
 // using the monotonicity of SafeDB (L2 safe head number is non-decreasing over L1).
 func (v *simpleVirtualNode) L1AtSafeHead(ctx context.Context, target eth.BlockID) (eth.BlockID, error) {
+	if v == nil {
+		return eth.BlockID{}, ErrVirtualNodeNotRunning
+	}
```
Comment (ajsutton) [inline op-supernode/supernode/chain_container/virtual_node/virtual_node.go]: Checking if self is nil is a weird pattern - we probably should just put these checks in the calling code.

**Review by ajsutton — COMMENTED** [review]
Nice - this will fix https://github.com/ethereum-optimism/optimism/issues/19573

**Comment by nonsense** [comment]
@ajsutton I pinged @axelKingsley about this panic, and handed off this to him, given that he is actively working on `op-supernode` code, and I'd rather not change from underneath him. Will chat with him today and see if I will complete this PR or he will do a fix.

**Comment by axelKingsley** [comment]
@nonsense thanks for the ping/reminder. If you can take this PR from draft to merge, I'd appreciate it greatly. If you need me to take it, I can do that but it won't be prioritized.

Agreed with @ajsutton about removing the self nil checks, but otherwise this all looks fine and I can give it a review/approve once out of draft.

**Review by ajsutton — APPROVED** [review]
LGTM.
