### PR TITLE
op-batcher: handle errors more gracefully on shutdown

### LINKED ISSUE #14090: op-batcher confusing logs on shutdown (`SetMaxDASize rpc failed, retrying`, `err: context cancelled`)
When the op-batcher shutsdown, it cancels the `shutdownCtx`. If this happens at the same time the batcher is trying to set the max da size it logs an error for 2-3 logs before shutting down. This behavior is benign, but can be confusing if you don't understand what is going on. 

I'm not really sure if there is a good solution. I guess you could have a second shutdwon signal the every loop and cleanly exists rather than cancelling the ctx, but cancelling the ctx works.

https://github.com/ethereum-optimism/optimism/blob/4bb98fab58d7edce9b027e1d1aeed20e831f905e/op-batcher/batcher/driver.go#L545

### PR DESCRIPTION
**Pull request by geoknee**
Closes #14090

I also tackled some errors we get from the txmgr Queue on shutdown as well. 

Tests: I have tested this manually using a local kurtosis devnet.

### CODE REVIEW

File: op-batcher/batcher/driver.go [hunk 1]
```diff
@@ -476,9 +475,15 @@ func (l *BatchSubmitter) mainLoop(ctx context.Context, receiptsCh chan txmgr.TxR
...
+			queueCancel()
 			if err := queue.Wait(); err != nil {
-				l.Log.Error("error waiting for transactions to complete", "err", err)
+				if !errors.Is(err, context.Canceled) {
+					l.Log.Error("error waiting for transactions to complete", "err", err)
+				}
 			}
+			throttlingLoopCancel()
+			receiptsLoopCancel()
+			l.wg.Done()
```
Comment (sebastianst) [inline op-batcher/batcher/driver.go:486]: what's the difference to calling them in a `defer` at the top?

**Review by sebastianst — APPROVED** [review]
lgtm, just one question

File: op-batcher/batcher/driver.go (hunk 1 above)
Comment (geoknee) [reply op-batcher/batcher/driver.go:486]: No difference -- there's only one return statement in this function. I wanted to put all of the cleanup work in one spot to make it a bit easier to reason about.

Comment (sebastianst) [reply op-batcher/batcher/driver.go:486]: also works, just wanted to make sure I don't misunderstand
