### PR TITLE
fix(op-batcher): support new fjord maxRLPBytesPerChannelFjord via rollup chain spec

### LINKED ISSUE #10428: fjord: Use new large RLP limit in the batcher
Right now we use the parameter `SafeMaxRLPBytesPerChannel` throughout the op-node channel building & op-batcher. We should remove this constant and use the chain spec instead. The specific timestamp to use is the timestamp of the L1 origin of the newest L2 block in the channel. Technically in derivation the new limit will be applied for channels that get processed after the L1 origin of the CB is past the activation time.

### PR DESCRIPTION
**Pull request by emilianobonassi**
Context:

Fjord bump 10x `MaxRLPBytesPerChannel` to support higher gas limits.

On derivation the new limit is supported but op-batcher still use the old value.

This can lead to situation where the batcher halt in a chain post-Fjord with high block gas limit when a block bigger than 10M(bytes) is produced (this because a block cannot span today more than 1 channel).

This fixes https://github.com/ethereum-optimism/optimism/issues/10428 using the new value when appropriated and remove legacy `SafeMaxRLPBytesPerChannel`.

In the comments on the channel builder there a note about the choice of timestamp.

### CODE REVIEW

File: op-e2e/actions/garbage_channel_out.go [hunk 1]
```diff
@@ -159,9 +159,12 @@ func (co *GarbageChannelOut) AddBlock(rollupCfg *rollup.Config, block *types.Blo
 		buf.Reset()
 		buf.Write(bufBytes)
 	}
-	if co.rlpLength+buf.Len() > rollup.SafeMaxRLPBytesPerChannel {
+
+	var chainSpec = rollup.NewChainSpec(rollupCfg)
+	var maxRLPBytesPerChannel = chainSpec.MaxRLPBytesPerChannel(block.Time())
```
Comment (sebastianst) [inline op-e2e/actions/garbage_channel_out.go]:
```suggestion
	chainSpec := rollup.NewChainSpec(rollupCfg)
	maxRLPBytesPerChannel := chainSpec.MaxRLPBytesPerChannel(block.Time())
```
we prefer to use the `:=` syntax to define a new variable with a given value, which is more common.

File: op-batcher/batcher/channel_builder_test.go [hunk 2]
```diff
@@ -505,7 +505,8 @@ func ChannelBuilder_OutputFrames_SpanBatch(t *testing.T, algo derive.Compression
 func ChannelBuilder_MaxRLPBytesPerChannel(t *testing.T, batchType uint) {
 	t.Parallel()
 	channelConfig := defaultTestChannelConfig()
-	channelConfig.MaxFrameSize = rollup.SafeMaxRLPBytesPerChannel * 2
+	var chainSpec = rollup.NewChainSpec(&defaultTestRollupConfig)
```
Comment (sebastianst) [inline op-batcher/batcher/channel_builder_test.go]:
```suggestion
	chainSpec := rollup.NewChainSpec(&defaultTestRollupConfig)
```

File: op-batcher/batcher/channel_builder.go [hunk 3]
```diff
@@ -90,11 +90,13 @@ func NewChannelBuilder(cfg ChannelConfig, rollupCfg rollup.Config, latestL1Origi
 	if err != nil {
 		return nil, err
 	}
+
+	var chainSpec = rollup.NewChainSpec(&rollupCfg)
```
Comment (sebastianst) [inline op-batcher/batcher/channel_builder.go]:
```suggestion
	chainSpec := rollup.NewChainSpec(&rollupCfg)
```

File: op-e2e/actions/l2_batcher.go [hunk 4]
```diff
@@ -199,12 +199,13 @@ func (s *L2Batcher) Buffer(t Testing) error {
 			if s.l2BatcherCfg.ForceSubmitSingularBatch && s.l2BatcherCfg.ForceSubmitSpanBatch {
 				t.Fatalf("ForceSubmitSingularBatch and ForceSubmitSpanBatch cannot be set to true at the same time")
 			} else {
+				var chainSpec = rollup.NewChainSpec(s.rollupCfg)
```
Comment (sebastianst) [inline op-e2e/actions/l2_batcher.go]:
```suggestion
				chainSpec := rollup.NewChainSpec(s.rollupCfg)
```

File: op-node/benchmarks/batchbuilding_test.go [hunk 5]
```diff
@@ -8,10 +8,17 @@ import (
...
+	"github.com/ethereum-optimism/optimism/op-node/rollup"
 	"github.com/ethereum-optimism/optimism/op-node/rollup/derive"
+	"github.com/ethereum-optimism/optimism/op-service/eth"
 	"github.com/stretchr/testify/require"
 )
 
+var defaultTestRollupConfig = rollup.Config{
+	Genesis:   rollup.Genesis{L2: eth.BlockID{Number: 0}},
+	L2ChainID: big.NewInt(1234),
+}
```
Comment (sebastianst) [inline op-node/benchmarks/batchbuilding_test.go]: I think that in the benchmarks below, the config is only accessed to check whether Fjord is active. Since you don't set a Fjord timestamp, it will be `nil` and thus inactive, which is fine here. The config is not accessed for anything else, so I think you can just delete this `defaultTestRollupConfig` and pass an empty `new(rollup.Config)` to the `rollup.NewChainSpec` calls.

File: op-node/rollup/derive/channel_out.go [hunk 6]
```diff
@@ -139,9 +142,14 @@ func (co *SingularChannelOut) AddSingularBatch(batch *SingularBatch, _ uint64) e
 	if err := rlp.Encode(&buf, NewBatchData(batch)); err != nil {
 		return err
 	}
-	if co.rlpLength+buf.Len() > rollup.SafeMaxRLPBytesPerChannel {
+
+	// it's ok to use the batch timestamp
+	// on derivation we check that l1 timestamp were this channel will be included is after the fork
+	// eventually on the boundary of the fork we might use still the old value, which is lower so its ok (minor optimization)
+	var maxRLPBytesPerChannel = co.chainSpec.MaxRLPBytesPerChannel(batch.Timestamp)
```
Comment (sebastianst) [inline op-node/rollup/derive/channel_out.go]:
```suggestion
	// Fjord increases the max RLP bytes per channel. Activation of this change in the derivation pipeline
	// is dependent on the timestamp of the L1 block that this channel got included in. So using the timestamp
	// of the current batch guarantees that this channel will be included in an L1 block with a timestamp well after
	// the Fjord activation.
	maxRLPBytesPerChannel := co.chainSpec.MaxRLPBytesPerChannel(batch.Timestamp)
```
also improved the comment

File: op-node/rollup/derive/span_channel_out.go [hunk 7]
```diff
@@ -143,9 +146,13 @@ func (co *SpanChannelOut) AddSingularBatch(batch *SingularBatch, seqNum uint64)
 	}
 
 	// check the RLP length against the max
-	if co.activeRLP().Len() > rollup.SafeMaxRLPBytesPerChannel {
+	// it's ok to use the batch timestamp
+	// on derivation we check that l1 timestamp were this channel will be included is after the fork
+	// eventually on the boundary of the fork we might use still the old value, which is lower so its ok (minor optimization)
+	var maxRLPBytesPerChannel = co.chainSpec.MaxRLPBytesPerChannel(batch.Timestamp)
```
Comment (sebastianst) [inline op-node/rollup/derive/span_channel_out.go]:
```suggestion
	// Fjord increases the max RLP bytes per channel. Activation of this change in the derivation pipeline
	// is dependent on the timestamp of the L1 block that this channel got included in. So using the timestamp
	// of the current batch guarantees that this channel will be included in an L1 block with a timestamp well after
	// the Fjord activation.
	maxRLPBytesPerChannel := co.chainSpec.MaxRLPBytesPerChannel(batch.Timestamp)
```

File: op-node/rollup/derive/channel_out_test.go
Comment (sebastianst) [inline op-node/rollup/derive/channel_out_test.go:1]: It would be great to add a test here to confirm that the change is correctly applied with Fjord activation. The test could work as follows:
- Define a positive Fjord activation timestamp in the rollup config.
- Add randomly generated blocks with pre-Fjord timestamps (I believe timestamps have to increase for each block, so can just start with 0), until we get an expected rlp size error. Track how many blocks were added.
- Now add double that amount of blocks with timestamps starting at the Fjord activation timestamp. This should succeed, as the limit got 10x'd.

**Review by sebastianst — COMMENTED** [review]
Thanks for this fix! I think the pragmatic solution to just use the batch's timestamp as an activation reference works well, as it is fine around the Fjord boundary to activate it a few blocks later than could be, since the max size is _increased_.

File: op-e2e/actions/garbage_channel_out.go (hunk 1 above)
Comment (emilianobonassi) [reply op-e2e/actions/garbage_channel_out.go]: thanks, fixed

File: op-e2e/actions/l2_batcher.go (hunk 4 above)
Comment (emilianobonassi) [reply op-e2e/actions/l2_batcher.go]: thanks, fixed

File: op-node/benchmarks/batchbuilding_test.go (hunk 5 above)
Comment (emilianobonassi) [reply op-node/benchmarks/batchbuilding_test.go]: thanks, fixed

File: op-node/rollup/derive/channel_out.go (hunk 6 above)
Comment (emilianobonassi) [reply op-node/rollup/derive/channel_out.go]: thanks, fixed

File: op-node/rollup/derive/span_channel_out.go (hunk 7 above)
Comment (emilianobonassi) [reply op-node/rollup/derive/span_channel_out.go]: thanks, fixed

File: op-batcher/batcher/channel_builder_test.go (hunk 2 above)
Comment (emilianobonassi) [reply op-batcher/batcher/channel_builder_test.go]: thanks, fixed

**Review by sebastianst — APPROVED** [review]
LGTM, thanks!

**Review by protolambda — APPROVED** [review]

**Comment by emilianobonassi** [comment]
Worth to mention that this fix was possible collaborating with Derive (former Lyra) team which was exploring higher gas block limits (120M).
