### PR TITLE
batcher: add batchSubmitter.checkExpectedProgress

### LINKED ISSUE #12124: Holocene-D: op-batcher: Periodically check sync status
In `calculateL2BlockRangeToStore`, the batcher loads the sync status of the node it is connected to, to determine the unsafe block range to batch-submit. It does some checks, like whether the safe head unexpectedly jumped forward (which may happen if this is a restarted batcher and old transactions from a previous instance just got included L1). Then later, when adding the blocks to the channel manager, reorgs are detected.

However, what is not checked yet is whether the node made the expected progress. If a channel is fully submitted on L1, and that L1 inclusion block has been visited according to the sync status, we should check that the safe head has moved accordingly to the highest block in that channel. And if that's not the case, we should reset the batch submitter state (`l.lastStoredBlock` and possibly others) so that it starts batching again from the oldest non-safe unsafe head in the hope of repairing the situation.

We should make this behavior of resetting and reattempting batching optional. The alternative should be to just halt after printing an error message about the detected unexpected non-advancement of the safe chain.

This will improve the likelihood that the batcher can self-heal from any unexpected situations that arise from the stricter ordering rules in Holocene.

### PR DESCRIPTION
**Pull request by geoknee**
towards #12124

### CODE REVIEW

File: op-batcher/batcher/driver.go [hunk 1]
```diff
@@ -407,6 +408,45 @@ func (l *BatchSubmitter) mainLoop(ctx context.Context, receiptsCh chan txmgr.TxR
...
+// state.
+func (l *BatchSubmitter) checkExpectedProgress(syncStatus eth.SyncStatus) error {
+
+	// Define a buffer: a delay denominated in L1 blocks
+	// to allow verifier to process blocks.
+	// Set to 0 to require immediate safe head advancement.
+	// Set to 1 to allow e.g. 12s for the safe head to advance
+	// after the L1 inclusion block was ingested.
+	// TODO extract this into a config variable
+	// TODO should we also wait numConfirmations (this is a txmgr config variable, not in scope of the batch submitter)
```
Comment (geoknee) [inline op-batcher/batcher/driver.go]: What we really want to know is the verifier numConfirmations, but I don't think we can get access to that. We probably have to proceed with our own conservative buffer / confirmation depth. 

When this is a CLI config variable, it can be set in a coordinated way with how the verifier node / sequencer is configured.

File: op-batcher/batcher/driver.go [hunk 2]
```diff
@@ -407,6 +408,45 @@ func (l *BatchSubmitter) mainLoop(ctx context.Context, receiptsCh chan txmgr.TxR
...
+
+	BUFFER := uint64(1)
```
Comment (vdamle) [inline op-batcher/batcher/driver.go]: Just a thought - given how this is used, I wonder whether naming it`PROCESSING_WINDOW` would make it more intuitive?

Comment (geoknee) [reply op-batcher/batcher/driver.go]: +1 for choosing a better name. What do you think about just using `VERIFIER_L1_CONFS`, which is the flag for the verifier?



https://github.com/ethereum-optimism/optimism/blob/466fd958f7f2ba25c982f9326a9af90aeea1feb7/op-node/flags/flags.go#L206-L212

Comment (vdamle) [reply op-batcher/batcher/driver.go]: Ah yeah, that sounds great!

Comment (geoknee) [reply op-batcher/batcher/driver.go]: [cd05cb5](https://github.com/ethereum-optimism/optimism/pull/12430/commits/cd05cb5be1bb2ee9c4ce313151f6e849fb138131)

File: op-batcher/batcher/driver.go [hunk 3]
```diff
@@ -407,6 +408,34 @@ func (l *BatchSubmitter) mainLoop(ctx context.Context, receiptsCh chan txmgr.TxR
...
+// checkExpectedProgress uses the supplied syncStatus to infer
+// whether the node providing the status has made the expected
+// safe head progress given fully submitted channels held in
+// state.
+func (l *BatchSubmitter) checkExpectedProgress(syncStatus eth.SyncStatus) error {
+	verifierCurrentL1 := syncStatus.CurrentL1
+	for _, ch := range l.state.channelQueue {
+		if ch.isFullySubmitted() && // This implies a number of l1 confirmations has passed, depending on how the txmgr was configured
+			!ch.isTimedOut() &&
+			verifierCurrentL1.Number > ch.maxInclusionBlock+l.Config.VerifierL1Confs &&
```
Comment (sebastianst) [inline op-batcher/batcher/driver.go]: Since the sync status tells us where the actual derivation at right now, I think we don't need to add the verifier depth at all.
```suggestion
			verifierCurrentL1.Number > ch.maxInclusionBlock &&
```
This should suffice to tell us that derivation is past the channel inclusion block.

File: op-batcher/batcher/driver.go [hunk 4]
```diff
@@ -388,17 +388,18 @@ func (l *BatchSubmitter) mainLoop(ctx context.Context, receiptsCh chan txmgr.TxR
 
 			l.state.pruneSafeBlocks(syncStatus.SafeL2)
 			l.state.pruneChannels(syncStatus.SafeL2)
+
+			err = l.checkExpectedProgress(*syncStatus)
```
Comment (sebastianst) [inline op-batcher/batcher/driver.go]: couldn't the channel pruning before the check delete the last fully submitted channel on which you rely for the check?

File: op-batcher/flags/flags.go [hunk 5]
```diff
@@ -156,6 +156,12 @@ var (
 		Value:   false,
 		EnvVars: prefixEnvVars("WAIT_NODE_SYNC"),
 	}
+	VerifierL1Confs = &cli.Uint64Flag{
```
Comment (sebastianst) [inline op-batcher/flags/flags.go]: I think we can remove this config value entirely.

File: op-batcher/batcher/driver.go (hunk 4 above)
Comment (sebastianst) [reply op-batcher/batcher/driver.go]: Would be good to test this new feature.

File: op-batcher/batcher/driver.go [hunk 6]
```diff
@@ -388,17 +388,18 @@ func (l *BatchSubmitter) mainLoop(ctx context.Context, receiptsCh chan txmgr.TxR
...
+			if err != nil {
+				l.waitNodeSyncAndClearState()
+				continue
+			}
```
Comment (sebastianst) [inline op-batcher/batcher/driver.go]: Let's add a warning log before the `waitNodeSyncAndClearState()` call. Could be very valuable for debugging.

**Review by sebastianst — CHANGES_REQUESTED** [review]

File: op-batcher/batcher/driver.go (hunk 3 above)
Comment (geoknee) [reply op-batcher/batcher/driver.go]: I see, I guess I was double counting the verifier confirmation depth in a sense. https://github.com/ethereum-optimism/optimism/blob/d526e425254671aefb2085590b58b15a65789243/op-service/eth/sync_status.go#L5-L18

File: op-batcher/flags/flags.go (hunk 5 above)
Comment (geoknee) [reply op-batcher/flags/flags.go]: [31d7374](https://github.com/ethereum-optimism/optimism/pull/12430/commits/31d7374b97ee7aa8a570ed96edde463cae269d7b)

File: op-batcher/batcher/driver.go (hunk 3 above)
Comment (geoknee) [reply op-batcher/batcher/driver.go]: [3df8d16](https://github.com/ethereum-optimism/optimism/pull/12430/commits/3df8d166daaea9e96139c050c390244192766239)

File: op-batcher/batcher/driver.go (hunk 4 above)
Comment (geoknee) [reply op-batcher/batcher/driver.go]: Yes agreed about adding a test I will get on to that.

I don't think the pruning should affect the progress check. If a channel got pruned, that is because all of the blocks in that channel became safe. So none of those pruned channels should trigger the "did not make progress" error condition (since `syncStatus.SafeL2.Number < ch.LatestL2().Number` would always be false).

File: op-batcher/batcher/driver.go (hunk 6 above)
Comment (geoknee) [reply op-batcher/batcher/driver.go]: [9a3cf87](https://github.com/ethereum-optimism/optimism/pull/12430/commits/9a3cf87af43b607864c5505abf34132ce7517b0a)

File: op-batcher/batcher/channel_manager_test.go [hunk 7]
```diff
@@ -627,3 +627,46 @@ func TestChannelManager_ChannelOutFactory(t *testing.T) {
...
+
+	m.channelQueue = append(m.channelQueue, A)
+
+	// The current L1 number implies that
+	// channel A above should have been derived
+	// from, so we expect safe head to progress to 3.
+	// Since the safe head moved to 4, there is no error:
+	ss := eth.SyncStatus{
+		CurrentL1: eth.L1BlockRef{Number: 4},
+		SafeL2:    eth.L2BlockRef{Number: 4},
```
Comment (sebastianst) [inline op-batcher/batcher/channel_manager_test.go]: wouldn't it be a "closer" test to set this to 3?
```suggestion
		SafeL2:    eth.L2BlockRef{Number: 3},
```

Comment (geoknee) [reply op-batcher/batcher/channel_manager_test.go]: [b2ccead](https://github.com/ethereum-optimism/optimism/pull/12430/commits/b2ccead057f9bcaf382bcc29736bef0fc9405602)

Comment (geoknee) [reply op-batcher/batcher/channel_manager_test.go]: [a2ff417](https://github.com/ethereum-optimism/optimism/pull/12430/commits/a2ff417d647aad646548adbb6a13ba6b56404a16) after rebase

File: op-batcher/batcher/driver.go (hunk 4 above)
Comment (sebastianst) [reply op-batcher/batcher/driver.go]: Ah I see, that makes sense.

**Review by sebastianst — APPROVED** [review]
