### PR TITLE
fix(op-reth): replace HashMap with sequential grouping in init store_entries

### LINKED ISSUE #19640: op-reth: OOM during `proofs init`
# Description

The proofs init command is killed by the Linux OOM killer while syncing hashed storage on base mainnet. 

Source: Anonymous memory (~19 bytes/entry) — UNSOLVED 
What: anon-rss grows at a steady ~19 bytes/entry regardless of batch size or env reopen. This memory survives complete `DatabaseEnv` drop+reopen, proving it is not in Proof's MDBX environment handle.

### PR DESCRIPTION
**Pull request by dhyaniarun1993**
# Description

## Problem

`HashedStoragesInit::store_entries` and `StoragesTrieInit::store_entries` grouped entries into a `HashMap<B256, Vec<…>>` before writing them to the proofs DB. The source cursor yields entries in sorted order `(address ASC, key ASC)`, but `HashMap` iteration randomises that order.

This caused silent data loss when the init process was killed(before processing the full batch) and restarted:

1.  A batch of 100K entries spans addresses A → E
2. HashMap iterates in random order, e.g. B, D, A, C, E
3. `store_hashed_storages(B, …)` → opens MDBX txn → commits
4. `store_hashed_storages(D, …)` → D → OK → commits
5. `store_hashed_storages(A, …)` → A → process dies (e.g. OOM)
6. On restart, `initial_state_anchor()` reads last key = D
7. Source cursor seeks past D, permanently skipping A and C
8. Init eventually completes, but the proof DB has missing entries
9. At query time → trie root / hash mismatch

## Fix
Replace `HashMap` grouping with sequential grouping that preserves the source cursor's sorted order. Consecutive entries with the same address are naturally grouped, and flushed in order. This guarantees on resume after partial commit, the last committed address is always the highest → no entries are skipped

# Tests

Added two regression tests using a `RecordingStore` spy that implements `OpProofsInitialStateStore` and captures the order of addresses passed to `store_hashed_storages` / `store_storage_branches`. Both tests assert:

1. Exactly one call per address
2. Calls arrive in strictly ascending address order

# Additional context

NA

# Metadata

Also contains code from https://github.com/ethereum-optimism/optimism/pull/19663 which fixes #19640

### CODE REVIEW

**Comment by sebastianst** [comment]
/ci authorize https://github.com/ethereum-optimism/optimism/pull/19664/commits/68cd5ff33736387f66cd15ae937bb3b31267e471

File: rust/op-reth/crates/trie/src/initialize.rs [hunk 1]
```diff
@@ -394,21 +394,45 @@ impl<C> InitTable for HashedStoragesInit<C> {
...
+    // HashMap randomised iteration order, which caused silent data loss
+    // when a batch contained multiple addresses and was only partially
+    // processed before a failure (e.g. OOM kill).
+    //
+    // Each `store_hashed_storages` call commits its own MDBX transaction,
+    // so if the HashMap happened to flush addresses B, D (committed) and
+    // then failed on A (e.g. OOM kill), the
+    // resume key would be set to D. On restart the source cursor seeks
+    // past D, permanently skipping A and C — producing a proof DB with
+    // missing entries and ultimately a trie root / hash mismatch.
```
Comment (theochap) [inline rust/op-reth/crates/trie/src/initialize.rs:414]: Instead of a Vec, you could use a BTree or a BtreeMap. It is a hash map with sorted entries (if you need to iterate in order, which it seems is what you need). Maybe that is not necessary

Comment (dhyaniarun1993) [reply rust/op-reth/crates/trie/src/initialize.rs:414]: Yea, we could use that but I think current solution is more ideal here because the entries already arrive pre-sorted from the MDBX DupSort cursor in `(address ASC, slot/nibbles ASC)` order(database-layer guarantee).

Sequential grouping gives us:
- O(n) single pass, no extra allocations beyond the per-address Vec
- Preserves the cursor's sort order directly

A BTreeMap would add O(n log n) insertion cost and tree-node overhead to re-sort data that's already sorted. Let me know what you think.

Comment (theochap) [reply rust/op-reth/crates/trie/src/initialize.rs:414]: Ok sounds good, I wasn't sure the database ensures that the entries arrive pre-sorted. Thanks

**Review by theochap — APPROVED** [review]
