### PR TITLE
fix(kona/derive): copy origin field during Holocene BatchQueue→BatchValidator transition

### LINKED ISSUE #19356: kona: BatchProvider.attempt_update() does not copy origin field on Holocene transition
## Summary

When the kona derivation pipeline transitions from `BatchQueue` to `BatchValidator` at Holocene activation, `BatchProvider::attempt_update()` copies `l1_blocks` from the old `BatchQueue` but does **not** copy the `origin` field.

The Go reference (`BatchMux.TransformHolocene`) copies **both** fields:

```go
// optimism/op-node/rollup/derive/batch_mux.go#L67-L68
bs.l1Blocks = slices.Clone(bp.l1Blocks)
bs.origin = bp.origin         // ← this line is missing in Rust
```

The Rust code:

```rust
// optimism/rust/kona/crates/protocol/derive/src/stages/batch/batch_provider.rs#L74-L77
let batch_queue = self.batch_queue.take().expect("Must have batch queue");
let mut bv = BatchValidator::new(self.cfg.clone(), batch_queue.prev);
bv.l1_blocks = batch_queue.l1_blocks;   // ← origin is NOT copied
self.batch_validator = Some(bv);
```

Reference: https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/op-node/rollup/derive/batch_mux.go#L67
Subject: https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/rust/kona/crates/protocol/derive/src/stages/batch/batch_provider.rs#L74

## Failure modes

Because `BatchValidator::new()` initialises `origin` to `None`, the very first call to `update_origins()` after the Holocene transition always enters the `self.origin != self.prev.origin()` branch (`None != Some(...)`).

This causes two distinct failure modes:

**1. Normal-case duplicate insertion (affects every transitioning node)**

When `origin_behind` is `false` (the common case where the pipeline is caught up with L1), `update_origins()` pushes the current L1 block onto `l1_blocks` again. If `l1_blocks` was `[block_a, block_b]` after the transfer, it becomes `[block_a, block_b, block_b]`. After epoch pruning, this leaves two identical entries `[block_b, block_b]`, corrupting the two-slot epoch window relied on by `try_derive_empty_batch` and epoch-advancement logic.

**2. Lagging/startup case — l1_blocks cleared, derivation halts**

When `origin_behind` is `true` (`prev.origin().number < parent.l1_origin.number`), `update_origins()` calls `self.l1_blocks.clear()`, discarding all L1 history transferred from `BatchQueue`. The subsequent `next_batch` call returns `MissingOrigin.crit()`, permanently halting the derivation pipeline.

In Go, neither failure can occur because `bs.origin` is set to `bp.origin` before the first `NextBatch` call, making `bs.origin == bs.prev.Origin()` and causing `update_origins()` to skip the update branch entirely.

## Impact

Every kona node that was running before Holocene activated (i.e. all nodes that were not started fresh after Holocene) would have been affected during the transition. Today Holocene is already active on all supported chains, so new nodes start with Holocene already active and take the direct-initialisation path in `attempt_update()` — meaning **there is no current impact in production**. The bug would surface again only if a new hardfork resets the mux or if a future chain activates Holocene after initial deployment.

## Fix

In `attempt_update()`, when constructing the new `BatchValidator` from `BatchQueue`, also copy the `origin` field, analogous to `TransformHolocene` in Go:

```rust
let batch_queue = self.batch_queue.take().expect("Must have batch queue");
let mut bv = BatchValidator::new(self.cfg.clone(), batch_queue.prev);
bv.l1_blocks = batch_queue.l1_blocks;
bv.origin = batch_queue.origin;   // ← add this line
self.batch_validator = Some(bv);
```

An existing test `test_spec_batch_provider_holocene_transition_origin_not_transferred` documents the discrepancy and currently passes (documents the bug via `assert!(bv.origin.is_none())`). After the fix the assertion should be inverted to verify the origin is correctly propagated.

### PR DESCRIPTION
**Pull request by ajsutton**
## Description

When kona's derivation pipeline transitions from `BatchQueue` to `BatchValidator` at Holocene activation, `BatchProvider::attempt_update()` copies `l1_blocks` from the old `BatchQueue` but does **not** copy the `origin` field.

Go's `BatchMux.TransformHolocene()` copies both fields ([batch_mux.go#L67-L68](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/op-node/rollup/derive/batch_mux.go#L67)):

```go
bs.l1Blocks = slices.Clone(bp.l1Blocks)
bs.origin = bp.origin         // ← this line was missing in Rust
```

The Rust code before this fix ([batch_provider.rs#L74-L77](https://github.com/ethereum-optimism/optimism/blob/9eaad92f7f2f8a5f9687b6a703d4afc3dad1d347/rust/kona/crates/protocol/derive/src/stages/batch/batch_provider.rs#L74)):

```rust
let batch_queue = self.batch_queue.take().expect("Must have batch queue");
let mut bv = BatchValidator::new(self.cfg.clone(), batch_queue.prev);
bv.l1_blocks = batch_queue.l1_blocks;
// bv.origin was not set — starts as None
self.batch_validator = Some(bv);
```

### Failure modes

Because `BatchValidator::new()` initialises `origin` to `None`, the very first call to `update_origins()` after the Holocene transition always enters the `self.origin != self.prev.origin()` branch (`None != Some(...)`):

**1. Normal-case duplicate insertion (affects every transitioning node)**

When `origin_behind` is `false` (the common case where the pipeline is caught up with L1), `update_origins()` pushes the current L1 block onto `l1_blocks` again. If `l1_blocks` was `[block_a, block_b]` after the transfer, it becomes `[block_a, block_b, block_b]`. After epoch pruning fires, this leaves two identical entries `[block_b, block_b]`, corrupting the two-slot epoch window relied on by `try_derive_empty_batch` and epoch-advancement logic.

**2. Lagging/startup case — l1_blocks cleared, derivation halts**

When `origin_behind` is `true` (`prev.origin().number < parent.l1_origin.number`), `update_origins()` calls `self.l1_blocks.clear()`, discarding all L1 history transferred from `BatchQueue`. The next `next_batch()` call returns `MissingOrigin.crit()`, permanently halting the derivation pipeline.

Go is immune to both because `bs.origin = bp.origin` is set before the first `NextBatch` call, making `bs.origin == bs.prev.Origin()` and causing `update_origins()` to skip the update branch entirely.

### Current impact

Holocene is already active on all supported chains, so new nodes start with Holocene already active and take the direct-initialisation path in `attempt_update()` — meaning there is **no current impact in production**. The bug would surface again if a new hardfork resets the mux or if a future chain activates Holocene after initial deployment.

## Fix

Copy `batch_queue.origin` into `bv.origin` alongside `l1_blocks`:

```rust
let batch_queue = self.batch_queue.take().expect("Must have batch queue");
let mut bv = BatchValidator::new(self.cfg.clone(), batch_queue.prev);
bv.l1_blocks = batch_queue.l1_blocks;
bv.origin = batch_queue.origin;   // ← new line
self.batch_validator = Some(bv);
```

A regression test `test_spec_batch_provider_holocene_transition_origin_not_transferred` is included that verifies both `l1_blocks` and `origin` are correctly transferred after the Holocene transition.

Fixes https://github.com/ethereum-optimism/optimism/issues/19356

### CODE REVIEW

File: rust/kona/crates/protocol/derive/src/stages/batch/batch_provider.rs [hunk 1]
```diff
@@ -306,4 +307,61 @@ mod test {
         };
         assert!(bv.l1_blocks.len() == 1);
     }
+
+    // BQ-12 fix: On Holocene activation, BatchProvider.attempt_update() must copy BOTH l1_blocks
```
Comment (ajsutton) [inline rust/kona/crates/protocol/derive/src/stages/batch/batch_provider.rs]: Remove references to BQ-12.

File: rust/kona/crates/protocol/derive/src/stages/batch/batch_provider.rs [hunk 2]
```diff
@@ -306,4 +307,61 @@ mod test {
...
+    // AND origin from the old BatchQueue to the new BatchValidator, matching Go's
+    // BatchMux.TransformHolocene() which copies both bs.l1Blocks and bs.origin
+    // (batch_mux.go:67-68).
```
Comment (ajsutton) [inline rust/kona/crates/protocol/derive/src/stages/batch/batch_provider.rs]: Remove references to matching Go's implementation.

File: rust/kona/crates/protocol/derive/src/stages/batch/batch_provider.rs [hunk 3]
```diff
@@ -306,4 +307,59 @@ mod test {
...
+
+    // On Holocene activation, BatchProvider.attempt_update() must copy BOTH l1_blocks
+    // AND origin from the old BatchQueue to the new BatchValidator.
+    //
+    // Without copying origin, BatchValidator.origin starts as None. The first
+    // update_origins() call always enters the `self.origin != self.prev.origin()` branch
+    // (None != Some(...)), causing either duplicate l1_block insertion (normal case) or
+    // l1_blocks.clear() followed by MissingOrigin.crit() halt (lagging case).
+    #[test]
+    fn test_spec_batch_provider_holocene_transition_origin_not_transferred() {
```
Comment (ajsutton) [inline rust/kona/crates/protocol/derive/src/stages/batch/batch_provider.rs]: Nit: the test name says `not_transferred` but the test now verifies that origin IS transferred (the fix). Consider renaming to `test_spec_batch_provider_holocene_transition_origin_transferred` to describe the expected behavior rather than the old bug.

**Review by ajsutton — COMMENTED** [review]
Minor nit on test naming.

**Review by sebastianst — APPROVED** [review]

File: rust/kona/crates/protocol/derive/src/stages/batch/batch_provider.rs [hunk 4]
```diff
@@ -306,4 +307,59 @@ mod test {
...
+        assert!(batch_provider.batch_validator.is_some(), "Expected BatchValidator post-Holocene");
+
+        let bv = batch_provider.batch_validator.as_ref().unwrap();
+
+        // Verify l1_blocks were transferred.
+        assert_eq!(bv.l1_blocks.len(), 2, "l1_blocks must be transferred from BatchQueue");
+        assert_eq!(bv.l1_blocks[0], block_a);
+        assert_eq!(bv.l1_blocks[1], block_b);
+
+        // Verify origin was transferred (BQ-12 fix): BatchValidator.origin must equal the
```
Comment (sebastianst) [inline rust/kona/crates/protocol/derive/src/stages/batch/batch_provider.rs]: dangling reference to `BQ-12`
