### PR TITLE
op-acceptance-tests, op-devstack: base; withdrawal

### LINKED ISSUE #327: [acceptance] [sysgo] Test: base; Complete Withdrawal Flow Test
Test the entire withdrawal process from L2 to L1, including initiation, proof generation, and finalization.

### Implementation
Implement using op-devstack to configure a test environment with L1 and L2 chains. Initialize a funded account on L2, perform a withdrawal transaction to L1, wait for the challenge period, generate and submit the withdrawal proof, and verify the finalization on L1. Track all transaction hashes and confirm proper state changes on both chains.

### LINKED ISSUE #16294: op-devstack: can't deploy additional games due to mismatching deployer key
**Bug Description**
We can't deploy additional games using sysgo due to a mismatching deployer key. Relevant files are:
- op-devstack/sysgo/deployer.go:304 => Deployer private key is set as an option
- op-deployer/pkg/deployer/apply.go => Deployer private key is read from the options
- op-deployer/pkg/deployer/pipeline/dispute_games.go:35 => Deployer key will mismatch the L1ProxyAdminOwner.go.

When starting up a sysgo test, we call multiple times op-e2e/config/init.go which has a defaultConfig where all the proxy admins are set to the deployer key. Therefore the initial deployment would work.
However it seems that sysgo will not use this logic and therefore all the owners are different.

**Steps to Reproduce**

- Add the following method in op-e2e/e2eutils/intentbuilder/builder.go
```go
func (c *l2Configurator) WithAdditionalDisputeGames(games []state.AdditionalDisputeGame) {
	c.builder.intent.Chains[c.chainIndex].AdditionalDisputeGames = games
}
```
- Add the corresponding method in a preset and call it like this
```go
	presets.DoMain(m, presets.WithMinimal(),  presets.WithAdditonalDisputeGames([]state.AdditionalDisputeGame{
		{
			ChainProofParams: state.ChainProofParams{
				// Fast game
				DisputeGameType:         254,
				DisputeAbsolutePrestate: common.HexToHash("0x03c7ae758795765c6664a5d39bf63841c71ff191e9189522bad8ebff5d4eca98"),
				DisputeMaxGameDepth:     14 + 3 + 1,
				DisputeSplitDepth:       14,
				DisputeClockExtension:   0,
				DisputeMaxClockDuration: 0,
			},
			VMType:                       state.VMTypeAlphabet,
			UseCustomOracle:              true,
			OracleMinProposalSize:        10000,
			OracleChallengePeriodSeconds: 0,
			MakeRespected:                true,
		},
	}))
```

**Expected behavior**

Sysgo should have a similar configuration than op-e2e.

**Environment Information:**

**Configurations:**

**Logs:**

**Additional context**

---

⚠️ **Notice:** Issues that do not include the following sections will be subject to closure:
- Bug Description
- Steps to Reproduce
- Environment Information

Please ensure all required sections are filled out accurately to expedite the debugging process and improve issue resolution efficiency.

### PR DESCRIPTION
**Pull request by pcw109550**
**Description**

Builds upon the contract DSL for struct at https://github.com/ethereum-optimism/optimism/pull/16254 (base branch). 

The PR adds multiple sysgo presets for testing the withdrawal:
```go
func TestMain(m *testing.M) {
	presets.DoMain(m, presets.WithMinimal(),
		presets.WithProposerGameType(faultTypes.FastGameType),
		// Fast game for test
		presets.WithFastGame(),
		// Deployer must be L1PAO to make op-deployer happy
		presets.WithDeployerMatchL1PAO(),
		// Guardian must be L1PAO to make AnchorStateRegistry's setRespectedGameType method work
		presets.WithGuardianMatchL1PAO(),
		// Fast finalization for fast withdrawal
		presets.WithFinalizationPeriodSeconds(2),
		// Satisfy OptimismPortal2 PROOF_MATURITY_DELAY_SECONDS check, avoid OptimismPortal_ProofNotOldEnough() revert
		presets.WithProofMaturityDelaySeconds(12),
		// Satisfy AnchorStateRegistry DISPUTE_GAME_FINALITY_DELAY_SECONDS check, avoid OptimismPortal_InvalidRootClaim() revert
		presets.WithDisputeGameFinalityDelaySeconds(6),
	)
}
```
which mimics the hardcoded config at `op-e2e/config/init.go` but with minimal preset to pass the test using the fast game type.

Ports withdrawal test from `op-e2e/system/bridge/withdrawal_test.go` using the op-devstack.

**Tests**

Deposit -> Withdrawal(L2toL1 message send, prove, finalize) sequence works at `op-acceptance-tests/tests/base/withdrawal/withdrawal_test.go::TestWithdrawal` test.

Intentionally not added at the `acceptance-tests.yaml` not to target the sysext because presets does not work against sysext.

**Additional context**

There are some logic dups because of the client difference, original withdrawal test used `ethclient.Client`, but our op-devstack uses `api.EthClient`, resulting in different types and manual conversion

**Metadata**

- Fixes https://github.com/ethereum-optimism/infra/issues/327
- Fixes https://github.com/ethereum-optimism/optimism/issues/16294

### CODE REVIEW

File: op-devstack/presets/proof.go [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+// TODO(infra#401): Implement support in the sysext toolset
+func WithFastGame() stack.CommonOption {
+	return stack.MakeCommon(
+		sysgo.WithDeployerOptions(
+			sysgo.WithAdditionalDisputeGames(
+				[]state.AdditionalDisputeGame{
+					{
+						ChainProofParams: state.ChainProofParams{
+							DisputeGameType:         uint32(faultTypes.FastGameType),
+							DisputeAbsolutePrestate: common.HexToHash("0x03c7ae758795765c6664a5d39bf63841c71ff191e9189522bad8ebff5d4eca98"),
```
Comment (serpixel) [inline op-devstack/presets/proof.go:30]: Might be worth adding a comment on why we use these values.

**Review by serpixel — APPROVED** [review]
Looks good to me! Though may be worth getting an extra review here

**Review by teddyknox — APPROVED** [review]

File: op-devstack/presets/proof.go (hunk 1 above)
Comment (pcw109550) [reply op-devstack/presets/proof.go:30]: Fixed at https://github.com/ethereum-optimism/optimism/pull/16333/commits/2a161d84048ab50892be7576caeec4f90231bd36

**Review by protolambda — APPROVED** [review]

**Comment by pcw109550** [comment]
Tweaks at sysgo op-deployer makes the superroot proof test(`op-acceptance-tests/tests/interop/proofs/init_test.go`) to fail.  Currently investigating

**Comment by pcw109550** [comment]
Since the fix touches the `superroot.go` impl, asked question at https://github.com/ethereum-optimism/optimism/pull/16236#discussion_r2139809313
