### PR TITLE
cannon: Fix stack patching

### LINKED ISSUE #11660: Offchain MTCannon: Clean up memprofile handling
## Description

Clean up our approach to disabling memory profiling for go programs loaded into Cannon. 

As part of https://github.com/ethereum-optimism/optimism/pull/11188, we reworked our approach to disabling memory profiling.  For details, see commits [here](https://github.com/ethereum-optimism/optimism/pull/11188/commits/4fd9c3917baf9c17d1642576d73eea53616cc440) and [here](https://github.com/ethereum-optimism/optimism/pull/11188/commits/9e80acf4a653b068d490e187baa2e3cf1c38c672).  The original approached directly overwrote the`MemProfileRate` symbol in the compiled MIPS bytecode in order to disable memory profiling for performance reasons.  The current approach sets `runtime.MemProfileRate` in the op-program itself, which is less hacky, but has the disadvantage that any go program we want to run needs to separately ensure that mem profiling is disabled. 

The suggested approach is to move the memprofile handling back to `patch.go` and out of op-program, but to handle this in a cleaner way by setting an envar on the initial program stack.  You can see where the initial stacks envars are set up in `PatchStack()` [here](https://github.com/ethereum-optimism/optimism/blob/05a9c478264302a257f30daad877449a31b0aaeb/cannon/mipsevm/program/patch.go#L74).  For documentation on the initial stack see this [MIPS ABI documentation](https://refspecs.linuxfoundation.org/elf/mipsabi.pdf) "Figure 3-26: Initial Process Stack" . The envar set is currently empty, but we can push the value `GODEBUG=memprofilerate=0` in order to inform the runtime to disable mem profiling.  Documentation on go runtime envars is available [here](https://pkg.go.dev/runtime#hdr-Environment_Variables).

### PR DESCRIPTION
**Pull request by Inphi**
Fixes the base stack pointer of the op-program.
Also adds the `memprofilerate=0` environment variable to all patched programs.

Setting `memprofilerate` avoids floating point operations within the Go runtime. We should be able to disable Go specific patches with this change, but this will be done on a later PR.

fixes: https://github.com/ethereum-optimism/optimism/issues/11660

### CODE REVIEW

File: cannon/mipsevm/program/patch.go [hunk 1]
```diff
@@ -73,16 +72,24 @@ func PatchStack(st mipsevm.FPVMState) error {
...
-	storeMem(sp+4*3, 0)      // envp[term] = 0 (no env vars)
-	storeMem(sp+4*4, 6)      // auxv[0] = _AT_PAGESZ = 6 (key)
-	storeMem(sp+4*5, 4096)   // auxv[1] = page size of 4 KiB (value) - (== minPhysPageSize)
-	storeMem(sp+4*6, 25)     // auxv[2] = AT_RANDOM
-	storeMem(sp+4*7, sp+4*9) // auxv[3] = address of 16 bytes containing random value
-	storeMem(sp+4*8, 0)      // auxv[term] = 0
+	storeMem(sp+4*0, 1)       // argc = 1 (argument count)
+	storeMem(sp+4*1, sp+4*20) // argv[0]
+	storeMem(sp+4*2, 0)       // argv[1] = terminating
+	storeMem(sp+4*3, sp+4*15) // envp[0] = 0 (no env vars)
```
Comment (protolambda) [inline cannon/mipsevm/program/patch.go]:
```suggestion
	storeMem(sp+4*3, sp+4*15) // envp[0] = x (offset to first env var)
```

File: cannon/mipsevm/program/patch.go [hunk 2]
```diff
@@ -73,16 +72,24 @@ func PatchStack(st mipsevm.FPVMState) error {
...
+	storeMem(sp+4*4, 0)       // envp[1] = terminating
+	storeMem(sp+4*5, 6)       // auxv[0] = _AT_PAGESZ = 6 (key)
+	storeMem(sp+4*6, 4096)    // auxv[1] = page size of 4 KiB (value) - (== minPhysPageSize)
+	storeMem(sp+4*7, 25)      // auxv[2] = AT_RANDOM
+	storeMem(sp+4*8, sp+4*10) // auxv[3] = address of 16 bytes containing random value
+	storeMem(sp+4*9, 0)       // auxv[term] = 0
 
-	_ = st.GetMemory().SetMemoryRange(sp+4*9, bytes.NewReader([]byte("4;byfairdiceroll"))) // 16 bytes of "randomness"
+	_ = st.GetMemory().SetMemoryRange(sp+4*10, bytes.NewReader([]byte("4;byfairdiceroll"))) // 16 bytes of "randomness"
```
Comment (protolambda) [inline cannon/mipsevm/program/patch.go:82]: `sp+4*10+16 != sp+4*15` ?
Why 4 trailing bytes after the randomness section?

File: cannon/mipsevm/program/patch.go [hunk 3]
```diff
@@ -73,16 +72,24 @@ func PatchStack(st mipsevm.FPVMState) error {
...
+
+	envar := append([]byte("memprofilerate=0"), 0x0)
```
Comment (protolambda) [inline cannon/mipsevm/program/patch.go]: Appending 4 zero bytes, to have a full terminating word, would maybe be better?

File: cannon/mipsevm/program/patch.go [hunk 4]
```diff
@@ -73,16 +72,24 @@ func PatchStack(st mipsevm.FPVMState) error {
...
+	_ = st.GetMemory().SetMemoryRange(sp+4*15, bytes.NewReader(envar))
+
+	programName := append([]byte("op-program"), 0x0)
```
Comment (protolambda) [inline cannon/mipsevm/program/patch.go]: An assertion, that the env-var that precides this, is indeed 16 bytes + 4 bytes for terminator, would be nice as sanity-check. Or at least a comment about the otherwise seemingly magic offsets.

File: cannon/mipsevm/program/patch.go [hunk 5]
```diff
@@ -56,7 +56,6 @@ func PatchGo(f *elf.File, st mipsevm.FPVMState) error {
 	return nil
 }
 
-// TODO(cp-903) Consider setting envar "GODEBUG=memprofilerate=0" for go programs to disable memprofiling, instead of patching it out in PatchGo()
```
Comment (mbaxter) [inline cannon/mipsevm/program/patch.go:59]: We should cut the "runtime.MemProfileRate" patching above in `PatchGo()`

File: cannon/mipsevm/program/patch.go (hunk 2 above)
Comment (Inphi) [reply cannon/mipsevm/program/patch.go:82]: Leftover debugging. It was easier to detect zero value reads when values are discontiguous. Will fix.

File: cannon/mipsevm/program/patch.go [hunk 6]
```diff
@@ -73,16 +72,24 @@ func PatchStack(st mipsevm.FPVMState) error {
...
+	storeMem(sp+4*8, sp+4*10) // auxv[3] = address of 16 bytes containing random value
+	storeMem(sp+4*9, 0)       // auxv[term] = 0
 
-	_ = st.GetMemory().SetMemoryRange(sp+4*9, bytes.NewReader([]byte("4;byfairdiceroll"))) // 16 bytes of "randomness"
+	_ = st.GetMemory().SetMemoryRange(sp+4*10, bytes.NewReader([]byte("4;byfairdiceroll"))) // 16 bytes of "randomness"
+
+	envar := append([]byte("memprofilerate=0"), 0x0)
+	_ = st.GetMemory().SetMemoryRange(sp+4*15, bytes.NewReader(envar))
+
+	programName := append([]byte("op-program"), 0x0)
```
Comment (mbaxter) [inline cannon/mipsevm/program/patch.go]: (nit) Seems a little bit incorrect to say every program is "op-program", but not worth configuring this...

File: cannon/mipsevm/program/patch.go (hunk 4 above)
Comment (Inphi) [reply cannon/mipsevm/program/patch.go]: added a comment. The `entry.elf` test already asserts the layout.

File: cannon/mipsevm/program/patch.go (hunk 6 above)
Comment (mbaxter) [reply cannon/mipsevm/program/patch.go]: I guess we are kind of assuming op-program here.  Should we rename it to `patchOpProgram` or something?

File: cannon/mipsevm/program/patch.go (hunk 5 above)
Comment (Inphi) [reply cannon/mipsevm/program/patch.go:59]: Done. Confirmed that running disabling that patch doesn't noticeably increase the init time.

File: cannon/mipsevm/program/patch.go (hunk 6 above)
Comment (Inphi) [reply cannon/mipsevm/program/patch.go]: True. This was only done to avoid logic for handling large program names. I'll leave it as op-program for now.

File: cannon/mipsevm/program/patch.go [hunk 7]
```diff
@@ -73,16 +68,26 @@ func PatchStack(st mipsevm.FPVMState) error {
...
+	storeMem(sp+4*4, 0)       // envp[1] = terminating
+	storeMem(sp+4*5, 6)       // auxv[0] = _AT_PAGESZ = 6 (key)
+	storeMem(sp+4*6, 4096)    // auxv[1] = page size of 4 KiB (value) - (== minPhysPageSize)
+	storeMem(sp+4*7, 25)      // auxv[2] = AT_RANDOM
+	storeMem(sp+4*8, sp+4*10) // auxv[3] = address of 16 bytes containing random value
+	storeMem(sp+4*9, 0)       // auxv[term] = 0
+
+	_ = st.GetMemory().SetMemoryRange(sp+4*10, bytes.NewReader([]byte("4;byfairdiceroll"))) // 16 bytes of "randomness"
+
+	// append 3 extra zero bytes to end at 4-byte alignment
```
Comment (mbaxter) [inline cannon/mipsevm/program/patch.go]:
```suggestion
	// append 4 extra zero bytes to end at 4-byte alignment
```

File: cannon/mipsevm/program/patch.go [hunk 8]
```diff
@@ -73,16 +68,26 @@ func PatchStack(st mipsevm.FPVMState) error {
...
+	envar := append([]byte("GODEBUG=memprofilerate=0"), 0x0, 0x0, 0x0, 0x0)
+	_ = st.GetMemory().SetMemoryRange(sp+4*14, bytes.NewReader(envar))
 
-	_ = st.GetMemory().SetMemoryRange(sp+4*9, bytes.NewReader([]byte("4;byfairdiceroll"))) // 16 bytes of "randomness"
+	// 24 bytes for GODEBUG=memprofilerate=0 + 4 null bytes
+	programName := append([]byte("op-program"), 0x0)
```
Comment (mbaxter) [inline cannon/mipsevm/program/patch.go]: Should this also extend to hit the 4-byte alignment (for future-proofing)?
```suggestion
	programName := append([]byte("op-program"), 0x0, 0x0)
```

**Review by mbaxter — APPROVED** [review]

File: cannon/mipsevm/program/patch.go (hunk 8 above)
Comment (Inphi) [reply cannon/mipsevm/program/patch.go]: Good idea.
